import { encodeCheckpointValue, decodeCheckpointValue } from "../../../src/persistence/value.ts";
import { expect, test } from 'bun:test';
import { openArchive } from '../../../src/content/archive/index.ts';
import { openMountPlan, digestFile } from '../../../src/content/mounts/index.ts';
import { Q1_DONOR_PROFILE, createNumericOperations } from '../../../src/core/numeric.ts';
import { QcEntityMemory, QcMachine, classicQcEntityLayout, createQcBuiltins, createQcSourceSlotStorage, loadQcProgram, qcLinkBounds } from '../../../src/compat/qc/index.ts';
import type { QcHostBuiltinName } from '../../../src/compat/qc/index.ts';
import { QcWorldHost } from '../../../src/compat/qc/world-host.ts';
import { QcBroadcastMessages, createQcPresentationBindings } from '../../../src/compat/qc/presentation-host.ts';
import type { QcQuakeWorldMessageServices, QcMessageDestination, QcRoutedMessage } from '../../../src/compat/qc/presentation-host.ts';
import { createIdentityOwner } from '../../../src/contracts/identity.ts';
import { SessionActorRegistry, SharedBodyTable, SourceActorSlots, quakeEdictLifetime } from '../../../src/world/actors/index.ts';
import { createSceneQueries } from '../../../src/world/collision/index.ts';
import { readQ1Bsp } from '../../../src/formats/q1-map/index.ts';

const corpus=new URL('../../../../qfiles/q1/',import.meta.url).pathname;
test('actual QW QC prints, door sounds and multicast retain native destinations and source ownership',async()=>{
  const program=loadQcProgram(new Uint8Array(await Bun.file(corpus+'qw/qwprogs.dat').arrayBuffer()));
  expect(program.api.kind).toBe('q1-quakeworld');
  const archive=await openArchive(corpus+'id1/PAK0.PAK');
  const actors=new SessionActorRegistry(createIdentityOwner('qw-presentation'));
  const mounted=await openMountPlan({id:'mount-plan:qw:presentation',prefixOrders:[],defaultOrder:['mount:qw:test'],mounts:[{kind:'archive',identity:{id:'mount:qw:test',content:'q1:classic:id1:retail',generation:0},format:'pak',archivePath:corpus+'id1/PAK0.PAK',archiveDigest:await digestFile(corpus+'id1/PAK0.PAK')}]});
  try {
    const mapEntry=archive.findEntries('maps/e1m1.bsp')[0];if(mapEntry===undefined)throw Error('Missing map');
    const sound=await mounted.open('sound/ambience/water1.wav');if(sound===null)throw Error('Missing door sound');
    const scene=createSceneQueries(readQ1Bsp(await archive.readEntry(mapEntry))),numeric=createNumericOperations(Q1_DONOR_PROFILE);
    const entities=new QcEntityMemory(classicQcEntityLayout(program),16);
    const bodies=new SharedBodyTable(actors,{absoluteBounds:(_actor,body)=>qcLinkBounds(body,0,numeric),onUnlink:actor=>{scene.unlink(actor);return undefined;},onLink:body=>{scene.link(body,{family:'q1',shape:{kind:'box'},contents:-2,owner:null,role:'solid',monster:false,deadMonster:false});return undefined;}});
    const slots=new SourceActorSlots(actors,{provider:'test:qw',capacity:16,lifetime:quakeEdictLifetime(1),storage:createQcSourceSlotStorage({program,entities},{freeOffsetBytes:0,freeTimeOffsetBytes:100}),now:()=>({kind:'seconds',value:3}),unlink:actor=>bodies.unlink(actor),exhausted:()=>{throw Error('No edicts');}});
    slots.bindExisting(0,'quakec:world');const player=slots.allocate('quakec:player');
    const world=new QcWorldHost({program,entities,actors,slots,bodies,scene,numeric:Q1_DONOR_PROFILE,model:()=>null,foreignReference:()=>{throw Error('No foreign actor');}});
    world.actor(0);world.actor(1);
    let loading=true,phs=true;
    const routes:{entries:readonly QcRoutedMessage[];destination:QcMessageDestination}[]=[],emitted:unknown[]=[],prints:string[]=[];
    const qw:QcQuakeWorldMessageServices={loading:()=>loading,phs:()=>phs,client:actor=>actor.equals(player.id),route:(entries,destination)=>{routes.push({entries,destination});return undefined;}};
    const presentation=createQcPresentationBindings(world,{qw,content:'q1:classic:id1:retail',loading:()=>loading,print:text=>{prints.push(text);return undefined;},precache:()=>({index:1,resource:sound.reference}),lookup:()=>({index:1,resource:sound.reference}),events:{registerResource:()=>undefined,emit:(_content,event)=>{emitted.push(event);return undefined;}}});
    const messages=new QcBroadcastMessages(world,()=>{throw Error('QW cannot emit NQ global effects');},qw);
    const vm=new QcMachine({program,entities,numeric,builtins:createQcBuiltins({kind:'quakeworld',host:new Map([...world.host,...presentation,...messages.host])}),serverActive:()=>true});
    const text=(arg:number,value:string):void=>vm.globals.setInt(4+arg*3,vm.strings.setEngine(`arg${arg}`,value));
    vm.globals.setFloat(4,3);text(1,'hello');text(2,' world');vm.execute(program.functionNamed('bprint').index,3);
    expect(routes.pop()).toMatchObject({entries:[{message:{kind:'print',level:3,text:'hello world'},actor:null}],destination:{kind:'broadcast',reliable:true}});
    vm.globals.setInt(4,entities.reference(1));vm.globals.setFloat(7,1);text(2,'private');vm.execute(program.functionNamed('sprint').index,3);
    expect(routes.pop()).toMatchObject({entries:[{message:{kind:'print',level:1,text:'private'},actor:player.id}],destination:{kind:'client',actor:player.id,reliable:true}});
    const words=entities.at(1),field=(name:string):number=>vm.fieldOffset(name);
    words.setVector(field('origin'),{x:100,y:200,z:300});words.setVector(field('mins'),{x:-10,y:-20,z:-30});words.setVector(field('maxs'),{x:30,y:60,z:90});words.setFloat(field('solid'),4);words.setInt(field('noise1'),vm.strings.setEngine('door','ambience/water1.wav'));
    vm.globals.setInt(vm.globalOffset('self'),entities.reference(1));vm.execute(program.functionNamed('door_hit_bottom').index);
    expect(routes.pop()).toMatchObject({entries:[{message:{kind:'sound',channel:2,volume:255,origin:{x:110,y:220,z:330}},actor:player.id}],destination:{kind:'multicast',visibility:'all',reliable:true,origin:{x:110,y:220,z:330}}});
    vm.globals.setInt(4,entities.reference(1));vm.globals.setFloat(7,2);text(2,'ambience/water1.wav');vm.globals.setFloat(13,1);vm.globals.setFloat(16,1);vm.execute(program.functionNamed('sound').index,5);
    expect(routes.pop()?.destination).toMatchObject({visibility:'phs',reliable:false});
    phs=false;vm.execute(program.functionNamed('sound').index,5);expect(routes.pop()?.destination).toMatchObject({visibility:'all',reliable:false});
    const write=(name:QcHostBuiltinName,dest:number,value:number):void=>{vm.globals.setFloat(4,dest);vm.globals.setFloat(7,value);const fn=messages.host.get(name);if(fn===undefined)throw Error('Missing writer');fn(vm);};
    const teleport=(dest:number):void=>{write('WriteByte',dest,23);write('WriteByte',dest,11);for(const value of [1,2,3])write('WriteCoord',dest,value);};
    teleport(4);messages.flush();expect(routes).toHaveLength(0);
    vm.globals.setVector(4,{x:1,y:2,z:3});vm.globals.setFloat(7,5);vm.execute(program.functionNamed('multicast').index,2);
    expect(routes.pop()).toMatchObject({entries:[{message:{kind:'temporary-entity',effect:{type:11,origin:{x:1,y:2,z:3}}}}],destination:{kind:'multicast',visibility:'pvs',reliable:true}});
    for(const dest of [0,2,3])teleport(dest);vm.globals.setInt(vm.globalOffset('msg_entity'),entities.reference(1));teleport(1);messages.flush();
    expect(routes.map(route=>route.destination)).toEqual([{kind:'broadcast',reliable:false},{kind:'broadcast',reliable:true},{kind:'signon'},{kind:'client',actor:player.id,reliable:true}]);routes.length=0;
    loading=false;expect(()=>write('WriteByte',3,23)).toThrow('MSG_INIT');expect(()=>write('WriteByte',7,23)).toThrow('bad destination');
    write('WriteByte',4,23);write('WriteByte',4,5);write('WriteShort',4,1);for(const value of [1,2,3,4,5,6])write('WriteCoord',4,value);
    write('WriteByte',4,6);write('WriteShort',4,10);write('WriteByte',4,1);for(const value of [7,8,9])write('WriteCoord',4,value);
    write('WriteByte',4,16);write('WriteShort',4,10);
    actors.release(player);const replacement=slots.bindExisting(1,'quakec:replacement');expect(replacement.id.equals(player.id)).toBe(false);
    const savedMessages = decodeCheckpointValue(encodeCheckpointValue(messages.capture()));
    const resumedMessages = new QcBroadcastMessages(world, () => { throw Error('Unexpected NQ event'); }, qw);
    resumedMessages.restore(savedMessages, saved => actors.referenceSaved(saved, 'current'));
    expect(resumedMessages.capture()).toEqual(messages.capture());
    vm.globals.setVector(4, { x: 1, y: 2, z: 3 }); vm.globals.setFloat(7, 0);
    const resumedMulticast = resumedMessages.host.get('multicast'); if (resumedMulticast === undefined) throw Error('Missing restored multicast');
    resumedMulticast(vm);
    const resumedRoute = routes.pop(); if (resumedRoute === undefined) throw Error("Missing restored route");
    expect(resumedRoute?.entries.map(entry => entry.actor?.equals(player.id))).toEqual([true, true, true]);
    const savedEntries = resumedMessages.captureEntries(resumedRoute?.entries ?? []);
    expect(resumedMessages.restoreEntries(decodeCheckpointValue(encodeCheckpointValue(savedEntries)), saved => actors.referenceSaved(saved, 'current')))
      .toEqual(resumedRoute.entries);
    vm.globals.setVector(4,{x:1,y:2,z:3});vm.globals.setFloat(7,0);vm.execute(program.functionNamed('multicast').index,2);
    expect(routes.pop()?.entries.map(entry=>({kind:entry.message.kind,actor:entry.actor}))).toEqual([{kind:'temporary-entity',actor:player.id},{kind:'sound',actor:player.id},{kind:'stop-sound',actor:player.id}]);
    loading=true;for(let index=0;index<938;index++)write('WriteByte',3,1);messages.flushSignon();expect(routes.pop()?.entries).toHaveLength(938);
    for(let index=0;index<1451;index++)write('WriteByte',0,1);messages.flush();expect(routes).toHaveLength(0);
    for(let index=0;index<1450;index++)write('WriteByte',4,1);expect(()=>write('WriteByte',4,1)).toThrow('overflow');
    expect(emitted).toEqual([]);expect(prints).toEqual(['hello world']);
  } finally {mounted.close();actors.close();archive.close();}
});
