/* Source frame tables: id Software Quake II game and ZeniMax rerelease DLL. GPL-2.0-or-later. */
import type { MonsterMove, MonsterFrame } from "./types.ts";

function f(ai: MonsterFrame["ai"], distance: number, actions: MonsterFrame["actions"] = [], lerpFrame = -1): MonsterFrame {
  return { ai, distance, actions, lerpFrame };
}

export const classic_soldierMoves: readonly MonsterMove[] = [
  { name: "soldier_move_stand1", firstFrame: 146, lastFrame: 175, end: "soldier_stand", sidestepScale: 0, frames: [
    f("stand", 0, ["soldier_idle"]),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
  ] },
  { name: "soldier_move_stand3", firstFrame: 176, lastFrame: 214, end: "soldier_stand", sidestepScale: 0, frames: [
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0, ["soldier_cock"]),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
  ] },
  { name: "soldier_move_walk1", firstFrame: 215, lastFrame: 247, end: null, sidestepScale: 0, frames: [
    f("walk", 3),
    f("walk", 6),
    f("walk", 2),
    f("walk", 2),
    f("walk", 2),
    f("walk", 1),
    f("walk", 6),
    f("walk", 5),
    f("walk", 3),
    f("walk", -1, ["soldier_walk1_random"]),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
  ] },
  { name: "soldier_move_walk2", firstFrame: 256, lastFrame: 265, end: null, sidestepScale: 0, frames: [
    f("walk", 4),
    f("walk", 4),
    f("walk", 9),
    f("walk", 8),
    f("walk", 5),
    f("walk", 1),
    f("walk", 3),
    f("walk", 7),
    f("walk", 6),
    f("walk", 7),
  ] },
  { name: "soldier_move_start_run", firstFrame: 97, lastFrame: 98, end: "soldier_run", sidestepScale: 0, frames: [
    f("run", 7),
    f("run", 5),
  ] },
  { name: "soldier_move_run", firstFrame: 99, lastFrame: 104, end: null, sidestepScale: 0, frames: [
    f("run", 10),
    f("run", 11),
    f("run", 11),
    f("run", 16),
    f("run", 10),
    f("run", 15),
  ] },
  { name: "soldier_move_pain1", firstFrame: 50, lastFrame: 54, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", -3),
    f("move", 4),
    f("move", 1),
    f("move", 1),
    f("move", 0),
  ] },
  { name: "soldier_move_pain2", firstFrame: 55, lastFrame: 61, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", -13),
    f("move", -1),
    f("move", 2),
    f("move", 4),
    f("move", 2),
    f("move", 3),
    f("move", 2),
  ] },
  { name: "soldier_move_pain3", firstFrame: 62, lastFrame: 79, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", -8),
    f("move", 10),
    f("move", -4),
    f("move", -1),
    f("move", -3),
    f("move", 0),
    f("move", 3),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 1),
    f("move", 0),
    f("move", 1),
    f("move", 2),
    f("move", 4),
    f("move", 3),
    f("move", 2),
  ] },
  { name: "soldier_move_pain4", firstFrame: 80, lastFrame: 96, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", -10),
    f("move", -6),
    f("move", 8),
    f("move", 4),
    f("move", 1),
    f("move", 0),
    f("move", 2),
    f("move", 5),
    f("move", 2),
    f("move", -1),
    f("move", -1),
    f("move", 3),
    f("move", 2),
    f("move", 0),
  ] },
  { name: "soldier_move_attack1", firstFrame: 0, lastFrame: 11, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_fire1"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_attack1_refire1"]),
    f("charge", 0),
    f("charge", 0, ["soldier_cock"]),
    f("charge", 0, ["soldier_attack1_refire2"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack2", firstFrame: 12, lastFrame: 29, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_fire2"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_attack2_refire1"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_cock"]),
    f("charge", 0),
    f("charge", 0, ["soldier_attack2_refire2"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack3", firstFrame: 30, lastFrame: 38, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_fire3"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_attack3_refire"]),
    f("charge", 0, ["soldier_duck_up"]),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack4", firstFrame: 39, lastFrame: 44, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_fire4"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack6", firstFrame: 109, lastFrame: 122, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 10),
    f("charge", 4),
    f("charge", 12),
    f("charge", 11, ["soldier_fire8"]),
    f("charge", 13),
    f("charge", 18),
    f("charge", 15),
    f("charge", 14),
    f("charge", 11),
    f("charge", 8),
    f("charge", 11),
    f("charge", 12),
    f("charge", 12),
    f("charge", 17, ["soldier_attack6_refire"]),
  ] },
  { name: "soldier_move_duck", firstFrame: 45, lastFrame: 49, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", 5, ["soldier_duck_down"]),
    f("move", -1, ["soldier_duck_hold"]),
    f("move", 1),
    f("move", 0, ["soldier_duck_up"]),
    f("move", 5),
  ] },
  { name: "soldier_move_death1", firstFrame: 272, lastFrame: 307, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", -10),
    f("move", -10),
    f("move", -10),
    f("move", -5),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["soldier_fire6"]),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["soldier_fire7"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death2", firstFrame: 308, lastFrame: 342, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", -5),
    f("move", -5),
    f("move", -5),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death3", firstFrame: 343, lastFrame: 387, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", -5),
    f("move", -5),
    f("move", -5),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death4", firstFrame: 388, lastFrame: 440, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death5", firstFrame: 441, lastFrame: 464, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", -5),
    f("move", -5),
    f("move", -5),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death6", firstFrame: 465, lastFrame: 474, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
];

export const classic_infantryMoves: readonly MonsterMove[] = [
  { name: "infantry_move_stand", firstFrame: 50, lastFrame: 71, end: null, sidestepScale: 0, frames: [
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
  ] },
  { name: "infantry_move_fidget", firstFrame: 1, lastFrame: 49, end: "infantry_stand", sidestepScale: 0, frames: [
    f("stand", 1),
    f("stand", 0),
    f("stand", 1),
    f("stand", 3),
    f("stand", 6),
    f("stand", 3),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", -2),
    f("stand", 1),
    f("stand", 1),
    f("stand", 1),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", 0),
    f("stand", -1),
    f("stand", -1),
    f("stand", 0),
    f("stand", -3),
    f("stand", -2),
    f("stand", -3),
    f("stand", -3),
    f("stand", -2),
  ] },
  { name: "infantry_move_walk", firstFrame: 74, lastFrame: 85, end: null, sidestepScale: 0, frames: [
    f("walk", 5),
    f("walk", 4),
    f("walk", 4),
    f("walk", 5),
    f("walk", 4),
    f("walk", 5),
    f("walk", 6),
    f("walk", 4),
    f("walk", 4),
    f("walk", 4),
    f("walk", 4),
    f("walk", 5),
  ] },
  { name: "infantry_move_run", firstFrame: 92, lastFrame: 99, end: null, sidestepScale: 0, frames: [
    f("run", 10),
    f("run", 20),
    f("run", 5),
    f("run", 7),
    f("run", 30),
    f("run", 35),
    f("run", 2),
    f("run", 6),
  ] },
  { name: "infantry_move_pain1", firstFrame: 100, lastFrame: 109, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", -3),
    f("move", -2),
    f("move", -1),
    f("move", -2),
    f("move", -1),
    f("move", 1),
    f("move", -1),
    f("move", 1),
    f("move", 6),
    f("move", 2),
  ] },
  { name: "infantry_move_pain2", firstFrame: 110, lastFrame: 119, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", -3),
    f("move", -3),
    f("move", 0),
    f("move", -1),
    f("move", -2),
    f("move", 0),
    f("move", 0),
    f("move", 2),
    f("move", 5),
    f("move", 2),
  ] },
  { name: "infantry_move_death1", firstFrame: 125, lastFrame: 144, end: "infantry_dead", sidestepScale: 0, frames: [
    f("move", -4),
    f("move", 0),
    f("move", 0),
    f("move", -1),
    f("move", -4),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", -1),
    f("move", 3),
    f("move", 1),
    f("move", 1),
    f("move", -2),
    f("move", 2),
    f("move", 2),
    f("move", 9),
    f("move", 9),
    f("move", 5),
    f("move", -3),
    f("move", -3),
  ] },
  { name: "infantry_move_death2", firstFrame: 145, lastFrame: 169, end: "infantry_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 1),
    f("move", 5),
    f("move", -1),
    f("move", 0),
    f("move", 1),
    f("move", 1),
    f("move", 4),
    f("move", 3),
    f("move", 0),
    f("move", -2, ["InfantryMachineGun"]),
    f("move", -2, ["InfantryMachineGun"]),
    f("move", -3, ["InfantryMachineGun"]),
    f("move", -1, ["InfantryMachineGun"]),
    f("move", -2, ["InfantryMachineGun"]),
    f("move", 0, ["InfantryMachineGun"]),
    f("move", 2, ["InfantryMachineGun"]),
    f("move", 2, ["InfantryMachineGun"]),
    f("move", 3, ["InfantryMachineGun"]),
    f("move", -10, ["InfantryMachineGun"]),
    f("move", -7, ["InfantryMachineGun"]),
    f("move", -8, ["InfantryMachineGun"]),
    f("move", -6),
    f("move", 4),
    f("move", 0),
  ] },
  { name: "infantry_move_death3", firstFrame: 170, lastFrame: 178, end: "infantry_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", -6),
    f("move", -11),
    f("move", -3),
    f("move", -11),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "infantry_move_duck", firstFrame: 120, lastFrame: 124, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", -2, ["infantry_duck_down"]),
    f("move", -5, ["infantry_duck_hold"]),
    f("move", 3),
    f("move", 4, ["infantry_duck_up"]),
    f("move", 0),
  ] },
  { name: "infantry_move_attack1", firstFrame: 184, lastFrame: 198, end: "infantry_run", sidestepScale: 0, frames: [
    f("charge", 4),
    f("charge", -1),
    f("charge", -1),
    f("charge", 0, ["infantry_cock_gun"]),
    f("charge", -1),
    f("charge", 1),
    f("charge", 1),
    f("charge", 2),
    f("charge", -2),
    f("charge", -3),
    f("charge", 1, ["infantry_fire"]),
    f("charge", 5),
    f("charge", -1),
    f("charge", -2),
    f("charge", -3),
  ] },
  { name: "infantry_move_attack2", firstFrame: 199, lastFrame: 206, end: "infantry_run", sidestepScale: 0, frames: [
    f("charge", 3),
    f("charge", 6),
    f("charge", 0, ["infantry_swing"]),
    f("charge", 8),
    f("charge", 5),
    f("charge", 8, ["infantry_smack"]),
    f("charge", 6),
    f("charge", 3),
  ] },
];

export const rerelease_soldierMoves: readonly MonsterMove[] = [
  { name: "soldier_move_stand1", firstFrame: 146, lastFrame: 175, end: "soldier_stand", sidestepScale: 0, frames: [
    f("stand", 0, ["soldier_idle"]),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
  ] },
  { name: "soldier_move_stand2", firstFrame: 527, lastFrame: 566, end: "soldier_stand", sidestepScale: 0, frames: [
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0, ["monster_footstep"]),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0, ["monster_footstep"]),
  ] },
  { name: "soldier_move_stand3", firstFrame: 176, lastFrame: 214, end: "soldier_stand", sidestepScale: 0, frames: [
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0, ["soldier_cock"]),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
  ] },
  { name: "soldier_move_walk1", firstFrame: 215, lastFrame: 247, end: null, sidestepScale: 0, frames: [
    f("walk", 3),
    f("walk", 6),
    f("walk", 2),
    f("walk", 2, ["monster_footstep"]),
    f("walk", 2),
    f("walk", 1),
    f("walk", 6),
    f("walk", 5),
    f("walk", 3, ["monster_footstep"]),
    f("walk", -1, ["soldier_walk1_random"]),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
    f("walk", 0),
  ] },
  { name: "soldier_move_walk2", firstFrame: 256, lastFrame: 265, end: null, sidestepScale: 0, frames: [
    f("walk", 4, ["monster_footstep"]),
    f("walk", 4),
    f("walk", 9),
    f("walk", 8),
    f("walk", 5),
    f("walk", 1, ["monster_footstep"]),
    f("walk", 3),
    f("walk", 7),
    f("walk", 6),
    f("walk", 7),
  ] },
  { name: "soldier_move_start_run", firstFrame: 97, lastFrame: 98, end: "soldier_run", sidestepScale: 0, frames: [
    f("run", 7),
    f("run", 5),
  ] },
  { name: "soldier_move_run", firstFrame: 99, lastFrame: 104, end: null, sidestepScale: 0, frames: [
    f("run", 10),
    f("run", 11, ["monster_done_dodge","monster_footstep"]),
    f("run", 11),
    f("run", 16),
    f("run", 10, ["monster_footstep"]),
    f("run", 15, ["monster_done_dodge"]),
  ] },
  { name: "soldier_move_pain1", firstFrame: 50, lastFrame: 54, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", -3),
    f("move", 4),
    f("move", 1),
    f("move", 1),
    f("move", 0),
  ] },
  { name: "soldier_move_pain2", firstFrame: 55, lastFrame: 61, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", -13),
    f("move", -1),
    f("move", 2),
    f("move", 4),
    f("move", 2),
    f("move", 3),
    f("move", 2),
  ] },
  { name: "soldier_move_pain3", firstFrame: 62, lastFrame: 79, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", -8),
    f("move", 10),
    f("move", -4, ["monster_footstep"]),
    f("move", -1),
    f("move", -3),
    f("move", 0),
    f("move", 3),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 1),
    f("move", 0),
    f("move", 1),
    f("move", 2),
    f("move", 4),
    f("move", 3),
    f("move", 2, ["monster_footstep"]),
  ] },
  { name: "soldier_move_pain4", firstFrame: 80, lastFrame: 96, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", -10),
    f("move", -6),
    f("move", 8),
    f("move", 4),
    f("move", 1),
    f("move", 0),
    f("move", 2),
    f("move", 5),
    f("move", 2),
    f("move", -1),
    f("move", -1),
    f("move", 3),
    f("move", 2),
    f("move", 0),
  ] },
  { name: "soldier_move_attack1", firstFrame: 0, lastFrame: 11, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0, ["soldier_blind_check"]),
    f("charge", 0, ["soldier_attack1_shotgun_check"]),
    f("charge", 0, ["soldier_fire1"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_attack1_refire1"]),
    f("charge", 0),
    f("charge", 0, ["soldier_cock"]),
    f("charge", 0, ["soldier_attack1_refire2"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldierh_move_attack1", firstFrame: 0, lastFrame: 11, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0, ["soldier_blind_check"]),
    f("charge", 0, ["soldierh_hyper_laser_sound_start"]),
    f("charge", 0, ["soldier_fire1"]),
    f("charge", 0, ["soldierh_hyperripper1"]),
    f("charge", 0, ["soldierh_hyperripper1"]),
    f("charge", 0, ["soldier_attack1_refire1"]),
    f("charge", 0, ["soldierh_hyper_refire1"]),
    f("charge", 0, ["soldier_cock"]),
    f("charge", 0, ["soldier_attack1_refire2"]),
    f("charge", 0, ["soldierh_hyper_laser_sound_end"]),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack2", firstFrame: 12, lastFrame: 29, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_attack2_shotgun_check"]),
    f("charge", 0),
    f("charge", 0, ["soldier_fire2"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_attack2_refire1"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_cock"]),
    f("charge", 0),
    f("charge", 0, ["soldier_attack2_refire2"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldierh_move_attack2", firstFrame: 12, lastFrame: 29, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldierh_hyper_laser_sound_start"]),
    f("charge", 0, ["soldier_fire2"]),
    f("charge", 0, ["soldierh_hyperripper2"]),
    f("charge", 0, ["soldierh_hyperripper2"]),
    f("charge", 0, ["soldier_attack2_refire1"]),
    f("charge", 0, ["soldierh_hyper_refire2"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["soldier_cock"]),
    f("charge", 0),
    f("charge", 0, ["soldier_attack2_refire2"]),
    f("charge", 0, ["soldierh_hyper_laser_sound_end"]),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack3", firstFrame: 30, lastFrame: 38, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0, ["monster_duck_down"]),
    f("charge", 0, ["soldierh_hyper_laser_sound_start"]),
    f("charge", 0, ["soldier_fire3"]),
    f("charge", 0, ["soldierh_hyperripper3"]),
    f("charge", 0, ["soldierh_hyperripper3"]),
    f("charge", 0, ["soldier_attack3_refire"]),
    f("charge", 0, ["monster_duck_up"]),
    f("charge", 0, ["soldierh_hyper_laser_sound_end"]),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack4", firstFrame: 39, lastFrame: 44, end: "soldier_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0, ["soldierh_hyper_laser_sound_start"]),
    f("charge", 0, ["soldier_fire4"]),
    f("charge", 0, ["soldierh_hyper_laser_sound_end"]),
    f("charge", 0),
    f("charge", 0),
  ] },
  { name: "soldier_move_attack6", firstFrame: 109, lastFrame: 122, end: "soldier_run", sidestepScale: 0.65, frames: [
    f("run", 10, ["soldier_start_charge"]),
    f("run", 4, ["soldier_attack6_shotgun_check"]),
    f("run", 12, ["soldierh_hyper_laser_sound_start"]),
    f("run", 11, ["soldier_fire8","monster_footstep"]),
    f("run", 13, ["soldierh_hyperripper8","monster_done_dodge"]),
    f("run", 18, ["soldierh_hyperripper8"]),
    f("run", 15, ["monster_footstep"]),
    f("run", 14, ["soldier_attack6_refire1"]),
    f("run", 11),
    f("run", 8, ["monster_footstep"]),
    f("run", 11, ["soldier_cock"]),
    f("run", 12),
    f("run", 12, ["monster_footstep"]),
    f("run", 17, ["soldier_attack6_refire2"]),
  ] },
  { name: "soldier_move_duck", firstFrame: 45, lastFrame: 49, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", 5, ["monster_duck_down"]),
    f("move", -1, ["monster_duck_hold"]),
    f("move", 1),
    f("move", 0, ["monster_duck_up"]),
    f("move", 5),
  ] },
  { name: "soldier_move_attack5", firstFrame: 567, lastFrame: 574, end: "soldier_stand_up", sidestepScale: 0, frames: [
    f("move", 18, ["monster_duck_down"]),
    f("move", 11, ["monster_footstep"]),
    f("move", 0, ["monster_footstep"]),
    f("soldier_move", 0),
    f("soldier_move", 0, ["soldierh_hyper_laser_sound_start"]),
    f("soldier_move", 0, ["soldier_fire5"]),
    f("soldier_move", 0, ["soldierh_hyperripper5"]),
    f("soldier_move", 0, ["soldierh_hyperripper5"]),
  ] },
  { name: "soldier_move_trip", firstFrame: 127, lastFrame: 145, end: "soldier_run", sidestepScale: 0, frames: [
    f("move", 10),
    f("move", 2, ["monster_check_prone"]),
    f("move", 18, ["monster_duck_down"]),
    f("move", 11, ["monster_footstep"]),
    f("move", 9),
    f("move", -11, ["monster_footstep"]),
    f("move", -2),
    f("move", 0),
    f("move", 6),
    f("move", -5),
    f("move", 0),
    f("move", 1),
    f("move", 0, ["monster_footstep"]),
    f("move", 0, ["monster_duck_up"]),
    f("move", 3),
    f("move", 2, ["monster_footstep"]),
    f("move", -1),
    f("move", 2),
    f("move", 0),
  ] },
  { name: "soldier_move_death1", firstFrame: 272, lastFrame: 307, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", -10),
    f("move", -10),
    f("move", -10, ["soldier_death_shrink"]),
    f("move", -5),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["soldierh_hyper_laser_sound_start"]),
    f("move", 0, ["soldier_fire6"]),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["soldier_fire7"]),
    f("move", 0, ["soldierh_hyper_laser_sound_end"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death2", firstFrame: 308, lastFrame: 342, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", -5),
    f("move", -5),
    f("move", -5),
    f("move", 0, ["soldier_death_shrink"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death3", firstFrame: 343, lastFrame: 387, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", -5),
    f("move", -5),
    f("move", -5),
    f("move", 0, ["soldier_death_shrink"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death4", firstFrame: 388, lastFrame: 440, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 1.5),
    f("move", 2.5),
    f("move", -1.5),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", -0.5),
    f("move", 0),
    f("move", 0),
    f("move", 4),
    f("move", 4),
    f("move", 8, ["soldier_death_shrink"]),
    f("move", 8),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 5.5),
    f("move", 2.5),
    f("move", -2),
    f("move", -2),
  ] },
  { name: "soldier_move_death5", firstFrame: 441, lastFrame: 464, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", -5),
    f("move", -5),
    f("move", -5),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["soldier_death_shrink"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_death6", firstFrame: 465, lastFrame: 474, end: "soldier_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["soldier_death_shrink"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "soldier_move_blind", firstFrame: 146, lastFrame: 175, end: "soldier_blind", sidestepScale: 0, frames: [
    f("move", 0, ["soldier_idle"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0),
  ] },
];

export const rerelease_infantryMoves: readonly MonsterMove[] = [
  { name: "infantry_move_stand", firstFrame: 50, lastFrame: 71, end: null, sidestepScale: 0, frames: [
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
  ] },
  { name: "infantry_move_fidget", firstFrame: 1, lastFrame: 49, end: "infantry_stand", sidestepScale: 0, frames: [
    f("stand", 1),
    f("stand", 0),
    f("stand", 1),
    f("stand", 3),
    f("stand", 6),
    f("stand", 3, ["monster_footstep"]),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", -2),
    f("stand", 1),
    f("stand", 1),
    f("stand", 1),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", 0),
    f("stand", -1),
    f("stand", 0),
    f("stand", 0),
    f("stand", 1),
    f("stand", 0),
    f("stand", 0),
    f("stand", -1),
    f("stand", -1),
    f("stand", 0),
    f("stand", -3),
    f("stand", -2),
    f("stand", -3),
    f("stand", -3, ["monster_footstep"]),
    f("stand", -2),
  ] },
  { name: "infantry_move_walk", firstFrame: 74, lastFrame: 85, end: null, sidestepScale: 0, frames: [
    f("walk", 5, ["monster_footstep"]),
    f("walk", 4),
    f("walk", 4),
    f("walk", 5),
    f("walk", 4),
    f("walk", 5),
    f("walk", 6, ["monster_footstep"]),
    f("walk", 4),
    f("walk", 4),
    f("walk", 4),
    f("walk", 4),
    f("walk", 5),
  ] },
  { name: "infantry_move_run", firstFrame: 92, lastFrame: 99, end: null, sidestepScale: 0, frames: [
    f("run", 10),
    f("run", 15, ["monster_footstep"]),
    f("run", 5),
    f("run", 7, ["monster_done_dodge"]),
    f("run", 18),
    f("run", 20, ["monster_footstep"]),
    f("run", 2),
    f("run", 6),
  ] },
  { name: "infantry_move_pain1", firstFrame: 100, lastFrame: 109, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", -3),
    f("move", -2),
    f("move", -1),
    f("move", -2),
    f("move", -1, ["monster_footstep"]),
    f("move", 1),
    f("move", -1),
    f("move", 1),
    f("move", 6),
    f("move", 2, ["monster_footstep"]),
  ] },
  { name: "infantry_move_pain2", firstFrame: 110, lastFrame: 119, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", -3),
    f("move", -3),
    f("move", 0),
    f("move", -1),
    f("move", -2, ["monster_footstep"]),
    f("move", 0),
    f("move", 0),
    f("move", 2),
    f("move", 5),
    f("move", 2, ["monster_footstep"]),
  ] },
  { name: "infantry_move_death1", firstFrame: 125, lastFrame: 144, end: "infantry_dead", sidestepScale: 0, frames: [
    f("move", -4, [], 126),
    f("move", 0),
    f("move", 0),
    f("move", -1),
    f("move", -4, ["monster_footstep"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", -1, ["monster_footstep"]),
    f("move", 3),
    f("move", 1),
    f("move", 1),
    f("move", -2),
    f("move", 2),
    f("move", 2),
    f("move", 9, ["infantry_shrink","monster_footstep"]),
    f("move", 9),
    f("move", 5, ["monster_footstep"]),
    f("move", -3),
    f("move", -3),
  ] },
  { name: "infantry_move_death2", firstFrame: 145, lastFrame: 169, end: "infantry_dead", sidestepScale: 0, frames: [
    f("move", 0, [], 146),
    f("move", 1),
    f("move", 5),
    f("move", -1),
    f("move", 0),
    f("move", 1, ["monster_footstep"]),
    f("move", 1, ["monster_footstep"]),
    f("move", 4),
    f("move", 3),
    f("move", 0),
    f("move", -2, ["InfantryMachineGun"]),
    f("move", -2, ["InfantryMachineGun"]),
    f("move", -3, ["InfantryMachineGun"]),
    f("move", -1, ["InfantryMachineGun"]),
    f("move", -2, ["InfantryMachineGun"]),
    f("move", 0, ["InfantryMachineGun"]),
    f("move", 2, ["InfantryMachineGun"]),
    f("move", 2, ["InfantryMachineGun"]),
    f("move", 3, ["InfantryMachineGun"]),
    f("move", -10, ["InfantryMachineGun"]),
    f("move", -7, ["InfantryMachineGun"]),
    f("move", -8, ["InfantryMachineGun"]),
    f("move", -6, ["infantry_shrink","monster_footstep"]),
    f("move", 4),
    f("move", 0),
  ] },
  { name: "infantry_move_death3", firstFrame: 170, lastFrame: 178, end: "infantry_dead", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0, ["infantry_shrink","monster_footstep"]),
    f("move", -6),
    f("move", -11, [{"kind":"nextframe","frame":176}]),
    f("move", -3),
    f("move", -11),
    f("move", 0, ["monster_footstep"]),
    f("move", 0),
  ] },
  { name: "infantry_move_duck", firstFrame: 120, lastFrame: 124, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", -2, ["monster_duck_down"]),
    f("move", -5, ["monster_duck_hold"]),
    f("move", 3),
    f("move", 4, ["monster_duck_up"]),
    f("move", 0),
  ] },
  { name: "infantry_move_attack1", firstFrame: 184, lastFrame: 198, end: "infantry_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 6, ["infantry_set_firetime","monster_footstep"]),
    f("charge", 0, ["infantry_fire"]),
    f("charge", 0),
    f("charge", 1),
    f("charge", -7),
    f("charge", -6, [{"kind":"nextframe","frame":197},"monster_footstep"]),
    f("charge", -1),
    f("charge", 0, ["infantry_cock_gun"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", -1),
    f("charge", -1),
  ] },
  { name: "infantry_move_attack3", firstFrame: 217, lastFrame: 231, end: "infantry_run", sidestepScale: 0, frames: [
    f("charge", 4),
    f("charge", -1),
    f("charge", -1),
    f("charge", 0, ["infantry_cock_gun"]),
    f("charge", -1),
    f("charge", 1),
    f("charge", 1),
    f("charge", 2),
    f("charge", -2),
    f("charge", -3, ["infantry_set_firetime","monster_footstep"]),
    f("charge", 1, ["infantry_fire"]),
    f("charge", 5),
    f("charge", -1),
    f("charge", -2),
    f("charge", -3),
  ] },
  { name: "infantry_move_attack5", firstFrame: 240, lastFrame: 262, end: "infantry_run", sidestepScale: 0, frames: [
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["monster_footstep"]),
    f("charge", 0, ["infantry_cock_gun"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, [{"kind":"nextframe","frame":"next"}]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["infantry_set_firetime"]),
    f("charge", 0, ["infantry_fire"]),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0),
    f("charge", 0, ["monster_footstep"]),
  ] },
  { name: "infantry_move_attack2", firstFrame: 199, lastFrame: 206, end: "infantry_run", sidestepScale: 0, frames: [
    f("charge", 3),
    f("charge", 6),
    f("charge", 0, ["infantry_swing"]),
    f("charge", 8, ["monster_footstep"]),
    f("charge", 5),
    f("charge", 8, ["infantry_smack"]),
    f("charge", 6),
    f("charge", 3),
  ] },
  { name: "infantry_move_attack4", firstFrame: 232, lastFrame: 239, end: "infantry_run", sidestepScale: 0.5, frames: [
    f("charge", 16, ["infantry_fire"]),
    f("charge", 16, ["monster_footstep","infantry_fire"]),
    f("charge", 13, ["infantry_fire"]),
    f("charge", 10, ["infantry_fire"]),
    f("charge", 16, ["infantry_fire"]),
    f("charge", 16, ["monster_footstep","infantry_fire"]),
    f("charge", 16, ["infantry_fire"]),
    f("charge", 16, ["infantry_attack4_refire"]),
  ] },
  { name: "infantry_move_jump", firstFrame: 207, lastFrame: 216, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["infantry_jump_now"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["infantry_jump_wait_land"]),
    f("move", 0),
    f("move", 0),
  ] },
  { name: "infantry_move_jump2", firstFrame: 207, lastFrame: 216, end: "infantry_run", sidestepScale: 0, frames: [
    f("move", -8),
    f("move", -4),
    f("move", -4),
    f("move", 0, ["infantry_jump2_now"]),
    f("move", 0),
    f("move", 0),
    f("move", 0),
    f("move", 0, ["infantry_jump_wait_land"]),
    f("move", 0),
    f("move", 0),
  ] },
];
