import type { Q1Input, Q1Output } from "./oracle.ts";

export interface Q1Case {
  readonly id: string;
  readonly sources: readonly string[];
  readonly derivation: string;
  readonly input: Q1Input;
  readonly expected: Q1Output;
}

const initialGlobals = { time: 7, self: 99, other: 98 };
const thinkSources = ["quake-sv-phys", "quake-prog-fields", "quake-server-clock", "quake-host-clock"];
const scalarSources = ["quake-pr-exec", "quake-eval-type"];
const mg1Sources = ["mg1-hub", "mg1-sigils"];
const mg3Sources = ["mg3-counter", "mg3-defs", "mg3-subs"];

export const q1Cases: readonly Q1Case[] = [
  { id: "q1.scalar.store-after-each-op", sources: scalarSources,
    derivation: "At 2^24 binary32 spacing is 2. 2^24+1 is halfway and rounds to even 2^24 at the OP_ADD_F store; subtracting 2^24 then stores zero. Keeping a binary64 intermediate would incorrectly produce one.",
    input: { kind: "scalar-program", initial: 16777216, operations: [{ operator: "add", operand: 1 }, { operator: "subtract", operand: 16777216 }] },
    expected: { kind: "scalar-program", values: [16777216, 16777216, 0], bits: ["4b800000", "4b800000", "00000000"] } },
  { id: "q1.scalar.ties-round-up-to-even", sources: scalarSources,
    derivation: "16777218 has an odd low significand bit. Adding one reaches the midpoint and rounds to the even 16777220.",
    input: { kind: "scalar-program", initial: 16777218, operations: [{ operator: "add", operand: 1 }] },
    expected: { kind: "scalar-program", values: [16777218, 16777220], bits: ["4b800001", "4b800002"] } },
  { id: "q1.scalar.divide-multiply-stores", sources: scalarSources,
    derivation: "1/10 stores binary32 bits 0x3dcccccd, exactly 0.10000000149011612. Multiplying the stored value by 10 gives 1.0000000149011612, which rounds to 1 at the next store.",
    input: { kind: "scalar-program", initial: 1, operations: [{ operator: "divide", operand: 10 }, { operator: "multiply", operand: 10 }] },
    expected: { kind: "scalar-program", values: [1, 0.10000000149011612, 1], bits: ["3f800000", "3dcccccd", "3f800000"] } },
  { id: "q1.scalar.bitwise-truncates-fractions", sources: scalarSources,
    derivation: "C conversion truncates 15.75 to signed integer 15. 15 & 31 is 15; 15 | 16 is 31. Each result is stored as float.",
    input: { kind: "scalar-program", initial: 15.75, operations: [{ operator: "bit-and", operand: 31 }, { operator: "bit-or", operand: 16 }] },
    expected: { kind: "scalar-program", values: [15.75, 15, 31], bits: ["417c0000", "41700000", "41f80000"] } },
  { id: "q1.think.zero-is-disabled", sources: thinkSources,
    derivation: "The thinktime <= 0 guard returns true without clearing state or executing a callback.",
    input: { kind: "run-think", serverTime: 10, frameTime: 0.125, nextThink: 0, entity: 3, globals: initialGlobals, effect: { kind: "remove" } },
    expected: { kind: "run-think", ran: false, continuePhysics: true, nextThink: 0, free: false, globals: initialGlobals, callbackEntry: null } },
  { id: "q1.think.negative-is-disabled", sources: thinkSources,
    derivation: "A negative nextthink also satisfies the disabled guard and leaves callback globals unchanged.",
    input: { kind: "run-think", serverTime: 10, frameTime: 0.125, nextThink: -1, entity: 3, globals: initialGlobals, effect: { kind: "remove" } },
    expected: { kind: "run-think", ran: false, continuePhysics: true, nextThink: -1, free: false, globals: initialGlobals, callbackEntry: null } },
  { id: "q1.think.inclusive-frame-end", sources: thinkSources,
    derivation: "10.125 equals the double frame endpoint 10+0.125. Only greater times are skipped. The callback sees nextthink zero, its entity as self, world as other and the due time.",
    input: { kind: "run-think", serverTime: 10, frameTime: 0.125, nextThink: 10.125, entity: 3, globals: initialGlobals, effect: { kind: "retain" } },
    expected: { kind: "run-think", ran: true, continuePhysics: true, nextThink: 0, free: false,
      globals: { time: 10.125, self: 3, other: 0 }, callbackEntry: { time: 10.125, self: 3, other: 0, nextThink: 0 } } },
  { id: "q1.think.next-float-after-end", sources: thinkSources,
    derivation: "The next binary32 value after 10.125 is 10.125000953674316. It is greater than the frame endpoint and must remain pending.",
    input: { kind: "run-think", serverTime: 10, frameTime: 0.125, nextThink: 10.125000953674316, entity: 3, globals: initialGlobals, effect: { kind: "remove" } },
    expected: { kind: "run-think", ran: false, continuePhysics: true, nextThink: 10.125000953674316, free: false, globals: initialGlobals, callbackEntry: null } },
  { id: "q1.think.double-endpoint", sources: thinkSources,
    derivation: "The stored binary32 nextthink for decimal 0.1 is 0.10000000149011612. It exceeds the binary64 endpoint 0+0.1, so it is not due. Rounding the endpoint to binary32 would change this branch.",
    input: { kind: "run-think", serverTime: 0, frameTime: 0.1, nextThink: 0.1, entity: 3, globals: initialGlobals, effect: { kind: "retain" } },
    expected: { kind: "run-think", ran: false, continuePhysics: true, nextThink: 0.10000000149011612, free: false, globals: initialGlobals, callbackEntry: null } },
  { id: "q1.think.overdue-clamps-through-float", sources: thinkSources,
    derivation: "The overdue value 9 is clamped by assigning double sv.time=10.1 to float thinktime, yielding exactly 10.100000381469727. Callback globals remain installed after return.",
    input: { kind: "run-think", serverTime: 10.1, frameTime: 0.01, nextThink: 9, entity: 3, globals: initialGlobals, effect: { kind: "retain" } },
    expected: { kind: "run-think", ran: true, continuePhysics: true, nextThink: 0, free: false,
      globals: { time: 10.100000381469727, self: 3, other: 0 }, callbackEntry: { time: 10.100000381469727, self: 3, other: 0, nextThink: 0 } } },
  { id: "q1.think.removal-stops-physics", sources: [...thinkSources, "quake-remove-builtin", "quake-free-edict"],
    derivation: "The callback sees nextthink zero. Its remove(self) calls PF_Remove then ED_Free, setting free and nextthink=-1. SV_RunThink returns !free, therefore false.",
    input: { kind: "run-think", serverTime: 10, frameTime: 0.125, nextThink: 10, entity: 3, globals: initialGlobals, effect: { kind: "remove" } },
    expected: { kind: "run-think", ran: true, continuePhysics: false, nextThink: -1, free: true,
      globals: { time: 10, self: 3, other: 0 }, callbackEntry: { time: 10, self: 3, other: 0, nextThink: 0 } } },
  { id: "q1.think.reschedule-runs-once", sources: thinkSources,
    derivation: "The callback sees nextthink cleared, then reschedules to 10.0625 inside the same frame. SV_RunThink has no loop, so it returns after one invocation and retains the new schedule.",
    input: { kind: "run-think", serverTime: 10, frameTime: 0.125, nextThink: 10, entity: 3, globals: initialGlobals, effect: { kind: "reschedule", nextThink: 10.0625 } },
    expected: { kind: "run-think", ran: true, continuePhysics: true, nextThink: 10.0625, free: false,
      globals: { time: 10, self: 3, other: 0 }, callbackEntry: { time: 10, self: 3, other: 0, nextThink: 0 } } },
  { id: "q1.mg1.four-sigils-blocked", sources: mg1Sources,
    derivation: "SIGIL_ALL=1|2|4|8|16=31. Flags 15 omit E5, so the entity removes itself and never calls trigger_changelevel.",
    input: { kind: "mg1-hub", serverFlags: 15 },
    expected: { kind: "mg1-hub", requiredMask: 31, presentMask: 15, calls: ["remove(self)"] } },
  { id: "q1.mg1.five-sigils-open", sources: mg1Sources,
    derivation: "31 & 31 equals 31, so the wrapper invokes trigger_changelevel once.",
    input: { kind: "mg1-hub", serverFlags: 31 },
    expected: { kind: "mg1-hub", requiredMask: 31, presentMask: 31, calls: ["trigger_changelevel()"] } },
  { id: "q1.mg1.sixth-bit-does-not-fill-missing-fifth", sources: mg1Sources,
    derivation: "Flags 47 contain E1..E4 and E6. E6 is absent from SIGIL_ALL, so 47 & 31=15 and the gate stays closed.",
    input: { kind: "mg1-hub", serverFlags: 47 },
    expected: { kind: "mg1-hub", requiredMask: 31, presentMask: 15, calls: ["remove(self)"] } },
  { id: "q1.mg1.extra-flags-preserve-open-gate", sources: mg1Sources,
    derivation: "63 includes all five required bits and the unrelated sixth bit. Masking gives 31 and opens the gate.",
    input: { kind: "mg1-hub", serverFlags: 63 },
    expected: { kind: "mg1-hub", requiredMask: 31, presentMask: 31, calls: ["trigger_changelevel()"] } },
  { id: "q1.mg3.default-count-below-threshold", sources: mg3Sources,
    derivation: "Spawn count zero is replaced by 2. Flags 1 contain one counted rune, so use leaves SUB_UseTargets uncalled.",
    input: { kind: "mg3-counter", serverFlags: 1, count: 0, coop: false, spawnFlags: 0, entity: 40, activator: 2 },
    expected: { kind: "mg3-counter", removed: false, count: 2, use: "rune_counter_use", runes: 1, callback: null } },
  { id: "q1.mg3.exact-threshold-calls-targets", sources: mg3Sources,
    derivation: "Flags 5 contain E1 and E3, exactly two runes. 2>=2 invokes SUB_UseTargets with the same self and activator.",
    input: { kind: "mg3-counter", serverFlags: 5, count: 2, coop: false, spawnFlags: 0, entity: 40, activator: 2 },
    expected: { kind: "mg3-counter", removed: false, count: 2, use: "rune_counter_use", runes: 2,
      callback: { name: "SUB_UseTargets", self: 40, activator: 2 } } },
  { id: "q1.mg3.fifth-sigil-is-not-counted", sources: mg3Sources,
    derivation: "Flags 17 contain E1 and E5. The four source conditions count only E1, so the two-rune threshold is not reached.",
    input: { kind: "mg3-counter", serverFlags: 17, count: 2, coop: false, spawnFlags: 0, entity: 40, activator: 2 },
    expected: { kind: "mg3-counter", removed: false, count: 2, use: "rune_counter_use", runes: 1, callback: null } },
  { id: "q1.mg3.fractional-threshold-is-preserved", sources: mg3Sources,
    derivation: "Count 2.5 is nonzero and stays fractional. Two runes do not satisfy 2>=2.5.",
    input: { kind: "mg3-counter", serverFlags: 3, count: 2.5, coop: false, spawnFlags: 0, entity: 40, activator: 2 },
    expected: { kind: "mg3-counter", removed: false, count: 2.5, use: "rune_counter_use", runes: 2, callback: null } },
  { id: "q1.mg3.negative-count-is-not-defaulted", sources: mg3Sources,
    derivation: "Only a zero count selects the default. Count -1 is retained and zero runes satisfy 0>=-1.",
    input: { kind: "mg3-counter", serverFlags: 0, count: -1, coop: false, spawnFlags: 0, entity: 40, activator: 2 },
    expected: { kind: "mg3-counter", removed: false, count: -1, use: "rune_counter_use", runes: 0,
      callback: { name: "SUB_UseTargets", self: 40, activator: 2 } } },
  { id: "q1.mg3.inhibited-in-coop", sources: mg3Sources,
    derivation: "NOT_IN_COOP is 131072. In coop its macro removes self and returns before count default or callback installation.",
    input: { kind: "mg3-counter", serverFlags: 15, count: 0, coop: true, spawnFlags: 131072, entity: 40, activator: 2 },
    expected: { kind: "mg3-counter", removed: true, count: 0, use: null, runes: null, callback: null } },
  { id: "q1.mg3.coop-only-inhibited-outside-coop", sources: mg3Sources,
    derivation: "COOP_ONLY is 32768. RemovedOutsideCoop removes self and returns before count default or callback installation.",
    input: { kind: "mg3-counter", serverFlags: 15, count: 0, coop: false, spawnFlags: 32768, entity: 40, activator: 2 },
    expected: { kind: "mg3-counter", removed: true, count: 0, use: null, runes: null, callback: null } },
];
