import type { Q2WeaponDefinition, Q2WeaponName } from "./types.ts";

const definitions: Readonly<Record<Q2WeaponName, Q2WeaponDefinition>> = {
  blaster: { name: "blaster", item: "q2:weapon_blaster", classname: "weapon_blaster", ammo: null, quantity: 0, warning: 0, viewModel: "models/weapons/v_blast/tris.md2", worldModel: "", playerModel: 1, activateLast: 4, fireLast: 8, idleLast: 52, deactivateLast: 55, pauses: [19,32], fires: [5], repeating: false },
  shotgun: { name: "shotgun", item: "q2:weapon_shotgun", classname: "weapon_shotgun", ammo: "q2:ammo_shells", quantity: 1, warning: 5, viewModel: "models/weapons/v_shotg/tris.md2", worldModel: "models/weapons/g_shotg/tris.md2", playerModel: 2, activateLast: 7, fireLast: 18, idleLast: 36, deactivateLast: 39, pauses: [22,28,34], fires: [8,9], repeating: false },
  supershotgun: { name: "supershotgun", item: "q2:weapon_supershotgun", classname: "weapon_supershotgun", ammo: "q2:ammo_shells", quantity: 2, warning: 10, viewModel: "models/weapons/v_shotg2/tris.md2", worldModel: "models/weapons/g_shotg2/tris.md2", playerModel: 3, activateLast: 6, fireLast: 17, idleLast: 57, deactivateLast: 61, pauses: [29,42,57], fires: [7], repeating: false },
  machinegun: { name: "machinegun", item: "q2:weapon_machinegun", classname: "weapon_machinegun", ammo: "q2:ammo_bullets", quantity: 1, warning: 30, viewModel: "models/weapons/v_machn/tris.md2", worldModel: "models/weapons/g_machn/tris.md2", playerModel: 4, activateLast: 3, fireLast: 5, idleLast: 45, deactivateLast: 49, pauses: [23,45], fires: [4,5], repeating: true },
  chaingun: { name: "chaingun", item: "q2:weapon_chaingun", classname: "weapon_chaingun", ammo: "q2:ammo_bullets", quantity: 1, warning: 60, viewModel: "models/weapons/v_chain/tris.md2", worldModel: "models/weapons/g_chain/tris.md2", playerModel: 5, activateLast: 4, fireLast: 31, idleLast: 61, deactivateLast: 64, pauses: [38,43,51,61], fires: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21], repeating: true },
  grenades: { name: "grenades", item: "q2:ammo_grenades", classname: "ammo_grenades", ammo: "q2:ammo_grenades", quantity: 1, warning: 2, viewModel: "models/weapons/v_handgr/tris.md2", worldModel: "models/items/ammo/grenades/medium/tris.md2", playerModel: 6, activateLast: 0, fireLast: 15, idleLast: 48, deactivateLast: 48, pauses: [29,34,39,48], fires: [12], repeating: false },
  grenadelauncher: { name: "grenadelauncher", item: "q2:weapon_grenadelauncher", classname: "weapon_grenadelauncher", ammo: "q2:ammo_grenades", quantity: 1, warning: 5, viewModel: "models/weapons/v_launch/tris.md2", worldModel: "models/weapons/g_launch/tris.md2", playerModel: 7, activateLast: 5, fireLast: 16, idleLast: 59, deactivateLast: 64, pauses: [34,51,59], fires: [6], repeating: false },
  rocketlauncher: { name: "rocketlauncher", item: "q2:weapon_rocketlauncher", classname: "weapon_rocketlauncher", ammo: "q2:ammo_rockets", quantity: 1, warning: 5, viewModel: "models/weapons/v_rocket/tris.md2", worldModel: "models/weapons/g_rocket/tris.md2", playerModel: 8, activateLast: 4, fireLast: 12, idleLast: 50, deactivateLast: 54, pauses: [25,33,42,50], fires: [5], repeating: false },
  hyperblaster: { name: "hyperblaster", item: "q2:weapon_hyperblaster", classname: "weapon_hyperblaster", ammo: "q2:ammo_cells", quantity: 1, warning: 30, viewModel: "models/weapons/v_hyperb/tris.md2", worldModel: "models/weapons/g_hyperb/tris.md2", playerModel: 9, activateLast: 5, fireLast: 20, idleLast: 49, deactivateLast: 53, pauses: [], fires: [6,7,8,9,10,11], repeating: true },
  railgun: { name: "railgun", item: "q2:weapon_railgun", classname: "weapon_railgun", ammo: "q2:ammo_slugs", quantity: 1, warning: 5, viewModel: "models/weapons/v_rail/tris.md2", worldModel: "models/weapons/g_rail/tris.md2", playerModel: 10, activateLast: 3, fireLast: 18, idleLast: 56, deactivateLast: 61, pauses: [56], fires: [4], repeating: false },
  bfg: { name: "bfg", item: "q2:weapon_bfg", classname: "weapon_bfg", ammo: "q2:ammo_cells", quantity: 50, warning: 50, viewModel: "models/weapons/v_bfg/tris.md2", worldModel: "models/weapons/g_bfg/tris.md2", playerModel: 11, activateLast: 8, fireLast: 32, idleLast: 55, deactivateLast: 58, pauses: [39,45,50,55], fires: [9,17], repeating: false },
};

export const Q2_BASE_WEAPONS: readonly Q2WeaponDefinition[] = Object.values(definitions);
export function q2WeaponDefinition(name: Q2WeaponName): Q2WeaponDefinition { return definitions[name]; }
export function q2WeaponFromClassname(classname: string): Q2WeaponDefinition | null { return Q2_BASE_WEAPONS.find(definition => definition.classname === classname) ?? null; }
