import type { ImageLevel } from "../../contracts/render.ts";
import { FrameCapture } from "../../capture/index.ts";
import { registerConsoleCommands, type ConfigurationWriteStarted } from "../../console/commands.ts";
import { archivedBindings } from "../../input/bindings.ts";
import { consoleConfigRoot, seatConsoleConfig } from "./config-scripts.ts";
import type { SeatId } from "../../contracts/identity.ts";
import type { SeatInput } from "../../input/seat.ts";
import type { SeatConsole } from "../../console/session.ts";
import type { CommandBuffer } from "../../core/commands/index.ts";
import type { ApplicationInput } from "./input.ts";
import type { NativeRenderer } from "./renderer.ts";

export function applicationCaptureRoot(userContentRoot: string | undefined): string {
  return consoleConfigRoot(userContentRoot);
}

export interface ApplicationCaptureServices {
  readonly commands: CommandBuffer;
  readonly configurationWriteStarted?: ConfigurationWriteStarted;
  console(seat: SeatId): SeatConsole | null;
  input(seat: SeatId): SeatInput | null;
  canChat(): boolean;
  root(): string;
  mapName(): string;
  write(operation: () => Promise<void>): Promise<void>;
  print(text: string): void;
}

export function inputCaptureServices(input: ApplicationInput, root: string,
  mapName: () => string, print: (text: string) => void): ApplicationCaptureServices {
  return { commands: input.commands, root: () => root, mapName, print,
    console: seat => input.locals.find(local => local.player.seat.id.equals(seat))?.console ?? null,
    input: seat => input.locals.find(local => local.player.seat.id.equals(seat))?.input ?? null,
    canChat: () => input.bindingCapabilities.chat, write: operation => input.scripts.write(operation) };
}

/** Arms readback during command dispatch; the host drains writes after presentation. */
export class ApplicationCapture {
  private readonly operations = new Set<Promise<void>>();
  private readonly reads = new Set<AbortController>();
  private unregister: (() => void) | null = null;
  private closed = false;
  private frameCapture: FrameCapture | null = null;

  constructor(private readonly services: ApplicationCaptureServices, private readonly renderer: NativeRenderer) {}

  activate(): void {
    if (this.closed) throw new Error("Cannot activate a closed capture owner");
    if (this.unregister !== null) return;
    const services = this.services;
    this.unregister = registerConsoleCommands({ commands: services.commands,
      ...(services.configurationWriteStarted === undefined ? {} : { configurationWriteStarted: services.configurationWriteStarted }),
      config: seat => seatConsoleConfig(services.root(), seat),
      configuration: invocation => {
        let origin = invocation.source.origin;
        while (origin.kind === "script") origin = origin.caller;
        const input = origin.kind === "local-seat" ? services.input(origin.seat) : null;
        const bindings = input === null ? [] : archivedBindings(input);
        return `// Generated by quake-typescript\n${[...bindings, ...services.commands.archiveCommands(invocation.source)].join("\n")}\n`;
      },
      console: seat => services.console(seat), canChat: () => services.canChat(),
      capture: seat => services.console(seat) === null ? null : this.currentFrameCapture(),
      mapName: () => services.mapName(), print: text => services.print(text),
      queue: (operation, frameReadback) => this.queue(operation, frameReadback) });
  }

  private currentFrameCapture(): FrameCapture {
    const root = this.services.root();
    if (this.frameCapture === null || this.frameCapture.root !== root)
      this.frameCapture = new FrameCapture(root, { readRgba: () => this.readFrame() });
    return this.frameCapture;
  }

  private async readFrame(): Promise<ImageLevel> {
    const controller = new AbortController();
    this.reads.add(controller);
    try {
      return await this.renderer.captureNextFrame(controller.signal);
    } finally { this.reads.delete(controller); }
  }

  private queue(operation: () => Promise<void>, frameReadback = false): void {
    if (this.closed) { this.services.print("Console output owner is closed\n"); return; }
    let result: Promise<void>;
    try { result = frameReadback ? operation() : this.services.write(operation); } catch (error) { result = Promise.reject(error); }
    const pending = result.catch((error: unknown) => { this.services.print(`Console output failed: ${error instanceof Error ? error.message : String(error)}\n`); });
    this.operations.add(pending);
    void pending.then(() => { this.operations.delete(pending); });
  }

  /** cl_avidemo uses the same pending readback and retirement path as screenshot. */
  captureFrame(): void {
    this.queue(async () => { await this.currentFrameCapture().screenshot({ format: "tga" }); }, true);
  }

  get pendingReadback(): boolean { return this.reads.size !== 0; }

  async drain(): Promise<void> { await Promise.all([...this.operations]); }

  async beforeWorldChange(): Promise<void> {
    for (const controller of this.reads) controller.abort(new Error("Screenshot cancelled before the requested frame was presented"));
    await this.drain();
  }

  async close(): Promise<void> {
    if (this.closed) return;
    this.closed = true;
    this.unregister?.();
    this.unregister = null;
    await this.beforeWorldChange();
  }
}
