import type { ImageLevel } from "../../contracts/render.ts";
import { FrameCapture } from "../../capture/index.ts";
import { registerConsoleCommands } from "../../console/commands.ts";
import { archivedBindings } from "../../input/bindings.ts";
import { consoleConfigRoot, seatConsoleConfig } from "./config-scripts.ts";
import type { ApplicationInput } from "./input.ts";
import type { NativeRenderer } from "./renderer.ts";

export function applicationCaptureRoot(userContentRoot: string | undefined): string {
  return consoleConfigRoot(userContentRoot);
}

/** Arms readback during command dispatch; the host drains writes after presentation. */
export class ApplicationCapture {
  private readonly operations = new Set<Promise<void>>();
  private readonly reads = new Set<AbortController>();
  private unregister: (() => void) | null = null;
  private closed = false;

  constructor(private readonly input: ApplicationInput, private readonly renderer: NativeRenderer,
    readonly root: string, private readonly mapName: () => string, private readonly print: (text: string) => void) {}

  activate(): void {
    if (this.closed) throw new Error("Cannot activate a closed capture owner");
    if (this.unregister !== null) return;
    const { input, root, mapName, print } = this;
    const capture = new FrameCapture(root, { readRgba: () => this.readFrame() });
    this.unregister = registerConsoleCommands({ commands: input.commands,
      config: seat => seatConsoleConfig(root, seat),
      configuration: invocation => {
        let origin = invocation.source.origin;
        while (origin.kind === "script") origin = origin.caller;
        const seat = origin.kind === "local-seat" ? origin.seat : null;
        const local = input.locals.find(local => seat !== null && local.player.seat.id.equals(seat));
        const bindings = local === undefined ? [] : archivedBindings(local.input);
        return `// Generated by quake-typescript\n${[...bindings, ...input.commands.archiveCommands(invocation.source)].join("\n")}\n`;
      },
      console: seat => input.locals.find(local => local.player.seat.id.equals(seat))?.console ?? null,
      capture: seat => input.locals.some(local => local.player.seat.id.equals(seat)) ? capture : null,
      mapName, print, queue: (operation, frameReadback) => this.queue(operation, frameReadback) });
  }

  private async readFrame(): Promise<ImageLevel> {
    const controller = new AbortController();
    this.reads.add(controller);
    try {
      const pixels = await this.renderer.captureNextFrame(controller.signal);
      return { width: this.renderer.backend.width, height: this.renderer.backend.height, pixels };
    } finally { this.reads.delete(controller); }
  }

  private queue(operation: () => Promise<void>, frameReadback = false): void {
    if (this.closed) { this.print("Console output owner is closed\n"); return; }
    let result: Promise<void>;
    try { result = frameReadback ? operation() : this.input.scripts.write(operation); } catch (error) { result = Promise.reject(error); }
    const pending = result.catch((error: unknown) => { this.print(`Console output failed: ${error instanceof Error ? error.message : String(error)}\n`); });
    this.operations.add(pending);
    void pending.then(() => { this.operations.delete(pending); });
  }

  get pendingReadback(): boolean { return this.reads.size !== 0; }

  async drain(): Promise<void> { await Promise.all([...this.operations]); }

  async beforeWorldChange(): Promise<void> {
    for (const controller of this.reads) controller.abort(new Error("Screenshot cancelled before the requested frame was presented"));
    await this.drain();
  }

  async close(): Promise<void> {
    if (this.closed) return;
    this.closed = true;
    this.unregister?.();
    this.unregister = null;
    await this.beforeWorldChange();
  }
}
