/* quakec_mg3/monsters/mg3_rknight.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["rknight_stand1", {"frame": 0, "next": "rknight_stand2", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand2", {"frame": 1, "next": "rknight_stand3", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand3", {"frame": 2, "next": "rknight_stand4", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand4", {"frame": 3, "next": "rknight_stand5", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand5", {"frame": 4, "next": "rknight_stand6", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand6", {"frame": 5, "next": "rknight_stand7", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand7", {"frame": 6, "next": "rknight_stand8", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand8", {"frame": 7, "next": "rknight_stand9", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_stand9", {"frame": 8, "next": "rknight_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["rknight_walk1", {"frame": 9, "next": "rknight_walk2", "operations": [{"kind": "action", "name": "rk_idle_sound"}, {"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["rknight_walk2", {"frame": 10, "next": "rknight_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["rknight_walk3", {"frame": 11, "next": "rknight_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["rknight_walk4", {"frame": 12, "next": "rknight_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["rknight_walk5", {"frame": 13, "next": "rknight_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["rknight_walk6", {"frame": 14, "next": "rknight_walk7", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["rknight_walk7", {"frame": 15, "next": "rknight_walk8", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["rknight_walk8", {"frame": 16, "next": "rknight_walk9", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["rknight_walk9", {"frame": 17, "next": "rknight_walk10", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["rknight_walk10", {"frame": 18, "next": "rknight_walk11", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["rknight_walk11", {"frame": 19, "next": "rknight_walk12", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["rknight_walk12", {"frame": 20, "next": "rknight_walk13", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["rknight_walk13", {"frame": 21, "next": "rknight_walk14", "operations": [{"kind": "ai", "mode": "walk", "distance": 6.0}]}],
  ["rknight_walk14", {"frame": 22, "next": "rknight_walk15", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["rknight_walk15", {"frame": 23, "next": "rknight_walk16", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["rknight_walk16", {"frame": 24, "next": "rknight_walk17", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["rknight_walk17", {"frame": 25, "next": "rknight_walk18", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["rknight_walk18", {"frame": 26, "next": "rknight_walk19", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["rknight_walk19", {"frame": 27, "next": "rknight_walk20", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["rknight_walk20", {"frame": 28, "next": "rknight_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["rknight_runb1", {"frame": 9, "next": "rknight_runb2", "operations": [{"kind": "action", "name": "rk_idle_sound"}, {"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["rknight_runb2", {"frame": 10, "next": "rknight_runb3", "operations": [{"kind": "ai", "mode": "run", "distance": 5.0}]}],
  ["rknight_runb3", {"frame": 11, "next": "rknight_runb4", "operations": [{"kind": "ai", "mode": "run", "distance": 5.0}]}],
  ["rknight_runb4", {"frame": 12, "next": "rknight_runb5", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["rknight_runb5", {"frame": 13, "next": "rknight_runb6", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["rknight_runb6", {"frame": 14, "next": "rknight_runb7", "operations": [{"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["rknight_runb7", {"frame": 15, "next": "rknight_runb8", "operations": [{"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["rknight_runb8", {"frame": 16, "next": "rknight_runb9", "operations": [{"kind": "ai", "mode": "run", "distance": 3.0}]}],
  ["rknight_runb9", {"frame": 17, "next": "rknight_runb10", "operations": [{"kind": "ai", "mode": "run", "distance": 3.0}]}],
  ["rknight_runb10", {"frame": 18, "next": "rknight_runb11", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["rknight_runb11", {"frame": 19, "next": "rknight_runb12", "operations": [{"kind": "ai", "mode": "run", "distance": 3.0}]}],
  ["rknight_runb12", {"frame": 20, "next": "rknight_runb13", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["rknight_runb13", {"frame": 21, "next": "rknight_runb14", "operations": [{"kind": "ai", "mode": "run", "distance": 6.0}]}],
  ["rknight_runb14", {"frame": 22, "next": "rknight_runb15", "operations": [{"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["rknight_runb15", {"frame": 23, "next": "rknight_runb16", "operations": [{"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["rknight_runb16", {"frame": 24, "next": "rknight_runb17", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["rknight_runb17", {"frame": 25, "next": "rknight_runb18", "operations": [{"kind": "ai", "mode": "run", "distance": 3.0}]}],
  ["rknight_runb18", {"frame": 26, "next": "rknight_runb19", "operations": [{"kind": "ai", "mode": "run", "distance": 3.0}]}],
  ["rknight_runb19", {"frame": 27, "next": "rknight_runb20", "operations": [{"kind": "ai", "mode": "run", "distance": 3.0}]}],
  ["rknight_runb20", {"frame": 28, "next": "rknight_runb1", "operations": [{"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["rknight_run1", {"frame": 29, "next": "rknight_run2", "operations": [{"kind": "action", "name": "rk_idle_sound"}, {"kind": "ai", "mode": "run", "distance": 20.0}]}],
  ["rknight_run2", {"frame": 30, "next": "rknight_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 25.0}]}],
  ["rknight_run3", {"frame": 31, "next": "rknight_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 18.0}]}],
  ["rknight_run4", {"frame": 32, "next": "rknight_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 16.0}]}],
  ["rknight_run5", {"frame": 33, "next": "rknight_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["rknight_run6", {"frame": 34, "next": "rknight_run7", "operations": [{"kind": "ai", "mode": "run", "distance": 25.0}]}],
  ["rknight_run7", {"frame": 35, "next": "rknight_run8", "operations": [{"kind": "ai", "mode": "run", "distance": 21.0}]}],
  ["rknight_run8", {"frame": 36, "next": "rknight_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 13.0}]}],
  ["rknight_pain1", {"frame": 37, "next": "rknight_pain2", "operations": [{"kind": "action", "name": "rknight_pain_sound"}]}],
  ["rknight_pain2", {"frame": 38, "next": "rknight_pain3", "operations": []}],
  ["rknight_pain3", {"frame": 39, "next": "rknight_pain4", "operations": []}],
  ["rknight_pain4", {"frame": 40, "next": "rknight_pain5", "operations": []}],
  ["rknight_pain5", {"frame": 41, "next": "rknight_run", "operations": []}],
  ["rknight_die1", {"frame": 42, "next": "rknight_die2", "operations": [{"kind": "ai", "mode": "forward", "distance": 10.0}]}],
  ["rknight_die2", {"frame": 43, "next": "rknight_die3", "operations": [{"kind": "ai", "mode": "forward", "distance": 8.0}]}],
  ["rknight_die3", {"frame": 44, "next": "rknight_die4", "operations": [{"kind": "solid", "solid": "none"}, {"kind": "ai", "mode": "forward", "distance": 7.0}]}],
  ["rknight_die4", {"frame": 45, "next": "rknight_die5", "operations": []}],
  ["rknight_die5", {"frame": 46, "next": "rknight_die6", "operations": []}],
  ["rknight_die6", {"frame": 47, "next": "rknight_die7", "operations": []}],
  ["rknight_die7", {"frame": 48, "next": "rknight_die8", "operations": []}],
  ["rknight_die8", {"frame": 49, "next": "rknight_die9", "operations": [{"kind": "ai", "mode": "forward", "distance": 10.0}]}],
  ["rknight_die9", {"frame": 50, "next": "rknight_die10", "operations": [{"kind": "ai", "mode": "forward", "distance": 11.0}]}],
  ["rknight_die10", {"frame": 51, "next": "rknight_die11", "operations": []}],
  ["rknight_die11", {"frame": 52, "next": "rknight_die12", "operations": []}],
  ["rknight_die12", {"frame": 53, "next": "rknight_die12", "operations": []}],
  ["rknight_dieb1", {"frame": 54, "next": "rknight_dieb2", "operations": []}],
  ["rknight_dieb2", {"frame": 55, "next": "rknight_dieb3", "operations": []}],
  ["rknight_dieb3", {"frame": 56, "next": "rknight_dieb4", "operations": [{"kind": "solid", "solid": "none"}]}],
  ["rknight_dieb4", {"frame": 57, "next": "rknight_dieb5", "operations": []}],
  ["rknight_dieb5", {"frame": 58, "next": "rknight_dieb6", "operations": []}],
  ["rknight_dieb6", {"frame": 59, "next": "rknight_dieb7", "operations": []}],
  ["rknight_dieb7", {"frame": 60, "next": "rknight_dieb8", "operations": []}],
  ["rknight_dieb8", {"frame": 61, "next": "rknight_dieb9", "operations": []}],
  ["rknight_dieb9", {"frame": 62, "next": "rknight_dieb9", "operations": []}],
  ["rknight_magica1", {"frame": 79, "next": "rknight_magica2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica2", {"frame": 80, "next": "rknight_magica3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica3", {"frame": 81, "next": "rknight_magica4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica4", {"frame": 82, "next": "rknight_magica5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica5", {"frame": 83, "next": "rknight_magica6", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica6", {"frame": 84, "next": "rknight_magica7", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica7", {"frame": 85, "next": "rknight_magica8", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica8", {"frame": 86, "next": "rknight_magica9", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magica8"}]}],
  ["rknight_magica9", {"frame": 87, "next": "rknight_magica10", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magica9"}]}],
  ["rknight_magica10", {"frame": 88, "next": "rknight_magica11", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magica10"}]}],
  ["rknight_magica11", {"frame": 89, "next": "rknight_magica12", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magica11"}]}],
  ["rknight_magica12", {"frame": 90, "next": "rknight_magica13", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magica12"}]}],
  ["rknight_magica13", {"frame": 91, "next": "rknight_magica14", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magica14", {"frame": 92, "next": "rknight_run", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicb1", {"frame": 93, "next": "rknight_magicb2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicb2", {"frame": 94, "next": "rknight_magicb3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicb3", {"frame": 95, "next": "rknight_magicb4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicb4", {"frame": 96, "next": "rknight_magicb5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicb5", {"frame": 97, "next": "rknight_magicb6", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicb6", {"frame": 98, "next": "rknight_magicb7", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicb6"}]}],
  ["rknight_magicb7", {"frame": 99, "next": "rknight_magicb8", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicb7"}]}],
  ["rknight_magicb8", {"frame": 100, "next": "rknight_magicb9", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicb8"}]}],
  ["rknight_magicb9", {"frame": 101, "next": "rknight_magicb10", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicb9"}]}],
  ["rknight_magicb10", {"frame": 102, "next": "rknight_magicb11", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicb10"}]}],
  ["rknight_magicb11", {"frame": 103, "next": "rknight_magicb12", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicb11"}]}],
  ["rknight_magicb12", {"frame": 104, "next": "rknight_magicb13", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicb12"}]}],
  ["rknight_magicb13", {"frame": 105, "next": "rknight_run", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicc1", {"frame": 155, "next": "rknight_magicc2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicc2", {"frame": 156, "next": "rknight_magicc3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicc3", {"frame": 157, "next": "rknight_magicc4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicc4", {"frame": 158, "next": "rknight_magicc5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicc5", {"frame": 159, "next": "rknight_magicc6", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["rknight_magicc6", {"frame": 160, "next": "rknight_magicc7", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicc6"}]}],
  ["rknight_magicc7", {"frame": 161, "next": "rknight_magicc8", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicc7"}]}],
  ["rknight_magicc8", {"frame": 162, "next": "rknight_magicc9", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicc8"}]}],
  ["rknight_magicc9", {"frame": 163, "next": "rknight_magicc10", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicc9"}]}],
  ["rknight_magicc10", {"frame": 164, "next": "rknight_magicc11", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicc10"}]}],
  ["rknight_magicc11", {"frame": 165, "next": "rknight_run", "operations": [{"kind": "action", "name": "mg3_rknight:rknight_magicc11"}]}],
  ["rknight_slice1", {"frame": 112, "next": "rknight_slice2", "operations": [{"kind": "ai", "mode": "charge", "distance": 9.0}]}],
  ["rknight_slice2", {"frame": 113, "next": "rknight_slice3", "operations": [{"kind": "ai", "mode": "charge", "distance": 6.0}]}],
  ["rknight_slice3", {"frame": 114, "next": "rknight_slice4", "operations": [{"kind": "ai", "mode": "charge", "distance": 13.0}]}],
  ["rknight_slice4", {"frame": 115, "next": "rknight_slice5", "operations": [{"kind": "ai", "mode": "charge", "distance": 4.0}]}],
  ["rknight_slice5", {"frame": 116, "next": "rknight_slice6", "operations": [{"kind": "ai", "mode": "charge", "distance": 7.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_slice6", {"frame": 117, "next": "rknight_slice7", "operations": [{"kind": "ai", "mode": "charge", "distance": 15.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_slice7", {"frame": 118, "next": "rknight_slice8", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_slice8", {"frame": 119, "next": "rknight_slice9", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_slice9", {"frame": 120, "next": "rknight_slice10", "operations": [{"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_slice10", {"frame": 121, "next": "rknight_run", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}]}],
  ["rknight_smash1", {"frame": 122, "next": "rknight_smash2", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["rknight_smash2", {"frame": 123, "next": "rknight_smash3", "operations": [{"kind": "ai", "mode": "charge", "distance": 13.0}]}],
  ["rknight_smash3", {"frame": 124, "next": "rknight_smash4", "operations": [{"kind": "ai", "mode": "charge", "distance": 9.0}]}],
  ["rknight_smash4", {"frame": 125, "next": "rknight_smash5", "operations": [{"kind": "ai", "mode": "charge", "distance": 11.0}]}],
  ["rknight_smash5", {"frame": 126, "next": "rknight_smash6", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_smash6", {"frame": 127, "next": "rknight_smash7", "operations": [{"kind": "ai", "mode": "charge", "distance": 7.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_smash7", {"frame": 128, "next": "rknight_smash8", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_smash8", {"frame": 129, "next": "rknight_smash9", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_smash9", {"frame": 130, "next": "rknight_smash10", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_smash10", {"frame": 131, "next": "rknight_smash11", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["rknight_smash11", {"frame": 132, "next": "rknight_run", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["rknight_watk1", {"frame": 133, "next": "rknight_watk2", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}]}],
  ["rknight_watk2", {"frame": 134, "next": "rknight_watk3", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["rknight_watk3", {"frame": 135, "next": "rknight_watk4", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["rknight_watk4", {"frame": 136, "next": "rknight_watk5", "operations": [{"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk5", {"frame": 137, "next": "rknight_watk6", "operations": [{"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk6", {"frame": 138, "next": "rknight_watk7", "operations": [{"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk7", {"frame": 139, "next": "rknight_watk8", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["rknight_watk8", {"frame": 140, "next": "rknight_watk9", "operations": [{"kind": "ai", "mode": "charge", "distance": 4.0}]}],
  ["rknight_watk9", {"frame": 141, "next": "rknight_watk10", "operations": [{"kind": "ai", "mode": "charge", "distance": 5.0}]}],
  ["rknight_watk10", {"frame": 142, "next": "rknight_watk11", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk11", {"frame": 143, "next": "rknight_watk12", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk12", {"frame": 144, "next": "rknight_watk13", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk13", {"frame": 145, "next": "rknight_watk14", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["rknight_watk14", {"frame": 146, "next": "rknight_watk15", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["rknight_watk15", {"frame": 147, "next": "rknight_watk16", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["rknight_watk16", {"frame": 148, "next": "rknight_watk17", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["rknight_watk17", {"frame": 149, "next": "rknight_watk18", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk18", {"frame": 150, "next": "rknight_watk19", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk19", {"frame": 151, "next": "rknight_watk20", "operations": [{"kind": "ai", "mode": "charge", "distance": 4.0}, {"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["rknight_watk20", {"frame": 152, "next": "rknight_watk21", "operations": [{"kind": "ai", "mode": "charge", "distance": 6.0}]}],
  ["rknight_watk21", {"frame": 153, "next": "rknight_watk22", "operations": [{"kind": "ai", "mode": "charge", "distance": 7.0}]}],
  ["rknight_watk22", {"frame": 154, "next": "rknight_run", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}]}],
]);
