/* quakec_mg3/monsters/mg3_super_shambler.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["supsham_stand1", {"frame": 0, "next": "supsham_stand2", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand2", {"frame": 1, "next": "supsham_stand3", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand3", {"frame": 2, "next": "supsham_stand4", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand4", {"frame": 3, "next": "supsham_stand5", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand5", {"frame": 4, "next": "supsham_stand6", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand6", {"frame": 5, "next": "supsham_stand7", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand7", {"frame": 6, "next": "supsham_stand8", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand8", {"frame": 7, "next": "supsham_stand9", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand9", {"frame": 8, "next": "supsham_stand10", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand10", {"frame": 9, "next": "supsham_stand11", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand11", {"frame": 10, "next": "supsham_stand12", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand12", {"frame": 11, "next": "supsham_stand13", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand13", {"frame": 12, "next": "supsham_stand14", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand14", {"frame": 13, "next": "supsham_stand15", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand15", {"frame": 14, "next": "supsham_stand16", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand16", {"frame": 15, "next": "supsham_stand17", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_stand17", {"frame": 16, "next": "supsham_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["supsham_walk1", {"frame": 17, "next": "supsham_walk2", "operations": [{"kind": "ai", "mode": "walk", "distance": 10.0}]}],
  ["supsham_walk2", {"frame": 18, "next": "supsham_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 9.0}]}],
  ["supsham_walk3", {"frame": 19, "next": "supsham_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 9.0}]}],
  ["supsham_walk4", {"frame": 20, "next": "supsham_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["supsham_walk5", {"frame": 21, "next": "supsham_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 6.0}]}],
  ["supsham_walk6", {"frame": 22, "next": "supsham_walk7", "operations": [{"kind": "ai", "mode": "walk", "distance": 12.0}]}],
  ["supsham_walk7", {"frame": 23, "next": "supsham_walk8", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["supsham_walk8", {"frame": 24, "next": "supsham_walk9", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["supsham_walk9", {"frame": 25, "next": "supsham_walk10", "operations": [{"kind": "ai", "mode": "walk", "distance": 13.0}]}],
  ["supsham_walk10", {"frame": 26, "next": "supsham_walk11", "operations": [{"kind": "ai", "mode": "walk", "distance": 9.0}]}],
  ["supsham_walk11", {"frame": 27, "next": "supsham_walk12", "operations": [{"kind": "ai", "mode": "walk", "distance": 7.0}]}],
  ["supsham_walk12", {"frame": 28, "next": "supsham_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 7.0}, {"kind": "sound", "path": "shambler/sidle.wav", "channel": "voice", "attenuation": 2, "comparison": "greater", "chance": 0.8}]}],
  ["supsham_run1", {"frame": 29, "next": "supsham_run2", "operations": [{"kind": "action", "name": "supsham_removechild"}, {"kind": "ai", "mode": "run", "distance": 20.0}]}],
  ["supsham_run2", {"frame": 30, "next": "supsham_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 24.0}]}],
  ["supsham_run3", {"frame": 31, "next": "supsham_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 20.0}]}],
  ["supsham_run4", {"frame": 32, "next": "supsham_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 20.0}]}],
  ["supsham_run5", {"frame": 33, "next": "supsham_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 24.0}]}],
  ["supsham_run6", {"frame": 34, "next": "supsham_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 20.0}, {"kind": "sound", "path": "shambler/sidle.wav", "channel": "voice", "attenuation": 2, "comparison": "greater", "chance": 0.8}]}],
  ["supsham_smash1", {"frame": 35, "next": "supsham_smash2", "operations": [{"kind": "sound", "path": "shambler/melee1.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}, {"kind": "ai", "mode": "charge", "distance": 2.0}]}],
  ["supsham_smash2", {"frame": 36, "next": "supsham_smash3", "operations": [{"kind": "ai", "mode": "charge", "distance": 6.0}]}],
  ["supsham_smash3", {"frame": 37, "next": "supsham_smash4", "operations": [{"kind": "ai", "mode": "charge", "distance": 6.0}]}],
  ["supsham_smash4", {"frame": 38, "next": "supsham_smash5", "operations": [{"kind": "ai", "mode": "charge", "distance": 5.0}]}],
  ["supsham_smash5", {"frame": 39, "next": "supsham_smash6", "operations": [{"kind": "ai", "mode": "charge", "distance": 4.0}]}],
  ["supsham_smash6", {"frame": 40, "next": "supsham_smash7", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["supsham_smash7", {"frame": 41, "next": "supsham_smash8", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["supsham_smash8", {"frame": 42, "next": "supsham_smash9", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["supsham_smash9", {"frame": 43, "next": "supsham_smash10", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["supsham_smash10", {"frame": 44, "next": "supsham_smash11", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_smash10"}]}],
  ["supsham_smash11", {"frame": 45, "next": "supsham_smash12", "operations": [{"kind": "ai", "mode": "charge", "distance": 5.0}]}],
  ["supsham_smash12", {"frame": 46, "next": "supsham_run1", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_smash12"}]}],
  ["supsham_swingl1", {"frame": 56, "next": "supsham_swingl2", "operations": [{"kind": "sound", "path": "shambler/melee2.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}, {"kind": "ai", "mode": "charge", "distance": 5.0}]}],
  ["supsham_swingl2", {"frame": 57, "next": "supsham_swingl3", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}]}],
  ["supsham_swingl3", {"frame": 58, "next": "supsham_swingl4", "operations": [{"kind": "ai", "mode": "charge", "distance": 7.0}]}],
  ["supsham_swingl4", {"frame": 59, "next": "supsham_swingl5", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}]}],
  ["supsham_swingl5", {"frame": 60, "next": "supsham_swingl6", "operations": [{"kind": "ai", "mode": "charge", "distance": 7.0}]}],
  ["supsham_swingl6", {"frame": 61, "next": "supsham_swingl7", "operations": [{"kind": "ai", "mode": "charge", "distance": 9.0}]}],
  ["supsham_swingl7", {"frame": 62, "next": "supsham_swingl8", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_swingl7"}]}],
  ["supsham_swingl8", {"frame": 63, "next": "supsham_swingl9", "operations": [{"kind": "ai", "mode": "charge", "distance": 4.0}]}],
  ["supsham_swingl9", {"frame": 64, "next": "supsham_run1", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_swingl9"}]}],
  ["supsham_swingr1", {"frame": 47, "next": "supsham_swingr2", "operations": [{"kind": "sound", "path": "shambler/melee1.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}, {"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["supsham_swingr2", {"frame": 48, "next": "supsham_swingr3", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}]}],
  ["supsham_swingr3", {"frame": 49, "next": "supsham_swingr4", "operations": [{"kind": "ai", "mode": "charge", "distance": 14.0}]}],
  ["supsham_swingr4", {"frame": 50, "next": "supsham_swingr5", "operations": [{"kind": "ai", "mode": "charge", "distance": 7.0}]}],
  ["supsham_swingr5", {"frame": 51, "next": "supsham_swingr6", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}]}],
  ["supsham_swingr6", {"frame": 52, "next": "supsham_swingr7", "operations": [{"kind": "ai", "mode": "charge", "distance": 6.0}]}],
  ["supsham_swingr7", {"frame": 53, "next": "supsham_swingr8", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_swingr7"}]}],
  ["supsham_swingr8", {"frame": 54, "next": "supsham_swingr9", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}]}],
  ["supsham_swingr9", {"frame": 55, "next": "supsham_run1", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_swingr9"}]}],
  ["supsham_magic1", {"frame": 65, "next": "supsham_magic2", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic1"}]}],
  ["supsham_magic2", {"frame": 66, "next": "supsham_magic3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["supsham_magic3", {"frame": 67, "next": "supsham_magic4", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic3"}]}],
  ["supsham_magic4", {"frame": 68, "next": "supsham_magic5", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic4"}]}],
  ["supsham_magic5", {"frame": 69, "next": "supsham_magic4b", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic5"}]}],
  ["supsham_magic4b", {"frame": 68, "next": "supsham_magic5b", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic4b"}]}],
  ["supsham_magic5b", {"frame": 69, "next": "supsham_magic4c", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic5"}]}],
  ["supsham_magic4c", {"frame": 68, "next": "supsham_magic5c", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic4"}]}],
  ["supsham_magic5c", {"frame": 69, "next": "supsham_magic6", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic5"}]}],
  ["supsham_magic6", {"frame": 70, "next": "supsham_magic9", "operations": [{"kind": "action", "name": "supsham_removechild"}, {"kind": "action", "name": "SupCastLightning"}, {"kind": "sound", "path": "shambler/sboom.wav", "channel": "weapon", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["supsham_magic9", {"frame": 73, "next": "supsham_magic10", "operations": [{"kind": "action", "name": "SupCastLightning"}]}],
  ["supsham_magic10", {"frame": 74, "next": "supsham_magic11", "operations": [{"kind": "action", "name": "SupCastLightning"}]}],
  ["supsham_magic11", {"frame": 75, "next": "supsham_magic12", "operations": []}],
  ["supsham_magic12", {"frame": 76, "next": "supsham_run1", "operations": []}],
  ["supsham_magic_b1", {"frame": 65, "next": "supsham_magic_b2", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic1"}]}],
  ["supsham_magic_b2", {"frame": 66, "next": "supsham_magic_b3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["supsham_magic_b3", {"frame": 67, "next": "supsham_magic_b4", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic_b3"}]}],
  ["supsham_magic_b4", {"frame": 68, "next": "supsham_magic_b5", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic4"}]}],
  ["supsham_magic_b5", {"frame": 69, "next": "supsham_magic_b6", "operations": [{"kind": "action", "name": "mg3_super_shambler:supsham_magic5"}]}],
  ["supsham_magic_b6", {"frame": 70, "next": "supsham_magic_b9", "operations": [{"kind": "action", "name": "supsham_removechild"}, {"kind": "action", "name": "SupCastLightning"}, {"kind": "sound", "path": "shambler/sboom.wav", "channel": "weapon", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["supsham_magic_b9", {"frame": 73, "next": "supsham_magic_b10", "operations": [{"kind": "action", "name": "SupCastLightning"}]}],
  ["supsham_magic_b10", {"frame": 74, "next": "supsham_magic_b11", "operations": [{"kind": "action", "name": "SupCastLightning"}]}],
  ["supsham_magic_b11", {"frame": 75, "next": "supsham_magic_b12", "operations": []}],
  ["supsham_magic_b12", {"frame": 76, "next": "supsham_run1", "operations": []}],
  ["supsham_pain1", {"frame": 77, "next": "supsham_pain2", "operations": []}],
  ["supsham_pain2", {"frame": 78, "next": "supsham_pain3", "operations": []}],
  ["supsham_pain3", {"frame": 79, "next": "supsham_pain4", "operations": []}],
  ["supsham_pain4", {"frame": 80, "next": "supsham_pain5", "operations": []}],
  ["supsham_pain5", {"frame": 81, "next": "supsham_pain6", "operations": []}],
  ["supsham_pain6", {"frame": 82, "next": "supsham_run1", "operations": []}],
  ["supsham_death1", {"frame": 83, "next": "supsham_death2", "operations": []}],
  ["supsham_death2", {"frame": 84, "next": "supsham_death3", "operations": []}],
  ["supsham_death3", {"frame": 85, "next": "supsham_death4", "operations": [{"kind": "solid", "solid": "none"}, {"kind": "action", "name": "cleanup_orbs"}]}],
  ["supsham_death4", {"frame": 86, "next": "supsham_death5", "operations": []}],
  ["supsham_death5", {"frame": 87, "next": "supsham_death6", "operations": []}],
  ["supsham_death6", {"frame": 88, "next": "supsham_death7", "operations": []}],
  ["supsham_death7", {"frame": 89, "next": "supsham_death8", "operations": []}],
  ["supsham_death8", {"frame": 90, "next": "supsham_death9", "operations": []}],
  ["supsham_death9", {"frame": 91, "next": "supsham_death10", "operations": []}],
  ["supsham_death10", {"frame": 92, "next": "supsham_death11", "operations": []}],
  ["supsham_death11", {"frame": 93, "next": "supsham_death11", "operations": []}],
]);
