/* quakec_mg3/monsters/mg3_lavaman.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["lavaman_rise1", {"frame": 0, "next": "lavaman_rise2", "operations": [{"kind": "sound", "path": "boss1/out1.wav", "channel": "weapon", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["lavaman_rise2", {"frame": 1, "next": "lavaman_rise3", "operations": [{"kind": "sound", "path": "boss1/sight1.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["lavaman_rise3", {"frame": 2, "next": "lavaman_rise4", "operations": []}],
  ["lavaman_rise4", {"frame": 3, "next": "lavaman_rise5", "operations": []}],
  ["lavaman_rise5", {"frame": 4, "next": "lavaman_rise6", "operations": []}],
  ["lavaman_rise6", {"frame": 5, "next": "lavaman_rise7", "operations": []}],
  ["lavaman_rise7", {"frame": 6, "next": "lavaman_rise8", "operations": []}],
  ["lavaman_rise8", {"frame": 7, "next": "lavaman_rise9", "operations": []}],
  ["lavaman_rise9", {"frame": 8, "next": "lavaman_rise10", "operations": []}],
  ["lavaman_rise10", {"frame": 9, "next": "lavaman_rise11", "operations": []}],
  ["lavaman_rise11", {"frame": 10, "next": "lavaman_rise12", "operations": []}],
  ["lavaman_rise12", {"frame": 11, "next": "lavaman_rise13", "operations": []}],
  ["lavaman_rise13", {"frame": 12, "next": "lavaman_rise14", "operations": []}],
  ["lavaman_rise14", {"frame": 13, "next": "lavaman_rise15", "operations": []}],
  ["lavaman_rise15", {"frame": 14, "next": "lavaman_rise16", "operations": []}],
  ["lavaman_rise16", {"frame": 15, "next": "lavaman_rise17", "operations": []}],
  ["lavaman_rise17", {"frame": 16, "next": "lavaman_fire1", "operations": []}],
  ["lavaman_idle1", {"frame": 17, "next": "lavaman_idle2", "operations": [{"kind": "sound", "path": "boss1/sight1.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": 0.2}]}],
  ["lavaman_idle2", {"frame": 18, "next": "lavaman_idle3", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_idle3", {"frame": 19, "next": "lavaman_idle4", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_idle4", {"frame": 20, "next": "lavaman_idle5", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_idle5", {"frame": 21, "next": "lavaman_idle6", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_idle6", {"frame": 20, "next": "lavaman_idle7", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_idle7", {"frame": 19, "next": "lavaman_idle8", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_idle8", {"frame": 18, "next": "lavaman_idle9", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_idle9", {"frame": 17, "next": "lavaman_idle1", "operations": [{"kind": "action", "name": "lavaman_stand"}]}],
  ["lavaman_walk1", {"frame": 17, "next": "lavaman_walk2", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk2", {"frame": 18, "next": "lavaman_walk3", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk3", {"frame": 19, "next": "lavaman_walk4", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk4", {"frame": 20, "next": "lavaman_walk5", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk5", {"frame": 21, "next": "lavaman_walk6", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk6", {"frame": 22, "next": "lavaman_walk7", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk7", {"frame": 23, "next": "lavaman_walk8", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk8", {"frame": 24, "next": "lavaman_walk9", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk9", {"frame": 25, "next": "lavaman_walk10", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk10", {"frame": 26, "next": "lavaman_walk11", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk11", {"frame": 27, "next": "lavaman_walk12", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk12", {"frame": 28, "next": "lavaman_walk13", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk13", {"frame": 29, "next": "lavaman_walk14", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk14", {"frame": 30, "next": "lavaman_walk15", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk15", {"frame": 31, "next": "lavaman_walk16", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk16", {"frame": 32, "next": "lavaman_walk17", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk17", {"frame": 33, "next": "lavaman_walk18", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk18", {"frame": 34, "next": "lavaman_walk19", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk19", {"frame": 35, "next": "lavaman_walk20", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk20", {"frame": 36, "next": "lavaman_walk21", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk21", {"frame": 37, "next": "lavaman_walk22", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk22", {"frame": 38, "next": "lavaman_walk23", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk23", {"frame": 39, "next": "lavaman_walk24", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk24", {"frame": 40, "next": "lavaman_walk25", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk25", {"frame": 41, "next": "lavaman_walk26", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk26", {"frame": 42, "next": "lavaman_walk27", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk27", {"frame": 43, "next": "lavaman_walk28", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk28", {"frame": 44, "next": "lavaman_walk29", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk29", {"frame": 45, "next": "lavaman_walk30", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk30", {"frame": 46, "next": "lavaman_walk31", "operations": [{"kind": "action", "name": "lavaman_walk"}]}],
  ["lavaman_walk31", {"frame": 47, "next": "lavaman_walk1", "operations": []}],
  ["lavaman_run1", {"frame": 17, "next": "lavaman_run2", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run2", {"frame": 18, "next": "lavaman_run3", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run3", {"frame": 19, "next": "lavaman_run4", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run4", {"frame": 20, "next": "lavaman_run5", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run5", {"frame": 21, "next": "lavaman_run6", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run6", {"frame": 22, "next": "lavaman_run7", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run7", {"frame": 23, "next": "lavaman_run8", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run8", {"frame": 24, "next": "lavaman_run9", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run9", {"frame": 25, "next": "lavaman_run10", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run10", {"frame": 26, "next": "lavaman_run11", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run11", {"frame": 27, "next": "lavaman_run12", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run12", {"frame": 28, "next": "lavaman_run13", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run13", {"frame": 29, "next": "lavaman_run14", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run14", {"frame": 30, "next": "lavaman_run15", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run15", {"frame": 31, "next": "lavaman_run16", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run16", {"frame": 32, "next": "lavaman_run17", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run17", {"frame": 33, "next": "lavaman_run18", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run18", {"frame": 34, "next": "lavaman_run19", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run19", {"frame": 35, "next": "lavaman_run20", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run20", {"frame": 36, "next": "lavaman_run21", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run21", {"frame": 37, "next": "lavaman_run22", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run22", {"frame": 38, "next": "lavaman_run23", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run23", {"frame": 39, "next": "lavaman_run24", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run24", {"frame": 40, "next": "lavaman_run25", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run25", {"frame": 41, "next": "lavaman_run26", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run26", {"frame": 42, "next": "lavaman_run27", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run27", {"frame": 43, "next": "lavaman_run28", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run28", {"frame": 44, "next": "lavaman_run29", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run29", {"frame": 45, "next": "lavaman_run30", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run30", {"frame": 46, "next": "lavaman_run31", "operations": [{"kind": "action", "name": "lavaman_run"}]}],
  ["lavaman_run31", {"frame": 47, "next": "lavaman_run1", "operations": []}],
  ["lavaman_fire1", {"frame": 57, "next": "lavaman_fire2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire2", {"frame": 58, "next": "lavaman_fire3", "operations": []}],
  ["lavaman_fire3", {"frame": 59, "next": "lavaman_fire4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire4", {"frame": 60, "next": "lavaman_fire5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire5", {"frame": 61, "next": "lavaman_fire6", "operations": []}],
  ["lavaman_fire6", {"frame": 62, "next": "lavaman_fire7", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire7", {"frame": 63, "next": "lavaman_fire8", "operations": [{"kind": "action", "name": "lavaman_missile(1)"}]}],
  ["lavaman_fire8", {"frame": 64, "next": "lavaman_fire9", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire9", {"frame": 65, "next": "lavaman_fire10", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire10", {"frame": 66, "next": "lavaman_fire11", "operations": []}],
  ["lavaman_fire11", {"frame": 67, "next": "lavaman_fire12", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire12", {"frame": 68, "next": "lavaman_fire13", "operations": []}],
  ["lavaman_fire13", {"frame": 69, "next": "lavaman_fire14", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire14", {"frame": 70, "next": "lavaman_fire15", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire15", {"frame": 71, "next": "lavaman_fire16", "operations": []}],
  ["lavaman_fire16", {"frame": 72, "next": "lavaman_fire17", "operations": []}],
  ["lavaman_fire17", {"frame": 73, "next": "lavaman_fire18", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire18", {"frame": 74, "next": "lavaman_fire19", "operations": [{"kind": "action", "name": "lavaman_missile(2)"}]}],
  ["lavaman_fire19", {"frame": 75, "next": "lavaman_fire20", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire20", {"frame": 76, "next": "lavaman_fire21", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire21", {"frame": 77, "next": "lavaman_fire22", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["lavaman_fire22", {"frame": 78, "next": "lavaman_fire23", "operations": []}],
  ["lavaman_fire23", {"frame": 79, "next": "lavaman_run1", "operations": []}],
  ["lavaman_shocka1", {"frame": 80, "next": "lavaman_shocka2", "operations": [{"kind": "sound", "path": "boss1/pain.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["lavaman_shocka2", {"frame": 81, "next": "lavaman_shocka3", "operations": []}],
  ["lavaman_shocka3", {"frame": 82, "next": "lavaman_shocka4", "operations": []}],
  ["lavaman_shocka4", {"frame": 83, "next": "lavaman_shocka5", "operations": []}],
  ["lavaman_shocka5", {"frame": 84, "next": "lavaman_shocka6", "operations": []}],
  ["lavaman_shocka6", {"frame": 85, "next": "lavaman_shocka7", "operations": []}],
  ["lavaman_shocka7", {"frame": 86, "next": "lavaman_shocka8", "operations": []}],
  ["lavaman_shocka8", {"frame": 87, "next": "lavaman_shocka9", "operations": []}],
  ["lavaman_shocka9", {"frame": 88, "next": "lavaman_shocka10", "operations": []}],
  ["lavaman_shocka10", {"frame": 89, "next": "lavaman_run1", "operations": []}],
  ["lavaman_death1", {"frame": 48, "next": "lavaman_death2", "operations": [{"kind": "sound", "path": "boss1/death.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["lavaman_death2", {"frame": 49, "next": "lavaman_death3", "operations": []}],
  ["lavaman_death3", {"frame": 50, "next": "lavaman_death4", "operations": []}],
  ["lavaman_death4", {"frame": 51, "next": "lavaman_death5", "operations": []}],
  ["lavaman_death5", {"frame": 52, "next": "lavaman_death6", "operations": []}],
  ["lavaman_death6", {"frame": 53, "next": "lavaman_death7", "operations": []}],
  ["lavaman_death7", {"frame": 54, "next": "lavaman_death8", "operations": []}],
  ["lavaman_death8", {"frame": 55, "next": "lavaman_death9", "operations": []}],
  ["lavaman_death9", {"frame": 56, "next": "lavaman_death10", "operations": [{"kind": "action", "name": "mg3_lavaman:lavaman_death9"}]}],
  ["lavaman_death10", {"frame": 56, "next": "lavaman_death10", "operations": [{"kind": "action", "name": "mg3_lavaman:lavaman_death10"}]}],
]);
