import type { GameFamily } from "../../contracts/content.ts";

export interface ProductExpectation {
  readonly id: string;
  readonly family: GameFamily;
  readonly edition: string;
  readonly campaign: string;
  readonly title: string;
  readonly contentDirectory: string;
  readonly baseProduct: string | null;
  readonly requiredContentArchives: readonly string[];
  readonly requiredPrograms: readonly string[];
  readonly mapWitness: string | null;
  readonly unresolvedReason: string | null;
}

/** Product rows from the installed-content inventory; unavailable rows stay visible. */
export const expectedProducts: readonly ProductExpectation[] = [
  {"id": "q1-classic-id1", "family": "q1", "edition": "classic", "campaign": "id1", "title": "Quake", "contentDirectory": "q1/id1", "baseProduct": null, "requiredContentArchives": ["q1/id1/pak0.pak", "q1/id1/pak1.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-classic-hipnotic", "family": "q1", "edition": "classic", "campaign": "hipnotic", "title": "Scourge of Armagon", "contentDirectory": "q1/hipnotic", "baseProduct": "q1-classic-id1", "requiredContentArchives": ["q1/hipnotic/pak0.pak", "q1/id1/pak0.pak", "q1/id1/pak1.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-classic-rogue", "family": "q1", "edition": "classic", "campaign": "rogue", "title": "Dissolution of Eternity", "contentDirectory": "q1/rogue", "baseProduct": "q1-classic-id1", "requiredContentArchives": ["q1/rogue/pak0.pak", "q1/id1/pak0.pak", "q1/id1/pak1.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-id1", "family": "q1", "edition": "rerelease", "campaign": "id1", "title": "Quake", "contentDirectory": "q1/rerelease/id1", "baseProduct": null, "requiredContentArchives": ["q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-hipnotic", "family": "q1", "edition": "rerelease", "campaign": "hipnotic", "title": "Scourge of Armagon", "contentDirectory": "q1/rerelease/hipnotic", "baseProduct": "q1-rerelease-id1", "requiredContentArchives": ["q1/rerelease/hipnotic/pak0.pak", "q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-rogue", "family": "q1", "edition": "rerelease", "campaign": "rogue", "title": "Dissolution of Eternity", "contentDirectory": "q1/rerelease/rogue", "baseProduct": "q1-rerelease-id1", "requiredContentArchives": ["q1/rerelease/rogue/pak0.pak", "q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-dopa", "family": "q1", "edition": "rerelease", "campaign": "dopa", "title": "Dimension of the Past", "contentDirectory": "q1/rerelease/dopa", "baseProduct": "q1-rerelease-id1", "requiredContentArchives": ["q1/rerelease/dopa/pak0.pak", "q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-mg1", "family": "q1", "edition": "rerelease", "campaign": "mg1", "title": "Dimension of the Machine", "contentDirectory": "q1/rerelease/mg1", "baseProduct": "q1-rerelease-id1", "requiredContentArchives": ["q1/rerelease/mg1/pak0.pak", "q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-mg3", "family": "q1", "edition": "rerelease", "campaign": "mg3", "title": "Dawn of the Machine", "contentDirectory": "q1/rerelease/mg3", "baseProduct": "q1-rerelease-id1", "requiredContentArchives": ["q1/rerelease/mg3/pak0.pak", "q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-ctf", "family": "q1", "edition": "rerelease", "campaign": "ctf", "title": "Capture the Flag", "contentDirectory": "q1/rerelease/ctf", "baseProduct": "q1-rerelease-id1", "requiredContentArchives": ["q1/rerelease/ctf/pak0.pak", "q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-quakeworld", "family": "q1", "edition": "quakeworld", "campaign": "id1", "title": "QuakeWorld", "contentDirectory": "q1/qw", "baseProduct": "q1-classic-id1", "requiredContentArchives": ["q1/id1/pak0.pak", "q1/id1/pak1.pak"], "requiredPrograms": ["qwprogs.dat"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q1-rerelease-quake64", "family": "q1", "edition": "rerelease", "campaign": "quake64", "title": "Quake 64", "contentDirectory": "q1/rerelease/q64", "baseProduct": "q1-rerelease-id1", "requiredContentArchives": ["q1/rerelease/id1/pak0.pak"], "requiredPrograms": ["progs.dat"], "mapWitness": "maps/start.bsp", "unresolvedReason": null},
  {"id": "q2-classic-baseq2", "family": "q2", "edition": "classic", "campaign": "baseq2", "title": "Quake II", "contentDirectory": "q2/baseq2", "baseProduct": null, "requiredContentArchives": ["q2/baseq2/pak0.pak"], "requiredPrograms": ["gamex86.dll"], "mapWitness": "maps/base1.bsp", "unresolvedReason": null},
  {"id": "q2-classic-xatrix", "family": "q2", "edition": "classic", "campaign": "xatrix", "title": "The Reckoning", "contentDirectory": "q2/xatrix", "baseProduct": "q2-classic-baseq2", "requiredContentArchives": ["q2/xatrix/pak0.pak", "q2/baseq2/pak0.pak"], "requiredPrograms": ["gamex86.dll"], "mapWitness": "maps/xswamp.bsp", "unresolvedReason": null},
  {"id": "q2-classic-rogue", "family": "q2", "edition": "classic", "campaign": "rogue", "title": "Ground Zero", "contentDirectory": "q2/rogue", "baseProduct": "q2-classic-baseq2", "requiredContentArchives": ["q2/rogue/pak0.pak", "q2/baseq2/pak0.pak"], "requiredPrograms": ["gamex86.dll"], "mapWitness": "maps/rmine1.bsp", "unresolvedReason": null},
  {"id": "q2-classic-ctf", "family": "q2", "edition": "classic", "campaign": "ctf", "title": "Capture the Flag", "contentDirectory": "q2/ctf", "baseProduct": "q2-classic-baseq2", "requiredContentArchives": ["q2/ctf/pak0.pak", "q2/baseq2/pak0.pak"], "requiredPrograms": ["gamex86.dll"], "mapWitness": "maps/q2ctf1.bsp", "unresolvedReason": null},
  {"id": "q2-classic-lmctf", "family": "q2", "edition": "classic", "campaign": "lmctf", "title": "Loki's Minions CTF", "contentDirectory": "q2/lmctf", "baseProduct": "q2-classic-baseq2", "requiredContentArchives": ["q2/lmctf/pak0.pak", "q2/baseq2/pak0.pak"], "requiredPrograms": ["gamex86.dll"], "mapWitness": "maps/lmctf09.bsp", "unresolvedReason": null},
  {"id": "q2-rerelease-baseq2", "family": "q2", "edition": "rerelease", "campaign": "baseq2", "title": "Quake II", "contentDirectory": "q2/rerelease/baseq2", "baseProduct": null, "requiredContentArchives": ["q2/rerelease/baseq2/pak0.pak"], "requiredPrograms": ["game_x64.dll"], "mapWitness": "maps/base1.bsp", "unresolvedReason": null},
  {"id": "q2-rerelease-xatrix", "family": "q2", "edition": "rerelease", "campaign": "xatrix", "title": "The Reckoning", "contentDirectory": "q2/rerelease/baseq2", "baseProduct": "q2-rerelease-baseq2", "requiredContentArchives": ["q2/rerelease/baseq2/pak0.pak"], "requiredPrograms": ["game_x64.dll"], "mapWitness": "maps/xswamp.bsp", "unresolvedReason": null},
  {"id": "q2-rerelease-rogue", "family": "q2", "edition": "rerelease", "campaign": "rogue", "title": "Ground Zero", "contentDirectory": "q2/rerelease/baseq2", "baseProduct": "q2-rerelease-baseq2", "requiredContentArchives": ["q2/rerelease/baseq2/pak0.pak"], "requiredPrograms": ["game_x64.dll"], "mapWitness": "maps/rmine1.bsp", "unresolvedReason": null},
  {"id": "q2-rerelease-ctf", "family": "q2", "edition": "rerelease", "campaign": "ctf", "title": "Capture the Flag", "contentDirectory": "q2/rerelease/baseq2", "baseProduct": "q2-rerelease-baseq2", "requiredContentArchives": ["q2/rerelease/baseq2/pak0.pak"], "requiredPrograms": ["game_x64.dll"], "mapWitness": "maps/q2ctf1.bsp", "unresolvedReason": null},
  {"id": "q2-rerelease-mg2", "family": "q2", "edition": "rerelease", "campaign": "mg2", "title": "Call of the Machine", "contentDirectory": "q2/rerelease/baseq2", "baseProduct": "q2-rerelease-baseq2", "requiredContentArchives": ["q2/rerelease/baseq2/pak0.pak"], "requiredPrograms": ["game_x64.dll"], "mapWitness": "maps/mguhub.bsp", "unresolvedReason": null},
  {"id": "q2-rerelease-n64", "family": "q2", "edition": "rerelease", "campaign": "n64", "title": "Quake II 64", "contentDirectory": "q2/rerelease/baseq2", "baseProduct": "q2-rerelease-baseq2", "requiredContentArchives": ["q2/rerelease/baseq2/pak0.pak"], "requiredPrograms": ["game_x64.dll"], "mapWitness": "maps/q64/rtest.bsp", "unresolvedReason": null},
  {"id": "q3-baseq3", "family": "q3", "edition": "classic", "campaign": "baseq3", "title": "Quake III Arena", "contentDirectory": "q3a/baseq3", "baseProduct": null, "requiredContentArchives": ["q3a/baseq3/pak0.pk3"], "requiredPrograms": ["vm/qagame.qvm", "vm/cgame.qvm", "vm/ui.qvm"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q3-missionpack", "family": "q3", "edition": "classic", "campaign": "missionpack", "title": "Team Arena", "contentDirectory": "q3a/missionpack", "baseProduct": "q3-baseq3", "requiredContentArchives": ["q3a/missionpack/pak0.pk3", "q3a/baseq3/pak0.pk3"], "requiredPrograms": ["vm/qagame.qvm", "vm/cgame.qvm", "vm/ui.qvm"], "mapWitness": null, "unresolvedReason": null},
  {"id": "q3-demota", "family": "q3", "edition": "demo", "campaign": "demota", "title": "Quake III restricted demo content", "contentDirectory": "q3a/demota", "baseProduct": null, "requiredContentArchives": ["q3a/demota/pak0.pk3"], "requiredPrograms": ["vm/qagame.qvm", "vm/cgame.qvm", "vm/ui.qvm"], "mapWitness": null, "unresolvedReason": null},
];
