import type { MonsterSourceDefinition } from "./definitions.ts";

const army = { resources: ["progs/soldier.mdl", "progs/h_guard.mdl", "progs/gib1.mdl", "progs/gib2.mdl", "progs/gib3.mdl", "progs/backpack.mdl",
  ...["soldier/death1.wav", "soldier/idle.wav", "soldier/pain1.wav", "soldier/pain2.wav", "soldier/sattck1.wav", "soldier/sight1.wav", "player/udeath.wav", "weapons/lock4.wav"].map(path => `sound/${path}`)] };
const dog = { resources: ["progs/dog.mdl", "progs/h_dog.mdl", "progs/gib3.mdl",
  ...["dog/dattack1.wav", "dog/ddeath.wav", "dog/dpain1.wav", "dog/dsight.wav", "dog/idle.wav", "player/udeath.wav"].map(path => `sound/${path}`)] };
const enforcer = { resources: ["progs/enforcer.mdl", "progs/h_mega.mdl", "progs/laser.mdl", "progs/gib1.mdl", "progs/gib2.mdl", "progs/gib3.mdl", "progs/backpack.mdl",
  ...["enforcer/death1.wav", "enforcer/enfire.wav", "enforcer/enfstop.wav", "enforcer/idle1.wav", "enforcer/pain1.wav", "enforcer/pain2.wav",
    "enforcer/sight1.wav", "enforcer/sight2.wav", "enforcer/sight3.wav", "enforcer/sight4.wav", "player/udeath.wav", "weapons/lock4.wav"].map(path => `sound/${path}`)] };
const knight = { resources: [
  "progs/knight.mdl",
  "progs/h_knight.mdl",
  "sound/knight/kdeath.wav",
  "sound/knight/khurt.wav",
  "sound/knight/ksight.wav",
  "sound/knight/sword1.wav",
  "sound/knight/sword2.wav",
  "sound/knight/idle.wav",
  "progs/gib1.mdl",
  "progs/gib2.mdl",
  "progs/gib3.mdl",
  "sound/player/udeath.wav",
] };
const demon = { resources: [
  "progs/demon.mdl",
  "progs/h_demon.mdl",
  "sound/demon/ddeath.wav",
  "sound/demon/dhit2.wav",
  "sound/demon/djump.wav",
  "sound/demon/dpain1.wav",
  "sound/demon/idle1.wav",
  "sound/demon/sight2.wav",
  "progs/gib1.mdl",
  "progs/zom_gib.mdl",
  "sound/player/udeath.wav",
] };
const ogre = { resources: [
  "progs/ogre.mdl",
  "progs/h_ogre.mdl",
  "progs/grenade.mdl",
  "sound/ogre/ogdrag.wav",
  "sound/ogre/ogdth.wav",
  "sound/ogre/ogidle.wav",
  "sound/ogre/ogidle2.wav",
  "sound/ogre/ogpain1.wav",
  "sound/ogre/ogsawatk.wav",
  "sound/ogre/ogwake.wav",
  "progs/gib3.mdl",
  "progs/zom_gib.mdl",
  "progs/backpack.mdl",
  "progs/s_explod.spr",
  "sound/player/udeath.wav",
  "sound/weapons/grenade.wav",
  "sound/weapons/r_exp3.wav",
  "sound/weapons/bounce.wav",
  "sound/weapons/lock4.wav",
] };
const hellknight = { resources: [
  "progs/hknight.mdl",
  "progs/k_spike.mdl",
  "progs/h_hellkn.mdl",
  "sound/hknight/attack1.wav",
  "sound/hknight/death1.wav",
  "sound/hknight/pain1.wav",
  "sound/hknight/sight1.wav",
  "sound/hknight/hit.wav",
  "sound/hknight/slash1.wav",
  "sound/hknight/idle.wav",
  "sound/hknight/grunt.wav",
  "sound/knight/sword1.wav",
  "sound/knight/sword2.wav",
  "progs/gib1.mdl",
  "progs/gib2.mdl",
  "progs/gib3.mdl",
  "sound/player/udeath.wav",
] };
const shambler = { resources: [
  "progs/shambler.mdl",
  "progs/s_light.mdl",
  "progs/h_shams.mdl",
  "progs/bolt.mdl",
  "sound/shambler/sattck1.wav",
  "sound/shambler/sboom.wav",
  "sound/shambler/sdeath.wav",
  "sound/shambler/shurt2.wav",
  "sound/shambler/sidle.wav",
  "sound/shambler/ssight.wav",
  "sound/shambler/melee1.wav",
  "sound/shambler/melee2.wav",
  "sound/shambler/smack.wav",
  "progs/gib1.mdl",
  "progs/gib2.mdl",
  "progs/gib3.mdl",
  "progs/zom_gib.mdl",
  "sound/player/udeath.wav",
] };
const wizard = { resources: [
  "progs/wizard.mdl",
  "progs/h_wizard.mdl",
  "progs/w_spike.mdl",
  "sound/wizard/hit.wav",
  "sound/wizard/wattack.wav",
  "sound/wizard/wdeath.wav",
  "sound/wizard/widle1.wav",
  "sound/wizard/widle2.wav",
  "sound/wizard/wpain.wav",
  "sound/wizard/wsight.wav",
  "progs/gib2.mdl",
  "sound/player/udeath.wav",
] };
const shalrath = { resources: [
  "progs/shalrath.mdl",
  "progs/h_shal.mdl",
  "progs/v_spike.mdl",
  "sound/shalrath/attack.wav",
  "sound/shalrath/attack2.wav",
  "sound/shalrath/death.wav",
  "sound/shalrath/idle.wav",
  "sound/shalrath/pain.wav",
  "sound/shalrath/sight.wav",
  "progs/gib1.mdl",
  "progs/gib2.mdl",
  "progs/gib3.mdl",
  "progs/s_explod.spr",
  "sound/player/udeath.wav",
  "sound/weapons/r_exp3.wav",
] };
const tarbaby = { resources: [
  "progs/tarbaby.mdl",
  "sound/blob/death1.wav",
  "sound/blob/hit1.wav",
  "sound/blob/land1.wav",
  "sound/blob/sight1.wav",
] };
const zombie = { resources: [
  "progs/zombie.mdl",
  "progs/h_zombie.mdl",
  "progs/zom_gib.mdl",
  "sound/zombie/z_idle.wav",
  "sound/zombie/z_idle1.wav",
  "sound/zombie/z_shot1.wav",
  "sound/zombie/z_gib.wav",
  "sound/zombie/z_pain.wav",
  "sound/zombie/z_pain1.wav",
  "sound/zombie/z_fall.wav",
  "sound/zombie/z_miss.wav",
  "sound/zombie/z_hit.wav",
  "sound/zombie/idle_w2.wav",
  "progs/gib1.mdl",
  "progs/gib2.mdl",
  "progs/gib3.mdl",
] };

const ordinaryCreatures: MonsterSourceDefinition["creatures"] = {
  monster_army: army, monster_dog: dog, monster_enforcer: enforcer, monster_knight: knight, monster_demon1: demon,
  monster_ogre: ogre, monster_ogre_marksman: ogre, monster_hell_knight: hellknight, monster_shambler: shambler,
  monster_wizard: wizard, monster_shalrath: shalrath, monster_tarbaby: tarbaby, monster_zombie: zombie,
};

export const q1MonsterSources: readonly MonsterSourceDefinition[] = [
  { provider: "q1:monsters/classic/id1", family: "q1", edition: "classic", program: "id1", creatures: ordinaryCreatures },
  { provider: "q1:monsters/rerelease/id1", family: "q1", edition: "rerelease", program: "id1", creatures: ordinaryCreatures },
];
