import type { MonsterSourceDefinition } from "./definitions.ts";

const classicBerserk = { resources: ["models/monsters/berserk/tris.md2", "models/monsters/berserk/skin.pcx", "models/monsters/berserk/pain.pcx",
  "models/objects/gibs/bone/tris.md2", "models/objects/gibs/sm_meat/tris.md2", "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/bone/skin.pcx", "models/objects/gibs/sm_meat/skin.pcx", "models/objects/gibs/head2/skin.pcx", "models/objects/gibs/head2/player.pcx",
  ...["berserk/sight.wav", "berserk/bersrch1.wav", "berserk/berpain2.wav", "berserk/berdeth2.wav", "berserk/beridle1.wav", "berserk/attack.wav", "misc/udeath.wav"].map(path => `sound/${path}`)] };
const infantryResources = ["models/monsters/infantry/tris.md2", "models/monsters/infantry/skin.pcx", "models/monsters/infantry/pain.pcx",
  "models/objects/gibs/bone/tris.md2", "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/gibs/bone/skin.pcx", "models/objects/gibs/sm_meat/skin.pcx",
  ...["infantry/infsght1.wav", "infantry/infsrch1.wav", "infantry/infpain1.wav", "infantry/infpain2.wav", "infantry/infdeth1.wav", "infantry/infdeth2.wav",
    "infantry/infatck1.wav", "infantry/infatck2.wav", "infantry/infatck3.wav", "infantry/infidle1.wav", "infantry/melee2.wav", "misc/udeath.wav", "misc/fhit3.wav"].map(path => `sound/${path}`)];
const classicInfantry = { resources: [...infantryResources, "models/objects/gibs/head2/tris.md2", "models/objects/gibs/head2/skin.pcx", "models/objects/gibs/head2/player.pcx"] };
const rereleaseInfantry = { resources: [...infantryResources, "models/monsters/infantry/gibs/gun.pcx", ...["arm", "chest", "foot", "gun", "head"].map(part => `models/monsters/infantry/gibs/${part}.md2`)] };

const environmentResources = ["sound/infantry/inflies1.wav", "sound/misc/fhit3.wav", "sound/player/watr_in.wav", "sound/player/watr_out.wav", "sound/player/lava1.wav", "sound/player/lava2.wav"];

const soldier = { resources: [
  ...environmentResources,
  "models/monsters/soldier/pain.pcx",
  "models/monsters/soldier/skin.pcx",
  "models/monsters/soldier/skin_lt.pcx",
  "models/monsters/soldier/skin_ltp.pcx",
  "models/monsters/soldier/skin_ss.pcx",
  "models/monsters/soldier/skin_ssp.pcx",
  "models/monsters/soldier/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/chest/skin.pcx",
  "models/objects/gibs/chest/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/laser/skin.pcx",
  "models/objects/laser/tris.md2",
  "sound/infantry/infatck3.wav",
  "sound/misc/lasfly.wav",
  "sound/misc/udeath.wav",
  "sound/soldier/solatck1.wav",
  "sound/soldier/solatck2.wav",
  "sound/soldier/solatck3.wav",
  "sound/soldier/soldeth1.wav",
  "sound/soldier/soldeth2.wav",
  "sound/soldier/soldeth3.wav",
  "sound/soldier/solidle1.wav",
  "sound/soldier/solpain1.wav",
  "sound/soldier/solpain2.wav",
  "sound/soldier/solpain3.wav",
  "sound/soldier/solsght1.wav",
  "sound/soldier/solsrch1.wav",
] };

const gladiator = { resources: [
  ...environmentResources,
  "models/monsters/gladiatr/pain.pcx",
  "models/monsters/gladiatr/skin.pcx",
  "models/monsters/gladiatr/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "sound/gladiator/glddeth2.wav",
  "sound/gladiator/gldidle1.wav",
  "sound/gladiator/gldpain2.wav",
  "sound/gladiator/gldsrch1.wav",
  "sound/gladiator/melee1.wav",
  "sound/gladiator/melee2.wav",
  "sound/gladiator/melee3.wav",
  "sound/gladiator/pain.wav",
  "sound/gladiator/railgun.wav",
  "sound/gladiator/sight.wav",
  "sound/misc/udeath.wav",
] };

const gunner = { resources: [
  ...environmentResources,
  "models/monsters/gunner/pain.pcx",
  "models/monsters/gunner/skin.pcx",
  "models/monsters/gunner/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/grenade/skin.pcx",
  "models/objects/grenade/tris.md2",
  "sound/gunner/death1.wav",
  "sound/gunner/gunatck1.wav",
  "sound/gunner/gunatck2.wav",
  "sound/gunner/gunatck3.wav",
  "sound/gunner/gunidle1.wav",
  "sound/gunner/gunpain1.wav",
  "sound/gunner/gunpain2.wav",
  "sound/gunner/gunsrch1.wav",
  "sound/gunner/sight1.wav",
  "sound/misc/udeath.wav",
  "sound/weapons/grenlb1b.wav",
] };

const parasite = { resources: [
  ...environmentResources,
  "models/monsters/parasite/pain.pcx",
  "models/monsters/parasite/skin.pcx",
  "models/monsters/parasite/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "sound/misc/udeath.wav",
  "sound/parasite/paratck1.wav",
  "sound/parasite/paratck2.wav",
  "sound/parasite/paratck3.wav",
  "sound/parasite/paratck4.wav",
  "sound/parasite/pardeth1.wav",
  "sound/parasite/paridle1.wav",
  "sound/parasite/paridle2.wav",
  "sound/parasite/parpain1.wav",
  "sound/parasite/parpain2.wav",
  "sound/parasite/parsght1.wav",
  "sound/parasite/parsrch1.wav",
] };

const flyer = { resources: [
  ...environmentResources,
  "models/monsters/flyer/pain.pcx",
  "models/monsters/flyer/skin.pcx",
  "models/monsters/flyer/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/laser/skin.pcx",
  "models/objects/laser/tris.md2",
  "sound/flyer/flyatck1.wav",
  "sound/flyer/flyatck2.wav",
  "sound/flyer/flyatck3.wav",
  "sound/flyer/flydeth1.wav",
  "sound/flyer/flyidle1.wav",
  "sound/flyer/flypain1.wav",
  "sound/flyer/flypain2.wav",
  "sound/flyer/flysght1.wav",
  "sound/flyer/flysrch1.wav",
  "sound/misc/lasfly.wav",
  "sound/misc/udeath.wav",
] };

const floater = { resources: [
  ...environmentResources,
  "models/monsters/float/pain.pcx",
  "models/monsters/float/skin.pcx",
  "models/monsters/float/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/laser/skin.pcx",
  "models/objects/laser/tris.md2",
  "sound/floater/fltatck1.wav",
  "sound/floater/fltatck2.wav",
  "sound/floater/fltatck3.wav",
  "sound/floater/fltdeth1.wav",
  "sound/floater/fltidle1.wav",
  "sound/floater/fltpain1.wav",
  "sound/floater/fltpain2.wav",
  "sound/floater/fltsght1.wav",
  "sound/floater/fltsrch1.wav",
  "sound/misc/lasfly.wav",
  "sound/misc/udeath.wav",
] };

const hover = { resources: [
  ...environmentResources,
  "models/monsters/hover/pain.pcx",
  "models/monsters/hover/skin.pcx",
  "models/monsters/hover/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/laser/skin.pcx",
  "models/objects/laser/tris.md2",
  "sound/hover/hovatck1.wav",
  "sound/hover/hovdeth1.wav",
  "sound/hover/hovdeth2.wav",
  "sound/hover/hovidle1.wav",
  "sound/hover/hovpain1.wav",
  "sound/hover/hovpain2.wav",
  "sound/hover/hovsght1.wav",
  "sound/hover/hovsrch1.wav",
  "sound/hover/hovsrch2.wav",
  "sound/misc/lasfly.wav",
  "sound/misc/udeath.wav",
] };

const mutant = { resources: [
  ...environmentResources,
  "models/monsters/mutant/pain.pcx",
  "models/monsters/mutant/skin.pcx",
  "models/monsters/mutant/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "sound/misc/udeath.wav",
  "sound/mutant/mutatck1.wav",
  "sound/mutant/mutatck2.wav",
  "sound/mutant/mutatck3.wav",
  "sound/mutant/mutdeth1.wav",
  "sound/mutant/mutidle1.wav",
  "sound/mutant/mutpain1.wav",
  "sound/mutant/mutpain2.wav",
  "sound/mutant/mutsght1.wav",
  "sound/mutant/mutsrch1.wav",
  "sound/mutant/step1.wav",
  "sound/mutant/step2.wav",
  "sound/mutant/step3.wav",
  "sound/mutant/thud1.wav",
] };

const chick = { resources: [
  ...environmentResources,
  "models/monsters/bitch/pain.pcx",
  "models/monsters/bitch/skin.pcx",
  "models/monsters/bitch/tris.md2",
  "models/objects/debris2/skin.pcx",
  "models/objects/debris2/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/rocket/skin.pcx",
  "models/objects/rocket/tris.md2",
  "sound/chick/chkatck1.wav",
  "sound/chick/chkatck2.wav",
  "sound/chick/chkatck3.wav",
  "sound/chick/chkatck4.wav",
  "sound/chick/chkatck5.wav",
  "sound/chick/chkdeth1.wav",
  "sound/chick/chkdeth2.wav",
  "sound/chick/chkfall1.wav",
  "sound/chick/chkidle1.wav",
  "sound/chick/chkidle2.wav",
  "sound/chick/chkpain1.wav",
  "sound/chick/chkpain2.wav",
  "sound/chick/chkpain3.wav",
  "sound/chick/chksght1.wav",
  "sound/chick/chksrch1.wav",
  "sound/misc/udeath.wav",
  "sound/weapons/rockfly.wav",
] };

const tank = { resources: [
  ...environmentResources,
  "models/monsters/ctank/pain.pcx",
  "models/monsters/ctank/skin.pcx",
  "models/monsters/tank/pain.pcx",
  "models/monsters/tank/skin.pcx",
  "models/monsters/tank/tris.md2",
  "models/objects/debris2/skin.pcx",
  "models/objects/debris2/tris.md2",
  "models/objects/gibs/bone/skin.pcx",
  "models/objects/gibs/bone/tris.md2",
  "models/objects/gibs/chest/skin.pcx",
  "models/objects/gibs/chest/tris.md2",
  "models/objects/gibs/gear/skin.pcx",
  "models/objects/gibs/gear/tris.md2",
  "models/objects/gibs/head2/player.pcx",
  "models/objects/gibs/head2/skin.pcx",
  "models/objects/gibs/head2/tris.md2",
  "models/objects/gibs/sm_meat/skin.pcx",
  "models/objects/gibs/sm_meat/tris.md2",
  "models/objects/gibs/sm_metal/skin.pcx",
  "models/objects/gibs/sm_metal/tris.md2",
  "models/objects/laser/skin.pcx",
  "models/objects/laser/tris.md2",
  "models/objects/rocket/skin.pcx",
  "models/objects/rocket/tris.md2",
  "sound/misc/lasfly.wav",
  "sound/misc/udeath.wav",
  "sound/tank/death.wav",
  "sound/tank/sight1.wav",
  "sound/tank/step.wav",
  "sound/tank/tnkatck1.wav",
  "sound/tank/tnkatck3.wav",
  "sound/tank/tnkatck4.wav",
  "sound/tank/tnkatck5.wav",
  "sound/tank/tnkatk2a.wav",
  "sound/tank/tnkatk2b.wav",
  "sound/tank/tnkatk2c.wav",
  "sound/tank/tnkatk2d.wav",
  "sound/tank/tnkatk2e.wav",
  "sound/tank/tnkdeth2.wav",
  "sound/tank/tnkidle1.wav",
  "sound/tank/tnkpain2.wav",
  "sound/weapons/rockfly.wav",
] };

export const q2MonsterSources: readonly MonsterSourceDefinition[] = [
  { provider: "q2:monsters/classic/baseq2", family: "q2", edition: "classic", program: "baseq2", creatures: {
    monster_infantry: { resources: [...classicInfantry.resources, ...environmentResources] },
    monster_berserk: { resources: [...classicBerserk.resources, ...environmentResources] },
    monster_soldier: soldier,
    monster_gladiator: gladiator,
    monster_gunner: gunner,
    monster_parasite: parasite,
    monster_flyer: flyer,
    monster_floater: floater,
    monster_hover: hover,
    monster_mutant: mutant,
    monster_chick: chick,
    monster_tank: tank,
    monster_soldier_light: soldier,
    monster_soldier_ss: soldier,
    monster_tank_commander: tank,
  } },
  { provider: "q2:monsters/rerelease/baseq2", family: "q2", edition: "rerelease", program: "baseq2", creatures: { monster_infantry: { resources: [...rereleaseInfantry.resources, ...environmentResources] } } },
];
