import type { Q2RereleaseModuleCheckpoint, Q2RereleasePlayersCheckpoint } from "../content/q2/rerelease/checkpoint.ts";
import type { Q2RereleaseQ64Checkpoint } from "../content/q2/rerelease/q64/index.ts";
import type { Q2FogState, Q2RereleasePlayerState } from "../content/q2/rerelease/types.ts";
import { readSavedActor } from "./save-image.ts";
import { readVector } from "./shared.ts";
import { decodeCheckpointValue, encodeCheckpointValue, SaveReader } from "./value.ts";

export function readQ2FogState(reader: SaveReader): Q2FogState {
  const fog = reader.field("fog"), height = reader.field("heightFog");
  return { fog: { density: fog.field("density").number(), color: readVector(fog.field("color")), skyFactor: fog.field("skyFactor").number() },
    heightFog: { startColor: readVector(height.field("startColor")), startDistance: height.field("startDistance").number(), endColor: readVector(height.field("endColor")), endDistance: height.field("endDistance").number(), falloff: height.field("falloff").number(), density: height.field("density").number() } };
}
function player(reader: SaveReader): Readonly<Q2RereleasePlayerState> {
  const n = (key: string): number => reader.field(key).number(), b = (key: string): boolean => reader.field(key).boolean();
  return { spawned: b("spawned"), gameHelp1Changed: n("gameHelp1Changed"), gameHelp2Changed: n("gameHelp2Changed"), helpChanged: n("helpChanged"), helpTime: n("helpTime"), seat: reader.field("seat").integer(0), socialId: reader.field("socialId").string(), autoSwitch: reader.field("autoSwitch").choice(0, 1, 2, 3), autoShield: n("autoShield"), dogtag: reader.field("dogtag").string(), slimeDebounce: n("slimeDebounce"), windSoundTime: n("windSoundTime"), animationTime: n("animationTime"), flashTime: n("flashTime"), flashes: n("flashes"), lastDamageUntil: n("lastDamageUntil"), lastFiringUntil: n("lastFiringUntil"), lives: n("lives"),
    coopRespawnState: reader.field("coopRespawnState").choice("none", "in-combat", "bad-area", "blocked", "waiting", "no-lives"), flashlight: b("flashlight"), fog: readQ2FogState(reader.field("fog")), wantedFog: readQ2FogState(reader.field("wantedFog")), fogTransition: n("fogTransition"),
    bobSkip: b("bobSkip"), impactDelta: n("impactDelta"), onLadder: b("onLadder"), grappleReleasedUntil: n("grappleReleasedUntil"), grappleAttached: b("grappleAttached"), awaitingRespawn: b("awaitingRespawn"), respawnTimeout: n("respawnTimeout"), pendingLandmark: reader.field("pendingLandmark").nullable(value => ({ name: value.field("name").string(), relativeOrigin: readVector(value.field("relativeOrigin")), relativeVelocity: readVector(value.field("relativeVelocity")), relativeViewAngles: readVector(value.field("relativeViewAngles")) })), slowViewAngles: readVector(reader.field("slowViewAngles")), quakeTime: n("quakeTime"),
    helpLocation: readVector(reader.field("helpLocation")), helpImage: reader.field("helpImage").string(), helpPoints: reader.field("helpPoints").list(readVector), helpIndex: n("helpIndex"), helpDrawTime: n("helpDrawTime") };
}
export function readQ2RereleasePlayersCheckpoint(reader: SaveReader): Q2RereleasePlayersCheckpoint {
  const options = reader.field("options"), b = (key: string): boolean => options.field(key).boolean();
  return { version: reader.field("version").literal(1), options: { coopSquadRespawn: b("coopSquadRespawn"), coopInstancedItems: b("coopInstancedItems"), coopLives: b("coopLives"), coopNumLives: options.field("coopNumLives").number(), deathmatchForceRespawn: b("deathmatchForceRespawn"), deathmatchNoFallDamage: b("deathmatchNoFallDamage"), deathmatchAllowExit: b("deathmatchAllowExit"), deathmatchSpawnFarthest: b("deathmatchSpawnFarthest"), deathmatchForceRespawnTime: options.field("deathmatchForceRespawnTime").number(), coopPlayerCollision: b("coopPlayerCollision"), autoSaveMinimumTime: options.field("autoSaveMinimumTime").number() },
    coopRestartTime: reader.field("coopRestartTime").number(), intermissionFlags: reader.field("intermissionFlags").number(), intermissionFadeUntil: reader.field("intermissionFadeUntil").nullable(value => value.number()), intermissionCamera: reader.field("intermissionCamera").nullable(value => ({ origin: readVector(value.field("origin")), angles: readVector(value.field("angles")) })), intermissionCameraSet: reader.field("intermissionCameraSet").boolean(), deadlyKillBox: reader.field("deadlyKillBox").boolean(), players: reader.field("players").list(value => ({ actor: readSavedActor(value.field("actor")), state: player(value.field("state")) })),
    squadSpawns: reader.field("squadSpawns").list(value => ({ actor: readSavedActor(value.field("actor")), origin: readVector(value.field("origin")), angles: readVector(value.field("angles")) })) };
}
export function readQ2RereleaseModuleCheckpoint(reader: SaveReader): Q2RereleaseModuleCheckpoint {
  const sky = reader.field("sky"), campaign = reader.field("campaign"), mission = campaign.field("mission"), goals = reader.field("goals");
  return { version: reader.field("version").literal(1), worldFog: readQ2FogState(reader.field("worldFog")), story: reader.field("story").string(), sky: { name: sky.field("name").string(), rotation: sky.field("rotation").number(), autoRotate: sky.field("autoRotate").boolean(), axis: readVector(sky.field("axis")) },
    poi: reader.field("poi").nullable(value => ({ actor: readSavedActor(value.field("actor")), origin: readVector(value.field("origin")), image: value.field("image").string(), dynamic: value.field("dynamic").nullable(readSavedActor) })),
    poiStage: reader.field("poiStage").number(), lastAutoSave: reader.field("lastAutoSave").number(), goals: { goals: goals.field("goals").nullable(value => value.string()), goalNumber: goals.field("goalNumber").number() }, campaign: { mission: { primary: mission.field("primary").string(), secondary: mission.field("secondary").string(), primaryChanges: mission.field("primaryChanges").number(), secondaryChanges: mission.field("secondaryChanges").number() }, crossUnitFlags: campaign.field("crossUnitFlags").number(), visitedMaps: campaign.field("visitedMaps").list(value => value.string()), levels: campaign.field("levels").list(value => ({ map: value.field("map").string(), name: value.field("name").string(), visitOrder: value.field("visitOrder").number(), totalSecrets: value.field("totalSecrets").number(), foundSecrets: value.field("foundSecrets").number(), totalMonsters: value.field("totalMonsters").number(), killedMonsters: value.field("killedMonsters").number(), time: value.field("time").number() })) }, q64: readQ2RereleaseQ64Checkpoint(reader.field("q64")), lights: reader.field("lights").list(value => ({ actor: readSavedActor(value.field("actor")), active: value.field("active").boolean() })),
    healthBars: reader.field("healthBars").list(value => value.nullable(bar => ({ controller: readSavedActor(bar.field("controller")), target: readSavedActor(bar.field("target")), deadUntil: bar.field("deadUntil").nullable(time => time.number()) }))),
    healthTargets: reader.field("healthTargets").list(value => ({ controller: readSavedActor(value.field("controller")), target: readSavedActor(value.field("target")) })),
    pickedUpBy: reader.field("pickedUpBy").list(value => ({ actor: readSavedActor(value.field("actor")), slots: value.field("slots").list(slot => slot.integer(0)) })), triggerSoundTimes: reader.field("triggerSoundTimes").list(value => ({ actor: readSavedActor(value.field("actor")), time: value.field("time").number() })) };
}
export function readQ2RereleaseQ64Checkpoint(reader: SaveReader): Q2RereleaseQ64Checkpoint {
  return {
    eyes: reader.field("eyes").list(value => { const state = value.field("state"); return { actor: readSavedActor(value.field("actor")), state: { neutralAngles: readVector(state.field("neutralAngles")), eyePosition: readVector(state.field("eyePosition")), visionCone: state.field("visionCone").number() } }; }),
    cameras: reader.field("cameras").list(value => { const state = value.field("state"); return { actor: readSavedActor(value.field("actor")), state: { remaining: state.field("remaining").number(), distance: state.field("distance").number(), speed: state.field("speed").number(), angles: readVector(state.field("angles")) } }; }),
    dummies: reader.field("dummies").list(value => { const state = value.field("state"); return { actor: readSavedActor(value.field("actor")), state: { fadeRemaining: state.field("fadeRemaining").number(), fadeDuration: state.field("fadeDuration").number(), fading: state.field("fading").boolean() } }; }),
  };
}
export function encodeQ2RereleasePlayersCheckpoint(checkpoint: Q2RereleasePlayersCheckpoint): Uint8Array { return encodeCheckpointValue(checkpoint); }
export function decodeQ2RereleasePlayersCheckpoint(bytes: Uint8Array): Q2RereleasePlayersCheckpoint { return readQ2RereleasePlayersCheckpoint(new SaveReader(decodeCheckpointValue(bytes), "q2-rerelease-players")); }
export function encodeQ2RereleaseModuleCheckpoint(checkpoint: Q2RereleaseModuleCheckpoint): Uint8Array { return encodeCheckpointValue(checkpoint); }
export function decodeQ2RereleaseModuleCheckpoint(bytes: Uint8Array): Q2RereleaseModuleCheckpoint { return readQ2RereleaseModuleCheckpoint(new SaveReader(decodeCheckpointValue(bytes), "q2-rerelease-module")); }
