/* Original Quake II rogue/m_hover.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const hoverMoves: readonly MonsterMove[] = [
  { name: "hover_move_stand", firstFrame: 0, lastFrame: 29, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_pain3", firstFrame: 153, lastFrame: 161, end: "hover_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_pain2", firstFrame: 141, lastFrame: 152, end: "hover_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_pain1", firstFrame: 113, lastFrame: 140, end: "hover_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_walk", firstFrame: 30, lastFrame: 64, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_run", firstFrame: 30, lastFrame: 64, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_death1", firstFrame: 162, lastFrame: 172, end: "hover_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 7, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_start_attack", firstFrame: 197, lastFrame: 199, end: "hover_attack", sidestepScale: 0, frames: [
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_attack1", firstFrame: 200, lastFrame: 202, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: -10, actions: ["hover_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: ["hover_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["hover_reattack"], lerpFrame: -1 },
  ] },
  { name: "hover_move_end_attack", firstFrame: 203, lastFrame: 204, end: "hover_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_start_attack2", firstFrame: 197, lastFrame: 199, end: "hover_attack", sidestepScale: 0, frames: [
    { ai: "charge", distance: 15, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 15, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 15, actions: [], lerpFrame: -1 },
  ] },
  { name: "hover_move_attack2", firstFrame: 200, lastFrame: 202, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 10, actions: ["hover_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 10, actions: ["hover_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 10, actions: ["hover_reattack"], lerpFrame: -1 },
  ] },
  { name: "hover_move_end_attack2", firstFrame: 203, lastFrame: 204, end: "hover_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 15, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 15, actions: [], lerpFrame: -1 },
  ] },
];

export const hoverFrame = Object.freeze({
  "stand01": 0,
  "stand02": 1,
  "stand03": 2,
  "stand04": 3,
  "stand05": 4,
  "stand06": 5,
  "stand07": 6,
  "stand08": 7,
  "stand09": 8,
  "stand10": 9,
  "stand11": 10,
  "stand12": 11,
  "stand13": 12,
  "stand14": 13,
  "stand15": 14,
  "stand16": 15,
  "stand17": 16,
  "stand18": 17,
  "stand19": 18,
  "stand20": 19,
  "stand21": 20,
  "stand22": 21,
  "stand23": 22,
  "stand24": 23,
  "stand25": 24,
  "stand26": 25,
  "stand27": 26,
  "stand28": 27,
  "stand29": 28,
  "stand30": 29,
  "forwrd01": 30,
  "forwrd02": 31,
  "forwrd03": 32,
  "forwrd04": 33,
  "forwrd05": 34,
  "forwrd06": 35,
  "forwrd07": 36,
  "forwrd08": 37,
  "forwrd09": 38,
  "forwrd10": 39,
  "forwrd11": 40,
  "forwrd12": 41,
  "forwrd13": 42,
  "forwrd14": 43,
  "forwrd15": 44,
  "forwrd16": 45,
  "forwrd17": 46,
  "forwrd18": 47,
  "forwrd19": 48,
  "forwrd20": 49,
  "forwrd21": 50,
  "forwrd22": 51,
  "forwrd23": 52,
  "forwrd24": 53,
  "forwrd25": 54,
  "forwrd26": 55,
  "forwrd27": 56,
  "forwrd28": 57,
  "forwrd29": 58,
  "forwrd30": 59,
  "forwrd31": 60,
  "forwrd32": 61,
  "forwrd33": 62,
  "forwrd34": 63,
  "forwrd35": 64,
  "stop101": 65,
  "stop102": 66,
  "stop103": 67,
  "stop104": 68,
  "stop105": 69,
  "stop106": 70,
  "stop107": 71,
  "stop108": 72,
  "stop109": 73,
  "stop201": 74,
  "stop202": 75,
  "stop203": 76,
  "stop204": 77,
  "stop205": 78,
  "stop206": 79,
  "stop207": 80,
  "stop208": 81,
  "takeof01": 82,
  "takeof02": 83,
  "takeof03": 84,
  "takeof04": 85,
  "takeof05": 86,
  "takeof06": 87,
  "takeof07": 88,
  "takeof08": 89,
  "takeof09": 90,
  "takeof10": 91,
  "takeof11": 92,
  "takeof12": 93,
  "takeof13": 94,
  "takeof14": 95,
  "takeof15": 96,
  "takeof16": 97,
  "takeof17": 98,
  "takeof18": 99,
  "takeof19": 100,
  "takeof20": 101,
  "takeof21": 102,
  "takeof22": 103,
  "takeof23": 104,
  "takeof24": 105,
  "takeof25": 106,
  "takeof26": 107,
  "takeof27": 108,
  "takeof28": 109,
  "takeof29": 110,
  "takeof30": 111,
  "land01": 112,
  "pain101": 113,
  "pain102": 114,
  "pain103": 115,
  "pain104": 116,
  "pain105": 117,
  "pain106": 118,
  "pain107": 119,
  "pain108": 120,
  "pain109": 121,
  "pain110": 122,
  "pain111": 123,
  "pain112": 124,
  "pain113": 125,
  "pain114": 126,
  "pain115": 127,
  "pain116": 128,
  "pain117": 129,
  "pain118": 130,
  "pain119": 131,
  "pain120": 132,
  "pain121": 133,
  "pain122": 134,
  "pain123": 135,
  "pain124": 136,
  "pain125": 137,
  "pain126": 138,
  "pain127": 139,
  "pain128": 140,
  "pain201": 141,
  "pain202": 142,
  "pain203": 143,
  "pain204": 144,
  "pain205": 145,
  "pain206": 146,
  "pain207": 147,
  "pain208": 148,
  "pain209": 149,
  "pain210": 150,
  "pain211": 151,
  "pain212": 152,
  "pain301": 153,
  "pain302": 154,
  "pain303": 155,
  "pain304": 156,
  "pain305": 157,
  "pain306": 158,
  "pain307": 159,
  "pain308": 160,
  "pain309": 161,
  "death101": 162,
  "death102": 163,
  "death103": 164,
  "death104": 165,
  "death105": 166,
  "death106": 167,
  "death107": 168,
  "death108": 169,
  "death109": 170,
  "death110": 171,
  "death111": 172,
  "backwd01": 173,
  "backwd02": 174,
  "backwd03": 175,
  "backwd04": 176,
  "backwd05": 177,
  "backwd06": 178,
  "backwd07": 179,
  "backwd08": 180,
  "backwd09": 181,
  "backwd10": 182,
  "backwd11": 183,
  "backwd12": 184,
  "backwd13": 185,
  "backwd14": 186,
  "backwd15": 187,
  "backwd16": 188,
  "backwd17": 189,
  "backwd18": 190,
  "backwd19": 191,
  "backwd20": 192,
  "backwd21": 193,
  "backwd22": 194,
  "backwd23": 195,
  "backwd24": 196,
  "attak101": 197,
  "attak102": 198,
  "attak103": 199,
  "attak104": 200,
  "attak105": 201,
  "attak106": 202,
  "attak107": 203,
  "attak108": 204
});
