/* Original Quake II rogue/m_carrier.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const carrierMoves: readonly MonsterMove[] = [
  { name: "carrier_move_stand", firstFrame: 0, lastFrame: 12, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "carrier_move_walk", firstFrame: 0, lastFrame: 12, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "carrier_move_run", firstFrame: 0, lastFrame: 12, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_pre_mg", firstFrame: 13, lastFrame: 20, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["carrier_attack_mg"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_mg", firstFrame: 21, lastFrame: 23, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["carrier_reattack_mg"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_post_mg", firstFrame: 24, lastFrame: 27, end: "carrier_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_pre_gren", firstFrame: 28, lastFrame: 33, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["carrier_attack_gren"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_gren", firstFrame: 34, lastFrame: 37, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: -15, actions: ["CarrierGrenade"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["carrier_reattack_gren"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_post_gren", firstFrame: 38, lastFrame: 43, end: "carrier_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_rocket", firstFrame: 28, lastFrame: 28, end: "carrier_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 15, actions: ["CarrierRocket"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_attack_rail", firstFrame: 0, lastFrame: 8, end: "carrier_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 2, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["CarrierSaveLoc"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: -20, actions: ["CarrierRail"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["CarrierCoopCheck"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_spawn", firstFrame: 44, lastFrame: 61, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["carrier_prep_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["carrier_start_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["carrier_ready_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: ["carrier_spawn_check"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["CarrierMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: ["carrier_reattack_mg"], lerpFrame: -1 },
  ] },
  { name: "carrier_move_pain_heavy", firstFrame: 62, lastFrame: 71, end: "carrier_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "carrier_move_pain_light", firstFrame: 44, lastFrame: 47, end: "carrier_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "carrier_move_death", firstFrame: 62, lastFrame: 77, end: "carrier_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["BossExplode"], lerpFrame: -1 },
  ] },
];

export const carrierFrame = Object.freeze({
  "search01": 0,
  "search02": 1,
  "search03": 2,
  "search04": 3,
  "search05": 4,
  "search06": 5,
  "search07": 6,
  "search08": 7,
  "search09": 8,
  "search10": 9,
  "search11": 10,
  "search12": 11,
  "search13": 12,
  "firea01": 13,
  "firea02": 14,
  "firea03": 15,
  "firea04": 16,
  "firea05": 17,
  "firea06": 18,
  "firea07": 19,
  "firea08": 20,
  "firea09": 21,
  "firea10": 22,
  "firea11": 23,
  "firea12": 24,
  "firea13": 25,
  "firea14": 26,
  "firea15": 27,
  "fireb01": 28,
  "fireb02": 29,
  "fireb03": 30,
  "fireb04": 31,
  "fireb05": 32,
  "fireb06": 33,
  "fireb07": 34,
  "fireb08": 35,
  "fireb09": 36,
  "fireb10": 37,
  "fireb11": 38,
  "fireb12": 39,
  "fireb13": 40,
  "fireb14": 41,
  "fireb15": 42,
  "fireb16": 43,
  "spawn01": 44,
  "spawn02": 45,
  "spawn03": 46,
  "spawn04": 47,
  "spawn05": 48,
  "spawn06": 49,
  "spawn07": 50,
  "spawn08": 51,
  "spawn09": 52,
  "spawn10": 53,
  "spawn11": 54,
  "spawn12": 55,
  "spawn13": 56,
  "spawn14": 57,
  "spawn15": 58,
  "spawn16": 59,
  "spawn17": 60,
  "spawn18": 61,
  "death01": 62,
  "death02": 63,
  "death03": 64,
  "death04": 65,
  "death05": 66,
  "death06": 67,
  "death07": 68,
  "death08": 69,
  "death09": 70,
  "death10": 71,
  "death11": 72,
  "death12": 73,
  "death13": 74,
  "death14": 75,
  "death15": 76,
  "death16": 77
});
