/* Original Quake II rogue/m_berserk.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const berserkMoves: readonly MonsterMove[] = [
  { name: "berserk_move_stand", firstFrame: 0, lastFrame: 4, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: ["berserk_fidget"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_stand_fidget", firstFrame: 5, lastFrame: 24, end: "berserk_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_walk", firstFrame: 25, lastFrame: 35, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 9.1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.8, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_run1", firstFrame: 36, lastFrame: 41, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 21, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 11, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 21, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 25, actions: ["monster_done_dodge"], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 19, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_attack_spike", firstFrame: 76, lastFrame: 83, end: "berserk_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["berserk_swing"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["berserk_attack_spike"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_attack_club", firstFrame: 84, lastFrame: 95, end: "berserk_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["berserk_swing"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["berserk_attack_club"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_attack_strike", firstFrame: 96, lastFrame: 109, end: "berserk_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["berserk_swing"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["berserk_strike"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 9.7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 13.6, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_pain1", firstFrame: 199, lastFrame: 202, end: "berserk_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_pain2", firstFrame: 203, lastFrame: 222, end: "berserk_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_death1", firstFrame: 223, lastFrame: 235, end: "berserk_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_death2", firstFrame: 236, lastFrame: 243, end: "berserk_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_jump", firstFrame: 244, lastFrame: 252, end: "berserk_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["berserk_jump_now"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["berserk_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "berserk_move_jump2", firstFrame: 244, lastFrame: 252, end: "berserk_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["berserk_jump_now"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["berserk_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const berserkFrame = Object.freeze({
  "stand1": 0,
  "stand2": 1,
  "stand3": 2,
  "stand4": 3,
  "stand5": 4,
  "standb1": 5,
  "standb2": 6,
  "standb3": 7,
  "standb4": 8,
  "standb5": 9,
  "standb6": 10,
  "standb7": 11,
  "standb8": 12,
  "standb9": 13,
  "standb10": 14,
  "standb11": 15,
  "standb12": 16,
  "standb13": 17,
  "standb14": 18,
  "standb15": 19,
  "standb16": 20,
  "standb17": 21,
  "standb18": 22,
  "standb19": 23,
  "standb20": 24,
  "walkc1": 25,
  "walkc2": 26,
  "walkc3": 27,
  "walkc4": 28,
  "walkc5": 29,
  "walkc6": 30,
  "walkc7": 31,
  "walkc8": 32,
  "walkc9": 33,
  "walkc10": 34,
  "walkc11": 35,
  "run1": 36,
  "run2": 37,
  "run3": 38,
  "run4": 39,
  "run5": 40,
  "run6": 41,
  "att_a1": 42,
  "att_a2": 43,
  "att_a3": 44,
  "att_a4": 45,
  "att_a5": 46,
  "att_a6": 47,
  "att_a7": 48,
  "att_a8": 49,
  "att_a9": 50,
  "att_a10": 51,
  "att_a11": 52,
  "att_a12": 53,
  "att_a13": 54,
  "att_b1": 55,
  "att_b2": 56,
  "att_b3": 57,
  "att_b4": 58,
  "att_b5": 59,
  "att_b6": 60,
  "att_b7": 61,
  "att_b8": 62,
  "att_b9": 63,
  "att_b10": 64,
  "att_b11": 65,
  "att_b12": 66,
  "att_b13": 67,
  "att_b14": 68,
  "att_b15": 69,
  "att_b16": 70,
  "att_b17": 71,
  "att_b18": 72,
  "att_b19": 73,
  "att_b20": 74,
  "att_b21": 75,
  "att_c1": 76,
  "att_c2": 77,
  "att_c3": 78,
  "att_c4": 79,
  "att_c5": 80,
  "att_c6": 81,
  "att_c7": 82,
  "att_c8": 83,
  "att_c9": 84,
  "att_c10": 85,
  "att_c11": 86,
  "att_c12": 87,
  "att_c13": 88,
  "att_c14": 89,
  "att_c15": 90,
  "att_c16": 91,
  "att_c17": 92,
  "att_c18": 93,
  "att_c19": 94,
  "att_c20": 95,
  "att_c21": 96,
  "att_c22": 97,
  "att_c23": 98,
  "att_c24": 99,
  "att_c25": 100,
  "att_c26": 101,
  "att_c27": 102,
  "att_c28": 103,
  "att_c29": 104,
  "att_c30": 105,
  "att_c31": 106,
  "att_c32": 107,
  "att_c33": 108,
  "att_c34": 109,
  "r_att1": 110,
  "r_att2": 111,
  "r_att3": 112,
  "r_att4": 113,
  "r_att5": 114,
  "r_att6": 115,
  "r_att7": 116,
  "r_att8": 117,
  "r_att9": 118,
  "r_att10": 119,
  "r_att11": 120,
  "r_att12": 121,
  "r_att13": 122,
  "r_att14": 123,
  "r_att15": 124,
  "r_att16": 125,
  "r_att17": 126,
  "r_att18": 127,
  "r_attb1": 128,
  "r_attb2": 129,
  "r_attb3": 130,
  "r_attb4": 131,
  "r_attb5": 132,
  "r_attb6": 133,
  "r_attb7": 134,
  "r_attb8": 135,
  "r_attb9": 136,
  "r_attb10": 137,
  "r_attb11": 138,
  "r_attb12": 139,
  "r_attb13": 140,
  "r_attb14": 141,
  "r_attb15": 142,
  "r_attb16": 143,
  "r_attb17": 144,
  "r_attb18": 145,
  "slam1": 146,
  "slam2": 147,
  "slam3": 148,
  "slam4": 149,
  "slam5": 150,
  "slam6": 151,
  "slam7": 152,
  "slam8": 153,
  "slam9": 154,
  "slam10": 155,
  "slam11": 156,
  "slam12": 157,
  "slam13": 158,
  "slam14": 159,
  "slam15": 160,
  "slam16": 161,
  "slam17": 162,
  "slam18": 163,
  "slam19": 164,
  "slam20": 165,
  "slam21": 166,
  "slam22": 167,
  "slam23": 168,
  "duck1": 169,
  "duck2": 170,
  "duck3": 171,
  "duck4": 172,
  "duck5": 173,
  "duck6": 174,
  "duck7": 175,
  "duck8": 176,
  "duck9": 177,
  "duck10": 178,
  "fall1": 179,
  "fall2": 180,
  "fall3": 181,
  "fall4": 182,
  "fall5": 183,
  "fall6": 184,
  "fall7": 185,
  "fall8": 186,
  "fall9": 187,
  "fall10": 188,
  "fall11": 189,
  "fall12": 190,
  "fall13": 191,
  "fall14": 192,
  "fall15": 193,
  "fall16": 194,
  "fall17": 195,
  "fall18": 196,
  "fall19": 197,
  "fall20": 198,
  "painc1": 199,
  "painc2": 200,
  "painc3": 201,
  "painc4": 202,
  "painb1": 203,
  "painb2": 204,
  "painb3": 205,
  "painb4": 206,
  "painb5": 207,
  "painb6": 208,
  "painb7": 209,
  "painb8": 210,
  "painb9": 211,
  "painb10": 212,
  "painb11": 213,
  "painb12": 214,
  "painb13": 215,
  "painb14": 216,
  "painb15": 217,
  "painb16": 218,
  "painb17": 219,
  "painb18": 220,
  "painb19": 221,
  "painb20": 222,
  "death1": 223,
  "death2": 224,
  "death3": 225,
  "death4": 226,
  "death5": 227,
  "death6": 228,
  "death7": 229,
  "death8": 230,
  "death9": 231,
  "death10": 232,
  "death11": 233,
  "death12": 234,
  "death13": 235,
  "deathc1": 236,
  "deathc2": 237,
  "deathc3": 238,
  "deathc4": 239,
  "deathc5": 240,
  "deathc6": 241,
  "deathc7": 242,
  "deathc8": 243,
  "jump1": 244,
  "jump2": 245,
  "jump3": 246,
  "jump4": 247,
  "jump5": 248,
  "jump6": 249,
  "jump7": 250,
  "jump8": 251,
  "jump9": 252
});
