/* Original Quake II rogue/m_stalker.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const stalkerMoves: readonly MonsterMove[] = [
  { name: "stalker_move_idle", firstFrame: 0, lastFrame: 20, end: "stalker_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["stalker_idle_noise"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_idle2", firstFrame: 21, lastFrame: 33, end: "stalker_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_stand", firstFrame: 0, lastFrame: 20, end: "stalker_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["stalker_idle_noise"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_run", firstFrame: 49, lastFrame: 52, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 17, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 21, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_walk", firstFrame: 34, lastFrame: 41, end: "stalker_walk", sidestepScale: 0, frames: [
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_false_death_end", firstFrame: 89, lastFrame: 92, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_false_death", firstFrame: 79, lastFrame: 88, end: "stalker_false_death", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_heal"], lerpFrame: -1 },
  ] },
  { name: "stalker_move_false_death_start", firstFrame: 70, lastFrame: 78, end: "stalker_false_death", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_pain", firstFrame: 66, lastFrame: 69, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_shoot", firstFrame: 49, lastFrame: 52, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 17, actions: ["stalker_shoot_attack"], lerpFrame: -1 },
    { ai: "charge", distance: 21, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 18, actions: ["stalker_shoot_attack2"], lerpFrame: -1 },
  ] },
  { name: "stalker_move_swing_l", firstFrame: 53, lastFrame: 60, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: ["stalker_swing_attack"], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_swing_r", firstFrame: 61, lastFrame: 65, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: ["stalker_swing_attack"], lerpFrame: -1 },
    { ai: "charge", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_jump_straightup", firstFrame: 45, lastFrame: 48, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 1, actions: ["stalker_jump_straightup"], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: ["stalker_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_dodge_run", firstFrame: 49, lastFrame: 52, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 17, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 21, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: ["monster_done_dodge"], lerpFrame: -1 },
  ] },
  { name: "stalker_move_jump_up", firstFrame: 42, lastFrame: 48, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_jump_up"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_jump_down", firstFrame: 42, lastFrame: 48, end: "stalker_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_jump_down"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["stalker_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "stalker_move_death", firstFrame: 70, lastFrame: 78, end: "stalker_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -20, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const stalkerFrame = Object.freeze({
  "idle01": 0,
  "idle02": 1,
  "idle03": 2,
  "idle04": 3,
  "idle05": 4,
  "idle06": 5,
  "idle07": 6,
  "idle08": 7,
  "idle09": 8,
  "idle10": 9,
  "idle11": 10,
  "idle12": 11,
  "idle13": 12,
  "idle14": 13,
  "idle15": 14,
  "idle16": 15,
  "idle17": 16,
  "idle18": 17,
  "idle19": 18,
  "idle20": 19,
  "idle21": 20,
  "idle201": 21,
  "idle202": 22,
  "idle203": 23,
  "idle204": 24,
  "idle205": 25,
  "idle206": 26,
  "idle207": 27,
  "idle208": 28,
  "idle209": 29,
  "idle210": 30,
  "idle211": 31,
  "idle212": 32,
  "idle213": 33,
  "walk01": 34,
  "walk02": 35,
  "walk03": 36,
  "walk04": 37,
  "walk05": 38,
  "walk06": 39,
  "walk07": 40,
  "walk08": 41,
  "jump01": 42,
  "jump02": 43,
  "jump03": 44,
  "jump04": 45,
  "jump05": 46,
  "jump06": 47,
  "jump07": 48,
  "run01": 49,
  "run02": 50,
  "run03": 51,
  "run04": 52,
  "attack01": 53,
  "attack02": 54,
  "attack03": 55,
  "attack04": 56,
  "attack05": 57,
  "attack06": 58,
  "attack07": 59,
  "attack08": 60,
  "attack11": 61,
  "attack12": 62,
  "attack13": 63,
  "attack14": 64,
  "attack15": 65,
  "pain01": 66,
  "pain02": 67,
  "pain03": 68,
  "pain04": 69,
  "death01": 70,
  "death02": 71,
  "death03": 72,
  "death04": 73,
  "death05": 74,
  "death06": 75,
  "death07": 76,
  "death08": 77,
  "death09": 78,
  "twitch01": 79,
  "twitch02": 80,
  "twitch03": 81,
  "twitch04": 82,
  "twitch05": 83,
  "twitch06": 84,
  "twitch07": 85,
  "twitch08": 86,
  "twitch09": 87,
  "twitch10": 88,
  "reactive01": 89,
  "reactive02": 90,
  "reactive03": 91,
  "reactive04": 92
});
