/* Original Rogue m_infantry.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const infantryMoves: readonly MonsterMove[] = [
  { name: "infantry_move_stand", firstFrame: 50, lastFrame: 71, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_fidget", firstFrame: 1, lastFrame: 49, end: "infantry_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: -2, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_walk", firstFrame: 74, lastFrame: 85, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_run", firstFrame: 92, lastFrame: 99, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 20, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 7, actions: ["monster_done_dodge"], lerpFrame: -1 },
    { ai: "run", distance: 30, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 35, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_pain1", firstFrame: 100, lastFrame: 109, end: "infantry_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_pain2", firstFrame: 110, lastFrame: 119, end: "infantry_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_death1", firstFrame: 125, lastFrame: 144, end: "infantry_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_death2", firstFrame: 145, lastFrame: 169, end: "infantry_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -7, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -8, actions: ["InfantryMachineGun"], lerpFrame: -1 },
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_death3", firstFrame: 170, lastFrame: 178, end: "infantry_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -11, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -11, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_duck", firstFrame: 120, lastFrame: 124, end: "infantry_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -2, actions: ["monster_duck_down"], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: ["monster_duck_hold"], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: ["monster_duck_up"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_attack1", firstFrame: 184, lastFrame: 198, end: "infantry_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -1, actions: ["infantry_fire_prep"], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: ["infantry_fire"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["infantry_cock_gun"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_attack2", firstFrame: 199, lastFrame: 206, end: "infantry_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["infantry_swing"], lerpFrame: -1 },
    { ai: "charge", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 8, actions: ["infantry_smack"], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 3, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_jump", firstFrame: 207, lastFrame: 216, end: "infantry_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["infantry_jump_now"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["infantry_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "infantry_move_jump2", firstFrame: 207, lastFrame: 216, end: "infantry_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["infantry_jump_now"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["infantry_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const infantryFrame = {
  gun02: 0,
  stand01: 1,
  stand02: 2,
  stand03: 3,
  stand04: 4,
  stand05: 5,
  stand06: 6,
  stand07: 7,
  stand08: 8,
  stand09: 9,
  stand10: 10,
  stand11: 11,
  stand12: 12,
  stand13: 13,
  stand14: 14,
  stand15: 15,
  stand16: 16,
  stand17: 17,
  stand18: 18,
  stand19: 19,
  stand20: 20,
  stand21: 21,
  stand22: 22,
  stand23: 23,
  stand24: 24,
  stand25: 25,
  stand26: 26,
  stand27: 27,
  stand28: 28,
  stand29: 29,
  stand30: 30,
  stand31: 31,
  stand32: 32,
  stand33: 33,
  stand34: 34,
  stand35: 35,
  stand36: 36,
  stand37: 37,
  stand38: 38,
  stand39: 39,
  stand40: 40,
  stand41: 41,
  stand42: 42,
  stand43: 43,
  stand44: 44,
  stand45: 45,
  stand46: 46,
  stand47: 47,
  stand48: 48,
  stand49: 49,
  stand50: 50,
  stand51: 51,
  stand52: 52,
  stand53: 53,
  stand54: 54,
  stand55: 55,
  stand56: 56,
  stand57: 57,
  stand58: 58,
  stand59: 59,
  stand60: 60,
  stand61: 61,
  stand62: 62,
  stand63: 63,
  stand64: 64,
  stand65: 65,
  stand66: 66,
  stand67: 67,
  stand68: 68,
  stand69: 69,
  stand70: 70,
  stand71: 71,
  walk01: 72,
  walk02: 73,
  walk03: 74,
  walk04: 75,
  walk05: 76,
  walk06: 77,
  walk07: 78,
  walk08: 79,
  walk09: 80,
  walk10: 81,
  walk11: 82,
  walk12: 83,
  walk13: 84,
  walk14: 85,
  walk15: 86,
  walk16: 87,
  walk17: 88,
  walk18: 89,
  walk19: 90,
  walk20: 91,
  run01: 92,
  run02: 93,
  run03: 94,
  run04: 95,
  run05: 96,
  run06: 97,
  run07: 98,
  run08: 99,
  pain101: 100,
  pain102: 101,
  pain103: 102,
  pain104: 103,
  pain105: 104,
  pain106: 105,
  pain107: 106,
  pain108: 107,
  pain109: 108,
  pain110: 109,
  pain201: 110,
  pain202: 111,
  pain203: 112,
  pain204: 113,
  pain205: 114,
  pain206: 115,
  pain207: 116,
  pain208: 117,
  pain209: 118,
  pain210: 119,
  duck01: 120,
  duck02: 121,
  duck03: 122,
  duck04: 123,
  duck05: 124,
  death101: 125,
  death102: 126,
  death103: 127,
  death104: 128,
  death105: 129,
  death106: 130,
  death107: 131,
  death108: 132,
  death109: 133,
  death110: 134,
  death111: 135,
  death112: 136,
  death113: 137,
  death114: 138,
  death115: 139,
  death116: 140,
  death117: 141,
  death118: 142,
  death119: 143,
  death120: 144,
  death201: 145,
  death202: 146,
  death203: 147,
  death204: 148,
  death205: 149,
  death206: 150,
  death207: 151,
  death208: 152,
  death209: 153,
  death210: 154,
  death211: 155,
  death212: 156,
  death213: 157,
  death214: 158,
  death215: 159,
  death216: 160,
  death217: 161,
  death218: 162,
  death219: 163,
  death220: 164,
  death221: 165,
  death222: 166,
  death223: 167,
  death224: 168,
  death225: 169,
  death301: 170,
  death302: 171,
  death303: 172,
  death304: 173,
  death305: 174,
  death306: 175,
  death307: 176,
  death308: 177,
  death309: 178,
  block01: 179,
  block02: 180,
  block03: 181,
  block04: 182,
  block05: 183,
  attak101: 184,
  attak102: 185,
  attak103: 186,
  attak104: 187,
  attak105: 188,
  attak106: 189,
  attak107: 190,
  attak108: 191,
  attak109: 192,
  attak110: 193,
  attak111: 194,
  attak112: 195,
  attak113: 196,
  attak114: 197,
  attak115: 198,
  attak201: 199,
  attak202: 200,
  attak203: 201,
  attak204: 202,
  attak205: 203,
  attak206: 204,
  attak207: 205,
  attak208: 206,
  jump01: 207,
  jump02: 208,
  jump03: 209,
  jump04: 210,
  jump05: 211,
  jump06: 212,
  jump07: 213,
  jump08: 214,
  jump09: 215,
  jump10: 216,
};
