/* Original Quake II rogue/m_medic.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const medicMoves: readonly MonsterMove[] = [
  { name: "medic_move_stand", firstFrame: 12, lastFrame: 101, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: ["medic_idle"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_walk", firstFrame: 0, lastFrame: 11, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 6.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 18.1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 11, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 11.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 9.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 9.3, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_run", firstFrame: 102, lastFrame: 107, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22.5, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 25.4, actions: ["monster_done_dodge"], lerpFrame: -1 },
    { ai: "run", distance: 23.4, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 24, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 35.6, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_pain1", firstFrame: 108, lastFrame: 115, end: "medic_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_pain2", firstFrame: 116, lastFrame: 130, end: "medic_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_death", firstFrame: 147, lastFrame: 176, end: "medic_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_duck", firstFrame: 131, lastFrame: 146, end: "medic_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: ["monster_duck_down"], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: ["monster_duck_hold"], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: ["monster_duck_up"], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_attackHyperBlaster", firstFrame: 191, lastFrame: 206, end: "medic_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
  ] },
  { name: "medic_move_attackBlaster", firstFrame: 177, lastFrame: 190, end: "medic_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_continue"], lerpFrame: -1 },
  ] },
  { name: "medic_move_attackCable", firstFrame: 209, lastFrame: 236, end: "medic_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -4.4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -4.7, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_hook_launch"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_cable_attack"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_hook_retract"], lerpFrame: -1 },
    { ai: "move", distance: -1.5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1.3, actions: [], lerpFrame: -1 },
  ] },
  { name: "medic_move_callReinforcements", firstFrame: 209, lastFrame: 236, end: "medic_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4.4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4.7, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_start_spawn"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["medic_determine_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["medic_spawngrows"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -15, actions: ["medic_finish_spawn"], lerpFrame: -1 },
    { ai: "move", distance: -1.5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1.3, actions: [], lerpFrame: -1 },
  ] },
];

export const medicFrame = Object.freeze({
  "walk1": 0,
  "walk2": 1,
  "walk3": 2,
  "walk4": 3,
  "walk5": 4,
  "walk6": 5,
  "walk7": 6,
  "walk8": 7,
  "walk9": 8,
  "walk10": 9,
  "walk11": 10,
  "walk12": 11,
  "wait1": 12,
  "wait2": 13,
  "wait3": 14,
  "wait4": 15,
  "wait5": 16,
  "wait6": 17,
  "wait7": 18,
  "wait8": 19,
  "wait9": 20,
  "wait10": 21,
  "wait11": 22,
  "wait12": 23,
  "wait13": 24,
  "wait14": 25,
  "wait15": 26,
  "wait16": 27,
  "wait17": 28,
  "wait18": 29,
  "wait19": 30,
  "wait20": 31,
  "wait21": 32,
  "wait22": 33,
  "wait23": 34,
  "wait24": 35,
  "wait25": 36,
  "wait26": 37,
  "wait27": 38,
  "wait28": 39,
  "wait29": 40,
  "wait30": 41,
  "wait31": 42,
  "wait32": 43,
  "wait33": 44,
  "wait34": 45,
  "wait35": 46,
  "wait36": 47,
  "wait37": 48,
  "wait38": 49,
  "wait39": 50,
  "wait40": 51,
  "wait41": 52,
  "wait42": 53,
  "wait43": 54,
  "wait44": 55,
  "wait45": 56,
  "wait46": 57,
  "wait47": 58,
  "wait48": 59,
  "wait49": 60,
  "wait50": 61,
  "wait51": 62,
  "wait52": 63,
  "wait53": 64,
  "wait54": 65,
  "wait55": 66,
  "wait56": 67,
  "wait57": 68,
  "wait58": 69,
  "wait59": 70,
  "wait60": 71,
  "wait61": 72,
  "wait62": 73,
  "wait63": 74,
  "wait64": 75,
  "wait65": 76,
  "wait66": 77,
  "wait67": 78,
  "wait68": 79,
  "wait69": 80,
  "wait70": 81,
  "wait71": 82,
  "wait72": 83,
  "wait73": 84,
  "wait74": 85,
  "wait75": 86,
  "wait76": 87,
  "wait77": 88,
  "wait78": 89,
  "wait79": 90,
  "wait80": 91,
  "wait81": 92,
  "wait82": 93,
  "wait83": 94,
  "wait84": 95,
  "wait85": 96,
  "wait86": 97,
  "wait87": 98,
  "wait88": 99,
  "wait89": 100,
  "wait90": 101,
  "run1": 102,
  "run2": 103,
  "run3": 104,
  "run4": 105,
  "run5": 106,
  "run6": 107,
  "paina1": 108,
  "paina2": 109,
  "paina3": 110,
  "paina4": 111,
  "paina5": 112,
  "paina6": 113,
  "paina7": 114,
  "paina8": 115,
  "painb1": 116,
  "painb2": 117,
  "painb3": 118,
  "painb4": 119,
  "painb5": 120,
  "painb6": 121,
  "painb7": 122,
  "painb8": 123,
  "painb9": 124,
  "painb10": 125,
  "painb11": 126,
  "painb12": 127,
  "painb13": 128,
  "painb14": 129,
  "painb15": 130,
  "duck1": 131,
  "duck2": 132,
  "duck3": 133,
  "duck4": 134,
  "duck5": 135,
  "duck6": 136,
  "duck7": 137,
  "duck8": 138,
  "duck9": 139,
  "duck10": 140,
  "duck11": 141,
  "duck12": 142,
  "duck13": 143,
  "duck14": 144,
  "duck15": 145,
  "duck16": 146,
  "death1": 147,
  "death2": 148,
  "death3": 149,
  "death4": 150,
  "death5": 151,
  "death6": 152,
  "death7": 153,
  "death8": 154,
  "death9": 155,
  "death10": 156,
  "death11": 157,
  "death12": 158,
  "death13": 159,
  "death14": 160,
  "death15": 161,
  "death16": 162,
  "death17": 163,
  "death18": 164,
  "death19": 165,
  "death20": 166,
  "death21": 167,
  "death22": 168,
  "death23": 169,
  "death24": 170,
  "death25": 171,
  "death26": 172,
  "death27": 173,
  "death28": 174,
  "death29": 175,
  "death30": 176,
  "attack1": 177,
  "attack2": 178,
  "attack3": 179,
  "attack4": 180,
  "attack5": 181,
  "attack6": 182,
  "attack7": 183,
  "attack8": 184,
  "attack9": 185,
  "attack10": 186,
  "attack11": 187,
  "attack12": 188,
  "attack13": 189,
  "attack14": 190,
  "attack15": 191,
  "attack16": 192,
  "attack17": 193,
  "attack18": 194,
  "attack19": 195,
  "attack20": 196,
  "attack21": 197,
  "attack22": 198,
  "attack23": 199,
  "attack24": 200,
  "attack25": 201,
  "attack26": 202,
  "attack27": 203,
  "attack28": 204,
  "attack29": 205,
  "attack30": 206,
  "attack31": 207,
  "attack32": 208,
  "attack33": 209,
  "attack34": 210,
  "attack35": 211,
  "attack36": 212,
  "attack37": 213,
  "attack38": 214,
  "attack39": 215,
  "attack40": 216,
  "attack41": 217,
  "attack42": 218,
  "attack43": 219,
  "attack44": 220,
  "attack45": 221,
  "attack46": 222,
  "attack47": 223,
  "attack48": 224,
  "attack49": 225,
  "attack50": 226,
  "attack51": 227,
  "attack52": 228,
  "attack53": 229,
  "attack54": 230,
  "attack55": 231,
  "attack56": 232,
  "attack57": 233,
  "attack58": 234,
  "attack59": 235,
  "attack60": 236
});
