/* Original Quake II rogue/m_widow.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const widowMoves: readonly MonsterMove[] = [
  { name: "widow_move_stand", firstFrame: 0, lastFrame: 10, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow_move_walk", firstFrame: 11, lastFrame: 23, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 2.79, actions: ["widow_step"], lerpFrame: -1 },
    { ai: "walk", distance: 2.77, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.53, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.97, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.13, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.09, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.84, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.62, actions: ["widow_step"], lerpFrame: -1 },
    { ai: "walk", distance: 3.29, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.08, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.94, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5.73, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.85, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow_move_run", firstFrame: 11, lastFrame: 23, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 2.79, actions: ["widow_step"], lerpFrame: -1 },
    { ai: "run", distance: 2.77, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 3.53, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 3.97, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 4.13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 4.09, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 3.84, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 3.62, actions: ["widow_step"], lerpFrame: -1 },
    { ai: "run", distance: 3.29, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 6.08, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 6.94, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 5.73, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 2.85, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow_move_run_attack", firstFrame: 24, lastFrame: 31, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 13, actions: ["widow_stepshoot"], lerpFrame: -1 },
    { ai: "charge", distance: 11.72, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 18.04, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 14.58, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 13, actions: ["widow_stepshoot"], lerpFrame: -1 },
    { ai: "charge", distance: 12.12, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 19.63, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 11.37, actions: ["WidowBlaster"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_pre_blaster", firstFrame: 59, lastFrame: 61, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_attack_blaster"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_blaster", firstFrame: 61, lastFrame: 79, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_reattack_blaster"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_post_blaster", firstFrame: 80, lastFrame: 81, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_post_blaster_r", firstFrame: 116, lastFrame: 120, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_start_run_12"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_post_blaster_l", firstFrame: 121, lastFrame: 125, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 10, actions: ["widow_start_run_12"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_pre_rail", firstFrame: 126, lastFrame: 129, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["widow_start_rail"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_attack_rail"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_rail", firstFrame: 32, lastFrame: 40, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowSaveLoc"], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: ["WidowRail"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_rail_done"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_rail_r", firstFrame: 41, lastFrame: 49, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowSaveLoc"], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: ["WidowRail"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_rail_done"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_rail_l", firstFrame: 50, lastFrame: 58, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowSaveLoc"], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: ["WidowRail"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_rail_done"], lerpFrame: -1 },
  ] },
  { name: "widow_move_spawn", firstFrame: 82, lastFrame: 99, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_start_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_ready_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_spawn_check"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["WidowBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_done_spawn"], lerpFrame: -1 },
  ] },
  { name: "widow_move_pain_heavy", firstFrame: 100, lastFrame: 112, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow_move_pain_light", firstFrame: 113, lastFrame: 115, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow_move_death", firstFrame: 130, lastFrame: 160, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["spawn_out_start"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["spawn_out_do"], lerpFrame: -1 },
  ] },
  { name: "widow_move_attack_kick", firstFrame: 161, lastFrame: 168, end: "widow_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["widow_attack_kick"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const widowFrame = Object.freeze({
  "idle01": 0,
  "idle02": 1,
  "idle03": 2,
  "idle04": 3,
  "idle05": 4,
  "idle06": 5,
  "idle07": 6,
  "idle08": 7,
  "idle09": 8,
  "idle10": 9,
  "idle11": 10,
  "walk01": 11,
  "walk02": 12,
  "walk03": 13,
  "walk04": 14,
  "walk05": 15,
  "walk06": 16,
  "walk07": 17,
  "walk08": 18,
  "walk09": 19,
  "walk10": 20,
  "walk11": 21,
  "walk12": 22,
  "walk13": 23,
  "run01": 24,
  "run02": 25,
  "run03": 26,
  "run04": 27,
  "run05": 28,
  "run06": 29,
  "run07": 30,
  "run08": 31,
  "firea01": 32,
  "firea02": 33,
  "firea03": 34,
  "firea04": 35,
  "firea05": 36,
  "firea06": 37,
  "firea07": 38,
  "firea08": 39,
  "firea09": 40,
  "fireb01": 41,
  "fireb02": 42,
  "fireb03": 43,
  "fireb04": 44,
  "fireb05": 45,
  "fireb06": 46,
  "fireb07": 47,
  "fireb08": 48,
  "fireb09": 49,
  "firec01": 50,
  "firec02": 51,
  "firec03": 52,
  "firec04": 53,
  "firec05": 54,
  "firec06": 55,
  "firec07": 56,
  "firec08": 57,
  "firec09": 58,
  "fired01": 59,
  "fired02": 60,
  "fired02a": 61,
  "fired03": 62,
  "fired04": 63,
  "fired05": 64,
  "fired06": 65,
  "fired07": 66,
  "fired08": 67,
  "fired09": 68,
  "fired10": 69,
  "fired11": 70,
  "fired12": 71,
  "fired13": 72,
  "fired14": 73,
  "fired15": 74,
  "fired16": 75,
  "fired17": 76,
  "fired18": 77,
  "fired19": 78,
  "fired20": 79,
  "fired21": 80,
  "fired22": 81,
  "spawn01": 82,
  "spawn02": 83,
  "spawn03": 84,
  "spawn04": 85,
  "spawn05": 86,
  "spawn06": 87,
  "spawn07": 88,
  "spawn08": 89,
  "spawn09": 90,
  "spawn10": 91,
  "spawn11": 92,
  "spawn12": 93,
  "spawn13": 94,
  "spawn14": 95,
  "spawn15": 96,
  "spawn16": 97,
  "spawn17": 98,
  "spawn18": 99,
  "pain01": 100,
  "pain02": 101,
  "pain03": 102,
  "pain04": 103,
  "pain05": 104,
  "pain06": 105,
  "pain07": 106,
  "pain08": 107,
  "pain09": 108,
  "pain10": 109,
  "pain11": 110,
  "pain12": 111,
  "pain13": 112,
  "pain201": 113,
  "pain202": 114,
  "pain203": 115,
  "transa01": 116,
  "transa02": 117,
  "transa03": 118,
  "transa04": 119,
  "transa05": 120,
  "transb01": 121,
  "transb02": 122,
  "transb03": 123,
  "transb04": 124,
  "transb05": 125,
  "transc01": 126,
  "transc02": 127,
  "transc03": 128,
  "transc04": 129,
  "death01": 130,
  "death02": 131,
  "death03": 132,
  "death04": 133,
  "death05": 134,
  "death06": 135,
  "death07": 136,
  "death08": 137,
  "death09": 138,
  "death10": 139,
  "death11": 140,
  "death12": 141,
  "death13": 142,
  "death14": 143,
  "death15": 144,
  "death16": 145,
  "death17": 146,
  "death18": 147,
  "death19": 148,
  "death20": 149,
  "death21": 150,
  "death22": 151,
  "death23": 152,
  "death24": 153,
  "death25": 154,
  "death26": 155,
  "death27": 156,
  "death28": 157,
  "death29": 158,
  "death30": 159,
  "death31": 160,
  "kick01": 161,
  "kick02": 162,
  "kick03": 163,
  "kick04": 164,
  "kick05": 165,
  "kick06": 166,
  "kick07": 167,
  "kick08": 168
});
