/* Original Quake II rogue/m_widow2.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const widow2Moves: readonly MonsterMove[] = [
  { name: "widow2_move_stand", firstFrame: 0, lastFrame: 0, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow2_move_walk", firstFrame: 1, lastFrame: 9, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 9.01, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7.55, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7.01, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.66, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5.78, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7.25, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8.37, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 10.41, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow2_move_run", firstFrame: 1, lastFrame: 9, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 9.01, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 7.55, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 7.01, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 6.66, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 6.2, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 5.78, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 7.25, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8.37, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10.41, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow2_move_attack_pre_beam", firstFrame: 35, lastFrame: 38, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: ["widow2_attack_beam"], lerpFrame: -1 },
  ] },
  { name: "widow2_move_attack_beam", firstFrame: 39, lastFrame: 43, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow2_reattack_beam"], lerpFrame: -1 },
  ] },
  { name: "widow2_move_attack_post_beam", firstFrame: 40, lastFrame: 41, end: "widow2_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow2_move_attack_disrupt", firstFrame: 28, lastFrame: 34, end: "widow2_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["Widow2SaveDisruptLoc"], lerpFrame: -1 },
    { ai: "charge", distance: -20, actions: ["WidowDisrupt"], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["widow2_disrupt_reattack"], lerpFrame: -1 },
  ] },
  { name: "widow2_move_spawn", firstFrame: 10, lastFrame: 27, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow_start_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow2_ready_spawn"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Beam"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow2_spawn_check"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["widow2_reattack_beam"], lerpFrame: -1 },
  ] },
  { name: "widow2_move_tongs", firstFrame: 47, lastFrame: 54, end: "widow2_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["Widow2Tongue"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Tongue"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Tongue"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2TonguePull"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2TonguePull"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2TonguePull"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Crunch"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["Widow2Toss"], lerpFrame: -1 },
  ] },
  { name: "widow2_move_pain", firstFrame: 55, lastFrame: 59, end: "widow2_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "widow2_move_death", firstFrame: 60, lastFrame: 103, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosion1"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosion2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosion3"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosion4"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosion5"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosionLeg"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosion6"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplosion7"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["WidowExplode"], lerpFrame: -1 },
  ] },
  { name: "widow2_move_dead", firstFrame: 104, lastFrame: 118, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["widow2_start_searching"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["widow2_keep_searching"], lerpFrame: -1 },
  ] },
  { name: "widow2_move_really_dead", firstFrame: 119, lastFrame: 125, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["widow2_finaldeath"], lerpFrame: -1 },
  ] },
];

export const widow2Frame = Object.freeze({
  "blackwidow3": 0,
  "walk01": 1,
  "walk02": 2,
  "walk03": 3,
  "walk04": 4,
  "walk05": 5,
  "walk06": 6,
  "walk07": 7,
  "walk08": 8,
  "walk09": 9,
  "spawn01": 10,
  "spawn02": 11,
  "spawn03": 12,
  "spawn04": 13,
  "spawn05": 14,
  "spawn06": 15,
  "spawn07": 16,
  "spawn08": 17,
  "spawn09": 18,
  "spawn10": 19,
  "spawn11": 20,
  "spawn12": 21,
  "spawn13": 22,
  "spawn14": 23,
  "spawn15": 24,
  "spawn16": 25,
  "spawn17": 26,
  "spawn18": 27,
  "firea01": 28,
  "firea02": 29,
  "firea03": 30,
  "firea04": 31,
  "firea05": 32,
  "firea06": 33,
  "firea07": 34,
  "fireb01": 35,
  "fireb02": 36,
  "fireb03": 37,
  "fireb04": 38,
  "fireb05": 39,
  "fireb06": 40,
  "fireb07": 41,
  "fireb08": 42,
  "fireb09": 43,
  "fireb10": 44,
  "fireb11": 45,
  "fireb12": 46,
  "tongs01": 47,
  "tongs02": 48,
  "tongs03": 49,
  "tongs04": 50,
  "tongs05": 51,
  "tongs06": 52,
  "tongs07": 53,
  "tongs08": 54,
  "pain01": 55,
  "pain02": 56,
  "pain03": 57,
  "pain04": 58,
  "pain05": 59,
  "death01": 60,
  "death02": 61,
  "death03": 62,
  "death04": 63,
  "death05": 64,
  "death06": 65,
  "death07": 66,
  "death08": 67,
  "death09": 68,
  "death10": 69,
  "death11": 70,
  "death12": 71,
  "death13": 72,
  "death14": 73,
  "death15": 74,
  "death16": 75,
  "death17": 76,
  "death18": 77,
  "death19": 78,
  "death20": 79,
  "death21": 80,
  "death22": 81,
  "death23": 82,
  "death24": 83,
  "death25": 84,
  "death26": 85,
  "death27": 86,
  "death28": 87,
  "death29": 88,
  "death30": 89,
  "death31": 90,
  "death32": 91,
  "death33": 92,
  "death34": 93,
  "death35": 94,
  "death36": 95,
  "death37": 96,
  "death38": 97,
  "death39": 98,
  "death40": 99,
  "death41": 100,
  "death42": 101,
  "death43": 102,
  "death44": 103,
  "dthsrh01": 104,
  "dthsrh02": 105,
  "dthsrh03": 106,
  "dthsrh04": 107,
  "dthsrh05": 108,
  "dthsrh06": 109,
  "dthsrh07": 110,
  "dthsrh08": 111,
  "dthsrh09": 112,
  "dthsrh10": 113,
  "dthsrh11": 114,
  "dthsrh12": 115,
  "dthsrh13": 116,
  "dthsrh14": 117,
  "dthsrh15": 118,
  "dthsrh16": 119,
  "dthsrh17": 120,
  "dthsrh18": 121,
  "dthsrh19": 122,
  "dthsrh20": 123,
  "dthsrh21": 124,
  "dthsrh22": 125
});
