/* Original Quake II xatrix/m_fixbot.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const fixbotMoves: readonly MonsterMove[] = [
  { name: "fixbot_move_landing", firstFrame: 31, lastFrame: 88, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["fly_vertical2"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_stand", firstFrame: 121, lastFrame: 139, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["change_to_roam"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_stand2", firstFrame: 121, lastFrame: 139, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_pickup", firstFrame: 154, lastFrame: 180, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_roamgoal", firstFrame: 181, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["roam_goal"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_turn", firstFrame: 181, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_facing" }, distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_takeoff", firstFrame: 105, lastFrame: 120, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
    { ai: "move", distance: 0.01, actions: ["fly_vertical"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_paina", firstFrame: 140, lastFrame: 145, end: "fixbot_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_painb", firstFrame: 146, lastFrame: 153, end: "fixbot_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_pain3", firstFrame: 181, lastFrame: 181, end: "fixbot_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_land", firstFrame: 181, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_forward", firstFrame: 181, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_movetogoal" }, distance: 5, actions: ["use_scanner"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_walk", firstFrame: 181, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_run", firstFrame: 181, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_death1", firstFrame: 181, lastFrame: 181, end: "fixbot_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_backward", firstFrame: 181, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_start_attack", firstFrame: 181, lastFrame: 181, end: "fixbot_attack", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_attack1", firstFrame: 182, lastFrame: 187, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: ["fixbot_fire_blaster"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_laserattack", firstFrame: 182, lastFrame: 187, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["fixbot_fire_laser"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["fixbot_fire_laser"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["fixbot_fire_laser"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["fixbot_fire_laser"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["fixbot_fire_laser"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["fixbot_fire_laser"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_attack2", firstFrame: 0, lastFrame: 30, end: "fixbot_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["fixbot_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_weld_start", firstFrame: 188, lastFrame: 197, end: null, sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["weldstate"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_weld", firstFrame: 198, lastFrame: 204, end: null, sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["fixbot_fire_welder"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["fixbot_fire_welder"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["fixbot_fire_welder"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["fixbot_fire_welder"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["fixbot_fire_welder"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["fixbot_fire_welder"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: 0, actions: ["weldstate"], lerpFrame: -1 },
  ] },
  { name: "fixbot_move_weld_end", firstFrame: 205, lastFrame: 211, end: null, sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_move2" }, distance: -2, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: -2, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: -2, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: -2, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: -2, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: -2, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_move2" }, distance: -2, actions: ["weldstate"], lerpFrame: -1 },
  ] },
];

export const fixbotFrame = Object.freeze({
  "charging_01": 0,
  "charging_02": 1,
  "charging_03": 2,
  "charging_04": 3,
  "charging_05": 4,
  "charging_06": 5,
  "charging_07": 6,
  "charging_08": 7,
  "charging_09": 8,
  "charging_10": 9,
  "charging_11": 10,
  "charging_12": 11,
  "charging_13": 12,
  "charging_14": 13,
  "charging_15": 14,
  "charging_16": 15,
  "charging_17": 16,
  "charging_18": 17,
  "charging_19": 18,
  "charging_20": 19,
  "charging_21": 20,
  "charging_22": 21,
  "charging_23": 22,
  "charging_24": 23,
  "charging_25": 24,
  "charging_26": 25,
  "charging_27": 26,
  "charging_28": 27,
  "charging_29": 28,
  "charging_30": 29,
  "charging_31": 30,
  "landing_01": 31,
  "landing_02": 32,
  "landing_03": 33,
  "landing_04": 34,
  "landing_05": 35,
  "landing_06": 36,
  "landing_07": 37,
  "landing_08": 38,
  "landing_09": 39,
  "landing_10": 40,
  "landing_11": 41,
  "landing_12": 42,
  "landing_13": 43,
  "landing_14": 44,
  "landing_15": 45,
  "landing_16": 46,
  "landing_17": 47,
  "landing_18": 48,
  "landing_19": 49,
  "landing_20": 50,
  "landing_21": 51,
  "landing_22": 52,
  "landing_23": 53,
  "landing_24": 54,
  "landing_25": 55,
  "landing_26": 56,
  "landing_27": 57,
  "landing_28": 58,
  "landing_29": 59,
  "landing_30": 60,
  "landing_31": 61,
  "landing_32": 62,
  "landing_33": 63,
  "landing_34": 64,
  "landing_35": 65,
  "landing_36": 66,
  "landing_37": 67,
  "landing_38": 68,
  "landing_39": 69,
  "landing_40": 70,
  "landing_41": 71,
  "landing_42": 72,
  "landing_43": 73,
  "landing_44": 74,
  "landing_45": 75,
  "landing_46": 76,
  "landing_47": 77,
  "landing_48": 78,
  "landing_49": 79,
  "landing_50": 80,
  "landing_51": 81,
  "landing_52": 82,
  "landing_53": 83,
  "landing_54": 84,
  "landing_55": 85,
  "landing_56": 86,
  "landing_57": 87,
  "landing_58": 88,
  "pushback_01": 89,
  "pushback_02": 90,
  "pushback_03": 91,
  "pushback_04": 92,
  "pushback_05": 93,
  "pushback_06": 94,
  "pushback_07": 95,
  "pushback_08": 96,
  "pushback_09": 97,
  "pushback_10": 98,
  "pushback_11": 99,
  "pushback_12": 100,
  "pushback_13": 101,
  "pushback_14": 102,
  "pushback_15": 103,
  "pushback_16": 104,
  "takeoff_01": 105,
  "takeoff_02": 106,
  "takeoff_03": 107,
  "takeoff_04": 108,
  "takeoff_05": 109,
  "takeoff_06": 110,
  "takeoff_07": 111,
  "takeoff_08": 112,
  "takeoff_09": 113,
  "takeoff_10": 114,
  "takeoff_11": 115,
  "takeoff_12": 116,
  "takeoff_13": 117,
  "takeoff_14": 118,
  "takeoff_15": 119,
  "takeoff_16": 120,
  "ambient_01": 121,
  "ambient_02": 122,
  "ambient_03": 123,
  "ambient_04": 124,
  "ambient_05": 125,
  "ambient_06": 126,
  "ambient_07": 127,
  "ambient_08": 128,
  "ambient_09": 129,
  "ambient_10": 130,
  "ambient_11": 131,
  "ambient_12": 132,
  "ambient_13": 133,
  "ambient_14": 134,
  "ambient_15": 135,
  "ambient_16": 136,
  "ambient_17": 137,
  "ambient_18": 138,
  "ambient_19": 139,
  "paina_01": 140,
  "paina_02": 141,
  "paina_03": 142,
  "paina_04": 143,
  "paina_05": 144,
  "paina_06": 145,
  "painb_01": 146,
  "painb_02": 147,
  "painb_03": 148,
  "painb_04": 149,
  "painb_05": 150,
  "painb_06": 151,
  "painb_07": 152,
  "painb_08": 153,
  "pickup_01": 154,
  "pickup_02": 155,
  "pickup_03": 156,
  "pickup_04": 157,
  "pickup_05": 158,
  "pickup_06": 159,
  "pickup_07": 160,
  "pickup_08": 161,
  "pickup_09": 162,
  "pickup_10": 163,
  "pickup_11": 164,
  "pickup_12": 165,
  "pickup_13": 166,
  "pickup_14": 167,
  "pickup_15": 168,
  "pickup_16": 169,
  "pickup_17": 170,
  "pickup_18": 171,
  "pickup_19": 172,
  "pickup_20": 173,
  "pickup_21": 174,
  "pickup_22": 175,
  "pickup_23": 176,
  "pickup_24": 177,
  "pickup_25": 178,
  "pickup_26": 179,
  "pickup_27": 180,
  "freeze_01": 181,
  "shoot_01": 182,
  "shoot_02": 183,
  "shoot_03": 184,
  "shoot_04": 185,
  "shoot_05": 186,
  "shoot_06": 187,
  "weldstart_01": 188,
  "weldstart_02": 189,
  "weldstart_03": 190,
  "weldstart_04": 191,
  "weldstart_05": 192,
  "weldstart_06": 193,
  "weldstart_07": 194,
  "weldstart_08": 195,
  "weldstart_09": 196,
  "weldstart_10": 197,
  "weldmiddle_01": 198,
  "weldmiddle_02": 199,
  "weldmiddle_03": 200,
  "weldmiddle_04": 201,
  "weldmiddle_05": 202,
  "weldmiddle_06": 203,
  "weldmiddle_07": 204,
  "weldend_01": 205,
  "weldend_02": 206,
  "weldend_03": 207,
  "weldend_04": 208,
  "weldend_05": 209,
  "weldend_06": 210,
  "weldend_07": 211
});
