/* Original Quake II xatrix/m_soldier.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const soldierhMoves: readonly MonsterMove[] = [
  { name: "soldierh_move_stand1", firstFrame: 146, lastFrame: 175, end: "soldierh_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: ["soldierh_idle"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_stand3", firstFrame: 176, lastFrame: 214, end: "soldierh_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["soldierh_cock"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_walk1", firstFrame: 215, lastFrame: 247, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: -1, actions: ["soldierh_walk1_random"], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_walk2", firstFrame: 256, lastFrame: 265, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_start_run", firstFrame: 97, lastFrame: 98, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "run", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 5, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_run", firstFrame: 99, lastFrame: 104, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 11, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 11, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 15, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_pain1", firstFrame: 50, lastFrame: 54, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_pain2", firstFrame: 55, lastFrame: 61, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -13, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_pain3", firstFrame: 62, lastFrame: 79, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_pain4", firstFrame: 80, lastFrame: 96, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_attack1", firstFrame: 0, lastFrame: 11, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_hyper_sound"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_fire1"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_ripper1"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_ripper1"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_attack1_refire1"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_hyper_refire1"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_cock"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_attack1_refire2"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_attack2", firstFrame: 12, lastFrame: 29, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_hyper_sound"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_fire2"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_ripper2"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_ripper2"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_attack2_refire1"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_hyper_refire2"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_cock"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_attack2_refire2"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_attack3", firstFrame: 30, lastFrame: 38, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_fire3"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_attack3_refire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_duck_up"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_attack4", firstFrame: 39, lastFrame: 44, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["soldierh_fire4"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_attack6", firstFrame: 109, lastFrame: 122, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 11, actions: ["soldierh_fire8"], lerpFrame: -1 },
    { ai: "charge", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 15, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 11, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 11, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 17, actions: ["soldierh_attack6_refire"], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_duck", firstFrame: 45, lastFrame: 49, end: "soldierh_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 5, actions: ["soldierh_duck_down"], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: ["soldierh_duck_hold"], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["soldierh_duck_up"], lerpFrame: -1 },
    { ai: "move", distance: 5, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_death1", firstFrame: 272, lastFrame: 307, end: "soldierh_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["soldierh_fire6"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["soldierh_fire7"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_death2", firstFrame: 308, lastFrame: 342, end: "soldierh_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_death3", firstFrame: 343, lastFrame: 387, end: "soldierh_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_death4", firstFrame: 388, lastFrame: 440, end: "soldierh_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_death5", firstFrame: 441, lastFrame: 464, end: "soldierh_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "soldierh_move_death6", firstFrame: 465, lastFrame: 474, end: "soldierh_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const soldierhFrame = Object.freeze({
  "attak101": 0,
  "attak102": 1,
  "attak103": 2,
  "attak104": 3,
  "attak105": 4,
  "attak106": 5,
  "attak107": 6,
  "attak108": 7,
  "attak109": 8,
  "attak110": 9,
  "attak111": 10,
  "attak112": 11,
  "attak201": 12,
  "attak202": 13,
  "attak203": 14,
  "attak204": 15,
  "attak205": 16,
  "attak206": 17,
  "attak207": 18,
  "attak208": 19,
  "attak209": 20,
  "attak210": 21,
  "attak211": 22,
  "attak212": 23,
  "attak213": 24,
  "attak214": 25,
  "attak215": 26,
  "attak216": 27,
  "attak217": 28,
  "attak218": 29,
  "attak301": 30,
  "attak302": 31,
  "attak303": 32,
  "attak304": 33,
  "attak305": 34,
  "attak306": 35,
  "attak307": 36,
  "attak308": 37,
  "attak309": 38,
  "attak401": 39,
  "attak402": 40,
  "attak403": 41,
  "attak404": 42,
  "attak405": 43,
  "attak406": 44,
  "duck01": 45,
  "duck02": 46,
  "duck03": 47,
  "duck04": 48,
  "duck05": 49,
  "pain101": 50,
  "pain102": 51,
  "pain103": 52,
  "pain104": 53,
  "pain105": 54,
  "pain201": 55,
  "pain202": 56,
  "pain203": 57,
  "pain204": 58,
  "pain205": 59,
  "pain206": 60,
  "pain207": 61,
  "pain301": 62,
  "pain302": 63,
  "pain303": 64,
  "pain304": 65,
  "pain305": 66,
  "pain306": 67,
  "pain307": 68,
  "pain308": 69,
  "pain309": 70,
  "pain310": 71,
  "pain311": 72,
  "pain312": 73,
  "pain313": 74,
  "pain314": 75,
  "pain315": 76,
  "pain316": 77,
  "pain317": 78,
  "pain318": 79,
  "pain401": 80,
  "pain402": 81,
  "pain403": 82,
  "pain404": 83,
  "pain405": 84,
  "pain406": 85,
  "pain407": 86,
  "pain408": 87,
  "pain409": 88,
  "pain410": 89,
  "pain411": 90,
  "pain412": 91,
  "pain413": 92,
  "pain414": 93,
  "pain415": 94,
  "pain416": 95,
  "pain417": 96,
  "run01": 97,
  "run02": 98,
  "run03": 99,
  "run04": 100,
  "run05": 101,
  "run06": 102,
  "run07": 103,
  "run08": 104,
  "run09": 105,
  "run10": 106,
  "run11": 107,
  "run12": 108,
  "runs01": 109,
  "runs02": 110,
  "runs03": 111,
  "runs04": 112,
  "runs05": 113,
  "runs06": 114,
  "runs07": 115,
  "runs08": 116,
  "runs09": 117,
  "runs10": 118,
  "runs11": 119,
  "runs12": 120,
  "runs13": 121,
  "runs14": 122,
  "runs15": 123,
  "runs16": 124,
  "runs17": 125,
  "runs18": 126,
  "runt01": 127,
  "runt02": 128,
  "runt03": 129,
  "runt04": 130,
  "runt05": 131,
  "runt06": 132,
  "runt07": 133,
  "runt08": 134,
  "runt09": 135,
  "runt10": 136,
  "runt11": 137,
  "runt12": 138,
  "runt13": 139,
  "runt14": 140,
  "runt15": 141,
  "runt16": 142,
  "runt17": 143,
  "runt18": 144,
  "runt19": 145,
  "stand101": 146,
  "stand102": 147,
  "stand103": 148,
  "stand104": 149,
  "stand105": 150,
  "stand106": 151,
  "stand107": 152,
  "stand108": 153,
  "stand109": 154,
  "stand110": 155,
  "stand111": 156,
  "stand112": 157,
  "stand113": 158,
  "stand114": 159,
  "stand115": 160,
  "stand116": 161,
  "stand117": 162,
  "stand118": 163,
  "stand119": 164,
  "stand120": 165,
  "stand121": 166,
  "stand122": 167,
  "stand123": 168,
  "stand124": 169,
  "stand125": 170,
  "stand126": 171,
  "stand127": 172,
  "stand128": 173,
  "stand129": 174,
  "stand130": 175,
  "stand301": 176,
  "stand302": 177,
  "stand303": 178,
  "stand304": 179,
  "stand305": 180,
  "stand306": 181,
  "stand307": 182,
  "stand308": 183,
  "stand309": 184,
  "stand310": 185,
  "stand311": 186,
  "stand312": 187,
  "stand313": 188,
  "stand314": 189,
  "stand315": 190,
  "stand316": 191,
  "stand317": 192,
  "stand318": 193,
  "stand319": 194,
  "stand320": 195,
  "stand321": 196,
  "stand322": 197,
  "stand323": 198,
  "stand324": 199,
  "stand325": 200,
  "stand326": 201,
  "stand327": 202,
  "stand328": 203,
  "stand329": 204,
  "stand330": 205,
  "stand331": 206,
  "stand332": 207,
  "stand333": 208,
  "stand334": 209,
  "stand335": 210,
  "stand336": 211,
  "stand337": 212,
  "stand338": 213,
  "stand339": 214,
  "walk101": 215,
  "walk102": 216,
  "walk103": 217,
  "walk104": 218,
  "walk105": 219,
  "walk106": 220,
  "walk107": 221,
  "walk108": 222,
  "walk109": 223,
  "walk110": 224,
  "walk111": 225,
  "walk112": 226,
  "walk113": 227,
  "walk114": 228,
  "walk115": 229,
  "walk116": 230,
  "walk117": 231,
  "walk118": 232,
  "walk119": 233,
  "walk120": 234,
  "walk121": 235,
  "walk122": 236,
  "walk123": 237,
  "walk124": 238,
  "walk125": 239,
  "walk126": 240,
  "walk127": 241,
  "walk128": 242,
  "walk129": 243,
  "walk130": 244,
  "walk131": 245,
  "walk132": 246,
  "walk133": 247,
  "walk201": 248,
  "walk202": 249,
  "walk203": 250,
  "walk204": 251,
  "walk205": 252,
  "walk206": 253,
  "walk207": 254,
  "walk208": 255,
  "walk209": 256,
  "walk210": 257,
  "walk211": 258,
  "walk212": 259,
  "walk213": 260,
  "walk214": 261,
  "walk215": 262,
  "walk216": 263,
  "walk217": 264,
  "walk218": 265,
  "walk219": 266,
  "walk220": 267,
  "walk221": 268,
  "walk222": 269,
  "walk223": 270,
  "walk224": 271,
  "death101": 272,
  "death102": 273,
  "death103": 274,
  "death104": 275,
  "death105": 276,
  "death106": 277,
  "death107": 278,
  "death108": 279,
  "death109": 280,
  "death110": 281,
  "death111": 282,
  "death112": 283,
  "death113": 284,
  "death114": 285,
  "death115": 286,
  "death116": 287,
  "death117": 288,
  "death118": 289,
  "death119": 290,
  "death120": 291,
  "death121": 292,
  "death122": 293,
  "death123": 294,
  "death124": 295,
  "death125": 296,
  "death126": 297,
  "death127": 298,
  "death128": 299,
  "death129": 300,
  "death130": 301,
  "death131": 302,
  "death132": 303,
  "death133": 304,
  "death134": 305,
  "death135": 306,
  "death136": 307,
  "death201": 308,
  "death202": 309,
  "death203": 310,
  "death204": 311,
  "death205": 312,
  "death206": 313,
  "death207": 314,
  "death208": 315,
  "death209": 316,
  "death210": 317,
  "death211": 318,
  "death212": 319,
  "death213": 320,
  "death214": 321,
  "death215": 322,
  "death216": 323,
  "death217": 324,
  "death218": 325,
  "death219": 326,
  "death220": 327,
  "death221": 328,
  "death222": 329,
  "death223": 330,
  "death224": 331,
  "death225": 332,
  "death226": 333,
  "death227": 334,
  "death228": 335,
  "death229": 336,
  "death230": 337,
  "death231": 338,
  "death232": 339,
  "death233": 340,
  "death234": 341,
  "death235": 342,
  "death301": 343,
  "death302": 344,
  "death303": 345,
  "death304": 346,
  "death305": 347,
  "death306": 348,
  "death307": 349,
  "death308": 350,
  "death309": 351,
  "death310": 352,
  "death311": 353,
  "death312": 354,
  "death313": 355,
  "death314": 356,
  "death315": 357,
  "death316": 358,
  "death317": 359,
  "death318": 360,
  "death319": 361,
  "death320": 362,
  "death321": 363,
  "death322": 364,
  "death323": 365,
  "death324": 366,
  "death325": 367,
  "death326": 368,
  "death327": 369,
  "death328": 370,
  "death329": 371,
  "death330": 372,
  "death331": 373,
  "death332": 374,
  "death333": 375,
  "death334": 376,
  "death335": 377,
  "death336": 378,
  "death337": 379,
  "death338": 380,
  "death339": 381,
  "death340": 382,
  "death341": 383,
  "death342": 384,
  "death343": 385,
  "death344": 386,
  "death345": 387,
  "death401": 388,
  "death402": 389,
  "death403": 390,
  "death404": 391,
  "death405": 392,
  "death406": 393,
  "death407": 394,
  "death408": 395,
  "death409": 396,
  "death410": 397,
  "death411": 398,
  "death412": 399,
  "death413": 400,
  "death414": 401,
  "death415": 402,
  "death416": 403,
  "death417": 404,
  "death418": 405,
  "death419": 406,
  "death420": 407,
  "death421": 408,
  "death422": 409,
  "death423": 410,
  "death424": 411,
  "death425": 412,
  "death426": 413,
  "death427": 414,
  "death428": 415,
  "death429": 416,
  "death430": 417,
  "death431": 418,
  "death432": 419,
  "death433": 420,
  "death434": 421,
  "death435": 422,
  "death436": 423,
  "death437": 424,
  "death438": 425,
  "death439": 426,
  "death440": 427,
  "death441": 428,
  "death442": 429,
  "death443": 430,
  "death444": 431,
  "death445": 432,
  "death446": 433,
  "death447": 434,
  "death448": 435,
  "death449": 436,
  "death450": 437,
  "death451": 438,
  "death452": 439,
  "death453": 440,
  "death501": 441,
  "death502": 442,
  "death503": 443,
  "death504": 444,
  "death505": 445,
  "death506": 446,
  "death507": 447,
  "death508": 448,
  "death509": 449,
  "death510": 450,
  "death511": 451,
  "death512": 452,
  "death513": 453,
  "death514": 454,
  "death515": 455,
  "death516": 456,
  "death517": 457,
  "death518": 458,
  "death519": 459,
  "death520": 460,
  "death521": 461,
  "death522": 462,
  "death523": 463,
  "death524": 464,
  "death601": 465,
  "death602": 466,
  "death603": 467,
  "death604": 468,
  "death605": 469,
  "death606": 470,
  "death607": 471,
  "death608": 472,
  "death609": 473,
  "death610": 474
});
