/* Original Quake II xatrix/m_gekk.c frame order and distances. ZeniMax Media, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const gekkMoves: readonly MonsterMove[] = [
  { name: "gekk_move_stand", firstFrame: 0, lastFrame: 38, end: null, sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: ["gekk_check_underwater"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_standunderwater", firstFrame: 242, lastFrame: 245, end: null, sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: ["gekk_check_underwater"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_swim_loop", firstFrame: 242, lastFrame: 245, end: "gekk_swim_loop", sidestepScale: 0, frames: [
    { ai: "run", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 16, actions: ["gekk_swim"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_swim_start", firstFrame: 291, lastFrame: 322, end: "gekk_swim_loop", sidestepScale: 0, frames: [
    { ai: "run", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: ["gekk_hit_left"], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 20, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 20, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 24, actions: ["gekk_hit_right"], lerpFrame: -1 },
    { ai: "run", distance: 24, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 26, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 26, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 24, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 24, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: ["gekk_bite"], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 22, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_idle", firstFrame: 203, lastFrame: 234, end: "gekk_stand", sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: ["gekk_search"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: ["gekk_idle_loop"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_idle2", firstFrame: 203, lastFrame: 234, end: "gekk_face", sidestepScale: 0, frames: [
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: ["gekk_search"], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: [], lerpFrame: -1 },
    { ai: { kind: "source", name: "ai_stand2" }, distance: 0, actions: ["gekk_idle_loop"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_chant", firstFrame: 203, lastFrame: 234, end: "gekk_chant", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["gekk_search"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["gekk_idle_loop"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_walk", firstFrame: 39, lastFrame: 44, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 3.849, actions: ["gekk_check_underwater"], lerpFrame: -1 },
    { ai: "walk", distance: 19.606, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 25.583, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 34.625, actions: ["gekk_step"], lerpFrame: -1 },
    { ai: "walk", distance: 27.365, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 28.48, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_run", firstFrame: 39, lastFrame: 44, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 3.849, actions: ["gekk_check_underwater"], lerpFrame: -1 },
    { ai: "run", distance: 19.606, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 25.583, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 34.625, actions: ["gekk_step"], lerpFrame: -1 },
    { ai: "run", distance: 27.365, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 28.48, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_run_start", firstFrame: 0, lastFrame: 1, end: "gekk_run", sidestepScale: 0, frames: [
    { ai: "run", distance: 0.212, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 19.753, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_spit", firstFrame: 235, lastFrame: 241, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["loogie"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["reloogie"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_attack1", firstFrame: 45, lastFrame: 53, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["gekk_hit_left"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["gekk_check_refire"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_attack2", firstFrame: 62, lastFrame: 70, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["gekk_hit_left"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["gekk_hit_right"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["gekk_check_refire"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_leapatk", firstFrame: 71, lastFrame: 89, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -0.387, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -1.113, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -0.237, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6.72, actions: ["gekk_jump_takeoff"], lerpFrame: -1 },
    { ai: "charge", distance: 6.414, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0.163, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 28.316, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 24.198, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 31.742, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 35.977, actions: ["gekk_check_landing"], lerpFrame: -1 },
    { ai: "charge", distance: 12.303, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 20.122, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: -1.042, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 2.556, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 0.544, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 1.862, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 1.224, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: -0.457, actions: ["gekk_check_underwater"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_leapatk2", firstFrame: 71, lastFrame: 89, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -0.387, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -1.113, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -0.237, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6.72, actions: ["gekk_jump_takeoff2"], lerpFrame: -1 },
    { ai: "charge", distance: 6.414, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0.163, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 28.316, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 24.198, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 31.742, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 35.977, actions: ["gekk_check_landing"], lerpFrame: -1 },
    { ai: "charge", distance: 12.303, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 20.122, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: -1.042, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 2.556, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 0.544, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 1.862, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: 1.224, actions: ["gekk_stop_skid"], lerpFrame: -1 },
    { ai: "charge", distance: -0.457, actions: ["gekk_check_underwater"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_attack", firstFrame: 323, lastFrame: 343, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "charge", distance: 16, actions: ["gekk_preattack"], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: ["gekk_bite"], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: ["gekk_bite"], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: ["gekk_hit_left"], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: ["gekk_hit_right"], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 16, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_pain", firstFrame: 344, lastFrame: 349, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_pain1", firstFrame: 90, lastFrame: 100, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["gekk_check_underwater"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_pain2", firstFrame: 101, lastFrame: 113, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["gekk_check_underwater"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_death1", firstFrame: 114, lastFrame: 123, end: "gekk_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: -5.151, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -12.223, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -11.484, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -17.952, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -6.953, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -7.393, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10.713, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -17.464, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -11.678, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -11.678, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_death3", firstFrame: 135, lastFrame: 141, end: "gekk_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.022, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.169, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.71, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -13.446, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -7.654, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -31.951, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_death4", firstFrame: 142, lastFrame: 176, end: "gekk_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 5.103, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4.808, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -10.509, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -9.899, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4.033, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -5.197, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.919, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -8.821, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5.626, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -8.865, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -0.845, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1.986, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.17, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1.339, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -0.922, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.818, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.288, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.408, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -7.787, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3.995, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4.604, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.715, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -0.564, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.597, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.074, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.309, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -0.395, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.501, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.325, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.931, actions: ["isgibfest"], lerpFrame: -1 },
    { ai: "move", distance: -1.433, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.626, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4.68, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.56, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.549, actions: ["gekk_gibfest"], lerpFrame: -1 },
  ] },
  { name: "gekk_move_wdeath", firstFrame: 246, lastFrame: 290, end: "gekk_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_lduck", firstFrame: 190, lastFrame: 202, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gekk_move_rduck", firstFrame: 177, lastFrame: 189, end: "gekk_run_start", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const gekkFrame = Object.freeze({
  "stand_01": 0,
  "stand_02": 1,
  "stand_03": 2,
  "stand_04": 3,
  "stand_05": 4,
  "stand_06": 5,
  "stand_07": 6,
  "stand_08": 7,
  "stand_09": 8,
  "stand_10": 9,
  "stand_11": 10,
  "stand_12": 11,
  "stand_13": 12,
  "stand_14": 13,
  "stand_15": 14,
  "stand_16": 15,
  "stand_17": 16,
  "stand_18": 17,
  "stand_19": 18,
  "stand_20": 19,
  "stand_21": 20,
  "stand_22": 21,
  "stand_23": 22,
  "stand_24": 23,
  "stand_25": 24,
  "stand_26": 25,
  "stand_27": 26,
  "stand_28": 27,
  "stand_29": 28,
  "stand_30": 29,
  "stand_31": 30,
  "stand_32": 31,
  "stand_33": 32,
  "stand_34": 33,
  "stand_35": 34,
  "stand_36": 35,
  "stand_37": 36,
  "stand_38": 37,
  "stand_39": 38,
  "run_01": 39,
  "run_02": 40,
  "run_03": 41,
  "run_04": 42,
  "run_05": 43,
  "run_06": 44,
  "clawatk3_01": 45,
  "clawatk3_02": 46,
  "clawatk3_03": 47,
  "clawatk3_04": 48,
  "clawatk3_05": 49,
  "clawatk3_06": 50,
  "clawatk3_07": 51,
  "clawatk3_08": 52,
  "clawatk3_09": 53,
  "clawatk4_01": 54,
  "clawatk4_02": 55,
  "clawatk4_03": 56,
  "clawatk4_04": 57,
  "clawatk4_05": 58,
  "clawatk4_06": 59,
  "clawatk4_07": 60,
  "clawatk4_08": 61,
  "clawatk5_01": 62,
  "clawatk5_02": 63,
  "clawatk5_03": 64,
  "clawatk5_04": 65,
  "clawatk5_05": 66,
  "clawatk5_06": 67,
  "clawatk5_07": 68,
  "clawatk5_08": 69,
  "clawatk5_09": 70,
  "leapatk_01": 71,
  "leapatk_02": 72,
  "leapatk_03": 73,
  "leapatk_04": 74,
  "leapatk_05": 75,
  "leapatk_06": 76,
  "leapatk_07": 77,
  "leapatk_08": 78,
  "leapatk_09": 79,
  "leapatk_10": 80,
  "leapatk_11": 81,
  "leapatk_12": 82,
  "leapatk_13": 83,
  "leapatk_14": 84,
  "leapatk_15": 85,
  "leapatk_16": 86,
  "leapatk_17": 87,
  "leapatk_18": 88,
  "leapatk_19": 89,
  "pain3_01": 90,
  "pain3_02": 91,
  "pain3_03": 92,
  "pain3_04": 93,
  "pain3_05": 94,
  "pain3_06": 95,
  "pain3_07": 96,
  "pain3_08": 97,
  "pain3_09": 98,
  "pain3_10": 99,
  "pain3_11": 100,
  "pain4_01": 101,
  "pain4_02": 102,
  "pain4_03": 103,
  "pain4_04": 104,
  "pain4_05": 105,
  "pain4_06": 106,
  "pain4_07": 107,
  "pain4_08": 108,
  "pain4_09": 109,
  "pain4_10": 110,
  "pain4_11": 111,
  "pain4_12": 112,
  "pain4_13": 113,
  "death1_01": 114,
  "death1_02": 115,
  "death1_03": 116,
  "death1_04": 117,
  "death1_05": 118,
  "death1_06": 119,
  "death1_07": 120,
  "death1_08": 121,
  "death1_09": 122,
  "death1_10": 123,
  "death2_01": 124,
  "death2_02": 125,
  "death2_03": 126,
  "death2_04": 127,
  "death2_05": 128,
  "death2_06": 129,
  "death2_07": 130,
  "death2_08": 131,
  "death2_09": 132,
  "death2_10": 133,
  "death2_11": 134,
  "death3_01": 135,
  "death3_02": 136,
  "death3_03": 137,
  "death3_04": 138,
  "death3_05": 139,
  "death3_06": 140,
  "death3_07": 141,
  "death4_01": 142,
  "death4_02": 143,
  "death4_03": 144,
  "death4_04": 145,
  "death4_05": 146,
  "death4_06": 147,
  "death4_07": 148,
  "death4_08": 149,
  "death4_09": 150,
  "death4_10": 151,
  "death4_11": 152,
  "death4_12": 153,
  "death4_13": 154,
  "death4_14": 155,
  "death4_15": 156,
  "death4_16": 157,
  "death4_17": 158,
  "death4_18": 159,
  "death4_19": 160,
  "death4_20": 161,
  "death4_21": 162,
  "death4_22": 163,
  "death4_23": 164,
  "death4_24": 165,
  "death4_25": 166,
  "death4_26": 167,
  "death4_27": 168,
  "death4_28": 169,
  "death4_29": 170,
  "death4_30": 171,
  "death4_31": 172,
  "death4_32": 173,
  "death4_33": 174,
  "death4_34": 175,
  "death4_35": 176,
  "rduck_01": 177,
  "rduck_02": 178,
  "rduck_03": 179,
  "rduck_04": 180,
  "rduck_05": 181,
  "rduck_06": 182,
  "rduck_07": 183,
  "rduck_08": 184,
  "rduck_09": 185,
  "rduck_10": 186,
  "rduck_11": 187,
  "rduck_12": 188,
  "rduck_13": 189,
  "lduck_01": 190,
  "lduck_02": 191,
  "lduck_03": 192,
  "lduck_04": 193,
  "lduck_05": 194,
  "lduck_06": 195,
  "lduck_07": 196,
  "lduck_08": 197,
  "lduck_09": 198,
  "lduck_10": 199,
  "lduck_11": 200,
  "lduck_12": 201,
  "lduck_13": 202,
  "idle_01": 203,
  "idle_02": 204,
  "idle_03": 205,
  "idle_04": 206,
  "idle_05": 207,
  "idle_06": 208,
  "idle_07": 209,
  "idle_08": 210,
  "idle_09": 211,
  "idle_10": 212,
  "idle_11": 213,
  "idle_12": 214,
  "idle_13": 215,
  "idle_14": 216,
  "idle_15": 217,
  "idle_16": 218,
  "idle_17": 219,
  "idle_18": 220,
  "idle_19": 221,
  "idle_20": 222,
  "idle_21": 223,
  "idle_22": 224,
  "idle_23": 225,
  "idle_24": 226,
  "idle_25": 227,
  "idle_26": 228,
  "idle_27": 229,
  "idle_28": 230,
  "idle_29": 231,
  "idle_30": 232,
  "idle_31": 233,
  "idle_32": 234,
  "spit_01": 235,
  "spit_02": 236,
  "spit_03": 237,
  "spit_04": 238,
  "spit_05": 239,
  "spit_06": 240,
  "spit_07": 241,
  "amb_01": 242,
  "amb_02": 243,
  "amb_03": 244,
  "amb_04": 245,
  "wdeath_01": 246,
  "wdeath_02": 247,
  "wdeath_03": 248,
  "wdeath_04": 249,
  "wdeath_05": 250,
  "wdeath_06": 251,
  "wdeath_07": 252,
  "wdeath_08": 253,
  "wdeath_09": 254,
  "wdeath_10": 255,
  "wdeath_11": 256,
  "wdeath_12": 257,
  "wdeath_13": 258,
  "wdeath_14": 259,
  "wdeath_15": 260,
  "wdeath_16": 261,
  "wdeath_17": 262,
  "wdeath_18": 263,
  "wdeath_19": 264,
  "wdeath_20": 265,
  "wdeath_21": 266,
  "wdeath_22": 267,
  "wdeath_23": 268,
  "wdeath_24": 269,
  "wdeath_25": 270,
  "wdeath_26": 271,
  "wdeath_27": 272,
  "wdeath_28": 273,
  "wdeath_29": 274,
  "wdeath_30": 275,
  "wdeath_31": 276,
  "wdeath_32": 277,
  "wdeath_33": 278,
  "wdeath_34": 279,
  "wdeath_35": 280,
  "wdeath_36": 281,
  "wdeath_37": 282,
  "wdeath_38": 283,
  "wdeath_39": 284,
  "wdeath_40": 285,
  "wdeath_41": 286,
  "wdeath_42": 287,
  "wdeath_43": 288,
  "wdeath_44": 289,
  "wdeath_45": 290,
  "swim_01": 291,
  "swim_02": 292,
  "swim_03": 293,
  "swim_04": 294,
  "swim_05": 295,
  "swim_06": 296,
  "swim_07": 297,
  "swim_08": 298,
  "swim_09": 299,
  "swim_10": 300,
  "swim_11": 301,
  "swim_12": 302,
  "swim_13": 303,
  "swim_14": 304,
  "swim_15": 305,
  "swim_16": 306,
  "swim_17": 307,
  "swim_18": 308,
  "swim_19": 309,
  "swim_20": 310,
  "swim_21": 311,
  "swim_22": 312,
  "swim_23": 313,
  "swim_24": 314,
  "swim_25": 315,
  "swim_26": 316,
  "swim_27": 317,
  "swim_28": 318,
  "swim_29": 319,
  "swim_30": 320,
  "swim_31": 321,
  "swim_32": 322,
  "attack_01": 323,
  "attack_02": 324,
  "attack_03": 325,
  "attack_04": 326,
  "attack_05": 327,
  "attack_06": 328,
  "attack_07": 329,
  "attack_08": 330,
  "attack_09": 331,
  "attack_10": 332,
  "attack_11": 333,
  "attack_12": 334,
  "attack_13": 335,
  "attack_14": 336,
  "attack_15": 337,
  "attack_16": 338,
  "attack_17": 339,
  "attack_18": 340,
  "attack_19": 341,
  "attack_20": 342,
  "attack_21": 343,
  "pain_01": 344,
  "pain_02": 345,
  "pain_03": 346,
  "pain_04": 347,
  "pain_05": 348,
  "pain_06": 349
});
