/* Common CD-key state from id Software common.c, cl_main.c and cl_ui.c. GPL-2.0-or-later. */
import { CvarFlag } from './cvars/index.ts';
import type { CvarRegistry } from './cvars/index.ts';
import { sourceCommandText } from './commands/text.ts';

/** The existing selected product ConfigStore supplies loose q3key access. */
export interface Q3KeyStorage {
  loadText(name: string): Promise<string | null>;
  dump(name: string, contents: string): Promise<void>;
}
export function validateQ3CdKey(key: string, checksum: string | null): boolean {
  if ([...key].some(character => character.charCodeAt(0) > 255) || checksum !== null && [...checksum].some(character => character.charCodeAt(0) > 255)) return false;
  key = sourceCommandText(key);
  if (checksum !== null) checksum = sourceCommandText(checksum);
  if (key.length !== 16 || checksum !== null && checksum.length !== 2) return false;
  let sum = 0;
  for (let index = 0; index < key.length; index++) {
    let character = key.charCodeAt(index);
    if (character >= 97 && character <= 122) character -= 32;
    if (!'237ABCDGHJLPRSTW'.includes(String.fromCharCode(character))) return false;
    sum = (sum + character) & 255;
  }
  return checksum === null || checksum.toLowerCase() === sum.toString(16).padStart(2, '0');
}
export class Q3CdKeyState {
  private readonly bytes = new Uint8Array(34);
  constructor(private readonly cvars: Pick<CvarRegistry, 'markModifiedFlags'>, private readonly build: 'client' | 'dedicated' = 'client') {
    if (build === 'client') this.bytes.fill(32, 0, 32);
    else for (let index = 0; index < 9; index++) this.bytes[index] = 49 + index;
  }
  private async file(storage: Pick<Q3KeyStorage, 'loadText'>): Promise<Uint8Array | null> {
    const text = await storage.loadText('q3key');
    if (text === null) return null;
    const key = text.slice(0, 16);
    if (this.build === 'client' && !validateQ3CdKey(key, null)) return null;
    const result = new Uint8Array(33);
    for (let index = 0; index < Math.min(16, key.length); index++) {
      const byte = key.charCodeAt(index) & 255; if (byte === 0) break; result[index] = byte;
    }
    return result;
  }
  async readFile(storage: Pick<Q3KeyStorage, 'loadText'>): Promise<void> {
    const key = await this.file(storage);
    if (key === null) { this.bytes.fill(32, 0, 16); this.bytes[16] = 0; }
    else this.bytes.set(key.subarray(0, 17));
  }
  async appendFile(storage: Pick<Q3KeyStorage, 'loadText'>): Promise<void> {
    const key = await this.file(storage);
    if (key === null) { this.bytes.fill(32, 16, 32); this.bytes[32] = 0; return; }
    const end = this.bytes.indexOf(0, 16), length = key.indexOf(0) + 1;
    if (end < 0 || end + length > this.bytes.length) throw new RangeError('CD key storage overflow');
    this.bytes.set(key.subarray(0, length), end);
  }
  async writeFile(storage: Pick<Q3KeyStorage, 'dump'>, offset: 0 | 16): Promise<void> {
    const key = String.fromCharCode(...this.bytes.subarray(offset, offset + 16));
    if (!validateQ3CdKey(key, null)) return;
    await storage.dump('q3key', `${key}\n// generated by quake, do not modify\r\n// Do not give this file to ANYONE.\r\n// id Software and Activision will NOT ask you to send this file to them.\r\n`);
  }
  readAuthorization(destination: Uint8Array): void {
    if (destination.length < 33) throw new RangeError('CD key authorization requires 33 bytes');
    destination.set(this.bytes.subarray(0, 32)); destination[32] = 0;
  }
  readUi(uniqueKeyResult: number, gameDirectory: string, destination: Uint8Array,
    writes?: { copy(bytes: Uint8Array): void; setByte(offset: number, value: number): void }): void {
    if (destination.length < 17) throw new RangeError('CD key UI destination requires 17 bytes');
    const offset = uniqueKeyResult === 1 && sourceCommandText(gameDirectory).length !== 0 ? 16 : 0;
    const source = this.bytes.subarray(offset, offset + 16);
    if (writes === undefined) { destination.set(source); destination[16] = 0; }
    else { writes.copy(source); writes.setByte(16, 0); }
  }
  writeUi(uniqueKeyResult: number, gameDirectory: string, source: Uint8Array): void {
    if (source.length < 16) throw new RangeError('CD key UI source requires 16 bytes');
    const offset = uniqueKeyResult === 1 && sourceCommandText(gameDirectory).length !== 0 ? 16 : 0;
    this.bytes.set(source.subarray(0, 16), offset);
    if (offset === 16) this.bytes[32] = 0;
    this.cvars.markModifiedFlags(CvarFlag.Archive);
  }
}
