/* Original Quake II m_boss2.c frame order and distances. id Software, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const boss2Moves: readonly MonsterMove[] = [
  { name: "boss2_move_stand", firstFrame: 0, lastFrame: 20, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_fidget", firstFrame: 21, lastFrame: 0, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_walk", firstFrame: 50, lastFrame: 69, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_run", firstFrame: 50, lastFrame: 69, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_attack_pre_mg", firstFrame: 70, lastFrame: 78, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: ["boss2_attack_mg"], lerpFrame: -1 },
  ] },
  { name: "boss2_move_attack_mg", firstFrame: 79, lastFrame: 84, end: null, sidestepScale: 0, frames: [
    { ai: "charge", distance: 1, actions: ["Boss2MachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: ["Boss2MachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: ["Boss2MachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: ["Boss2MachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: ["Boss2MachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: ["boss2_reattack_mg"], lerpFrame: -1 },
  ] },
  { name: "boss2_move_attack_post_mg", firstFrame: 85, lastFrame: 88, end: "boss2_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_attack_rocket", firstFrame: 89, lastFrame: 109, end: "boss2_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -20, actions: ["Boss2Rocket"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_pain_heavy", firstFrame: 110, lastFrame: 127, end: "boss2_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_pain_light", firstFrame: 128, lastFrame: 131, end: "boss2_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "boss2_move_death", firstFrame: 132, lastFrame: 180, end: "boss2_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["BossExplode"], lerpFrame: -1 },
  ] },
];

export const boss2Frame = Object.freeze({
  "stand30": 0,
  "stand31": 1,
  "stand32": 2,
  "stand33": 3,
  "stand34": 4,
  "stand35": 5,
  "stand36": 6,
  "stand37": 7,
  "stand38": 8,
  "stand39": 9,
  "stand40": 10,
  "stand41": 11,
  "stand42": 12,
  "stand43": 13,
  "stand44": 14,
  "stand45": 15,
  "stand46": 16,
  "stand47": 17,
  "stand48": 18,
  "stand49": 19,
  "stand50": 20,
  "stand1": 21,
  "stand2": 22,
  "stand3": 23,
  "stand4": 24,
  "stand5": 25,
  "stand6": 26,
  "stand7": 27,
  "stand8": 28,
  "stand9": 29,
  "stand10": 30,
  "stand11": 31,
  "stand12": 32,
  "stand13": 33,
  "stand14": 34,
  "stand15": 35,
  "stand16": 36,
  "stand17": 37,
  "stand18": 38,
  "stand19": 39,
  "stand20": 40,
  "stand21": 41,
  "stand22": 42,
  "stand23": 43,
  "stand24": 44,
  "stand25": 45,
  "stand26": 46,
  "stand27": 47,
  "stand28": 48,
  "stand29": 49,
  "walk1": 50,
  "walk2": 51,
  "walk3": 52,
  "walk4": 53,
  "walk5": 54,
  "walk6": 55,
  "walk7": 56,
  "walk8": 57,
  "walk9": 58,
  "walk10": 59,
  "walk11": 60,
  "walk12": 61,
  "walk13": 62,
  "walk14": 63,
  "walk15": 64,
  "walk16": 65,
  "walk17": 66,
  "walk18": 67,
  "walk19": 68,
  "walk20": 69,
  "attack1": 70,
  "attack2": 71,
  "attack3": 72,
  "attack4": 73,
  "attack5": 74,
  "attack6": 75,
  "attack7": 76,
  "attack8": 77,
  "attack9": 78,
  "attack10": 79,
  "attack11": 80,
  "attack12": 81,
  "attack13": 82,
  "attack14": 83,
  "attack15": 84,
  "attack16": 85,
  "attack17": 86,
  "attack18": 87,
  "attack19": 88,
  "attack20": 89,
  "attack21": 90,
  "attack22": 91,
  "attack23": 92,
  "attack24": 93,
  "attack25": 94,
  "attack26": 95,
  "attack27": 96,
  "attack28": 97,
  "attack29": 98,
  "attack30": 99,
  "attack31": 100,
  "attack32": 101,
  "attack33": 102,
  "attack34": 103,
  "attack35": 104,
  "attack36": 105,
  "attack37": 106,
  "attack38": 107,
  "attack39": 108,
  "attack40": 109,
  "pain2": 110,
  "pain3": 111,
  "pain4": 112,
  "pain5": 113,
  "pain6": 114,
  "pain7": 115,
  "pain8": 116,
  "pain9": 117,
  "pain10": 118,
  "pain11": 119,
  "pain12": 120,
  "pain13": 121,
  "pain14": 122,
  "pain15": 123,
  "pain16": 124,
  "pain17": 125,
  "pain18": 126,
  "pain19": 127,
  "pain20": 128,
  "pain21": 129,
  "pain22": 130,
  "pain23": 131,
  "death2": 132,
  "death3": 133,
  "death4": 134,
  "death5": 135,
  "death6": 136,
  "death7": 137,
  "death8": 138,
  "death9": 139,
  "death10": 140,
  "death11": 141,
  "death12": 142,
  "death13": 143,
  "death14": 144,
  "death15": 145,
  "death16": 146,
  "death17": 147,
  "death18": 148,
  "death19": 149,
  "death20": 150,
  "death21": 151,
  "death22": 152,
  "death23": 153,
  "death24": 154,
  "death25": 155,
  "death26": 156,
  "death27": 157,
  "death28": 158,
  "death29": 159,
  "death30": 160,
  "death31": 161,
  "death32": 162,
  "death33": 163,
  "death34": 164,
  "death35": 165,
  "death36": 166,
  "death37": 167,
  "death38": 168,
  "death39": 169,
  "death40": 170,
  "death41": 171,
  "death42": 172,
  "death43": 173,
  "death44": 174,
  "death45": 175,
  "death46": 176,
  "death47": 177,
  "death48": 178,
  "death49": 179,
  "death50": 180
});
