/* Original Quake II m_brain.c frame order and distances. id Software, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const brainMoves: readonly MonsterMove[] = [
  { name: "brain_move_stand", firstFrame: 162, lastFrame: 191, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_idle", firstFrame: 192, lastFrame: 221, end: "brain_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_walk1", firstFrame: 0, lastFrame: 10, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_defense", firstFrame: 154, lastFrame: 161, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_pain3", firstFrame: 117, lastFrame: 122, end: "brain_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_pain2", firstFrame: 109, lastFrame: 116, end: "brain_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_pain1", firstFrame: 88, lastFrame: 108, end: "brain_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_duck", firstFrame: 146, lastFrame: 153, end: "brain_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: ["brain_duck_down"], lerpFrame: -1 },
    { ai: "move", distance: 17, actions: ["brain_duck_hold"], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: ["brain_duck_up"], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -6, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_death2", firstFrame: 141, lastFrame: 145, end: "brain_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_death1", firstFrame: 123, lastFrame: 140, end: "brain_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_attack1", firstFrame: 53, lastFrame: 70, end: "brain_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -3, actions: ["brain_swing_right"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -7, actions: ["brain_hit_right"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: ["brain_swing_left"], lerpFrame: -1 },
    { ai: "charge", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: ["brain_hit_left"], lerpFrame: -1 },
    { ai: "charge", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -11, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_attack2", firstFrame: 71, lastFrame: 87, end: "brain_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["brain_chest_open"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 13, actions: ["brain_tentacle_attack"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -9, actions: ["brain_chest_closed"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: -6, actions: [], lerpFrame: -1 },
  ] },
  { name: "brain_move_run", firstFrame: 0, lastFrame: 10, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: -4, actions: [], lerpFrame: -1 },
    { ai: "run", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 2, actions: [], lerpFrame: -1 },
  ] },
];

export const brainFrame = Object.freeze({
  "walk101": 0,
  "walk102": 1,
  "walk103": 2,
  "walk104": 3,
  "walk105": 4,
  "walk106": 5,
  "walk107": 6,
  "walk108": 7,
  "walk109": 8,
  "walk110": 9,
  "walk111": 10,
  "walk112": 11,
  "walk113": 12,
  "walk201": 13,
  "walk202": 14,
  "walk203": 15,
  "walk204": 16,
  "walk205": 17,
  "walk206": 18,
  "walk207": 19,
  "walk208": 20,
  "walk209": 21,
  "walk210": 22,
  "walk211": 23,
  "walk212": 24,
  "walk213": 25,
  "walk214": 26,
  "walk215": 27,
  "walk216": 28,
  "walk217": 29,
  "walk218": 30,
  "walk219": 31,
  "walk220": 32,
  "walk221": 33,
  "walk222": 34,
  "walk223": 35,
  "walk224": 36,
  "walk225": 37,
  "walk226": 38,
  "walk227": 39,
  "walk228": 40,
  "walk229": 41,
  "walk230": 42,
  "walk231": 43,
  "walk232": 44,
  "walk233": 45,
  "walk234": 46,
  "walk235": 47,
  "walk236": 48,
  "walk237": 49,
  "walk238": 50,
  "walk239": 51,
  "walk240": 52,
  "attak101": 53,
  "attak102": 54,
  "attak103": 55,
  "attak104": 56,
  "attak105": 57,
  "attak106": 58,
  "attak107": 59,
  "attak108": 60,
  "attak109": 61,
  "attak110": 62,
  "attak111": 63,
  "attak112": 64,
  "attak113": 65,
  "attak114": 66,
  "attak115": 67,
  "attak116": 68,
  "attak117": 69,
  "attak118": 70,
  "attak201": 71,
  "attak202": 72,
  "attak203": 73,
  "attak204": 74,
  "attak205": 75,
  "attak206": 76,
  "attak207": 77,
  "attak208": 78,
  "attak209": 79,
  "attak210": 80,
  "attak211": 81,
  "attak212": 82,
  "attak213": 83,
  "attak214": 84,
  "attak215": 85,
  "attak216": 86,
  "attak217": 87,
  "pain101": 88,
  "pain102": 89,
  "pain103": 90,
  "pain104": 91,
  "pain105": 92,
  "pain106": 93,
  "pain107": 94,
  "pain108": 95,
  "pain109": 96,
  "pain110": 97,
  "pain111": 98,
  "pain112": 99,
  "pain113": 100,
  "pain114": 101,
  "pain115": 102,
  "pain116": 103,
  "pain117": 104,
  "pain118": 105,
  "pain119": 106,
  "pain120": 107,
  "pain121": 108,
  "pain201": 109,
  "pain202": 110,
  "pain203": 111,
  "pain204": 112,
  "pain205": 113,
  "pain206": 114,
  "pain207": 115,
  "pain208": 116,
  "pain301": 117,
  "pain302": 118,
  "pain303": 119,
  "pain304": 120,
  "pain305": 121,
  "pain306": 122,
  "death101": 123,
  "death102": 124,
  "death103": 125,
  "death104": 126,
  "death105": 127,
  "death106": 128,
  "death107": 129,
  "death108": 130,
  "death109": 131,
  "death110": 132,
  "death111": 133,
  "death112": 134,
  "death113": 135,
  "death114": 136,
  "death115": 137,
  "death116": 138,
  "death117": 139,
  "death118": 140,
  "death201": 141,
  "death202": 142,
  "death203": 143,
  "death204": 144,
  "death205": 145,
  "duck01": 146,
  "duck02": 147,
  "duck03": 148,
  "duck04": 149,
  "duck05": 150,
  "duck06": 151,
  "duck07": 152,
  "duck08": 153,
  "defens01": 154,
  "defens02": 155,
  "defens03": 156,
  "defens04": 157,
  "defens05": 158,
  "defens06": 159,
  "defens07": 160,
  "defens08": 161,
  "stand01": 162,
  "stand02": 163,
  "stand03": 164,
  "stand04": 165,
  "stand05": 166,
  "stand06": 167,
  "stand07": 168,
  "stand08": 169,
  "stand09": 170,
  "stand10": 171,
  "stand11": 172,
  "stand12": 173,
  "stand13": 174,
  "stand14": 175,
  "stand15": 176,
  "stand16": 177,
  "stand17": 178,
  "stand18": 179,
  "stand19": 180,
  "stand20": 181,
  "stand21": 182,
  "stand22": 183,
  "stand23": 184,
  "stand24": 185,
  "stand25": 186,
  "stand26": 187,
  "stand27": 188,
  "stand28": 189,
  "stand29": 190,
  "stand30": 191,
  "stand31": 192,
  "stand32": 193,
  "stand33": 194,
  "stand34": 195,
  "stand35": 196,
  "stand36": 197,
  "stand37": 198,
  "stand38": 199,
  "stand39": 200,
  "stand40": 201,
  "stand41": 202,
  "stand42": 203,
  "stand43": 204,
  "stand44": 205,
  "stand45": 206,
  "stand46": 207,
  "stand47": 208,
  "stand48": 209,
  "stand49": 210,
  "stand50": 211,
  "stand51": 212,
  "stand52": 213,
  "stand53": 214,
  "stand54": 215,
  "stand55": 216,
  "stand56": 217,
  "stand57": 218,
  "stand58": 219,
  "stand59": 220,
  "stand60": 221
});
