/* Original Quake II m_float.c frame order and distances. id Software, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const floatMoves: readonly MonsterMove[] = [
  { name: "floater_move_stand1", firstFrame: 144, lastFrame: 195, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_stand2", firstFrame: 196, lastFrame: 247, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_activate", firstFrame: 0, lastFrame: 30, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_attack1", firstFrame: 31, lastFrame: 44, end: "floater_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_attack2", firstFrame: 45, lastFrame: 69, end: "floater_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_wham"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_attack3", firstFrame: 70, lastFrame: 103, end: "floater_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["floater_zap"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_death", firstFrame: 104, lastFrame: 116, end: "floater_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_pain1", firstFrame: 117, lastFrame: 123, end: "floater_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_pain2", firstFrame: 124, lastFrame: 131, end: "floater_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_pain3", firstFrame: 132, lastFrame: 143, end: "floater_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_walk", firstFrame: 144, lastFrame: 195, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
  ] },
  { name: "floater_move_run", firstFrame: 144, lastFrame: 195, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
  ] },
];

export const floatFrame = Object.freeze({
  "actvat01": 0,
  "actvat02": 1,
  "actvat03": 2,
  "actvat04": 3,
  "actvat05": 4,
  "actvat06": 5,
  "actvat07": 6,
  "actvat08": 7,
  "actvat09": 8,
  "actvat10": 9,
  "actvat11": 10,
  "actvat12": 11,
  "actvat13": 12,
  "actvat14": 13,
  "actvat15": 14,
  "actvat16": 15,
  "actvat17": 16,
  "actvat18": 17,
  "actvat19": 18,
  "actvat20": 19,
  "actvat21": 20,
  "actvat22": 21,
  "actvat23": 22,
  "actvat24": 23,
  "actvat25": 24,
  "actvat26": 25,
  "actvat27": 26,
  "actvat28": 27,
  "actvat29": 28,
  "actvat30": 29,
  "actvat31": 30,
  "attak101": 31,
  "attak102": 32,
  "attak103": 33,
  "attak104": 34,
  "attak105": 35,
  "attak106": 36,
  "attak107": 37,
  "attak108": 38,
  "attak109": 39,
  "attak110": 40,
  "attak111": 41,
  "attak112": 42,
  "attak113": 43,
  "attak114": 44,
  "attak201": 45,
  "attak202": 46,
  "attak203": 47,
  "attak204": 48,
  "attak205": 49,
  "attak206": 50,
  "attak207": 51,
  "attak208": 52,
  "attak209": 53,
  "attak210": 54,
  "attak211": 55,
  "attak212": 56,
  "attak213": 57,
  "attak214": 58,
  "attak215": 59,
  "attak216": 60,
  "attak217": 61,
  "attak218": 62,
  "attak219": 63,
  "attak220": 64,
  "attak221": 65,
  "attak222": 66,
  "attak223": 67,
  "attak224": 68,
  "attak225": 69,
  "attak301": 70,
  "attak302": 71,
  "attak303": 72,
  "attak304": 73,
  "attak305": 74,
  "attak306": 75,
  "attak307": 76,
  "attak308": 77,
  "attak309": 78,
  "attak310": 79,
  "attak311": 80,
  "attak312": 81,
  "attak313": 82,
  "attak314": 83,
  "attak315": 84,
  "attak316": 85,
  "attak317": 86,
  "attak318": 87,
  "attak319": 88,
  "attak320": 89,
  "attak321": 90,
  "attak322": 91,
  "attak323": 92,
  "attak324": 93,
  "attak325": 94,
  "attak326": 95,
  "attak327": 96,
  "attak328": 97,
  "attak329": 98,
  "attak330": 99,
  "attak331": 100,
  "attak332": 101,
  "attak333": 102,
  "attak334": 103,
  "death01": 104,
  "death02": 105,
  "death03": 106,
  "death04": 107,
  "death05": 108,
  "death06": 109,
  "death07": 110,
  "death08": 111,
  "death09": 112,
  "death10": 113,
  "death11": 114,
  "death12": 115,
  "death13": 116,
  "pain101": 117,
  "pain102": 118,
  "pain103": 119,
  "pain104": 120,
  "pain105": 121,
  "pain106": 122,
  "pain107": 123,
  "pain201": 124,
  "pain202": 125,
  "pain203": 126,
  "pain204": 127,
  "pain205": 128,
  "pain206": 129,
  "pain207": 130,
  "pain208": 131,
  "pain301": 132,
  "pain302": 133,
  "pain303": 134,
  "pain304": 135,
  "pain305": 136,
  "pain306": 137,
  "pain307": 138,
  "pain308": 139,
  "pain309": 140,
  "pain310": 141,
  "pain311": 142,
  "pain312": 143,
  "stand101": 144,
  "stand102": 145,
  "stand103": 146,
  "stand104": 147,
  "stand105": 148,
  "stand106": 149,
  "stand107": 150,
  "stand108": 151,
  "stand109": 152,
  "stand110": 153,
  "stand111": 154,
  "stand112": 155,
  "stand113": 156,
  "stand114": 157,
  "stand115": 158,
  "stand116": 159,
  "stand117": 160,
  "stand118": 161,
  "stand119": 162,
  "stand120": 163,
  "stand121": 164,
  "stand122": 165,
  "stand123": 166,
  "stand124": 167,
  "stand125": 168,
  "stand126": 169,
  "stand127": 170,
  "stand128": 171,
  "stand129": 172,
  "stand130": 173,
  "stand131": 174,
  "stand132": 175,
  "stand133": 176,
  "stand134": 177,
  "stand135": 178,
  "stand136": 179,
  "stand137": 180,
  "stand138": 181,
  "stand139": 182,
  "stand140": 183,
  "stand141": 184,
  "stand142": 185,
  "stand143": 186,
  "stand144": 187,
  "stand145": 188,
  "stand146": 189,
  "stand147": 190,
  "stand148": 191,
  "stand149": 192,
  "stand150": 193,
  "stand151": 194,
  "stand152": 195,
  "stand201": 196,
  "stand202": 197,
  "stand203": 198,
  "stand204": 199,
  "stand205": 200,
  "stand206": 201,
  "stand207": 202,
  "stand208": 203,
  "stand209": 204,
  "stand210": 205,
  "stand211": 206,
  "stand212": 207,
  "stand213": 208,
  "stand214": 209,
  "stand215": 210,
  "stand216": 211,
  "stand217": 212,
  "stand218": 213,
  "stand219": 214,
  "stand220": 215,
  "stand221": 216,
  "stand222": 217,
  "stand223": 218,
  "stand224": 219,
  "stand225": 220,
  "stand226": 221,
  "stand227": 222,
  "stand228": 223,
  "stand229": 224,
  "stand230": 225,
  "stand231": 226,
  "stand232": 227,
  "stand233": 228,
  "stand234": 229,
  "stand235": 230,
  "stand236": 231,
  "stand237": 232,
  "stand238": 233,
  "stand239": 234,
  "stand240": 235,
  "stand241": 236,
  "stand242": 237,
  "stand243": 238,
  "stand244": 239,
  "stand245": 240,
  "stand246": 241,
  "stand247": 242,
  "stand248": 243,
  "stand249": 244,
  "stand250": 245,
  "stand251": 246,
  "stand252": 247
});
