/* Original Quake II m_gladiator.c frame order and distances. id Software, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const gladiatorMoves: readonly MonsterMove[] = [
  { name: "gladiator_move_stand", firstFrame: 0, lastFrame: 6, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gladiator_move_walk", firstFrame: 7, lastFrame: 22, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 15, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 8, actions: [], lerpFrame: -1 },
  ] },
  { name: "gladiator_move_run", firstFrame: 23, lastFrame: 28, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 23, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 14, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 21, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
  ] },
  { name: "gladiator_move_attack_melee", firstFrame: 29, lastFrame: 45, end: "gladiator_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["gladiator_cleaver_swing"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GaldiatorMelee"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["gladiator_cleaver_swing"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GaldiatorMelee"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gladiator_move_attack_gun", firstFrame: 46, lastFrame: 54, end: "gladiator_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GladiatorGun"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gladiator_move_pain", firstFrame: 55, lastFrame: 60, end: "gladiator_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gladiator_move_pain_air", firstFrame: 83, lastFrame: 89, end: "gladiator_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gladiator_move_death", firstFrame: 61, lastFrame: 82, end: "gladiator_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const gladiatorFrame = Object.freeze({
  "stand1": 0,
  "stand2": 1,
  "stand3": 2,
  "stand4": 3,
  "stand5": 4,
  "stand6": 5,
  "stand7": 6,
  "walk1": 7,
  "walk2": 8,
  "walk3": 9,
  "walk4": 10,
  "walk5": 11,
  "walk6": 12,
  "walk7": 13,
  "walk8": 14,
  "walk9": 15,
  "walk10": 16,
  "walk11": 17,
  "walk12": 18,
  "walk13": 19,
  "walk14": 20,
  "walk15": 21,
  "walk16": 22,
  "run1": 23,
  "run2": 24,
  "run3": 25,
  "run4": 26,
  "run5": 27,
  "run6": 28,
  "melee1": 29,
  "melee2": 30,
  "melee3": 31,
  "melee4": 32,
  "melee5": 33,
  "melee6": 34,
  "melee7": 35,
  "melee8": 36,
  "melee9": 37,
  "melee10": 38,
  "melee11": 39,
  "melee12": 40,
  "melee13": 41,
  "melee14": 42,
  "melee15": 43,
  "melee16": 44,
  "melee17": 45,
  "attack1": 46,
  "attack2": 47,
  "attack3": 48,
  "attack4": 49,
  "attack5": 50,
  "attack6": 51,
  "attack7": 52,
  "attack8": 53,
  "attack9": 54,
  "pain1": 55,
  "pain2": 56,
  "pain3": 57,
  "pain4": 58,
  "pain5": 59,
  "pain6": 60,
  "death1": 61,
  "death2": 62,
  "death3": 63,
  "death4": 64,
  "death5": 65,
  "death6": 66,
  "death7": 67,
  "death8": 68,
  "death9": 69,
  "death10": 70,
  "death11": 71,
  "death12": 72,
  "death13": 73,
  "death14": 74,
  "death15": 75,
  "death16": 76,
  "death17": 77,
  "death18": 78,
  "death19": 79,
  "death20": 80,
  "death21": 81,
  "death22": 82,
  "painup1": 83,
  "painup2": 84,
  "painup3": 85,
  "painup4": 86,
  "painup5": 87,
  "painup6": 88,
  "painup7": 89
});
