/* Original Quake II m_gunner.c frame order and distances. id Software, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const gunnerMoves: readonly MonsterMove[] = [
  { name: "gunner_move_fidget", firstFrame: 30, lastFrame: 69, end: "gunner_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["gunner_idlesound"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_stand", firstFrame: 0, lastFrame: 29, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["gunner_fidget"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["gunner_fidget"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["gunner_fidget"], lerpFrame: -1 },
  ] },
  { name: "gunner_move_walk", firstFrame: 76, lastFrame: 88, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_run", firstFrame: 94, lastFrame: 101, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 26, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 9, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 15, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 13, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 6, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_runandshoot", firstFrame: 102, lastFrame: 107, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 32, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 15, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 10, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 18, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 20, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_pain3", firstFrame: 185, lastFrame: 189, end: "gunner_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_pain2", firstFrame: 177, lastFrame: 184, end: "gunner_run", sidestepScale: 0, frames: [
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 11, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -7, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_pain1", firstFrame: 159, lastFrame: 176, end: "gunner_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_death", firstFrame: 190, lastFrame: 200, end: "gunner_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_duck", firstFrame: 201, lastFrame: 208, end: "gunner_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 1, actions: ["gunner_duck_down"], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 1, actions: ["gunner_duck_hold"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["gunner_duck_up"], lerpFrame: -1 },
    { ai: "move", distance: -1, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_attack_chain", firstFrame: 137, lastFrame: 143, end: "gunner_fire_chain", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["gunner_opengun"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_fire_chain", firstFrame: 144, lastFrame: 151, end: "gunner_refire_chain", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerFire"], lerpFrame: -1 },
  ] },
  { name: "gunner_move_endfire_chain", firstFrame: 152, lastFrame: 158, end: "gunner_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "gunner_move_attack_grenade", firstFrame: 108, lastFrame: 128, end: "gunner_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerGrenade"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerGrenade"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerGrenade"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["GunnerGrenade"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const gunnerFrame = Object.freeze({
  "stand01": 0,
  "stand02": 1,
  "stand03": 2,
  "stand04": 3,
  "stand05": 4,
  "stand06": 5,
  "stand07": 6,
  "stand08": 7,
  "stand09": 8,
  "stand10": 9,
  "stand11": 10,
  "stand12": 11,
  "stand13": 12,
  "stand14": 13,
  "stand15": 14,
  "stand16": 15,
  "stand17": 16,
  "stand18": 17,
  "stand19": 18,
  "stand20": 19,
  "stand21": 20,
  "stand22": 21,
  "stand23": 22,
  "stand24": 23,
  "stand25": 24,
  "stand26": 25,
  "stand27": 26,
  "stand28": 27,
  "stand29": 28,
  "stand30": 29,
  "stand31": 30,
  "stand32": 31,
  "stand33": 32,
  "stand34": 33,
  "stand35": 34,
  "stand36": 35,
  "stand37": 36,
  "stand38": 37,
  "stand39": 38,
  "stand40": 39,
  "stand41": 40,
  "stand42": 41,
  "stand43": 42,
  "stand44": 43,
  "stand45": 44,
  "stand46": 45,
  "stand47": 46,
  "stand48": 47,
  "stand49": 48,
  "stand50": 49,
  "stand51": 50,
  "stand52": 51,
  "stand53": 52,
  "stand54": 53,
  "stand55": 54,
  "stand56": 55,
  "stand57": 56,
  "stand58": 57,
  "stand59": 58,
  "stand60": 59,
  "stand61": 60,
  "stand62": 61,
  "stand63": 62,
  "stand64": 63,
  "stand65": 64,
  "stand66": 65,
  "stand67": 66,
  "stand68": 67,
  "stand69": 68,
  "stand70": 69,
  "walk01": 70,
  "walk02": 71,
  "walk03": 72,
  "walk04": 73,
  "walk05": 74,
  "walk06": 75,
  "walk07": 76,
  "walk08": 77,
  "walk09": 78,
  "walk10": 79,
  "walk11": 80,
  "walk12": 81,
  "walk13": 82,
  "walk14": 83,
  "walk15": 84,
  "walk16": 85,
  "walk17": 86,
  "walk18": 87,
  "walk19": 88,
  "walk20": 89,
  "walk21": 90,
  "walk22": 91,
  "walk23": 92,
  "walk24": 93,
  "run01": 94,
  "run02": 95,
  "run03": 96,
  "run04": 97,
  "run05": 98,
  "run06": 99,
  "run07": 100,
  "run08": 101,
  "runs01": 102,
  "runs02": 103,
  "runs03": 104,
  "runs04": 105,
  "runs05": 106,
  "runs06": 107,
  "attak101": 108,
  "attak102": 109,
  "attak103": 110,
  "attak104": 111,
  "attak105": 112,
  "attak106": 113,
  "attak107": 114,
  "attak108": 115,
  "attak109": 116,
  "attak110": 117,
  "attak111": 118,
  "attak112": 119,
  "attak113": 120,
  "attak114": 121,
  "attak115": 122,
  "attak116": 123,
  "attak117": 124,
  "attak118": 125,
  "attak119": 126,
  "attak120": 127,
  "attak121": 128,
  "attak201": 129,
  "attak202": 130,
  "attak203": 131,
  "attak204": 132,
  "attak205": 133,
  "attak206": 134,
  "attak207": 135,
  "attak208": 136,
  "attak209": 137,
  "attak210": 138,
  "attak211": 139,
  "attak212": 140,
  "attak213": 141,
  "attak214": 142,
  "attak215": 143,
  "attak216": 144,
  "attak217": 145,
  "attak218": 146,
  "attak219": 147,
  "attak220": 148,
  "attak221": 149,
  "attak222": 150,
  "attak223": 151,
  "attak224": 152,
  "attak225": 153,
  "attak226": 154,
  "attak227": 155,
  "attak228": 156,
  "attak229": 157,
  "attak230": 158,
  "pain101": 159,
  "pain102": 160,
  "pain103": 161,
  "pain104": 162,
  "pain105": 163,
  "pain106": 164,
  "pain107": 165,
  "pain108": 166,
  "pain109": 167,
  "pain110": 168,
  "pain111": 169,
  "pain112": 170,
  "pain113": 171,
  "pain114": 172,
  "pain115": 173,
  "pain116": 174,
  "pain117": 175,
  "pain118": 176,
  "pain201": 177,
  "pain202": 178,
  "pain203": 179,
  "pain204": 180,
  "pain205": 181,
  "pain206": 182,
  "pain207": 183,
  "pain208": 184,
  "pain301": 185,
  "pain302": 186,
  "pain303": 187,
  "pain304": 188,
  "pain305": 189,
  "death01": 190,
  "death02": 191,
  "death03": 192,
  "death04": 193,
  "death05": 194,
  "death06": 195,
  "death07": 196,
  "death08": 197,
  "death09": 198,
  "death10": 199,
  "death11": 200,
  "duck01": 201,
  "duck02": 202,
  "duck03": 203,
  "duck04": 204,
  "duck05": 205,
  "duck06": 206,
  "duck07": 207,
  "duck08": 208
});
