/* Original Quake II m_insane.c frame order and distances. id Software, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const insaneMoves: readonly MonsterMove[] = [
  { name: "insane_move_stand_normal", firstFrame: 59, lastFrame: 64, end: "insane_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["insane_checkdown"], lerpFrame: -1 },
  ] },
  { name: "insane_move_stand_insane", firstFrame: 64, lastFrame: 93, end: "insane_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: ["insane_shake"], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: ["insane_checkdown"], lerpFrame: -1 },
  ] },
  { name: "insane_move_uptodown", firstFrame: 0, lastFrame: 39, end: "insane_onground", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["insane_moan"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 2.7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 4.1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 7.6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 3.6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["insane_fist"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["insane_fist"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_downtoup", firstFrame: 40, lastFrame: 58, end: "insane_stand", sidestepScale: 0, frames: [
    { ai: "move", distance: -0.7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -4.5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3.5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -3.3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.3, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_jumpdown", firstFrame: 95, lastFrame: 99, end: "insane_onground", sidestepScale: 0, frames: [
    { ai: "move", distance: 0.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 11.5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 5.1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 7.1, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_down", firstFrame: 99, lastFrame: 159, end: "insane_onground", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -1.6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["insane_fist"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["insane_moan"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.5, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: -0.2, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.2, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.4, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.6, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.8, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0.7, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["insane_checkup"], lerpFrame: -1 },
  ] },
  { name: "insane_move_walk_normal", firstFrame: 160, lastFrame: 172, end: "insane_walk", sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "walk", distance: 2.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_run_normal", firstFrame: 160, lastFrame: 172, end: "insane_run", sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "walk", distance: 2.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_walk_insane", firstFrame: 173, lastFrame: 198, end: "insane_walk", sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "walk", distance: 3.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5.3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1.1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1.8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_run_insane", firstFrame: 173, lastFrame: 198, end: "insane_run", sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "walk", distance: 3.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5.3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1.1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.7, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 6.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 1.8, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_stand_pain", firstFrame: 199, lastFrame: 209, end: "insane_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_stand_death", firstFrame: 210, lastFrame: 226, end: "insane_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_crawl", firstFrame: 227, lastFrame: 235, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "walk", distance: 1.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.4, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_runcrawl", firstFrame: 227, lastFrame: 235, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "walk", distance: 1.5, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.1, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.6, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0.9, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 3.4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 2.4, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_crawl_pain", firstFrame: 236, lastFrame: 244, end: "insane_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_crawl_death", firstFrame: 245, lastFrame: 251, end: "insane_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_cross", firstFrame: 252, lastFrame: 266, end: "insane_cross", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["insane_moan"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "insane_move_struggle_cross", firstFrame: 267, lastFrame: 281, end: "insane_cross", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["insane_scream"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const insaneFrame = Object.freeze({
  "stand1": 0,
  "stand2": 1,
  "stand3": 2,
  "stand4": 3,
  "stand5": 4,
  "stand6": 5,
  "stand7": 6,
  "stand8": 7,
  "stand9": 8,
  "stand10": 9,
  "stand11": 10,
  "stand12": 11,
  "stand13": 12,
  "stand14": 13,
  "stand15": 14,
  "stand16": 15,
  "stand17": 16,
  "stand18": 17,
  "stand19": 18,
  "stand20": 19,
  "stand21": 20,
  "stand22": 21,
  "stand23": 22,
  "stand24": 23,
  "stand25": 24,
  "stand26": 25,
  "stand27": 26,
  "stand28": 27,
  "stand29": 28,
  "stand30": 29,
  "stand31": 30,
  "stand32": 31,
  "stand33": 32,
  "stand34": 33,
  "stand35": 34,
  "stand36": 35,
  "stand37": 36,
  "stand38": 37,
  "stand39": 38,
  "stand40": 39,
  "stand41": 40,
  "stand42": 41,
  "stand43": 42,
  "stand44": 43,
  "stand45": 44,
  "stand46": 45,
  "stand47": 46,
  "stand48": 47,
  "stand49": 48,
  "stand50": 49,
  "stand51": 50,
  "stand52": 51,
  "stand53": 52,
  "stand54": 53,
  "stand55": 54,
  "stand56": 55,
  "stand57": 56,
  "stand58": 57,
  "stand59": 58,
  "stand60": 59,
  "stand61": 60,
  "stand62": 61,
  "stand63": 62,
  "stand64": 63,
  "stand65": 64,
  "stand66": 65,
  "stand67": 66,
  "stand68": 67,
  "stand69": 68,
  "stand70": 69,
  "stand71": 70,
  "stand72": 71,
  "stand73": 72,
  "stand74": 73,
  "stand75": 74,
  "stand76": 75,
  "stand77": 76,
  "stand78": 77,
  "stand79": 78,
  "stand80": 79,
  "stand81": 80,
  "stand82": 81,
  "stand83": 82,
  "stand84": 83,
  "stand85": 84,
  "stand86": 85,
  "stand87": 86,
  "stand88": 87,
  "stand89": 88,
  "stand90": 89,
  "stand91": 90,
  "stand92": 91,
  "stand93": 92,
  "stand94": 93,
  "stand95": 94,
  "stand96": 95,
  "stand97": 96,
  "stand98": 97,
  "stand99": 98,
  "stand100": 99,
  "stand101": 100,
  "stand102": 101,
  "stand103": 102,
  "stand104": 103,
  "stand105": 104,
  "stand106": 105,
  "stand107": 106,
  "stand108": 107,
  "stand109": 108,
  "stand110": 109,
  "stand111": 110,
  "stand112": 111,
  "stand113": 112,
  "stand114": 113,
  "stand115": 114,
  "stand116": 115,
  "stand117": 116,
  "stand118": 117,
  "stand119": 118,
  "stand120": 119,
  "stand121": 120,
  "stand122": 121,
  "stand123": 122,
  "stand124": 123,
  "stand125": 124,
  "stand126": 125,
  "stand127": 126,
  "stand128": 127,
  "stand129": 128,
  "stand130": 129,
  "stand131": 130,
  "stand132": 131,
  "stand133": 132,
  "stand134": 133,
  "stand135": 134,
  "stand136": 135,
  "stand137": 136,
  "stand138": 137,
  "stand139": 138,
  "stand140": 139,
  "stand141": 140,
  "stand142": 141,
  "stand143": 142,
  "stand144": 143,
  "stand145": 144,
  "stand146": 145,
  "stand147": 146,
  "stand148": 147,
  "stand149": 148,
  "stand150": 149,
  "stand151": 150,
  "stand152": 151,
  "stand153": 152,
  "stand154": 153,
  "stand155": 154,
  "stand156": 155,
  "stand157": 156,
  "stand158": 157,
  "stand159": 158,
  "stand160": 159,
  "walk27": 160,
  "walk28": 161,
  "walk29": 162,
  "walk30": 163,
  "walk31": 164,
  "walk32": 165,
  "walk33": 166,
  "walk34": 167,
  "walk35": 168,
  "walk36": 169,
  "walk37": 170,
  "walk38": 171,
  "walk39": 172,
  "walk1": 173,
  "walk2": 174,
  "walk3": 175,
  "walk4": 176,
  "walk5": 177,
  "walk6": 178,
  "walk7": 179,
  "walk8": 180,
  "walk9": 181,
  "walk10": 182,
  "walk11": 183,
  "walk12": 184,
  "walk13": 185,
  "walk14": 186,
  "walk15": 187,
  "walk16": 188,
  "walk17": 189,
  "walk18": 190,
  "walk19": 191,
  "walk20": 192,
  "walk21": 193,
  "walk22": 194,
  "walk23": 195,
  "walk24": 196,
  "walk25": 197,
  "walk26": 198,
  "st_pain2": 199,
  "st_pain3": 200,
  "st_pain4": 201,
  "st_pain5": 202,
  "st_pain6": 203,
  "st_pain7": 204,
  "st_pain8": 205,
  "st_pain9": 206,
  "st_pain10": 207,
  "st_pain11": 208,
  "st_pain12": 209,
  "st_death2": 210,
  "st_death3": 211,
  "st_death4": 212,
  "st_death5": 213,
  "st_death6": 214,
  "st_death7": 215,
  "st_death8": 216,
  "st_death9": 217,
  "st_death10": 218,
  "st_death11": 219,
  "st_death12": 220,
  "st_death13": 221,
  "st_death14": 222,
  "st_death15": 223,
  "st_death16": 224,
  "st_death17": 225,
  "st_death18": 226,
  "crawl1": 227,
  "crawl2": 228,
  "crawl3": 229,
  "crawl4": 230,
  "crawl5": 231,
  "crawl6": 232,
  "crawl7": 233,
  "crawl8": 234,
  "crawl9": 235,
  "cr_pain2": 236,
  "cr_pain3": 237,
  "cr_pain4": 238,
  "cr_pain5": 239,
  "cr_pain6": 240,
  "cr_pain7": 241,
  "cr_pain8": 242,
  "cr_pain9": 243,
  "cr_pain10": 244,
  "cr_death10": 245,
  "cr_death11": 246,
  "cr_death12": 247,
  "cr_death13": 248,
  "cr_death14": 249,
  "cr_death15": 250,
  "cr_death16": 251,
  "cross1": 252,
  "cross2": 253,
  "cross3": 254,
  "cross4": 255,
  "cross5": 256,
  "cross6": 257,
  "cross7": 258,
  "cross8": 259,
  "cross9": 260,
  "cross10": 261,
  "cross11": 262,
  "cross12": 263,
  "cross13": 264,
  "cross14": 265,
  "cross15": 266,
  "cross16": 267,
  "cross17": 268,
  "cross18": 269,
  "cross19": 270,
  "cross20": 271,
  "cross21": 272,
  "cross22": 273,
  "cross23": 274,
  "cross24": 275,
  "cross25": 276,
  "cross26": 277,
  "cross27": 278,
  "cross28": 279,
  "cross29": 280,
  "cross30": 281
});
