/* Original Quake II m_supertank.c frame order and distances. id Software, GPL-2.0-or-later. */
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const supertankMoves: readonly MonsterMove[] = [
  { name: "supertank_move_stand", firstFrame: 194, lastFrame: 253, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "stand", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_run", firstFrame: 128, lastFrame: 145, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: 12, actions: ["TreadSound"], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
    { ai: "run", distance: 12, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_forward", firstFrame: 128, lastFrame: 145, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 4, actions: ["TreadSound"], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 4, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_turn_right", firstFrame: 176, lastFrame: 193, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["TreadSound"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_turn_left", firstFrame: 146, lastFrame: 163, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: ["TreadSound"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_pain3", firstFrame: 172, lastFrame: 175, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_pain2", firstFrame: 168, lastFrame: 171, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_pain1", firstFrame: 164, lastFrame: 167, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_death", firstFrame: 98, lastFrame: 121, end: "supertank_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["BossExplode"], lerpFrame: -1 },
  ] },
  { name: "supertank_move_backward", firstFrame: 80, lastFrame: 97, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: 0, actions: ["TreadSound"], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "walk", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_attack4", firstFrame: 74, lastFrame: 79, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_attack3", firstFrame: 47, lastFrame: 73, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_attack2", firstFrame: 20, lastFrame: 46, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["supertankRocket"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["supertankRocket"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: ["supertankRocket"], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
  { name: "supertank_move_attack1", firstFrame: 0, lastFrame: 5, end: "supertank_reattack1", sidestepScale: 0, frames: [
    { ai: "charge", distance: 0, actions: ["supertankMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["supertankMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["supertankMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["supertankMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["supertankMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: 0, actions: ["supertankMachineGun"], lerpFrame: -1 },
  ] },
  { name: "supertank_move_end_attack1", firstFrame: 6, lastFrame: 19, end: "supertank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
    { ai: "move", distance: 0, actions: [], lerpFrame: -1 },
  ] },
];

export const supertankFrame = Object.freeze({
  "attak1_1": 0,
  "attak1_2": 1,
  "attak1_3": 2,
  "attak1_4": 3,
  "attak1_5": 4,
  "attak1_6": 5,
  "attak1_7": 6,
  "attak1_8": 7,
  "attak1_9": 8,
  "attak1_10": 9,
  "attak1_11": 10,
  "attak1_12": 11,
  "attak1_13": 12,
  "attak1_14": 13,
  "attak1_15": 14,
  "attak1_16": 15,
  "attak1_17": 16,
  "attak1_18": 17,
  "attak1_19": 18,
  "attak1_20": 19,
  "attak2_1": 20,
  "attak2_2": 21,
  "attak2_3": 22,
  "attak2_4": 23,
  "attak2_5": 24,
  "attak2_6": 25,
  "attak2_7": 26,
  "attak2_8": 27,
  "attak2_9": 28,
  "attak2_10": 29,
  "attak2_11": 30,
  "attak2_12": 31,
  "attak2_13": 32,
  "attak2_14": 33,
  "attak2_15": 34,
  "attak2_16": 35,
  "attak2_17": 36,
  "attak2_18": 37,
  "attak2_19": 38,
  "attak2_20": 39,
  "attak2_21": 40,
  "attak2_22": 41,
  "attak2_23": 42,
  "attak2_24": 43,
  "attak2_25": 44,
  "attak2_26": 45,
  "attak2_27": 46,
  "attak3_1": 47,
  "attak3_2": 48,
  "attak3_3": 49,
  "attak3_4": 50,
  "attak3_5": 51,
  "attak3_6": 52,
  "attak3_7": 53,
  "attak3_8": 54,
  "attak3_9": 55,
  "attak3_10": 56,
  "attak3_11": 57,
  "attak3_12": 58,
  "attak3_13": 59,
  "attak3_14": 60,
  "attak3_15": 61,
  "attak3_16": 62,
  "attak3_17": 63,
  "attak3_18": 64,
  "attak3_19": 65,
  "attak3_20": 66,
  "attak3_21": 67,
  "attak3_22": 68,
  "attak3_23": 69,
  "attak3_24": 70,
  "attak3_25": 71,
  "attak3_26": 72,
  "attak3_27": 73,
  "attak4_1": 74,
  "attak4_2": 75,
  "attak4_3": 76,
  "attak4_4": 77,
  "attak4_5": 78,
  "attak4_6": 79,
  "backwd_1": 80,
  "backwd_2": 81,
  "backwd_3": 82,
  "backwd_4": 83,
  "backwd_5": 84,
  "backwd_6": 85,
  "backwd_7": 86,
  "backwd_8": 87,
  "backwd_9": 88,
  "backwd_10": 89,
  "backwd_11": 90,
  "backwd_12": 91,
  "backwd_13": 92,
  "backwd_14": 93,
  "backwd_15": 94,
  "backwd_16": 95,
  "backwd_17": 96,
  "backwd_18": 97,
  "death_1": 98,
  "death_2": 99,
  "death_3": 100,
  "death_4": 101,
  "death_5": 102,
  "death_6": 103,
  "death_7": 104,
  "death_8": 105,
  "death_9": 106,
  "death_10": 107,
  "death_11": 108,
  "death_12": 109,
  "death_13": 110,
  "death_14": 111,
  "death_15": 112,
  "death_16": 113,
  "death_17": 114,
  "death_18": 115,
  "death_19": 116,
  "death_20": 117,
  "death_21": 118,
  "death_22": 119,
  "death_23": 120,
  "death_24": 121,
  "death_31": 122,
  "death_32": 123,
  "death_33": 124,
  "death_45": 125,
  "death_46": 126,
  "death_47": 127,
  "forwrd_1": 128,
  "forwrd_2": 129,
  "forwrd_3": 130,
  "forwrd_4": 131,
  "forwrd_5": 132,
  "forwrd_6": 133,
  "forwrd_7": 134,
  "forwrd_8": 135,
  "forwrd_9": 136,
  "forwrd_10": 137,
  "forwrd_11": 138,
  "forwrd_12": 139,
  "forwrd_13": 140,
  "forwrd_14": 141,
  "forwrd_15": 142,
  "forwrd_16": 143,
  "forwrd_17": 144,
  "forwrd_18": 145,
  "left_1": 146,
  "left_2": 147,
  "left_3": 148,
  "left_4": 149,
  "left_5": 150,
  "left_6": 151,
  "left_7": 152,
  "left_8": 153,
  "left_9": 154,
  "left_10": 155,
  "left_11": 156,
  "left_12": 157,
  "left_13": 158,
  "left_14": 159,
  "left_15": 160,
  "left_16": 161,
  "left_17": 162,
  "left_18": 163,
  "pain1_1": 164,
  "pain1_2": 165,
  "pain1_3": 166,
  "pain1_4": 167,
  "pain2_5": 168,
  "pain2_6": 169,
  "pain2_7": 170,
  "pain2_8": 171,
  "pain3_9": 172,
  "pain3_10": 173,
  "pain3_11": 174,
  "pain3_12": 175,
  "right_1": 176,
  "right_2": 177,
  "right_3": 178,
  "right_4": 179,
  "right_5": 180,
  "right_6": 181,
  "right_7": 182,
  "right_8": 183,
  "right_9": 184,
  "right_10": 185,
  "right_11": 186,
  "right_12": 187,
  "right_13": 188,
  "right_14": 189,
  "right_15": 190,
  "right_16": 191,
  "right_17": 192,
  "right_18": 193,
  "stand_1": 194,
  "stand_2": 195,
  "stand_3": 196,
  "stand_4": 197,
  "stand_5": 198,
  "stand_6": 199,
  "stand_7": 200,
  "stand_8": 201,
  "stand_9": 202,
  "stand_10": 203,
  "stand_11": 204,
  "stand_12": 205,
  "stand_13": 206,
  "stand_14": 207,
  "stand_15": 208,
  "stand_16": 209,
  "stand_17": 210,
  "stand_18": 211,
  "stand_19": 212,
  "stand_20": 213,
  "stand_21": 214,
  "stand_22": 215,
  "stand_23": 216,
  "stand_24": 217,
  "stand_25": 218,
  "stand_26": 219,
  "stand_27": 220,
  "stand_28": 221,
  "stand_29": 222,
  "stand_30": 223,
  "stand_31": 224,
  "stand_32": 225,
  "stand_33": 226,
  "stand_34": 227,
  "stand_35": 228,
  "stand_36": 229,
  "stand_37": 230,
  "stand_38": 231,
  "stand_39": 232,
  "stand_40": 233,
  "stand_41": 234,
  "stand_42": 235,
  "stand_43": 236,
  "stand_44": 237,
  "stand_45": 238,
  "stand_46": 239,
  "stand_47": 240,
  "stand_48": 241,
  "stand_49": 242,
  "stand_50": 243,
  "stand_51": 244,
  "stand_52": 245,
  "stand_53": 246,
  "stand_54": 247,
  "stand_55": 248,
  "stand_56": 249,
  "stand_57": 250,
  "stand_58": 251,
  "stand_59": 252,
  "stand_60": 253
});
