import { expect, test } from 'bun:test';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Q3CdKeyState, validateQ3CdKey } from '../../../src/core/q3-cd-key.ts';
import { CvarRegistry, CvarFlag } from '../../../src/core/cvars/index.ts';
import { createIdentityOwner } from '../../../src/contracts/identity.ts';
import { ConfigStore } from '../../../src/settings/config.ts';
import { Q3ClientAuthorization } from '../../../src/network/q3/client-authorization.ts';
import { decodeConnectionless } from '../../../src/network/q3/connectionless.ts';
import type { Ipv4Address } from '../../../src/network/common/endpoint.ts';

const fixtureBase = '2'.repeat(16), fixtureUnique = '3'.repeat(16);
function cvars(): CvarRegistry { return new CvarRegistry({ dialect: 'q3', context: { session: createIdentityOwner('q3-key-test').session, origin: { kind: 'local-console' } } }); }
const authority: Ipv4Address = { kind: 'ipv4', host: [192, 0, 2, 1], port: 27952 };

test('Q3 key owner preserves base/unique selection, validates checksum and writes native loose storage', async () => {
  const root = await mkdtemp(join(tmpdir(), 'q3-key-fixture-'));
  try {
    const base = new ConfigStore(join(root, 'base')), mod = new ConfigStore(join(root, 'mod'));
    await base.dump('q3key', fixtureBase + '\n'); await mod.dump('q3key', fixtureUnique + '\n');
    const registry = cvars(), keys = new Q3CdKeyState(registry);
    await keys.readFile(base); await keys.appendFile(mod);
    const destination = new Uint8Array(33), ui = new Uint8Array(17);
    keys.readAuthorization(destination);
    expect(String.fromCharCode(...destination.subarray(0, 32)) === fixtureBase + fixtureUnique).toBe(true);
    keys.readUi(1, 'missionpack', ui); expect(String.fromCharCode(...ui.subarray(0, 16)) === fixtureUnique).toBe(true);
    keys.readUi(2, 'missionpack', ui); expect(String.fromCharCode(...ui.subarray(0, 16)) === fixtureBase).toBe(true);
    keys.readUi(1, '', ui); expect(String.fromCharCode(...ui.subarray(0, 16)) === fixtureBase).toBe(true);
    expect(validateQ3CdKey(fixtureBase, '20')).toBe(true); expect(validateQ3CdKey(fixtureBase, '21')).toBe(false);
    expect(validateQ3CdKey('I'.repeat(16), null)).toBe(false);
    expect(validateQ3CdKey('ß'.repeat(16), null)).toBe(false);
    expect(validateQ3CdKey('界'.repeat(16), null)).toBe(false);
    keys.writeUi(1, 'missionpack', new TextEncoder().encode(fixtureBase));
    expect((registry.modifiedFlags & CvarFlag.Archive) !== 0).toBe(true);
    await keys.writeFile(mod, 16);
    expect((await mod.loadText('q3key'))?.startsWith(fixtureBase + '\n// generated by quake')).toBe(true);
    await keys.readFile(new ConfigStore(join(root, 'missing')));
    keys.readAuthorization(destination); expect(destination[16]).toBe(0);
    expect(destination.subarray(0, 16).every(byte => byte === 32)).toBe(true);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('Q3 client authorization uses native packet, cached endpoint, anonymous cvar and demo key', async () => {
  const registry = cvars(), keys = new Q3CdKeyState(registry);
  keys.writeUi(0, '', new TextEncoder().encode(fixtureBase));
  registry.register('cl_anonymous', '1', CvarFlag.None);
  let demo = false, lookups = 0;
  const packets: Uint8Array[] = [];
  const owner = new Q3ClientAuthorization({ cvars: registry, keys, demoRestricted: () => demo,
    async resolve() { lookups++; return authority; }, print() {} });
  const send = (address: Ipv4Address, packet: Uint8Array) => { expect(address).toEqual(authority); packets.push(packet); };
  await owner.request(() => undefined, send);
  const first = packets[0]; if (first === undefined) throw new Error('Missing authorization packet');
  const decoded = decodeConnectionless(first, 'server');
  expect(decoded.command).toBe('getKeyAuthorize'); expect(decoded.arguments[0]).toBe('1');
  expect(decoded.arguments[1] === fixtureBase).toBe(true);
  demo = true; await owner.request(() => undefined, send);
  const second = packets[1]; if (second === undefined) throw new Error('Missing demo request');
  expect(decodeConnectionless(second, 'server').arguments[1]).toBe('demota'); expect(lookups).toBe(1);
});

test('Q3 client authorization suppresses a pending request after owner retirement and retries failed lookup', async () => {
  const registry = cvars(), keys = new Q3CdKeyState(registry), gate = Promise.withResolvers<Ipv4Address | null>();
  let current = true, sent = 0, attempts = 0;
  const owner = new Q3ClientAuthorization({ cvars: registry, keys, demoRestricted: () => false,
    resolve: () => gate.promise, print() {} });
  const pending = owner.request(() => { if (!current) throw new Error('Retired fixture'); }, () => { sent++; });
  current = false; gate.resolve(authority);
  await expect(pending).rejects.toThrow('Retired fixture'); expect(sent).toBe(0);
  const retry = new Q3ClientAuthorization({ cvars: registry, keys, demoRestricted: () => false,
    async resolve() { attempts++; return attempts === 1 ? null : authority; }, print() {} });
  await retry.request(() => undefined, () => { sent++; }); expect(sent).toBe(0);
  await retry.request(() => undefined, () => { sent++; }); expect(sent).toBe(1); expect(attempts).toBe(2);
});

test('Q3 admission authorizes before WAN challenge, retains resend interval and exempts LAN', async () => {
  const { Q3ClientNetwork } = await import('../../../src/app/bootstrap/network/q3-client.ts');
  const { PacketQueue } = await import('../../../src/network/common/transport.ts');
  const registry = cvars(), keys = new Q3CdKeyState(registry);
  keys.writeUi(0, '', new TextEncoder().encode(fixtureBase));
  const packets: { readonly to: import('../../../src/network/common/endpoint.ts').IpAddress; readonly bytes: Uint8Array }[] = [];
  let lookups = 0;
  const authorization = new Q3ClientAuthorization({ cvars: registry, keys, demoRestricted: () => false,
    async resolve() { lookups++; return authority; }, print() {} });
  const host: import('../../../src/app/bootstrap/network/q3-client.ts').Q3ApplicationClientHost = {
    identity: { client: createIdentityOwner('q3-auth-admission').client(0, 0), seat: null }, downloading: false, userinfo: () => '',
    attach() {}, command() { throw new Error('No fixture gameplay'); }, disconnected() {}, print() {}, clearActive() {},
    async systemInfo() {}, async gamestate() {}, snapshot() {}, downloadSize: size => size, async download() {}, mapRestart() {},
  };
  function connection(remote: Ipv4Address) {
    const queue = new PacketQueue<import('../../../src/network/common/endpoint.ts').IpAddress>({ maxBytes: 16383, queuePackets: 8 }, () => 0);
    let closed = false;
    return new Q3ClientNetwork({ remote, host, qport: 77, authorization, transport: {
      address: { kind: 'ipv4', host: [127, 0, 0, 1], port: 30000 }, get closed() { return closed; },
      send(to, bytes) { packets.push({ to, bytes }); return true; }, poll: () => queue.poll(),
      subscribeReadable: listener => queue.subscribe(listener), close() { closed = true; queue.close(); },
    } });
  }
  const wan = connection({ kind: 'ipv4', host: [198, 51, 100, 1], port: 27960 });
  try {
    await wan.poll(0);
    expect(packets.map(packet => decodeConnectionless(packet.bytes, 'server').command)).toEqual(['getKeyAuthorize', 'getchallenge']);
    expect(packets[0]?.to).toEqual(authority);
    await wan.poll(2999); expect(packets).toHaveLength(2);
    await wan.poll(3000); expect(packets).toHaveLength(4); expect(lookups).toBe(1);
  } finally { wan.close(); }
  packets.length = 0;
  const lan = connection({ kind: 'ipv4', host: [192, 168, 1, 2], port: 27960 });
  try { await lan.poll(0); expect(packets.map(packet => decodeConnectionless(packet.bytes, 'server').command)).toEqual(['getchallenge']); }
  finally { lan.close(); }
});
