// Generated from rerelease/m_arachnid.cpp and m_arachnid.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const arachnidFrame = {
  rails1: 0,
  rails2: 1,
  rails3: 2,
  rails4: 3,
  rails5: 4,
  rails6: 5,
  rails7: 6,
  rails8: 7,
  rails9: 8,
  rails10: 9,
  rails11: 10,
  death1: 11,
  death2: 12,
  death3: 13,
  death4: 14,
  death5: 15,
  death6: 16,
  death7: 17,
  death8: 18,
  death9: 19,
  death10: 20,
  death11: 21,
  death12: 22,
  death13: 23,
  death14: 24,
  death15: 25,
  death16: 26,
  death17: 27,
  death18: 28,
  death19: 29,
  death20: 30,
  melee_atk1: 31,
  melee_atk2: 32,
  melee_atk3: 33,
  melee_atk4: 34,
  melee_atk5: 35,
  melee_atk6: 36,
  melee_atk7: 37,
  melee_atk8: 38,
  melee_atk9: 39,
  melee_atk10: 40,
  melee_atk11: 41,
  melee_atk12: 42,
  pain11: 43,
  pain12: 44,
  pain13: 45,
  pain14: 46,
  pain15: 47,
  idle1: 48,
  idle2: 49,
  idle3: 50,
  idle4: 51,
  idle5: 52,
  idle6: 53,
  idle7: 54,
  idle8: 55,
  idle9: 56,
  idle10: 57,
  idle11: 58,
  idle12: 59,
  idle13: 60,
  walk1: 61,
  walk2: 62,
  walk3: 63,
  walk4: 64,
  walk5: 65,
  walk6: 66,
  walk7: 67,
  walk8: 68,
  walk9: 69,
  walk10: 70,
  turn1: 71,
  turn2: 72,
  turn3: 73,
  melee_out1: 74,
  melee_out2: 75,
  melee_out3: 76,
  pain21: 77,
  pain22: 78,
  pain23: 79,
  pain24: 80,
  pain25: 81,
  pain26: 82,
  melee_pain1: 83,
  melee_pain2: 84,
  melee_pain3: 85,
  melee_pain4: 86,
  melee_pain5: 87,
  melee_pain6: 88,
  melee_pain7: 89,
  melee_pain8: 90,
  melee_pain9: 91,
  melee_pain10: 92,
  melee_pain11: 93,
  melee_pain12: 94,
  melee_pain13: 95,
  melee_pain14: 96,
  melee_pain15: 97,
  melee_pain16: 98,
  melee_in1: 99,
  melee_in2: 100,
  melee_in3: 101,
  melee_in4: 102,
  melee_in5: 103,
  melee_in6: 104,
  melee_in7: 105,
  melee_in8: 106,
  melee_in9: 107,
  melee_in10: 108,
  melee_in11: 109,
  melee_in12: 110,
  melee_in13: 111,
  melee_in14: 112,
  melee_in15: 113,
  melee_in16: 114,
  rails_up1: 115,
  rails_up2: 116,
  rails_up3: 117,
  rails_up4: 118,
  rails_up5: 119,
  rails_up6: 120,
  rails_up7: 121,
  rails_up8: 122,
  rails_up9: 123,
  rails_up10: 124,
  rails_up11: 125,
  rails_up12: 126,
  rails_up13: 127,
  rails_up14: 128,
  rails_up15: 129,
  rails_up16: 130,
};

export const arachnidMoves: readonly MonsterMove[] = [
  { name: "arachnid_move_stand", firstFrame: 48, lastFrame: 60, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_move_walk", firstFrame: 61, lastFrame: 70, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(8), actions: ["arachnid_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: ["arachnid_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_move_run", firstFrame: 61, lastFrame: 70, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(8), actions: ["arachnid_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: ["arachnid_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_move_pain1", firstFrame: 43, lastFrame: 47, end: "arachnid_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_move_pain2", firstFrame: 77, lastFrame: 82, end: "arachnid_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_attack1", firstFrame: 0, lastFrame: 10, end: "arachnid_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_charge_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_charge_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_attack_up1", firstFrame: 115, lastFrame: 130, end: "arachnid_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_charge_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_charge_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_rail"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_melee", firstFrame: 31, lastFrame: 42, end: "arachnid_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_melee_charge"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_melee_hit"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_melee_charge"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["arachnid_melee_hit"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "arachnid_move_death", firstFrame: 11, lastFrame: 30, end: "arachnid_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1.23), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1.23), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1.23), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1.23), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1.64), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1.64), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2.45), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8.63), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-4), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-4.5), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-6.8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-5.4), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-3.4), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1.9), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
