// Generated from rerelease/m_boss31.cpp and m_boss31.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const boss31Frame = {
  attak101: 0,
  attak102: 1,
  attak103: 2,
  attak104: 3,
  attak105: 4,
  attak106: 5,
  attak107: 6,
  attak108: 7,
  attak109: 8,
  attak110: 9,
  attak111: 10,
  attak112: 11,
  attak113: 12,
  attak114: 13,
  attak115: 14,
  attak116: 15,
  attak117: 16,
  attak118: 17,
  attak201: 18,
  attak202: 19,
  attak203: 20,
  attak204: 21,
  attak205: 22,
  attak206: 23,
  attak207: 24,
  attak208: 25,
  attak209: 26,
  attak210: 27,
  attak211: 28,
  attak212: 29,
  attak213: 30,
  death01: 31,
  death02: 32,
  death03: 33,
  death04: 34,
  death05: 35,
  death06: 36,
  death07: 37,
  death08: 38,
  death09: 39,
  death10: 40,
  death11: 41,
  death12: 42,
  death13: 43,
  death14: 44,
  death15: 45,
  death16: 46,
  death17: 47,
  death18: 48,
  death19: 49,
  death20: 50,
  death21: 51,
  death22: 52,
  death23: 53,
  death24: 54,
  death25: 55,
  death26: 56,
  death27: 57,
  death28: 58,
  death29: 59,
  death30: 60,
  death31: 61,
  death32: 62,
  death33: 63,
  death34: 64,
  death35: 65,
  death36: 66,
  death37: 67,
  death38: 68,
  death39: 69,
  death40: 70,
  death41: 71,
  death42: 72,
  death43: 73,
  death44: 74,
  death45: 75,
  death46: 76,
  death47: 77,
  death48: 78,
  death49: 79,
  death50: 80,
  pain101: 81,
  pain102: 82,
  pain103: 83,
  pain201: 84,
  pain202: 85,
  pain203: 86,
  pain301: 87,
  pain302: 88,
  pain303: 89,
  pain304: 90,
  pain305: 91,
  pain306: 92,
  pain307: 93,
  pain308: 94,
  pain309: 95,
  pain310: 96,
  pain311: 97,
  pain312: 98,
  pain313: 99,
  pain314: 100,
  pain315: 101,
  pain316: 102,
  pain317: 103,
  pain318: 104,
  pain319: 105,
  pain320: 106,
  pain321: 107,
  pain322: 108,
  pain323: 109,
  pain324: 110,
  pain325: 111,
  stand01: 112,
  stand02: 113,
  stand03: 114,
  stand04: 115,
  stand05: 116,
  stand06: 117,
  stand07: 118,
  stand08: 119,
  stand09: 120,
  stand10: 121,
  stand11: 122,
  stand12: 123,
  stand13: 124,
  stand14: 125,
  stand15: 126,
  stand16: 127,
  stand17: 128,
  stand18: 129,
  stand19: 130,
  stand20: 131,
  stand21: 132,
  stand22: 133,
  stand23: 134,
  stand24: 135,
  stand25: 136,
  stand26: 137,
  stand27: 138,
  stand28: 139,
  stand29: 140,
  stand30: 141,
  stand31: 142,
  stand32: 143,
  stand33: 144,
  stand34: 145,
  stand35: 146,
  stand36: 147,
  stand37: 148,
  stand38: 149,
  stand39: 150,
  stand40: 151,
  stand41: 152,
  stand42: 153,
  stand43: 154,
  stand44: 155,
  stand45: 156,
  stand46: 157,
  stand47: 158,
  stand48: 159,
  stand49: 160,
  stand50: 161,
  stand51: 162,
  walk01: 163,
  walk02: 164,
  walk03: 165,
  walk04: 166,
  walk05: 167,
  walk06: 168,
  walk07: 169,
  walk08: 170,
  walk09: 171,
  walk10: 172,
  walk11: 173,
  walk12: 174,
  walk13: 175,
  walk14: 176,
  walk15: 177,
  walk16: 178,
  walk17: 179,
  walk18: 180,
  walk19: 181,
  walk20: 182,
  walk21: 183,
  walk22: 184,
  walk23: 185,
  walk24: 186,
  walk25: 187,
};

export const boss31Moves: readonly MonsterMove[] = [
  { name: "jorg_move_stand", firstFrame: 112, lastFrame: 162, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: ["jorg_idle"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(19), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(11), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(9), actions: ["jorg_step_right"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(-17), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(-12), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(-14), actions: ["jorg_step_right"], lerpFrame: -1 },
  ] },
  { name: "jorg_move_run", firstFrame: 168, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(17), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(12), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(33), actions: ["jorg_step_right"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(9), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_start_walk", firstFrame: 163, lastFrame: 167, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(15), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_walk", firstFrame: 168, lastFrame: 181, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(17), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(12), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(33), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(9), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_end_walk", firstFrame: 182, lastFrame: 187, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(11), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_pain3", firstFrame: 87, lastFrame: 111, end: "jorg_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(-28), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-6), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-3), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-9), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["jorg_step_right"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-7), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-11), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-4), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(11), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(7), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(17), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["jorg_step_right"], lerpFrame: -1 },
  ] },
  { name: "jorg_move_pain2", firstFrame: 84, lastFrame: 86, end: "jorg_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_pain1", firstFrame: 81, lastFrame: 83, end: "jorg_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_death", firstFrame: 31, lastFrame: 80, end: "jorg_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: ["BossExplode"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-5), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-15), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-11), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-25), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-10), actions: ["jorg_step_right"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-21), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-10), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-16), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(22), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(33), actions: ["jorg_step_left"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(28), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(28), actions: ["jorg_step_right"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-19), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["jorg_death_hit"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_attack2", firstFrame: 18, lastFrame: 30, end: "jorg_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["jorgBFG"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_start_attack1", firstFrame: 0, lastFrame: 7, end: "jorg_attack1", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "jorg_move_attack1", firstFrame: 8, lastFrame: 13, end: "jorg_reattack1", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["jorg_firebullet"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["jorg_firebullet"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["jorg_firebullet"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["jorg_firebullet"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["jorg_firebullet"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["jorg_firebullet"], lerpFrame: -1 },
  ] },
  { name: "jorg_move_end_attack1", firstFrame: 14, lastFrame: 17, end: "jorg_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
