// Generated from rerelease/m_flipper.cpp and m_flipper.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const flipperFrame = {
  flpbit01: 0,
  flpbit02: 1,
  flpbit03: 2,
  flpbit04: 3,
  flpbit05: 4,
  flpbit06: 5,
  flpbit07: 6,
  flpbit08: 7,
  flpbit09: 8,
  flpbit10: 9,
  flpbit11: 10,
  flpbit12: 11,
  flpbit13: 12,
  flpbit14: 13,
  flpbit15: 14,
  flpbit16: 15,
  flpbit17: 16,
  flpbit18: 17,
  flpbit19: 18,
  flpbit20: 19,
  flptal01: 20,
  flptal02: 21,
  flptal03: 22,
  flptal04: 23,
  flptal05: 24,
  flptal06: 25,
  flptal07: 26,
  flptal08: 27,
  flptal09: 28,
  flptal10: 29,
  flptal11: 30,
  flptal12: 31,
  flptal13: 32,
  flptal14: 33,
  flptal15: 34,
  flptal16: 35,
  flptal17: 36,
  flptal18: 37,
  flptal19: 38,
  flptal20: 39,
  flptal21: 40,
  flphor01: 41,
  flphor02: 42,
  flphor03: 43,
  flphor04: 44,
  flphor05: 45,
  flphor06: 46,
  flphor07: 47,
  flphor08: 48,
  flphor09: 49,
  flphor10: 50,
  flphor11: 51,
  flphor12: 52,
  flphor13: 53,
  flphor14: 54,
  flphor15: 55,
  flphor16: 56,
  flphor17: 57,
  flphor18: 58,
  flphor19: 59,
  flphor20: 60,
  flphor21: 61,
  flphor22: 62,
  flphor23: 63,
  flphor24: 64,
  flpver01: 65,
  flpver02: 66,
  flpver03: 67,
  flpver04: 68,
  flpver05: 69,
  flpver06: 70,
  flpver07: 71,
  flpver08: 72,
  flpver09: 73,
  flpver10: 74,
  flpver11: 75,
  flpver12: 76,
  flpver13: 77,
  flpver14: 78,
  flpver15: 79,
  flpver16: 80,
  flpver17: 81,
  flpver18: 82,
  flpver19: 83,
  flpver20: 84,
  flpver21: 85,
  flpver22: 86,
  flpver23: 87,
  flpver24: 88,
  flpver25: 89,
  flpver26: 90,
  flpver27: 91,
  flpver28: 92,
  flpver29: 93,
  flppn101: 94,
  flppn102: 95,
  flppn103: 96,
  flppn104: 97,
  flppn105: 98,
  flppn201: 99,
  flppn202: 100,
  flppn203: 101,
  flppn204: 102,
  flppn205: 103,
  flpdth01: 104,
  flpdth02: 105,
  flpdth03: 106,
  flpdth04: 107,
  flpdth05: 108,
  flpdth06: 109,
  flpdth07: 110,
  flpdth08: 111,
  flpdth09: 112,
  flpdth10: 113,
  flpdth11: 114,
  flpdth12: 115,
  flpdth13: 116,
  flpdth14: 117,
  flpdth15: 118,
  flpdth16: 119,
  flpdth17: 120,
  flpdth18: 121,
  flpdth19: 122,
  flpdth20: 123,
  flpdth21: 124,
  flpdth22: 125,
  flpdth23: 126,
  flpdth24: 127,
  flpdth25: 128,
  flpdth26: 129,
  flpdth27: 130,
  flpdth28: 131,
  flpdth29: 132,
  flpdth30: 133,
  flpdth31: 134,
  flpdth32: 135,
  flpdth33: 136,
  flpdth34: 137,
  flpdth35: 138,
  flpdth36: 139,
  flpdth37: 140,
  flpdth38: 141,
  flpdth39: 142,
  flpdth40: 143,
  flpdth41: 144,
  flpdth42: 145,
  flpdth43: 146,
  flpdth44: 147,
  flpdth45: 148,
  flpdth46: 149,
  flpdth47: 150,
  flpdth48: 151,
  flpdth49: 152,
  flpdth50: 153,
  flpdth51: 154,
  flpdth52: 155,
  flpdth53: 156,
  flpdth54: 157,
  flpdth55: 158,
  flpdth56: 159,
};

export const flipperMoves: readonly MonsterMove[] = [
  { name: "flipper_move_stand", firstFrame: 41, lastFrame: 41, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flipper_move_run_loop", firstFrame: 70, lastFrame: 93, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
  ] },
  { name: "flipper_move_run_start", firstFrame: 65, lastFrame: 70, end: "flipper_run_loop", sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
  ] },
  { name: "flipper_move_walk", firstFrame: 41, lastFrame: 64, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
  ] },
  { name: "flipper_move_start_run", firstFrame: 41, lastFrame: 45, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: ["flipper_run"], lerpFrame: -1 },
  ] },
  { name: "flipper_move_pain2", firstFrame: 94, lastFrame: 98, end: "flipper_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flipper_move_pain1", firstFrame: 99, lastFrame: 103, end: "flipper_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flipper_move_attack", firstFrame: 0, lastFrame: 19, end: "flipper_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["flipper_preattack"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["flipper_bite"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["flipper_bite"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flipper_move_death", firstFrame: 104, lastFrame: 159, end: "flipper_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
