// Generated from rerelease/m_flyer.cpp and m_flyer.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const flyerFrame = {
  start01: 0,
  start02: 1,
  start03: 2,
  start04: 3,
  start05: 4,
  start06: 5,
  stop01: 6,
  stop02: 7,
  stop03: 8,
  stop04: 9,
  stop05: 10,
  stop06: 11,
  stop07: 12,
  stand01: 13,
  stand02: 14,
  stand03: 15,
  stand04: 16,
  stand05: 17,
  stand06: 18,
  stand07: 19,
  stand08: 20,
  stand09: 21,
  stand10: 22,
  stand11: 23,
  stand12: 24,
  stand13: 25,
  stand14: 26,
  stand15: 27,
  stand16: 28,
  stand17: 29,
  stand18: 30,
  stand19: 31,
  stand20: 32,
  stand21: 33,
  stand22: 34,
  stand23: 35,
  stand24: 36,
  stand25: 37,
  stand26: 38,
  stand27: 39,
  stand28: 40,
  stand29: 41,
  stand30: 42,
  stand31: 43,
  stand32: 44,
  stand33: 45,
  stand34: 46,
  stand35: 47,
  stand36: 48,
  stand37: 49,
  stand38: 50,
  stand39: 51,
  stand40: 52,
  stand41: 53,
  stand42: 54,
  stand43: 55,
  stand44: 56,
  stand45: 57,
  attak101: 58,
  attak102: 59,
  attak103: 60,
  attak104: 61,
  attak105: 62,
  attak106: 63,
  attak107: 64,
  attak108: 65,
  attak109: 66,
  attak110: 67,
  attak111: 68,
  attak112: 69,
  attak113: 70,
  attak114: 71,
  attak115: 72,
  attak116: 73,
  attak117: 74,
  attak118: 75,
  attak119: 76,
  attak120: 77,
  attak121: 78,
  attak201: 79,
  attak202: 80,
  attak203: 81,
  attak204: 82,
  attak205: 83,
  attak206: 84,
  attak207: 85,
  attak208: 86,
  attak209: 87,
  attak210: 88,
  attak211: 89,
  attak212: 90,
  attak213: 91,
  attak214: 92,
  attak215: 93,
  attak216: 94,
  attak217: 95,
  bankl01: 96,
  bankl02: 97,
  bankl03: 98,
  bankl04: 99,
  bankl05: 100,
  bankl06: 101,
  bankl07: 102,
  bankr01: 103,
  bankr02: 104,
  bankr03: 105,
  bankr04: 106,
  bankr05: 107,
  bankr06: 108,
  bankr07: 109,
  rollf01: 110,
  rollf02: 111,
  rollf03: 112,
  rollf04: 113,
  rollf05: 114,
  rollf06: 115,
  rollf07: 116,
  rollf08: 117,
  rollf09: 118,
  rollr01: 119,
  rollr02: 120,
  rollr03: 121,
  rollr04: 122,
  rollr05: 123,
  rollr06: 124,
  rollr07: 125,
  rollr08: 126,
  rollr09: 127,
  defens01: 128,
  defens02: 129,
  defens03: 130,
  defens04: 131,
  defens05: 132,
  defens06: 133,
  pain101: 134,
  pain102: 135,
  pain103: 136,
  pain104: 137,
  pain105: 138,
  pain106: 139,
  pain107: 140,
  pain108: 141,
  pain109: 142,
  pain201: 143,
  pain202: 144,
  pain203: 145,
  pain204: 146,
  pain301: 147,
  pain302: 148,
  pain303: 149,
  pain304: 150,
};

export const flyerMoves: readonly MonsterMove[] = [
  { name: "flyer_move_stand", firstFrame: 13, lastFrame: 57, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_walk", firstFrame: 13, lastFrame: 57, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_run", firstFrame: 13, lastFrame: 57, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_kamikaze", firstFrame: 120, lastFrame: 124, end: "flyer_kamikaze", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(40), actions: ["flyer_kamikaze_check"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(40), actions: ["flyer_kamikaze_check"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(40), actions: ["flyer_kamikaze_check"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(40), actions: ["flyer_kamikaze_check"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(40), actions: ["flyer_kamikaze_check"], lerpFrame: -1 },
  ] },
  { name: "flyer_move_rollright", firstFrame: 119, lastFrame: 127, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_rollleft", firstFrame: 110, lastFrame: 118, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_pain3", firstFrame: 147, lastFrame: 150, end: "flyer_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_pain2", firstFrame: 143, lastFrame: 146, end: "flyer_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_pain1", firstFrame: 134, lastFrame: 142, end: "flyer_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_defense", firstFrame: 128, lastFrame: 133, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_bankright", firstFrame: 103, lastFrame: 109, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_bankleft", firstFrame: 96, lastFrame: 102, end: null, sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_attack2", firstFrame: 79, lastFrame: 95, end: "flyer_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_attack3", firstFrame: 79, lastFrame: 95, end: "flyer_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireleft"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: ["flyer_fireright"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(10), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_start_melee", firstFrame: 58, lastFrame: 63, end: "flyer_loop_melee", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["flyer_pop_blades"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_end_melee", firstFrame: 76, lastFrame: 78, end: "flyer_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "flyer_move_loop_melee", firstFrame: 64, lastFrame: 75, end: "flyer_check_melee", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["flyer_slash_left"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["flyer_slash_right"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
