// Generated from rerelease/m_guardian.cpp and m_guardian.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const guardianFrame = {
  sleep1: 0,
  sleep2: 1,
  sleep3: 2,
  sleep4: 3,
  sleep5: 4,
  sleep6: 5,
  sleep7: 6,
  sleep8: 7,
  sleep9: 8,
  sleep10: 9,
  sleep11: 10,
  sleep12: 11,
  sleep13: 12,
  sleep14: 13,
  death1: 14,
  death2: 15,
  death3: 16,
  death4: 17,
  death5: 18,
  death6: 19,
  death7: 20,
  death8: 21,
  death9: 22,
  death10: 23,
  death11: 24,
  death12: 25,
  death13: 26,
  death14: 27,
  death15: 28,
  death16: 29,
  death17: 30,
  death18: 31,
  death19: 32,
  death20: 33,
  death21: 34,
  death22: 35,
  death23: 36,
  death24: 37,
  death25: 38,
  death26: 39,
  atk1_out1: 40,
  atk1_out2: 41,
  atk1_out3: 42,
  atk2_out1: 43,
  atk2_out2: 44,
  atk2_out3: 45,
  atk2_out4: 46,
  atk2_out5: 47,
  atk2_out6: 48,
  atk2_out7: 49,
  kick_out1: 50,
  kick_out2: 51,
  kick_out3: 52,
  kick_out4: 53,
  kick_out5: 54,
  kick_out6: 55,
  kick_out7: 56,
  kick_out8: 57,
  kick_out9: 58,
  kick_out10: 59,
  kick_out11: 60,
  kick_out12: 61,
  pain1_1: 62,
  pain1_2: 63,
  pain1_3: 64,
  pain1_4: 65,
  pain1_5: 66,
  pain1_6: 67,
  pain1_7: 68,
  pain1_8: 69,
  idle1: 70,
  idle2: 71,
  idle3: 72,
  idle4: 73,
  idle5: 74,
  idle6: 75,
  idle7: 76,
  idle8: 77,
  idle9: 78,
  idle10: 79,
  idle11: 80,
  idle12: 81,
  idle13: 82,
  idle14: 83,
  idle15: 84,
  idle16: 85,
  idle17: 86,
  idle18: 87,
  idle19: 88,
  idle20: 89,
  idle21: 90,
  idle22: 91,
  idle23: 92,
  idle24: 93,
  idle25: 94,
  idle26: 95,
  idle27: 96,
  idle28: 97,
  idle29: 98,
  idle30: 99,
  idle31: 100,
  idle32: 101,
  idle33: 102,
  idle34: 103,
  idle35: 104,
  idle36: 105,
  idle37: 106,
  idle38: 107,
  idle39: 108,
  idle40: 109,
  idle41: 110,
  idle42: 111,
  idle43: 112,
  idle44: 113,
  idle45: 114,
  idle46: 115,
  idle47: 116,
  idle48: 117,
  idle49: 118,
  idle50: 119,
  idle51: 120,
  idle52: 121,
  atk1_in1: 122,
  atk1_in2: 123,
  atk1_in3: 124,
  kick_in1: 125,
  kick_in2: 126,
  kick_in3: 127,
  kick_in4: 128,
  kick_in5: 129,
  kick_in6: 130,
  kick_in7: 131,
  kick_in8: 132,
  kick_in9: 133,
  kick_in10: 134,
  kick_in11: 135,
  kick_in12: 136,
  kick_in13: 137,
  walk1: 138,
  walk2: 139,
  walk3: 140,
  walk4: 141,
  walk5: 142,
  walk6: 143,
  walk7: 144,
  walk8: 145,
  walk9: 146,
  walk10: 147,
  walk11: 148,
  walk12: 149,
  walk13: 150,
  walk14: 151,
  walk15: 152,
  walk16: 153,
  walk17: 154,
  walk18: 155,
  walk19: 156,
  wake1: 157,
  wake2: 158,
  wake3: 159,
  wake4: 160,
  wake5: 161,
  atk1_spin1: 162,
  atk1_spin2: 163,
  atk1_spin3: 164,
  atk1_spin4: 165,
  atk1_spin5: 166,
  atk1_spin6: 167,
  atk1_spin7: 168,
  atk1_spin8: 169,
  atk1_spin9: 170,
  atk1_spin10: 171,
  atk1_spin11: 172,
  atk1_spin12: 173,
  atk1_spin13: 174,
  atk1_spin14: 175,
  atk1_spin15: 176,
  atk2_fire1: 177,
  atk2_fire2: 178,
  atk2_fire3: 179,
  atk2_fire4: 180,
  turnl_1: 181,
  turnl_2: 182,
  turnl_3: 183,
  turnl_4: 184,
  turnl_5: 185,
  turnl_6: 186,
  turnl_7: 187,
  turnl_8: 188,
  turnl_9: 189,
  turnl_10: 190,
  turnl_11: 191,
  turnr_1: 192,
  turnr_2: 193,
  turnr_3: 194,
  turnr_4: 195,
  turnr_5: 196,
  turnr_6: 197,
  turnr_7: 198,
  turnr_8: 199,
  turnr_9: 200,
  turnr_10: 201,
  turnr_11: 202,
  atk2_in1: 203,
  atk2_in2: 204,
  atk2_in3: 205,
  atk2_in4: 206,
  atk2_in5: 207,
  atk2_in6: 208,
  atk2_in7: 209,
  atk2_in8: 210,
  atk2_in9: 211,
  atk2_in10: 212,
  atk2_in11: 213,
  atk2_in12: 214,
};

export const guardianMoves: readonly MonsterMove[] = [
  { name: "guardian_move_stand", firstFrame: 70, lastFrame: 121, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_walk", firstFrame: 138, lastFrame: 156, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_run", firstFrame: 138, lastFrame: 156, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(8), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_pain1", firstFrame: 62, lastFrame: 69, end: "guardian_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_atk1_out", firstFrame: 40, lastFrame: 42, end: "guardian_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_atk1_spin", firstFrame: 162, lastFrame: 176, end: "guardian_atk1_finish", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_atk1_charge"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_fire_blaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_atk1_in", firstFrame: 122, lastFrame: 124, end: "guardian_atk1", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_atk2_out", firstFrame: 43, lastFrame: 49, end: "guardian_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_atk2_fire", firstFrame: 177, lastFrame: 180, end: "guardian_atk2_out", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_laser_fire"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_laser_fire"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_laser_fire"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_laser_fire"], lerpFrame: -1 },
  ] },
  { name: "guardian_move_atk2_in", firstFrame: 203, lastFrame: 214, end: "guardian_atk2", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_kick", firstFrame: 125, lastFrame: 137, end: "guardian_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_kick"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["guardian_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "guardian_move_death", firstFrame: 14, lastFrame: 39, end: "guardian_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: ["BossExplode"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
