// Generated from rerelease/m_mutant.cpp and m_mutant.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const mutantFrame = {
  attack01: 0,
  attack02: 1,
  attack03: 2,
  attack04: 3,
  attack05: 4,
  attack06: 5,
  attack07: 6,
  attack08: 7,
  attack09: 8,
  attack10: 9,
  attack11: 10,
  attack12: 11,
  attack13: 12,
  attack14: 13,
  attack15: 14,
  death101: 15,
  death102: 16,
  death103: 17,
  death104: 18,
  death105: 19,
  death106: 20,
  death107: 21,
  death108: 22,
  death109: 23,
  death201: 24,
  death202: 25,
  death203: 26,
  death204: 27,
  death205: 28,
  death206: 29,
  death207: 30,
  death208: 31,
  death209: 32,
  death210: 33,
  pain101: 34,
  pain102: 35,
  pain103: 36,
  pain104: 37,
  pain105: 38,
  pain201: 39,
  pain202: 40,
  pain203: 41,
  pain204: 42,
  pain205: 43,
  pain206: 44,
  pain301: 45,
  pain302: 46,
  pain303: 47,
  pain304: 48,
  pain305: 49,
  pain306: 50,
  pain307: 51,
  pain308: 52,
  pain309: 53,
  pain310: 54,
  pain311: 55,
  run03: 56,
  run04: 57,
  run05: 58,
  run06: 59,
  run07: 60,
  run08: 61,
  stand101: 62,
  stand102: 63,
  stand103: 64,
  stand104: 65,
  stand105: 66,
  stand106: 67,
  stand107: 68,
  stand108: 69,
  stand109: 70,
  stand110: 71,
  stand111: 72,
  stand112: 73,
  stand113: 74,
  stand114: 75,
  stand115: 76,
  stand116: 77,
  stand117: 78,
  stand118: 79,
  stand119: 80,
  stand120: 81,
  stand121: 82,
  stand122: 83,
  stand123: 84,
  stand124: 85,
  stand125: 86,
  stand126: 87,
  stand127: 88,
  stand128: 89,
  stand129: 90,
  stand130: 91,
  stand131: 92,
  stand132: 93,
  stand133: 94,
  stand134: 95,
  stand135: 96,
  stand136: 97,
  stand137: 98,
  stand138: 99,
  stand139: 100,
  stand140: 101,
  stand141: 102,
  stand142: 103,
  stand143: 104,
  stand144: 105,
  stand145: 106,
  stand146: 107,
  stand147: 108,
  stand148: 109,
  stand149: 110,
  stand150: 111,
  stand151: 112,
  stand152: 113,
  stand153: 114,
  stand154: 115,
  stand155: 116,
  stand156: 117,
  stand157: 118,
  stand158: 119,
  stand159: 120,
  stand160: 121,
  stand161: 122,
  stand162: 123,
  stand163: 124,
  stand164: 125,
  walk01: 126,
  walk02: 127,
  walk03: 128,
  walk04: 129,
  walk05: 130,
  walk06: 131,
  walk07: 132,
  walk08: 133,
  walk09: 134,
  walk10: 135,
  walk11: 136,
  walk12: 137,
  walk13: 138,
  walk14: 139,
  walk15: 140,
  walk16: 141,
  walk17: 142,
  walk18: 143,
  walk19: 144,
  walk20: 145,
  walk21: 146,
  walk22: 147,
  walk23: 148,
  jump01: 149,
  jump02: 150,
  jump03: 151,
  jump04: 152,
  jump05: 153,
};

export const mutantMoves: readonly MonsterMove[] = [
  { name: "mutant_move_stand", firstFrame: 62, lastFrame: 112, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_idle", firstFrame: 113, lastFrame: 125, end: "mutant_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["mutant_idle_loop"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_walk", firstFrame: 130, lastFrame: 141, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(13), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(16), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(15), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_start_walk", firstFrame: 126, lastFrame: 129, end: "mutant_walk_loop", sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(1), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_run", firstFrame: 56, lastFrame: 61, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(40), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(40), actions: ["mutant_step"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(5), actions: ["mutant_step"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(17), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_attack", firstFrame: 8, lastFrame: 14, end: "mutant_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["mutant_hit_left"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["mutant_hit_right"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["mutant_check_refire"], lerpFrame: -1 },
  ] },
  { name: "mutant_move_jump", firstFrame: 0, lastFrame: 7, end: "mutant_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(17), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(15), actions: ["mutant_jump_takeoff"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(15), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(15), actions: ["mutant_check_landing"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_pain1", firstFrame: 34, lastFrame: 38, end: "mutant_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(5), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_pain2", firstFrame: 39, lastFrame: 44, end: "mutant_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(-24), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(11), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(4), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_pain3", firstFrame: 45, lastFrame: 55, end: "mutant_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(-22), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_death1", firstFrame: 15, lastFrame: 23, end: "monster_dead", sidestepScale: 0, frames: [
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(7), actions: ["mutant_shrink"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_right"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_death2", firstFrame: 24, lastFrame: 33, end: "monster_dead", sidestepScale: 0, frames: [
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(3), actions: ["mutant_shrink"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"ai_move_slide_left"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_jump_up", firstFrame: 149, lastFrame: 153, end: "mutant_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8), actions: ["mutant_jump_up"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["mutant_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "mutant_move_jump_down", firstFrame: 149, lastFrame: 153, end: "mutant_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["mutant_jump_down"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["mutant_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
