// Generated from rerelease/m_parasite.cpp and m_parasite.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const parasiteFrame = {
  break01: 0,
  break02: 1,
  break03: 2,
  break04: 3,
  break05: 4,
  break06: 5,
  break07: 6,
  break08: 7,
  break09: 8,
  break10: 9,
  break11: 10,
  break12: 11,
  break13: 12,
  break14: 13,
  break15: 14,
  break16: 15,
  break17: 16,
  break18: 17,
  break19: 18,
  break20: 19,
  break21: 20,
  break22: 21,
  break23: 22,
  break24: 23,
  break25: 24,
  break26: 25,
  break27: 26,
  break28: 27,
  break29: 28,
  break30: 29,
  break31: 30,
  break32: 31,
  death101: 32,
  death102: 33,
  death103: 34,
  death104: 35,
  death105: 36,
  death106: 37,
  death107: 38,
  drain01: 39,
  drain02: 40,
  drain03: 41,
  drain04: 42,
  drain05: 43,
  drain06: 44,
  drain07: 45,
  drain08: 46,
  drain09: 47,
  drain10: 48,
  drain11: 49,
  drain12: 50,
  drain13: 51,
  drain14: 52,
  drain15: 53,
  drain16: 54,
  drain17: 55,
  drain18: 56,
  pain101: 57,
  pain102: 58,
  pain103: 59,
  pain104: 60,
  pain105: 61,
  pain106: 62,
  pain107: 63,
  pain108: 64,
  pain109: 65,
  pain110: 66,
  pain111: 67,
  run01: 68,
  run02: 69,
  run03: 70,
  run04: 71,
  run05: 72,
  run06: 73,
  run07: 74,
  run08: 75,
  run09: 76,
  run10: 77,
  run11: 78,
  run12: 79,
  run13: 80,
  run14: 81,
  run15: 82,
  stand01: 83,
  stand02: 84,
  stand03: 85,
  stand04: 86,
  stand05: 87,
  stand06: 88,
  stand07: 89,
  stand08: 90,
  stand09: 91,
  stand10: 92,
  stand11: 93,
  stand12: 94,
  stand13: 95,
  stand14: 96,
  stand15: 97,
  stand16: 98,
  stand17: 99,
  stand18: 100,
  stand19: 101,
  stand20: 102,
  stand21: 103,
  stand22: 104,
  stand23: 105,
  stand24: 106,
  stand25: 107,
  stand26: 108,
  stand27: 109,
  stand28: 110,
  stand29: 111,
  stand30: 112,
  stand31: 113,
  stand32: 114,
  stand33: 115,
  stand34: 116,
  stand35: 117,
  jump01: 118,
  jump02: 119,
  jump03: 120,
  jump04: 121,
  jump05: 122,
  jump06: 123,
  jump07: 124,
  jump08: 125,
};

export const parasiteMoves: readonly MonsterMove[] = [
  { name: "parasite_move_start_fidget", firstFrame: 100, lastFrame: 103, end: "parasite_do_fidget", sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_fidget", firstFrame: 104, lastFrame: 109, end: "parasite_refidget", sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_scratch"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_scratch"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_end_fidget", firstFrame: 110, lastFrame: 117, end: "parasite_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_scratch"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_stand", firstFrame: 83, lastFrame: 99, end: "parasite_stand", sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_tap"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_tap"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_tap"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_tap"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_tap"], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: ["parasite_tap"], lerpFrame: -1 },
  ] },
  { name: "parasite_move_run", firstFrame: 70, lastFrame: 76, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(30), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(30), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(22), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(19), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(28), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(25), actions: ["monster_footstep"], lerpFrame: -1 },
  ] },
  { name: "parasite_move_start_run", firstFrame: 68, lastFrame: 69, end: "parasite_run", sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(30), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_stop_run", firstFrame: 77, lastFrame: 82, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(20), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(20), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(12), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_walk", firstFrame: 70, lastFrame: 76, end: "parasite_walk", sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(30), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(30), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(22), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(19), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(28), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(25), actions: ["monster_footstep"], lerpFrame: -1 },
  ] },
  { name: "parasite_move_start_walk", firstFrame: 68, lastFrame: 69, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(30), actions: ["parasite_walk"], lerpFrame: -1 },
  ] },
  { name: "parasite_move_stop_walk", firstFrame: 77, lastFrame: 82, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(20), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(20), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(12), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_break", firstFrame: 0, lastFrame: 31, end: "parasite_start_run", sidestepScale: 0, frames: [
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-3), actions: ["parasite_break_noise"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-3), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: ["parasite_break_noise"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-18), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-18), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(8), actions: ["parasite_break_retract"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: ["parasite_break_wait"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-18), actions: ["parasite_break_sound"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(11), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-5), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(1), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_fire_proboscis", firstFrame: 39, lastFrame: 56, end: "parasite_start_run", sidestepScale: 0, frames: [
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: ["parasite_launch"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(15), actions: ["parasite_fire_proboscis"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: ["parasite_proboscis_wait"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: ["parasite_proboscis_wait"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-3), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: ["parasite_proboscis_pull_wait"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-1), actions: ["parasite_proboscis_pull_wait"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: ["parasite_reel_in"], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(-3), actions: [], lerpFrame: -1 },
    { ai: {"kind":"source","name":"parasite_charge_proboscis"}, distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_jump_up", firstFrame: 118, lastFrame: 125, end: "parasite_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-8), actions: ["parasite_jump_up"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["parasite_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_jump_down", firstFrame: 118, lastFrame: 125, end: "parasite_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["parasite_jump_down"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["parasite_jump_wait_land"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_death", firstFrame: 32, lastFrame: 38, end: "parasite_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: 83 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["parasite_shrink"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "parasite_move_pain1", firstFrame: 57, lastFrame: 67, end: "parasite_start_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: 83 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [{"kind":"nextframe","frame":61}], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(6), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(16), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-6), actions: ["monster_footstep"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-7), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
