// Generated from rerelease/m_shambler.cpp and m_shambler.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const shamblerFrame = {
  stand01: 0,
  stand02: 1,
  stand03: 2,
  stand04: 3,
  stand05: 4,
  stand06: 5,
  stand07: 6,
  stand08: 7,
  stand09: 8,
  stand10: 9,
  stand11: 10,
  stand12: 11,
  stand13: 12,
  stand14: 13,
  stand15: 14,
  stand16: 15,
  stand17: 16,
  walk01: 17,
  walk02: 18,
  walk03: 19,
  walk04: 20,
  walk05: 21,
  walk06: 22,
  walk07: 23,
  walk08: 24,
  walk09: 25,
  walk10: 26,
  walk11: 27,
  walk12: 28,
  run01: 29,
  run02: 30,
  run03: 31,
  run04: 32,
  run05: 33,
  run06: 34,
  smash01: 35,
  smash02: 36,
  smash03: 37,
  smash04: 38,
  smash05: 39,
  smash06: 40,
  smash07: 41,
  smash08: 42,
  smash09: 43,
  smash10: 44,
  smash11: 45,
  smash12: 46,
  swingr01: 47,
  swingr02: 48,
  swingr03: 49,
  swingr04: 50,
  swingr05: 51,
  swingr06: 52,
  swingr07: 53,
  swingr08: 54,
  swingr09: 55,
  swingl01: 56,
  swingl02: 57,
  swingl03: 58,
  swingl04: 59,
  swingl05: 60,
  swingl06: 61,
  swingl07: 62,
  swingl08: 63,
  swingl09: 64,
  magic01: 65,
  magic02: 66,
  magic03: 67,
  magic04: 68,
  magic05: 69,
  magic06: 70,
  magic07: 71,
  magic08: 72,
  magic09: 73,
  magic10: 74,
  magic11: 75,
  magic12: 76,
  pain01: 77,
  pain02: 78,
  pain03: 79,
  pain04: 80,
  pain05: 81,
  pain06: 82,
  death01: 83,
  death02: 84,
  death03: 85,
  death04: 86,
  death05: 87,
  death06: 88,
  death07: 89,
  death08: 90,
  death09: 91,
  death10: 92,
  death11: 93,
};

export const shamblerMoves: readonly MonsterMove[] = [
  { name: "shambler_move_stand", firstFrame: 0, lastFrame: 16, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "shambler_move_walk", firstFrame: 17, lastFrame: 28, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(10), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(12), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(13), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(7), actions: ["shambler_maybe_idle"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
  ] },
  { name: "shambler_move_run", firstFrame: 29, lastFrame: 34, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(20), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(20), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(20), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(24), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(20), actions: ["shambler_maybe_idle"], lerpFrame: -1 },
  ] },
  { name: "shambler_move_pain", firstFrame: 77, lastFrame: 82, end: "shambler_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "shambler_attack_magic", firstFrame: 65, lastFrame: 76, end: "shambler_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: ["shambler_windup"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["shambler_lightning_update"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["shambler_lightning_update"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["shambler_lightning_update"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["shambler_lightning_update"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["ShamblerSaveLoc"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["ShamblerCastLightning"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["ShamblerCastLightning"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["ShamblerCastLightning"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "shambler_attack_smash", firstFrame: 35, lastFrame: 46, end: "shambler_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(2), actions: ["shambler_melee1"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["sham_smash10"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(4), actions: [], lerpFrame: -1 },
  ] },
  { name: "shambler_attack_swingl", firstFrame: 56, lastFrame: 64, end: "shambler_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(5), actions: ["shambler_melee1"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(9), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(5), actions: ["ShamClaw"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(8), actions: ["sham_swingl9"], lerpFrame: -1 },
  ] },
  { name: "shambler_attack_swingr", firstFrame: 47, lastFrame: 55, end: "shambler_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(1), actions: ["shambler_melee2"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(8), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(14), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(6), actions: ["ShamClaw"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(8), actions: ["sham_swingr9"], lerpFrame: -1 },
  ] },
  { name: "shambler_move_death", firstFrame: 83, lastFrame: 93, end: "shambler_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["shambler_shrink"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
