// Generated from rerelease/m_tank.cpp and m_tank.h. ZeniMax Media, GPL-2.0.
import type { MonsterMove } from "../../../foundation/monsters/types.ts";

export const tankFrame = {
  stand01: 0,
  stand02: 1,
  stand03: 2,
  stand04: 3,
  stand05: 4,
  stand06: 5,
  stand07: 6,
  stand08: 7,
  stand09: 8,
  stand10: 9,
  stand11: 10,
  stand12: 11,
  stand13: 12,
  stand14: 13,
  stand15: 14,
  stand16: 15,
  stand17: 16,
  stand18: 17,
  stand19: 18,
  stand20: 19,
  stand21: 20,
  stand22: 21,
  stand23: 22,
  stand24: 23,
  stand25: 24,
  stand26: 25,
  stand27: 26,
  stand28: 27,
  stand29: 28,
  stand30: 29,
  walk01: 30,
  walk02: 31,
  walk03: 32,
  walk04: 33,
  walk05: 34,
  walk06: 35,
  walk07: 36,
  walk08: 37,
  walk09: 38,
  walk10: 39,
  walk11: 40,
  walk12: 41,
  walk13: 42,
  walk14: 43,
  walk15: 44,
  walk16: 45,
  walk17: 46,
  walk18: 47,
  walk19: 48,
  walk20: 49,
  walk21: 50,
  walk22: 51,
  walk23: 52,
  walk24: 53,
  walk25: 54,
  attak101: 55,
  attak102: 56,
  attak103: 57,
  attak104: 58,
  attak105: 59,
  attak106: 60,
  attak107: 61,
  attak108: 62,
  attak109: 63,
  attak110: 64,
  attak111: 65,
  attak112: 66,
  attak113: 67,
  attak114: 68,
  attak115: 69,
  attak116: 70,
  attak117: 71,
  attak118: 72,
  attak119: 73,
  attak120: 74,
  attak121: 75,
  attak122: 76,
  attak201: 77,
  attak202: 78,
  attak203: 79,
  attak204: 80,
  attak205: 81,
  attak206: 82,
  attak207: 83,
  attak208: 84,
  attak209: 85,
  attak210: 86,
  attak211: 87,
  attak212: 88,
  attak213: 89,
  attak214: 90,
  attak215: 91,
  attak216: 92,
  attak217: 93,
  attak218: 94,
  attak219: 95,
  attak220: 96,
  attak221: 97,
  attak222: 98,
  attak223: 99,
  attak224: 100,
  attak225: 101,
  attak226: 102,
  attak227: 103,
  attak228: 104,
  attak229: 105,
  attak230: 106,
  attak231: 107,
  attak232: 108,
  attak233: 109,
  attak234: 110,
  attak235: 111,
  attak236: 112,
  attak237: 113,
  attak238: 114,
  attak301: 115,
  attak302: 116,
  attak303: 117,
  attak304: 118,
  attak305: 119,
  attak306: 120,
  attak307: 121,
  attak308: 122,
  attak309: 123,
  attak310: 124,
  attak311: 125,
  attak312: 126,
  attak313: 127,
  attak314: 128,
  attak315: 129,
  attak316: 130,
  attak317: 131,
  attak318: 132,
  attak319: 133,
  attak320: 134,
  attak321: 135,
  attak322: 136,
  attak323: 137,
  attak324: 138,
  attak325: 139,
  attak326: 140,
  attak327: 141,
  attak328: 142,
  attak329: 143,
  attak330: 144,
  attak331: 145,
  attak332: 146,
  attak333: 147,
  attak334: 148,
  attak335: 149,
  attak336: 150,
  attak337: 151,
  attak338: 152,
  attak339: 153,
  attak340: 154,
  attak341: 155,
  attak342: 156,
  attak343: 157,
  attak344: 158,
  attak345: 159,
  attak346: 160,
  attak347: 161,
  attak348: 162,
  attak349: 163,
  attak350: 164,
  attak351: 165,
  attak352: 166,
  attak353: 167,
  attak401: 168,
  attak402: 169,
  attak403: 170,
  attak404: 171,
  attak405: 172,
  attak406: 173,
  attak407: 174,
  attak408: 175,
  attak409: 176,
  attak410: 177,
  attak411: 178,
  attak412: 179,
  attak413: 180,
  attak414: 181,
  attak415: 182,
  attak416: 183,
  attak417: 184,
  attak418: 185,
  attak419: 186,
  attak420: 187,
  attak421: 188,
  attak422: 189,
  attak423: 190,
  attak424: 191,
  attak425: 192,
  attak426: 193,
  attak427: 194,
  attak428: 195,
  attak429: 196,
  pain101: 197,
  pain102: 198,
  pain103: 199,
  pain104: 200,
  pain201: 201,
  pain202: 202,
  pain203: 203,
  pain204: 204,
  pain205: 205,
  pain301: 206,
  pain302: 207,
  pain303: 208,
  pain304: 209,
  pain305: 210,
  pain306: 211,
  pain307: 212,
  pain308: 213,
  pain309: 214,
  pain310: 215,
  pain311: 216,
  pain312: 217,
  pain313: 218,
  pain314: 219,
  pain315: 220,
  pain316: 221,
  death101: 222,
  death102: 223,
  death103: 224,
  death104: 225,
  death105: 226,
  death106: 227,
  death107: 228,
  death108: 229,
  death109: 230,
  death110: 231,
  death111: 232,
  death112: 233,
  death113: 234,
  death114: 235,
  death115: 236,
  death116: 237,
  death117: 238,
  death118: 239,
  death119: 240,
  death120: 241,
  death121: 242,
  death122: 243,
  death123: 244,
  death124: 245,
  death125: 246,
  death126: 247,
  death127: 248,
  death128: 249,
  death129: 250,
  death130: 251,
  death131: 252,
  death132: 253,
  recln101: 254,
  recln102: 255,
  recln103: 256,
  recln104: 257,
  recln105: 258,
  recln106: 259,
  recln107: 260,
  recln108: 261,
  recln109: 262,
  recln110: 263,
  recln111: 264,
  recln112: 265,
  recln113: 266,
  recln114: 267,
  recln115: 268,
  recln116: 269,
  recln117: 270,
  recln118: 271,
  recln119: 272,
  recln120: 273,
  recln121: 274,
  recln122: 275,
  recln123: 276,
  recln124: 277,
  recln125: 278,
  recln126: 279,
  recln127: 280,
  recln128: 281,
  recln129: 282,
  recln130: 283,
  recln131: 284,
  recln132: 285,
  recln133: 286,
  recln134: 287,
  recln135: 288,
  recln136: 289,
  recln137: 290,
  recln138: 291,
  recln139: 292,
  recln140: 293,
};

export const tankMoves: readonly MonsterMove[] = [
  { name: "tank_move_stand", firstFrame: 0, lastFrame: 29, end: null, sidestepScale: 0, frames: [
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "stand", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "tank_move_start_walk", firstFrame: 30, lastFrame: 33, end: "tank_walk", sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(11), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_walk", firstFrame: 34, lastFrame: 49, end: null, sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: ["tank_footstep"], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(6), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_stop_walk", firstFrame: 50, lastFrame: 54, end: "tank_stand", sidestepScale: 0, frames: [
    { ai: "walk", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "walk", distance: Math.fround(4), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_start_run", firstFrame: 30, lastFrame: 33, end: "tank_run", sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(11), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_run", firstFrame: 34, lastFrame: 49, end: null, sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(4), actions: ["tank_footstep"], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(5), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(6), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_stop_run", firstFrame: 50, lastFrame: 54, end: "tank_walk", sidestepScale: 0, frames: [
    { ai: "run", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "run", distance: Math.fround(4), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_pain1", firstFrame: 197, lastFrame: 200, end: "tank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "tank_move_pain2", firstFrame: 201, lastFrame: 205, end: "tank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "tank_move_pain3", firstFrame: 206, lastFrame: 221, end: "tank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(-7), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_attack_blast", firstFrame: 55, lastFrame: 70, end: "tank_reattack_blaster", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: ["tank_blind_check"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["TankBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["TankBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["TankBlaster"], lerpFrame: -1 },
  ] },
  { name: "tank_move_reattack_blast", firstFrame: 65, lastFrame: 70, end: "tank_reattack_blaster", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["TankBlaster"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["TankBlaster"], lerpFrame: -1 },
  ] },
  { name: "tank_move_attack_post_blast", firstFrame: 71, lastFrame: 76, end: "tank_run", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_attack_strike", firstFrame: 77, lastFrame: 114, end: "tank_poststrike", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(9), actions: ["tank_footstep"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: ["tank_footstep"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["tank_windup"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: ["TankStrike"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-10), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-10), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: ["tank_footstep"], lerpFrame: -1 },
  ] },
  { name: "tank_move_attack_pre_rocket", firstFrame: 115, lastFrame: 135, end: "tank_doattack_rocket", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(7), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(7), actions: ["tank_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-3), actions: [], lerpFrame: -1 },
  ] },
  { name: "tank_move_attack_fire_rocket", firstFrame: 136, lastFrame: 144, end: "tank_refire_rocket", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(-3), actions: ["tank_blind_check"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["TankRocket"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: ["TankRocket"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: ["TankRocket"], lerpFrame: -1 },
  ] },
  { name: "tank_move_attack_post_rocket", firstFrame: 145, lastFrame: 167, end: "tank_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(4), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-9), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-8), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-7), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(-1), actions: ["tank_footstep"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "tank_move_attack_chain", firstFrame: 168, lastFrame: 196, end: "tank_run", sidestepScale: 0, frames: [
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "none", distance: Math.fround(0), actions: ["TankMachineGun"], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "charge", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
  { name: "tank_move_death", firstFrame: 222, lastFrame: 253, end: "tank_dead", sidestepScale: 0, frames: [
    { ai: "move", distance: Math.fround(-7), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(6), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(1), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-2), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-3), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-4), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-6), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-4), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-5), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-7), actions: ["tank_shrink"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-15), actions: ["tank_thud"], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(-5), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
    { ai: "move", distance: Math.fround(0), actions: [], lerpFrame: -1 },
  ] },
];
