/* Quake III Arena code/game/g_public.h, cgame/cg_public.h, ui/ui_public.h.
 * Copyright (C) 1999-2005 Id Software, Inc. GPL-2.0-or-later. */

export enum QvmGameImport {
  G_PRINT,
  G_ERROR,
  G_MILLISECONDS,
  G_CVAR_REGISTER,
  G_CVAR_UPDATE,
  G_CVAR_SET,
  G_CVAR_VARIABLE_INTEGER_VALUE,
  G_CVAR_VARIABLE_STRING_BUFFER,
  G_ARGC,
  G_ARGV,
  G_FS_FOPEN_FILE,
  G_FS_READ,
  G_FS_WRITE,
  G_FS_FCLOSE_FILE,
  G_SEND_CONSOLE_COMMAND,
  G_LOCATE_GAME_DATA,
  G_DROP_CLIENT,
  G_SEND_SERVER_COMMAND,
  G_SET_CONFIGSTRING,
  G_GET_CONFIGSTRING,
  G_GET_USERINFO,
  G_SET_USERINFO,
  G_GET_SERVERINFO,
  G_SET_BRUSH_MODEL,
  G_TRACE,
  G_POINT_CONTENTS,
  G_IN_PVS,
  G_IN_PVS_IGNORE_PORTALS,
  G_ADJUST_AREA_PORTAL_STATE,
  G_AREAS_CONNECTED,
  G_LINKENTITY,
  G_UNLINKENTITY,
  G_ENTITIES_IN_BOX,
  G_ENTITY_CONTACT,
  G_BOT_ALLOCATE_CLIENT,
  G_BOT_FREE_CLIENT,
  G_GET_USERCMD,
  G_GET_ENTITY_TOKEN,
  G_FS_GETFILELIST,
  G_DEBUG_POLYGON_CREATE,
  G_DEBUG_POLYGON_DELETE,
  G_REAL_TIME,
  G_SNAPVECTOR,
  G_TRACECAPSULE,
  G_ENTITY_CONTACTCAPSULE,
  G_FS_SEEK,
  BOTLIB_SETUP = 200,
  BOTLIB_SHUTDOWN,
  BOTLIB_LIBVAR_SET,
  BOTLIB_LIBVAR_GET,
  BOTLIB_PC_ADD_GLOBAL_DEFINE,
  BOTLIB_START_FRAME,
  BOTLIB_LOAD_MAP,
  BOTLIB_UPDATENTITY,
  BOTLIB_TEST,
  BOTLIB_GET_SNAPSHOT_ENTITY,
  BOTLIB_GET_CONSOLE_MESSAGE,
  BOTLIB_USER_COMMAND,
  BOTLIB_AAS_ENABLE_ROUTING_AREA = 300,
  BOTLIB_AAS_BBOX_AREAS,
  BOTLIB_AAS_AREA_INFO,
  BOTLIB_AAS_ENTITY_INFO,
  BOTLIB_AAS_INITIALIZED,
  BOTLIB_AAS_PRESENCE_TYPE_BOUNDING_BOX,
  BOTLIB_AAS_TIME,
  BOTLIB_AAS_POINT_AREA_NUM,
  BOTLIB_AAS_TRACE_AREAS,
  BOTLIB_AAS_POINT_CONTENTS,
  BOTLIB_AAS_NEXT_BSP_ENTITY,
  BOTLIB_AAS_VALUE_FOR_BSP_EPAIR_KEY,
  BOTLIB_AAS_VECTOR_FOR_BSP_EPAIR_KEY,
  BOTLIB_AAS_FLOAT_FOR_BSP_EPAIR_KEY,
  BOTLIB_AAS_INT_FOR_BSP_EPAIR_KEY,
  BOTLIB_AAS_AREA_REACHABILITY,
  BOTLIB_AAS_AREA_TRAVEL_TIME_TO_GOAL_AREA,
  BOTLIB_AAS_SWIMMING,
  BOTLIB_AAS_PREDICT_CLIENT_MOVEMENT,
  BOTLIB_EA_SAY = 400,
  BOTLIB_EA_SAY_TEAM,
  BOTLIB_EA_COMMAND,
  BOTLIB_EA_ACTION,
  BOTLIB_EA_GESTURE,
  BOTLIB_EA_TALK,
  BOTLIB_EA_ATTACK,
  BOTLIB_EA_USE,
  BOTLIB_EA_RESPAWN,
  BOTLIB_EA_CROUCH,
  BOTLIB_EA_MOVE_UP,
  BOTLIB_EA_MOVE_DOWN,
  BOTLIB_EA_MOVE_FORWARD,
  BOTLIB_EA_MOVE_BACK,
  BOTLIB_EA_MOVE_LEFT,
  BOTLIB_EA_MOVE_RIGHT,
  BOTLIB_EA_SELECT_WEAPON,
  BOTLIB_EA_JUMP,
  BOTLIB_EA_DELAYED_JUMP,
  BOTLIB_EA_MOVE,
  BOTLIB_EA_VIEW,
  BOTLIB_EA_END_REGULAR,
  BOTLIB_EA_GET_INPUT,
  BOTLIB_EA_RESET_INPUT,
  BOTLIB_AI_LOAD_CHARACTER = 500,
  BOTLIB_AI_FREE_CHARACTER,
  BOTLIB_AI_CHARACTERISTIC_FLOAT,
  BOTLIB_AI_CHARACTERISTIC_BFLOAT,
  BOTLIB_AI_CHARACTERISTIC_INTEGER,
  BOTLIB_AI_CHARACTERISTIC_BINTEGER,
  BOTLIB_AI_CHARACTERISTIC_STRING,
  BOTLIB_AI_ALLOC_CHAT_STATE,
  BOTLIB_AI_FREE_CHAT_STATE,
  BOTLIB_AI_QUEUE_CONSOLE_MESSAGE,
  BOTLIB_AI_REMOVE_CONSOLE_MESSAGE,
  BOTLIB_AI_NEXT_CONSOLE_MESSAGE,
  BOTLIB_AI_NUM_CONSOLE_MESSAGE,
  BOTLIB_AI_INITIAL_CHAT,
  BOTLIB_AI_REPLY_CHAT,
  BOTLIB_AI_CHAT_LENGTH,
  BOTLIB_AI_ENTER_CHAT,
  BOTLIB_AI_STRING_CONTAINS,
  BOTLIB_AI_FIND_MATCH,
  BOTLIB_AI_MATCH_VARIABLE,
  BOTLIB_AI_UNIFY_WHITE_SPACES,
  BOTLIB_AI_REPLACE_SYNONYMS,
  BOTLIB_AI_LOAD_CHAT_FILE,
  BOTLIB_AI_SET_CHAT_GENDER,
  BOTLIB_AI_SET_CHAT_NAME,
  BOTLIB_AI_RESET_GOAL_STATE,
  BOTLIB_AI_RESET_AVOID_GOALS,
  BOTLIB_AI_PUSH_GOAL,
  BOTLIB_AI_POP_GOAL,
  BOTLIB_AI_EMPTY_GOAL_STACK,
  BOTLIB_AI_DUMP_AVOID_GOALS,
  BOTLIB_AI_DUMP_GOAL_STACK,
  BOTLIB_AI_GOAL_NAME,
  BOTLIB_AI_GET_TOP_GOAL,
  BOTLIB_AI_GET_SECOND_GOAL,
  BOTLIB_AI_CHOOSE_LTG_ITEM,
  BOTLIB_AI_CHOOSE_NBG_ITEM,
  BOTLIB_AI_TOUCHING_GOAL,
  BOTLIB_AI_ITEM_GOAL_IN_VIS_BUT_NOT_VISIBLE,
  BOTLIB_AI_GET_LEVEL_ITEM_GOAL,
  BOTLIB_AI_AVOID_GOAL_TIME,
  BOTLIB_AI_INIT_LEVEL_ITEMS,
  BOTLIB_AI_UPDATE_ENTITY_ITEMS,
  BOTLIB_AI_LOAD_ITEM_WEIGHTS,
  BOTLIB_AI_FREE_ITEM_WEIGHTS,
  BOTLIB_AI_SAVE_GOAL_FUZZY_LOGIC,
  BOTLIB_AI_ALLOC_GOAL_STATE,
  BOTLIB_AI_FREE_GOAL_STATE,
  BOTLIB_AI_RESET_MOVE_STATE,
  BOTLIB_AI_MOVE_TO_GOAL,
  BOTLIB_AI_MOVE_IN_DIRECTION,
  BOTLIB_AI_RESET_AVOID_REACH,
  BOTLIB_AI_RESET_LAST_AVOID_REACH,
  BOTLIB_AI_REACHABILITY_AREA,
  BOTLIB_AI_MOVEMENT_VIEW_TARGET,
  BOTLIB_AI_ALLOC_MOVE_STATE,
  BOTLIB_AI_FREE_MOVE_STATE,
  BOTLIB_AI_INIT_MOVE_STATE,
  BOTLIB_AI_CHOOSE_BEST_FIGHT_WEAPON,
  BOTLIB_AI_GET_WEAPON_INFO,
  BOTLIB_AI_LOAD_WEAPON_WEIGHTS,
  BOTLIB_AI_ALLOC_WEAPON_STATE,
  BOTLIB_AI_FREE_WEAPON_STATE,
  BOTLIB_AI_RESET_WEAPON_STATE,
  BOTLIB_AI_GENETIC_PARENTS_AND_CHILD_SELECTION,
  BOTLIB_AI_INTERBREED_GOAL_FUZZY_LOGIC,
  BOTLIB_AI_MUTATE_GOAL_FUZZY_LOGIC,
  BOTLIB_AI_GET_NEXT_CAMP_SPOT_GOAL,
  BOTLIB_AI_GET_MAP_LOCATION_GOAL,
  BOTLIB_AI_NUM_INITIAL_CHATS,
  BOTLIB_AI_GET_CHAT_MESSAGE,
  BOTLIB_AI_REMOVE_FROM_AVOID_GOALS,
  BOTLIB_AI_PREDICT_VISIBLE_POSITION,
  BOTLIB_AI_SET_AVOID_GOAL_TIME,
  BOTLIB_AI_ADD_AVOID_SPOT,
  BOTLIB_AAS_ALTERNATIVE_ROUTE_GOAL,
  BOTLIB_AAS_PREDICT_ROUTE,
  BOTLIB_AAS_POINT_REACHABILITY_AREA_INDEX,
  BOTLIB_PC_LOAD_SOURCE,
  BOTLIB_PC_FREE_SOURCE,
  BOTLIB_PC_READ_TOKEN,
  BOTLIB_PC_SOURCE_FILE_AND_LINE,
}

export function decodeQvmGameImport(word: number): QvmGameImport | null {
  switch (word) {
    case QvmGameImport.G_PRINT:
    case QvmGameImport.G_ERROR:
    case QvmGameImport.G_MILLISECONDS:
    case QvmGameImport.G_CVAR_REGISTER:
    case QvmGameImport.G_CVAR_UPDATE:
    case QvmGameImport.G_CVAR_SET:
    case QvmGameImport.G_CVAR_VARIABLE_INTEGER_VALUE:
    case QvmGameImport.G_CVAR_VARIABLE_STRING_BUFFER:
    case QvmGameImport.G_ARGC:
    case QvmGameImport.G_ARGV:
    case QvmGameImport.G_FS_FOPEN_FILE:
    case QvmGameImport.G_FS_READ:
    case QvmGameImport.G_FS_WRITE:
    case QvmGameImport.G_FS_FCLOSE_FILE:
    case QvmGameImport.G_SEND_CONSOLE_COMMAND:
    case QvmGameImport.G_LOCATE_GAME_DATA:
    case QvmGameImport.G_DROP_CLIENT:
    case QvmGameImport.G_SEND_SERVER_COMMAND:
    case QvmGameImport.G_SET_CONFIGSTRING:
    case QvmGameImport.G_GET_CONFIGSTRING:
    case QvmGameImport.G_GET_USERINFO:
    case QvmGameImport.G_SET_USERINFO:
    case QvmGameImport.G_GET_SERVERINFO:
    case QvmGameImport.G_SET_BRUSH_MODEL:
    case QvmGameImport.G_TRACE:
    case QvmGameImport.G_POINT_CONTENTS:
    case QvmGameImport.G_IN_PVS:
    case QvmGameImport.G_IN_PVS_IGNORE_PORTALS:
    case QvmGameImport.G_ADJUST_AREA_PORTAL_STATE:
    case QvmGameImport.G_AREAS_CONNECTED:
    case QvmGameImport.G_LINKENTITY:
    case QvmGameImport.G_UNLINKENTITY:
    case QvmGameImport.G_ENTITIES_IN_BOX:
    case QvmGameImport.G_ENTITY_CONTACT:
    case QvmGameImport.G_BOT_ALLOCATE_CLIENT:
    case QvmGameImport.G_BOT_FREE_CLIENT:
    case QvmGameImport.G_GET_USERCMD:
    case QvmGameImport.G_GET_ENTITY_TOKEN:
    case QvmGameImport.G_FS_GETFILELIST:
    case QvmGameImport.G_DEBUG_POLYGON_CREATE:
    case QvmGameImport.G_DEBUG_POLYGON_DELETE:
    case QvmGameImport.G_REAL_TIME:
    case QvmGameImport.G_SNAPVECTOR:
    case QvmGameImport.G_TRACECAPSULE:
    case QvmGameImport.G_ENTITY_CONTACTCAPSULE:
    case QvmGameImport.G_FS_SEEK:
    case QvmGameImport.BOTLIB_SETUP:
    case QvmGameImport.BOTLIB_SHUTDOWN:
    case QvmGameImport.BOTLIB_LIBVAR_SET:
    case QvmGameImport.BOTLIB_LIBVAR_GET:
    case QvmGameImport.BOTLIB_PC_ADD_GLOBAL_DEFINE:
    case QvmGameImport.BOTLIB_START_FRAME:
    case QvmGameImport.BOTLIB_LOAD_MAP:
    case QvmGameImport.BOTLIB_UPDATENTITY:
    case QvmGameImport.BOTLIB_TEST:
    case QvmGameImport.BOTLIB_GET_SNAPSHOT_ENTITY:
    case QvmGameImport.BOTLIB_GET_CONSOLE_MESSAGE:
    case QvmGameImport.BOTLIB_USER_COMMAND:
    case QvmGameImport.BOTLIB_AAS_ENABLE_ROUTING_AREA:
    case QvmGameImport.BOTLIB_AAS_BBOX_AREAS:
    case QvmGameImport.BOTLIB_AAS_AREA_INFO:
    case QvmGameImport.BOTLIB_AAS_ENTITY_INFO:
    case QvmGameImport.BOTLIB_AAS_INITIALIZED:
    case QvmGameImport.BOTLIB_AAS_PRESENCE_TYPE_BOUNDING_BOX:
    case QvmGameImport.BOTLIB_AAS_TIME:
    case QvmGameImport.BOTLIB_AAS_POINT_AREA_NUM:
    case QvmGameImport.BOTLIB_AAS_TRACE_AREAS:
    case QvmGameImport.BOTLIB_AAS_POINT_CONTENTS:
    case QvmGameImport.BOTLIB_AAS_NEXT_BSP_ENTITY:
    case QvmGameImport.BOTLIB_AAS_VALUE_FOR_BSP_EPAIR_KEY:
    case QvmGameImport.BOTLIB_AAS_VECTOR_FOR_BSP_EPAIR_KEY:
    case QvmGameImport.BOTLIB_AAS_FLOAT_FOR_BSP_EPAIR_KEY:
    case QvmGameImport.BOTLIB_AAS_INT_FOR_BSP_EPAIR_KEY:
    case QvmGameImport.BOTLIB_AAS_AREA_REACHABILITY:
    case QvmGameImport.BOTLIB_AAS_AREA_TRAVEL_TIME_TO_GOAL_AREA:
    case QvmGameImport.BOTLIB_AAS_SWIMMING:
    case QvmGameImport.BOTLIB_AAS_PREDICT_CLIENT_MOVEMENT:
    case QvmGameImport.BOTLIB_EA_SAY:
    case QvmGameImport.BOTLIB_EA_SAY_TEAM:
    case QvmGameImport.BOTLIB_EA_COMMAND:
    case QvmGameImport.BOTLIB_EA_ACTION:
    case QvmGameImport.BOTLIB_EA_GESTURE:
    case QvmGameImport.BOTLIB_EA_TALK:
    case QvmGameImport.BOTLIB_EA_ATTACK:
    case QvmGameImport.BOTLIB_EA_USE:
    case QvmGameImport.BOTLIB_EA_RESPAWN:
    case QvmGameImport.BOTLIB_EA_CROUCH:
    case QvmGameImport.BOTLIB_EA_MOVE_UP:
    case QvmGameImport.BOTLIB_EA_MOVE_DOWN:
    case QvmGameImport.BOTLIB_EA_MOVE_FORWARD:
    case QvmGameImport.BOTLIB_EA_MOVE_BACK:
    case QvmGameImport.BOTLIB_EA_MOVE_LEFT:
    case QvmGameImport.BOTLIB_EA_MOVE_RIGHT:
    case QvmGameImport.BOTLIB_EA_SELECT_WEAPON:
    case QvmGameImport.BOTLIB_EA_JUMP:
    case QvmGameImport.BOTLIB_EA_DELAYED_JUMP:
    case QvmGameImport.BOTLIB_EA_MOVE:
    case QvmGameImport.BOTLIB_EA_VIEW:
    case QvmGameImport.BOTLIB_EA_END_REGULAR:
    case QvmGameImport.BOTLIB_EA_GET_INPUT:
    case QvmGameImport.BOTLIB_EA_RESET_INPUT:
    case QvmGameImport.BOTLIB_AI_LOAD_CHARACTER:
    case QvmGameImport.BOTLIB_AI_FREE_CHARACTER:
    case QvmGameImport.BOTLIB_AI_CHARACTERISTIC_FLOAT:
    case QvmGameImport.BOTLIB_AI_CHARACTERISTIC_BFLOAT:
    case QvmGameImport.BOTLIB_AI_CHARACTERISTIC_INTEGER:
    case QvmGameImport.BOTLIB_AI_CHARACTERISTIC_BINTEGER:
    case QvmGameImport.BOTLIB_AI_CHARACTERISTIC_STRING:
    case QvmGameImport.BOTLIB_AI_ALLOC_CHAT_STATE:
    case QvmGameImport.BOTLIB_AI_FREE_CHAT_STATE:
    case QvmGameImport.BOTLIB_AI_QUEUE_CONSOLE_MESSAGE:
    case QvmGameImport.BOTLIB_AI_REMOVE_CONSOLE_MESSAGE:
    case QvmGameImport.BOTLIB_AI_NEXT_CONSOLE_MESSAGE:
    case QvmGameImport.BOTLIB_AI_NUM_CONSOLE_MESSAGE:
    case QvmGameImport.BOTLIB_AI_INITIAL_CHAT:
    case QvmGameImport.BOTLIB_AI_REPLY_CHAT:
    case QvmGameImport.BOTLIB_AI_CHAT_LENGTH:
    case QvmGameImport.BOTLIB_AI_ENTER_CHAT:
    case QvmGameImport.BOTLIB_AI_STRING_CONTAINS:
    case QvmGameImport.BOTLIB_AI_FIND_MATCH:
    case QvmGameImport.BOTLIB_AI_MATCH_VARIABLE:
    case QvmGameImport.BOTLIB_AI_UNIFY_WHITE_SPACES:
    case QvmGameImport.BOTLIB_AI_REPLACE_SYNONYMS:
    case QvmGameImport.BOTLIB_AI_LOAD_CHAT_FILE:
    case QvmGameImport.BOTLIB_AI_SET_CHAT_GENDER:
    case QvmGameImport.BOTLIB_AI_SET_CHAT_NAME:
    case QvmGameImport.BOTLIB_AI_RESET_GOAL_STATE:
    case QvmGameImport.BOTLIB_AI_RESET_AVOID_GOALS:
    case QvmGameImport.BOTLIB_AI_PUSH_GOAL:
    case QvmGameImport.BOTLIB_AI_POP_GOAL:
    case QvmGameImport.BOTLIB_AI_EMPTY_GOAL_STACK:
    case QvmGameImport.BOTLIB_AI_DUMP_AVOID_GOALS:
    case QvmGameImport.BOTLIB_AI_DUMP_GOAL_STACK:
    case QvmGameImport.BOTLIB_AI_GOAL_NAME:
    case QvmGameImport.BOTLIB_AI_GET_TOP_GOAL:
    case QvmGameImport.BOTLIB_AI_GET_SECOND_GOAL:
    case QvmGameImport.BOTLIB_AI_CHOOSE_LTG_ITEM:
    case QvmGameImport.BOTLIB_AI_CHOOSE_NBG_ITEM:
    case QvmGameImport.BOTLIB_AI_TOUCHING_GOAL:
    case QvmGameImport.BOTLIB_AI_ITEM_GOAL_IN_VIS_BUT_NOT_VISIBLE:
    case QvmGameImport.BOTLIB_AI_GET_LEVEL_ITEM_GOAL:
    case QvmGameImport.BOTLIB_AI_AVOID_GOAL_TIME:
    case QvmGameImport.BOTLIB_AI_INIT_LEVEL_ITEMS:
    case QvmGameImport.BOTLIB_AI_UPDATE_ENTITY_ITEMS:
    case QvmGameImport.BOTLIB_AI_LOAD_ITEM_WEIGHTS:
    case QvmGameImport.BOTLIB_AI_FREE_ITEM_WEIGHTS:
    case QvmGameImport.BOTLIB_AI_SAVE_GOAL_FUZZY_LOGIC:
    case QvmGameImport.BOTLIB_AI_ALLOC_GOAL_STATE:
    case QvmGameImport.BOTLIB_AI_FREE_GOAL_STATE:
    case QvmGameImport.BOTLIB_AI_RESET_MOVE_STATE:
    case QvmGameImport.BOTLIB_AI_MOVE_TO_GOAL:
    case QvmGameImport.BOTLIB_AI_MOVE_IN_DIRECTION:
    case QvmGameImport.BOTLIB_AI_RESET_AVOID_REACH:
    case QvmGameImport.BOTLIB_AI_RESET_LAST_AVOID_REACH:
    case QvmGameImport.BOTLIB_AI_REACHABILITY_AREA:
    case QvmGameImport.BOTLIB_AI_MOVEMENT_VIEW_TARGET:
    case QvmGameImport.BOTLIB_AI_ALLOC_MOVE_STATE:
    case QvmGameImport.BOTLIB_AI_FREE_MOVE_STATE:
    case QvmGameImport.BOTLIB_AI_INIT_MOVE_STATE:
    case QvmGameImport.BOTLIB_AI_CHOOSE_BEST_FIGHT_WEAPON:
    case QvmGameImport.BOTLIB_AI_GET_WEAPON_INFO:
    case QvmGameImport.BOTLIB_AI_LOAD_WEAPON_WEIGHTS:
    case QvmGameImport.BOTLIB_AI_ALLOC_WEAPON_STATE:
    case QvmGameImport.BOTLIB_AI_FREE_WEAPON_STATE:
    case QvmGameImport.BOTLIB_AI_RESET_WEAPON_STATE:
    case QvmGameImport.BOTLIB_AI_GENETIC_PARENTS_AND_CHILD_SELECTION:
    case QvmGameImport.BOTLIB_AI_INTERBREED_GOAL_FUZZY_LOGIC:
    case QvmGameImport.BOTLIB_AI_MUTATE_GOAL_FUZZY_LOGIC:
    case QvmGameImport.BOTLIB_AI_GET_NEXT_CAMP_SPOT_GOAL:
    case QvmGameImport.BOTLIB_AI_GET_MAP_LOCATION_GOAL:
    case QvmGameImport.BOTLIB_AI_NUM_INITIAL_CHATS:
    case QvmGameImport.BOTLIB_AI_GET_CHAT_MESSAGE:
    case QvmGameImport.BOTLIB_AI_REMOVE_FROM_AVOID_GOALS:
    case QvmGameImport.BOTLIB_AI_PREDICT_VISIBLE_POSITION:
    case QvmGameImport.BOTLIB_AI_SET_AVOID_GOAL_TIME:
    case QvmGameImport.BOTLIB_AI_ADD_AVOID_SPOT:
    case QvmGameImport.BOTLIB_AAS_ALTERNATIVE_ROUTE_GOAL:
    case QvmGameImport.BOTLIB_AAS_PREDICT_ROUTE:
    case QvmGameImport.BOTLIB_AAS_POINT_REACHABILITY_AREA_INDEX:
    case QvmGameImport.BOTLIB_PC_LOAD_SOURCE:
    case QvmGameImport.BOTLIB_PC_FREE_SOURCE:
    case QvmGameImport.BOTLIB_PC_READ_TOKEN:
    case QvmGameImport.BOTLIB_PC_SOURCE_FILE_AND_LINE:
      return word;
    default: return null;
  }
}

export enum QvmGameExport {
  GAME_INIT,
  GAME_SHUTDOWN,
  GAME_CLIENT_CONNECT,
  GAME_CLIENT_BEGIN,
  GAME_CLIENT_USERINFO_CHANGED,
  GAME_CLIENT_DISCONNECT,
  GAME_CLIENT_COMMAND,
  GAME_CLIENT_THINK,
  GAME_RUN_FRAME,
  GAME_CONSOLE_COMMAND,
  BOTAI_START_FRAME,
}

export enum QvmCgameImport {
  CG_PRINT,
  CG_ERROR,
  CG_MILLISECONDS,
  CG_CVAR_REGISTER,
  CG_CVAR_UPDATE,
  CG_CVAR_SET,
  CG_CVAR_VARIABLESTRINGBUFFER,
  CG_ARGC,
  CG_ARGV,
  CG_ARGS,
  CG_FS_FOPENFILE,
  CG_FS_READ,
  CG_FS_WRITE,
  CG_FS_FCLOSEFILE,
  CG_SENDCONSOLECOMMAND,
  CG_ADDCOMMAND,
  CG_SENDCLIENTCOMMAND,
  CG_UPDATESCREEN,
  CG_CM_LOADMAP,
  CG_CM_NUMINLINEMODELS,
  CG_CM_INLINEMODEL,
  CG_CM_LOADMODEL,
  CG_CM_TEMPBOXMODEL,
  CG_CM_POINTCONTENTS,
  CG_CM_TRANSFORMEDPOINTCONTENTS,
  CG_CM_BOXTRACE,
  CG_CM_TRANSFORMEDBOXTRACE,
  CG_CM_MARKFRAGMENTS,
  CG_S_STARTSOUND,
  CG_S_STARTLOCALSOUND,
  CG_S_CLEARLOOPINGSOUNDS,
  CG_S_ADDLOOPINGSOUND,
  CG_S_UPDATEENTITYPOSITION,
  CG_S_RESPATIALIZE,
  CG_S_REGISTERSOUND,
  CG_S_STARTBACKGROUNDTRACK,
  CG_R_LOADWORLDMAP,
  CG_R_REGISTERMODEL,
  CG_R_REGISTERSKIN,
  CG_R_REGISTERSHADER,
  CG_R_CLEARSCENE,
  CG_R_ADDREFENTITYTOSCENE,
  CG_R_ADDPOLYTOSCENE,
  CG_R_ADDLIGHTTOSCENE,
  CG_R_RENDERSCENE,
  CG_R_SETCOLOR,
  CG_R_DRAWSTRETCHPIC,
  CG_R_MODELBOUNDS,
  CG_R_LERPTAG,
  CG_GETGLCONFIG,
  CG_GETGAMESTATE,
  CG_GETCURRENTSNAPSHOTNUMBER,
  CG_GETSNAPSHOT,
  CG_GETSERVERCOMMAND,
  CG_GETCURRENTCMDNUMBER,
  CG_GETUSERCMD,
  CG_SETUSERCMDVALUE,
  CG_R_REGISTERSHADERNOMIP,
  CG_MEMORY_REMAINING,
  CG_R_REGISTERFONT,
  CG_KEY_ISDOWN,
  CG_KEY_GETCATCHER,
  CG_KEY_SETCATCHER,
  CG_KEY_GETKEY,
  CG_PC_ADD_GLOBAL_DEFINE,
  CG_PC_LOAD_SOURCE,
  CG_PC_FREE_SOURCE,
  CG_PC_READ_TOKEN,
  CG_PC_SOURCE_FILE_AND_LINE,
  CG_S_STOPBACKGROUNDTRACK,
  CG_REAL_TIME,
  CG_SNAPVECTOR,
  CG_REMOVECOMMAND,
  CG_R_LIGHTFORPOINT,
  CG_CIN_PLAYCINEMATIC,
  CG_CIN_STOPCINEMATIC,
  CG_CIN_RUNCINEMATIC,
  CG_CIN_DRAWCINEMATIC,
  CG_CIN_SETEXTENTS,
  CG_R_REMAP_SHADER,
  CG_S_ADDREALLOOPINGSOUND,
  CG_S_STOPLOOPINGSOUND,
  CG_CM_TEMPCAPSULEMODEL,
  CG_CM_CAPSULETRACE,
  CG_CM_TRANSFORMEDCAPSULETRACE,
  CG_R_ADDADDITIVELIGHTTOSCENE,
  CG_GET_ENTITY_TOKEN,
  CG_R_ADDPOLYSTOSCENE,
  CG_R_INPVS,
  CG_FS_SEEK,
  CG_MEMSET = 100,
  CG_MEMCPY,
  CG_STRNCPY,
  CG_SIN,
  CG_COS,
  CG_ATAN2,
  CG_SQRT,
  CG_FLOOR,
  CG_CEIL,
  CG_TESTPRINTINT,
  CG_TESTPRINTFLOAT,
  CG_ACOS,
}

export function decodeQvmCgameImport(word: number): QvmCgameImport | null {
  switch (word) {
    case QvmCgameImport.CG_PRINT:
    case QvmCgameImport.CG_ERROR:
    case QvmCgameImport.CG_MILLISECONDS:
    case QvmCgameImport.CG_CVAR_REGISTER:
    case QvmCgameImport.CG_CVAR_UPDATE:
    case QvmCgameImport.CG_CVAR_SET:
    case QvmCgameImport.CG_CVAR_VARIABLESTRINGBUFFER:
    case QvmCgameImport.CG_ARGC:
    case QvmCgameImport.CG_ARGV:
    case QvmCgameImport.CG_ARGS:
    case QvmCgameImport.CG_FS_FOPENFILE:
    case QvmCgameImport.CG_FS_READ:
    case QvmCgameImport.CG_FS_WRITE:
    case QvmCgameImport.CG_FS_FCLOSEFILE:
    case QvmCgameImport.CG_SENDCONSOLECOMMAND:
    case QvmCgameImport.CG_ADDCOMMAND:
    case QvmCgameImport.CG_SENDCLIENTCOMMAND:
    case QvmCgameImport.CG_UPDATESCREEN:
    case QvmCgameImport.CG_CM_LOADMAP:
    case QvmCgameImport.CG_CM_NUMINLINEMODELS:
    case QvmCgameImport.CG_CM_INLINEMODEL:
    case QvmCgameImport.CG_CM_LOADMODEL:
    case QvmCgameImport.CG_CM_TEMPBOXMODEL:
    case QvmCgameImport.CG_CM_POINTCONTENTS:
    case QvmCgameImport.CG_CM_TRANSFORMEDPOINTCONTENTS:
    case QvmCgameImport.CG_CM_BOXTRACE:
    case QvmCgameImport.CG_CM_TRANSFORMEDBOXTRACE:
    case QvmCgameImport.CG_CM_MARKFRAGMENTS:
    case QvmCgameImport.CG_S_STARTSOUND:
    case QvmCgameImport.CG_S_STARTLOCALSOUND:
    case QvmCgameImport.CG_S_CLEARLOOPINGSOUNDS:
    case QvmCgameImport.CG_S_ADDLOOPINGSOUND:
    case QvmCgameImport.CG_S_UPDATEENTITYPOSITION:
    case QvmCgameImport.CG_S_RESPATIALIZE:
    case QvmCgameImport.CG_S_REGISTERSOUND:
    case QvmCgameImport.CG_S_STARTBACKGROUNDTRACK:
    case QvmCgameImport.CG_R_LOADWORLDMAP:
    case QvmCgameImport.CG_R_REGISTERMODEL:
    case QvmCgameImport.CG_R_REGISTERSKIN:
    case QvmCgameImport.CG_R_REGISTERSHADER:
    case QvmCgameImport.CG_R_CLEARSCENE:
    case QvmCgameImport.CG_R_ADDREFENTITYTOSCENE:
    case QvmCgameImport.CG_R_ADDPOLYTOSCENE:
    case QvmCgameImport.CG_R_ADDLIGHTTOSCENE:
    case QvmCgameImport.CG_R_RENDERSCENE:
    case QvmCgameImport.CG_R_SETCOLOR:
    case QvmCgameImport.CG_R_DRAWSTRETCHPIC:
    case QvmCgameImport.CG_R_MODELBOUNDS:
    case QvmCgameImport.CG_R_LERPTAG:
    case QvmCgameImport.CG_GETGLCONFIG:
    case QvmCgameImport.CG_GETGAMESTATE:
    case QvmCgameImport.CG_GETCURRENTSNAPSHOTNUMBER:
    case QvmCgameImport.CG_GETSNAPSHOT:
    case QvmCgameImport.CG_GETSERVERCOMMAND:
    case QvmCgameImport.CG_GETCURRENTCMDNUMBER:
    case QvmCgameImport.CG_GETUSERCMD:
    case QvmCgameImport.CG_SETUSERCMDVALUE:
    case QvmCgameImport.CG_R_REGISTERSHADERNOMIP:
    case QvmCgameImport.CG_MEMORY_REMAINING:
    case QvmCgameImport.CG_R_REGISTERFONT:
    case QvmCgameImport.CG_KEY_ISDOWN:
    case QvmCgameImport.CG_KEY_GETCATCHER:
    case QvmCgameImport.CG_KEY_SETCATCHER:
    case QvmCgameImport.CG_KEY_GETKEY:
    case QvmCgameImport.CG_PC_ADD_GLOBAL_DEFINE:
    case QvmCgameImport.CG_PC_LOAD_SOURCE:
    case QvmCgameImport.CG_PC_FREE_SOURCE:
    case QvmCgameImport.CG_PC_READ_TOKEN:
    case QvmCgameImport.CG_PC_SOURCE_FILE_AND_LINE:
    case QvmCgameImport.CG_S_STOPBACKGROUNDTRACK:
    case QvmCgameImport.CG_REAL_TIME:
    case QvmCgameImport.CG_SNAPVECTOR:
    case QvmCgameImport.CG_REMOVECOMMAND:
    case QvmCgameImport.CG_R_LIGHTFORPOINT:
    case QvmCgameImport.CG_CIN_PLAYCINEMATIC:
    case QvmCgameImport.CG_CIN_STOPCINEMATIC:
    case QvmCgameImport.CG_CIN_RUNCINEMATIC:
    case QvmCgameImport.CG_CIN_DRAWCINEMATIC:
    case QvmCgameImport.CG_CIN_SETEXTENTS:
    case QvmCgameImport.CG_R_REMAP_SHADER:
    case QvmCgameImport.CG_S_ADDREALLOOPINGSOUND:
    case QvmCgameImport.CG_S_STOPLOOPINGSOUND:
    case QvmCgameImport.CG_CM_TEMPCAPSULEMODEL:
    case QvmCgameImport.CG_CM_CAPSULETRACE:
    case QvmCgameImport.CG_CM_TRANSFORMEDCAPSULETRACE:
    case QvmCgameImport.CG_R_ADDADDITIVELIGHTTOSCENE:
    case QvmCgameImport.CG_GET_ENTITY_TOKEN:
    case QvmCgameImport.CG_R_ADDPOLYSTOSCENE:
    case QvmCgameImport.CG_R_INPVS:
    case QvmCgameImport.CG_FS_SEEK:
    case QvmCgameImport.CG_MEMSET:
    case QvmCgameImport.CG_MEMCPY:
    case QvmCgameImport.CG_STRNCPY:
    case QvmCgameImport.CG_SIN:
    case QvmCgameImport.CG_COS:
    case QvmCgameImport.CG_ATAN2:
    case QvmCgameImport.CG_SQRT:
    case QvmCgameImport.CG_FLOOR:
    case QvmCgameImport.CG_CEIL:
    case QvmCgameImport.CG_TESTPRINTINT:
    case QvmCgameImport.CG_TESTPRINTFLOAT:
    case QvmCgameImport.CG_ACOS:
      return word;
    default: return null;
  }
}

export enum QvmCgameExport {
  CG_INIT,
  CG_SHUTDOWN,
  CG_CONSOLE_COMMAND,
  CG_DRAW_ACTIVE_FRAME,
  CG_CROSSHAIR_PLAYER,
  CG_LAST_ATTACKER,
  CG_KEY_EVENT,
  CG_MOUSE_EVENT,
  CG_EVENT_HANDLING,
}

export enum QvmUiImport {
  UI_ERROR,
  UI_PRINT,
  UI_MILLISECONDS,
  UI_CVAR_SET,
  UI_CVAR_VARIABLEVALUE,
  UI_CVAR_VARIABLESTRINGBUFFER,
  UI_CVAR_SETVALUE,
  UI_CVAR_RESET,
  UI_CVAR_CREATE,
  UI_CVAR_INFOSTRINGBUFFER,
  UI_ARGC,
  UI_ARGV,
  UI_CMD_EXECUTETEXT,
  UI_FS_FOPENFILE,
  UI_FS_READ,
  UI_FS_WRITE,
  UI_FS_FCLOSEFILE,
  UI_FS_GETFILELIST,
  UI_R_REGISTERMODEL,
  UI_R_REGISTERSKIN,
  UI_R_REGISTERSHADERNOMIP,
  UI_R_CLEARSCENE,
  UI_R_ADDREFENTITYTOSCENE,
  UI_R_ADDPOLYTOSCENE,
  UI_R_ADDLIGHTTOSCENE,
  UI_R_RENDERSCENE,
  UI_R_SETCOLOR,
  UI_R_DRAWSTRETCHPIC,
  UI_UPDATESCREEN,
  UI_CM_LERPTAG,
  UI_CM_LOADMODEL,
  UI_S_REGISTERSOUND,
  UI_S_STARTLOCALSOUND,
  UI_KEY_KEYNUMTOSTRINGBUF,
  UI_KEY_GETBINDINGBUF,
  UI_KEY_SETBINDING,
  UI_KEY_ISDOWN,
  UI_KEY_GETOVERSTRIKEMODE,
  UI_KEY_SETOVERSTRIKEMODE,
  UI_KEY_CLEARSTATES,
  UI_KEY_GETCATCHER,
  UI_KEY_SETCATCHER,
  UI_GETCLIPBOARDDATA,
  UI_GETGLCONFIG,
  UI_GETCLIENTSTATE,
  UI_GETCONFIGSTRING,
  UI_LAN_GETPINGQUEUECOUNT,
  UI_LAN_CLEARPING,
  UI_LAN_GETPING,
  UI_LAN_GETPINGINFO,
  UI_CVAR_REGISTER,
  UI_CVAR_UPDATE,
  UI_MEMORY_REMAINING,
  UI_GET_CDKEY,
  UI_SET_CDKEY,
  UI_R_REGISTERFONT,
  UI_R_MODELBOUNDS,
  UI_PC_ADD_GLOBAL_DEFINE,
  UI_PC_LOAD_SOURCE,
  UI_PC_FREE_SOURCE,
  UI_PC_READ_TOKEN,
  UI_PC_SOURCE_FILE_AND_LINE,
  UI_S_STOPBACKGROUNDTRACK,
  UI_S_STARTBACKGROUNDTRACK,
  UI_REAL_TIME,
  UI_LAN_GETSERVERCOUNT,
  UI_LAN_GETSERVERADDRESSSTRING,
  UI_LAN_GETSERVERINFO,
  UI_LAN_MARKSERVERVISIBLE,
  UI_LAN_UPDATEVISIBLEPINGS,
  UI_LAN_RESETPINGS,
  UI_LAN_LOADCACHEDSERVERS,
  UI_LAN_SAVECACHEDSERVERS,
  UI_LAN_ADDSERVER,
  UI_LAN_REMOVESERVER,
  UI_CIN_PLAYCINEMATIC,
  UI_CIN_STOPCINEMATIC,
  UI_CIN_RUNCINEMATIC,
  UI_CIN_DRAWCINEMATIC,
  UI_CIN_SETEXTENTS,
  UI_R_REMAP_SHADER,
  UI_VERIFY_CDKEY,
  UI_LAN_SERVERSTATUS,
  UI_LAN_GETSERVERPING,
  UI_LAN_SERVERISVISIBLE,
  UI_LAN_COMPARESERVERS,
  UI_FS_SEEK,
  UI_SET_PBCLSTATUS,
  UI_MEMSET = 100,
  UI_MEMCPY,
  UI_STRNCPY,
  UI_SIN,
  UI_COS,
  UI_ATAN2,
  UI_SQRT,
  UI_FLOOR,
  UI_CEIL,
}

export function decodeQvmUiImport(word: number): QvmUiImport | null {
  switch (word) {
    case QvmUiImport.UI_ERROR:
    case QvmUiImport.UI_PRINT:
    case QvmUiImport.UI_MILLISECONDS:
    case QvmUiImport.UI_CVAR_SET:
    case QvmUiImport.UI_CVAR_VARIABLEVALUE:
    case QvmUiImport.UI_CVAR_VARIABLESTRINGBUFFER:
    case QvmUiImport.UI_CVAR_SETVALUE:
    case QvmUiImport.UI_CVAR_RESET:
    case QvmUiImport.UI_CVAR_CREATE:
    case QvmUiImport.UI_CVAR_INFOSTRINGBUFFER:
    case QvmUiImport.UI_ARGC:
    case QvmUiImport.UI_ARGV:
    case QvmUiImport.UI_CMD_EXECUTETEXT:
    case QvmUiImport.UI_FS_FOPENFILE:
    case QvmUiImport.UI_FS_READ:
    case QvmUiImport.UI_FS_WRITE:
    case QvmUiImport.UI_FS_FCLOSEFILE:
    case QvmUiImport.UI_FS_GETFILELIST:
    case QvmUiImport.UI_R_REGISTERMODEL:
    case QvmUiImport.UI_R_REGISTERSKIN:
    case QvmUiImport.UI_R_REGISTERSHADERNOMIP:
    case QvmUiImport.UI_R_CLEARSCENE:
    case QvmUiImport.UI_R_ADDREFENTITYTOSCENE:
    case QvmUiImport.UI_R_ADDPOLYTOSCENE:
    case QvmUiImport.UI_R_ADDLIGHTTOSCENE:
    case QvmUiImport.UI_R_RENDERSCENE:
    case QvmUiImport.UI_R_SETCOLOR:
    case QvmUiImport.UI_R_DRAWSTRETCHPIC:
    case QvmUiImport.UI_UPDATESCREEN:
    case QvmUiImport.UI_CM_LERPTAG:
    case QvmUiImport.UI_CM_LOADMODEL:
    case QvmUiImport.UI_S_REGISTERSOUND:
    case QvmUiImport.UI_S_STARTLOCALSOUND:
    case QvmUiImport.UI_KEY_KEYNUMTOSTRINGBUF:
    case QvmUiImport.UI_KEY_GETBINDINGBUF:
    case QvmUiImport.UI_KEY_SETBINDING:
    case QvmUiImport.UI_KEY_ISDOWN:
    case QvmUiImport.UI_KEY_GETOVERSTRIKEMODE:
    case QvmUiImport.UI_KEY_SETOVERSTRIKEMODE:
    case QvmUiImport.UI_KEY_CLEARSTATES:
    case QvmUiImport.UI_KEY_GETCATCHER:
    case QvmUiImport.UI_KEY_SETCATCHER:
    case QvmUiImport.UI_GETCLIPBOARDDATA:
    case QvmUiImport.UI_GETGLCONFIG:
    case QvmUiImport.UI_GETCLIENTSTATE:
    case QvmUiImport.UI_GETCONFIGSTRING:
    case QvmUiImport.UI_LAN_GETPINGQUEUECOUNT:
    case QvmUiImport.UI_LAN_CLEARPING:
    case QvmUiImport.UI_LAN_GETPING:
    case QvmUiImport.UI_LAN_GETPINGINFO:
    case QvmUiImport.UI_CVAR_REGISTER:
    case QvmUiImport.UI_CVAR_UPDATE:
    case QvmUiImport.UI_MEMORY_REMAINING:
    case QvmUiImport.UI_GET_CDKEY:
    case QvmUiImport.UI_SET_CDKEY:
    case QvmUiImport.UI_R_REGISTERFONT:
    case QvmUiImport.UI_R_MODELBOUNDS:
    case QvmUiImport.UI_PC_ADD_GLOBAL_DEFINE:
    case QvmUiImport.UI_PC_LOAD_SOURCE:
    case QvmUiImport.UI_PC_FREE_SOURCE:
    case QvmUiImport.UI_PC_READ_TOKEN:
    case QvmUiImport.UI_PC_SOURCE_FILE_AND_LINE:
    case QvmUiImport.UI_S_STOPBACKGROUNDTRACK:
    case QvmUiImport.UI_S_STARTBACKGROUNDTRACK:
    case QvmUiImport.UI_REAL_TIME:
    case QvmUiImport.UI_LAN_GETSERVERCOUNT:
    case QvmUiImport.UI_LAN_GETSERVERADDRESSSTRING:
    case QvmUiImport.UI_LAN_GETSERVERINFO:
    case QvmUiImport.UI_LAN_MARKSERVERVISIBLE:
    case QvmUiImport.UI_LAN_UPDATEVISIBLEPINGS:
    case QvmUiImport.UI_LAN_RESETPINGS:
    case QvmUiImport.UI_LAN_LOADCACHEDSERVERS:
    case QvmUiImport.UI_LAN_SAVECACHEDSERVERS:
    case QvmUiImport.UI_LAN_ADDSERVER:
    case QvmUiImport.UI_LAN_REMOVESERVER:
    case QvmUiImport.UI_CIN_PLAYCINEMATIC:
    case QvmUiImport.UI_CIN_STOPCINEMATIC:
    case QvmUiImport.UI_CIN_RUNCINEMATIC:
    case QvmUiImport.UI_CIN_DRAWCINEMATIC:
    case QvmUiImport.UI_CIN_SETEXTENTS:
    case QvmUiImport.UI_R_REMAP_SHADER:
    case QvmUiImport.UI_VERIFY_CDKEY:
    case QvmUiImport.UI_LAN_SERVERSTATUS:
    case QvmUiImport.UI_LAN_GETSERVERPING:
    case QvmUiImport.UI_LAN_SERVERISVISIBLE:
    case QvmUiImport.UI_LAN_COMPARESERVERS:
    case QvmUiImport.UI_FS_SEEK:
    case QvmUiImport.UI_SET_PBCLSTATUS:
    case QvmUiImport.UI_MEMSET:
    case QvmUiImport.UI_MEMCPY:
    case QvmUiImport.UI_STRNCPY:
    case QvmUiImport.UI_SIN:
    case QvmUiImport.UI_COS:
    case QvmUiImport.UI_ATAN2:
    case QvmUiImport.UI_SQRT:
    case QvmUiImport.UI_FLOOR:
    case QvmUiImport.UI_CEIL:
      return word;
    default: return null;
  }
}

export enum QvmUiExport {
  UI_GETAPIVERSION = 0,
  UI_INIT,
  UI_SHUTDOWN,
  UI_KEY_EVENT,
  UI_MOUSE_EVENT,
  UI_REFRESH,
  UI_IS_FULLSCREEN,
  UI_SET_ACTIVE_MENU,
  UI_CONSOLE_COMMAND,
  UI_DRAW_CONNECT_SCREEN,
  UI_HASUNIQUECDKEY,
}

export enum QvmUiMenu {
  UIMENU_NONE,
  UIMENU_MAIN,
  UIMENU_INGAME,
  UIMENU_NEED_CD,
  UIMENU_BAD_CD_KEY,
  UIMENU_TEAM,
  UIMENU_POSTGAME,
}
