/* quakec_rogue/dragon.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["dragon_stand1", {"frame": 1, "next": "dragon_walk1", "operations": []}],
  ["dragon_atk_a1", {"frame": 43, "next": "dragon_atk_a2", "operations": [{"kind": "action", "name": "dragon_move(17)"}]}],
  ["dragon_atk_a2", {"frame": 44, "next": "dragon_atk_a3", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_fireball"}]}],
  ["dragon_atk_a3", {"frame": 45, "next": "dragon_walk5", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_stop_attack"}]}],
  ["dragon_atk_b1", {"frame": 46, "next": "dragon_atk_b2", "operations": [{"kind": "action", "name": "dragon_move(17)"}]}],
  ["dragon_atk_b2", {"frame": 47, "next": "dragon_atk_b3", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_fireball"}]}],
  ["dragon_atk_b3", {"frame": 48, "next": "dragon_walk7", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_stop_attack"}]}],
  ["dragon_atk_c1", {"frame": 49, "next": "dragon_atk_c2", "operations": [{"kind": "action", "name": "dragon_move(17)"}]}],
  ["dragon_atk_c2", {"frame": 50, "next": "dragon_atk_c3", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_fireball"}]}],
  ["dragon_atk_c3", {"frame": 51, "next": "dragon_walk9", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_stop_attack"}]}],
  ["dragon_atk_d1", {"frame": 52, "next": "dragon_atk_d2", "operations": [{"kind": "action", "name": "dragon_move(17)"}]}],
  ["dragon_atk_d2", {"frame": 53, "next": "dragon_atk_d3", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_fireball"}]}],
  ["dragon_atk_d3", {"frame": 54, "next": "dragon_walk11", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_stop_attack"}]}],
  ["dragon_atk_e1", {"frame": 55, "next": "dragon_atk_e2", "operations": [{"kind": "action", "name": "dragon_move(17)"}]}],
  ["dragon_atk_e2", {"frame": 56, "next": "dragon_atk_e3", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_fireball"}]}],
  ["dragon_atk_e3", {"frame": 57, "next": "dragon_walk13", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_stop_attack"}]}],
  ["dragon_atk_f1", {"frame": 58, "next": "dragon_atk_f2", "operations": [{"kind": "action", "name": "dragon_move(17)"}]}],
  ["dragon_atk_f2", {"frame": 59, "next": "dragon_atk_f3", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_fireball"}]}],
  ["dragon_atk_f3", {"frame": 60, "next": "dragon_atk_f4", "operations": [{"kind": "action", "name": "dragon_move(17)"}]}],
  ["dragon_atk_f4", {"frame": 60, "next": "dragon_walk3", "operations": [{"kind": "action", "name": "dragon_move(17)"}, {"kind": "action", "name": "dragon_stop_attack"}]}],
  ["dragon_walk1", {"frame": 1, "next": "dragon_walk2", "operations": [{"kind": "action", "name": "dragon:dragon_walk1"}]}],
  ["dragon_walk2", {"frame": 2, "next": "dragon_walk3", "operations": [{"kind": "action", "name": "dragon:dragon_walk2"}]}],
  ["dragon_walk3", {"frame": 3, "next": "dragon_walk4", "operations": [{"kind": "action", "name": "dragon:dragon_walk3"}]}],
  ["dragon_walk4", {"frame": 4, "next": "dragon_walk5", "operations": [{"kind": "action", "name": "dragon:dragon_walk2"}]}],
  ["dragon_walk5", {"frame": 5, "next": "dragon_walk6", "operations": [{"kind": "action", "name": "dragon:dragon_walk5"}]}],
  ["dragon_walk6", {"frame": 6, "next": "dragon_walk7", "operations": [{"kind": "action", "name": "dragon:dragon_walk2"}]}],
  ["dragon_walk7", {"frame": 7, "next": "dragon_walk8", "operations": [{"kind": "action", "name": "dragon:dragon_walk7"}]}],
  ["dragon_walk8", {"frame": 8, "next": "dragon_walk9", "operations": [{"kind": "action", "name": "dragon:dragon_walk2"}]}],
  ["dragon_walk9", {"frame": 9, "next": "dragon_walk10", "operations": [{"kind": "action", "name": "dragon:dragon_walk9"}]}],
  ["dragon_walk10", {"frame": 10, "next": "dragon_walk11", "operations": [{"kind": "action", "name": "dragon:dragon_walk2"}]}],
  ["dragon_walk11", {"frame": 11, "next": "dragon_walk12", "operations": [{"kind": "action", "name": "dragon:dragon_walk11"}]}],
  ["dragon_walk12", {"frame": 12, "next": "dragon_walk13", "operations": [{"kind": "action", "name": "dragon:dragon_walk2"}]}],
  ["dragon_walk13", {"frame": 13, "next": "dragon_walk1", "operations": [{"kind": "action", "name": "dragon:dragon_walk13"}]}],
  ["dragon_melee1", {"frame": 20, "next": "dragon_melee2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee2", {"frame": 21, "next": "dragon_melee3", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee3", {"frame": 22, "next": "dragon_melee4", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee4", {"frame": 23, "next": "dragon_melee5", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee5", {"frame": 24, "next": "dragon_melee6", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee6", {"frame": 25, "next": "dragon_melee7", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee7", {"frame": 26, "next": "dragon_melee8", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee8", {"frame": 27, "next": "dragon_melee9", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee9", {"frame": 28, "next": "dragon_melee10", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_melee10", {"frame": 29, "next": "dragon_melee11", "operations": [{"kind": "action", "name": "dragon_tail"}]}],
  ["dragon_melee11", {"frame": 30, "next": "dragon_melee12", "operations": [{"kind": "action", "name": "dragon_move(10)"}]}],
  ["dragon_melee12", {"frame": 31, "next": "dragon_melee13", "operations": [{"kind": "action", "name": "dragon_move(10)"}]}],
  ["dragon_melee13", {"frame": 32, "next": "dragon_walk1", "operations": [{"kind": "action", "name": "dragon_move(10)"}]}],
  ["dragon_painA1", {"frame": 62, "next": "dragon_painA2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painA2", {"frame": 63, "next": "dragon_painA3", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painA3", {"frame": 64, "next": "dragon_walk5", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painB1", {"frame": 65, "next": "dragon_painB2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painB2", {"frame": 66, "next": "dragon_painB3", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painB3", {"frame": 67, "next": "dragon_walk7", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painC1", {"frame": 68, "next": "dragon_painC2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painC2", {"frame": 69, "next": "dragon_painC3", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painC3", {"frame": 70, "next": "dragon_walk9", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painD1", {"frame": 71, "next": "dragon_painD2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painD2", {"frame": 72, "next": "dragon_painD3", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painD3", {"frame": 73, "next": "dragon_walk11", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painE1", {"frame": 74, "next": "dragon_painE2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painE2", {"frame": 75, "next": "dragon_painE3", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painE3", {"frame": 76, "next": "dragon_walk13", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painF1", {"frame": 77, "next": "dragon_painF2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painF2", {"frame": 78, "next": "dragon_painF3", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_painF3", {"frame": 79, "next": "dragon_walk2", "operations": [{"kind": "action", "name": "dragon_move(12)"}]}],
  ["dragon_death1", {"frame": 80, "next": "dragon_death2", "operations": [{"kind": "action", "name": "dragon:dragon_death1"}]}],
  ["dragon_death2", {"frame": 81, "next": "dragon_death3", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death3", {"frame": 82, "next": "dragon_death4", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death4", {"frame": 83, "next": "dragon_death5", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death5", {"frame": 84, "next": "dragon_death6", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death6", {"frame": 85, "next": "dragon_death7", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death7", {"frame": 86, "next": "dragon_death8", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death8", {"frame": 87, "next": "dragon_death9", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death9", {"frame": 88, "next": "dragon_death10", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death10", {"frame": 89, "next": "dragon_death11", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death11", {"frame": 90, "next": "dragon_death12", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death12", {"frame": 91, "next": "dragon_death13", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death13", {"frame": 92, "next": "dragon_death14", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death14", {"frame": 93, "next": "dragon_death15", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death15", {"frame": 94, "next": "dragon_death16", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death16", {"frame": 95, "next": "dragon_death17", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death17", {"frame": 96, "next": "dragon_death18", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death18", {"frame": 97, "next": "dragon_death19", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death19", {"frame": 98, "next": "dragon_death20", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death20", {"frame": 99, "next": "dragon_death21", "operations": [{"kind": "action", "name": "dragon_explode"}]}],
  ["dragon_death21", {"frame": 100, "next": "dragon_death21", "operations": [{"kind": "action", "name": "dragon:dragon_death21"}]}],
]);
