/* quakec_rogue/eel.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["eel_stand1", {"frame": 0, "next": "eel_stand2", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_stand2", {"frame": 1, "next": "eel_stand3", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_stand3", {"frame": 2, "next": "eel_stand4", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_stand4", {"frame": 3, "next": "eel_stand5", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_stand5", {"frame": 4, "next": "eel_stand6", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_stand6", {"frame": 5, "next": "eel_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_walk1", {"frame": 0, "next": "eel_walk2", "operations": [{"kind": "sound", "path": "eel/eactive1.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.2}, {"kind": "ai", "mode": "walk", "distance": 6.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_walk2", {"frame": 1, "next": "eel_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 6.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_walk3", {"frame": 2, "next": "eel_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 6.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_walk4", {"frame": 3, "next": "eel_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 6.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_walk5", {"frame": 4, "next": "eel_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 6.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_walk6", {"frame": 5, "next": "eel_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 6.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_run1", {"frame": 0, "next": "eel_run2", "operations": [{"kind": "sound", "path": "eel/eactive1.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.4}, {"kind": "ai", "mode": "run", "distance": 10.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_run2", {"frame": 1, "next": "eel_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_run3", {"frame": 2, "next": "eel_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_run4", {"frame": 3, "next": "eel_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_run5", {"frame": 4, "next": "eel_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_run6", {"frame": 5, "next": "eel_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack1", {"frame": 0, "next": "eel_attack2", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack2", {"frame": 1, "next": "eel_attack3", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack3", {"frame": 2, "next": "eel_attack4", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack4", {"frame": 3, "next": "eel_attack5", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack5", {"frame": 4, "next": "eel_attack6", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack6", {"frame": 5, "next": "eel_attack7", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack7", {"frame": 0, "next": "eel_attack8", "operations": [{"kind": "ai", "mode": "charge", "distance": 8.0}, {"kind": "action", "name": "eel_pitch_change"}]}],
  ["eel_attack8", {"frame": 1, "next": "eel_attack9", "operations": [{"kind": "action", "name": "eel:eel_attack8"}]}],
  ["eel_attack9", {"frame": 2, "next": "eel_attack10", "operations": [{"kind": "action", "name": "eel:eel_attack9"}]}],
  ["eel_attack10", {"frame": 3, "next": "eel_attack11", "operations": [{"kind": "action", "name": "eel:eel_attack10"}]}],
  ["eel_attack11", {"frame": 4, "next": "eel_attack12", "operations": [{"kind": "action", "name": "eel:eel_attack11"}]}],
  ["eel_attack12", {"frame": 5, "next": "eel_run1", "operations": [{"kind": "action", "name": "eel:eel_attack12"}]}],
  ["eel_death1", {"frame": 6, "next": "eel_death2", "operations": [{"kind": "action", "name": "eel:eel_death1"}]}],
  ["eel_death2", {"frame": 7, "next": "eel_death3", "operations": []}],
  ["eel_death3", {"frame": 8, "next": "eel_death4", "operations": []}],
  ["eel_death4", {"frame": 9, "next": "eel_death5", "operations": []}],
  ["eel_death5", {"frame": 8, "next": "eel_death6", "operations": []}],
  ["eel_death6", {"frame": 7, "next": "eel_death7", "operations": []}],
  ["eel_death7", {"frame": 6, "next": "eel_death8", "operations": []}],
  ["eel_death8", {"frame": 7, "next": "eel_death9", "operations": []}],
  ["eel_death9", {"frame": 8, "next": "eel_death10", "operations": []}],
  ["eel_death10", {"frame": 9, "next": "eel_death11", "operations": []}],
  ["eel_death11", {"frame": 10, "next": "eel_death12", "operations": [{"kind": "action", "name": "eel:eel_death11"}]}],
  ["eel_death12", {"frame": 11, "next": "eel_death13", "operations": []}],
  ["eel_death13", {"frame": 12, "next": "eel_death14", "operations": []}],
  ["eel_death14", {"frame": 13, "next": "eel_death15", "operations": []}],
  ["eel_death15", {"frame": 14, "next": "eel_death16", "operations": [{"kind": "action", "name": "droptofloor"}]}],
  ["eel_death16", {"frame": 15, "next": "eel_death16", "operations": [{"kind": "solid", "solid": "none"}]}],
  ["eel_pain1", {"frame": 6, "next": "eel_pain2", "operations": [{"kind": "action", "name": "eel:eel_pain1"}]}],
  ["eel_pain2", {"frame": 7, "next": "eel_pain3", "operations": []}],
  ["eel_pain3", {"frame": 8, "next": "eel_pain4", "operations": []}],
  ["eel_pain4", {"frame": 9, "next": "eel_pain5", "operations": []}],
  ["eel_pain5", {"frame": 8, "next": "eel_pain6", "operations": []}],
  ["eel_pain6", {"frame": 7, "next": "eel_pain7", "operations": []}],
  ["eel_pain7", {"frame": 6, "next": "eel_run1", "operations": []}],
]);
