/* quakec_hipnotic/monsters/grunt.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["army_stand1", {"frame": 0, "next": "army_stand2", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_stand2", {"frame": 1, "next": "army_stand3", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_stand3", {"frame": 2, "next": "army_stand4", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_stand4", {"frame": 3, "next": "army_stand5", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_stand5", {"frame": 4, "next": "army_stand6", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_stand6", {"frame": 5, "next": "army_stand7", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_stand7", {"frame": 6, "next": "army_stand8", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_stand8", {"frame": 7, "next": "army_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["army_walk1", {"frame": 90, "next": "army_walk2", "operations": [{"kind": "sound", "path": "soldier/idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.2}, {"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk2", {"frame": 91, "next": "army_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk3", {"frame": 92, "next": "army_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk4", {"frame": 93, "next": "army_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk5", {"frame": 94, "next": "army_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["army_walk6", {"frame": 95, "next": "army_walk7", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["army_walk7", {"frame": 96, "next": "army_walk8", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["army_walk8", {"frame": 97, "next": "army_walk9", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["army_walk9", {"frame": 98, "next": "army_walk10", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["army_walk10", {"frame": 99, "next": "army_walk11", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["army_walk11", {"frame": 100, "next": "army_walk12", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["army_walk12", {"frame": 101, "next": "army_walk13", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk13", {"frame": 102, "next": "army_walk14", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["army_walk14", {"frame": 103, "next": "army_walk15", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk15", {"frame": 104, "next": "army_walk16", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk16", {"frame": 105, "next": "army_walk17", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk17", {"frame": 106, "next": "army_walk18", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["army_walk18", {"frame": 107, "next": "army_walk19", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["army_walk19", {"frame": 108, "next": "army_walk20", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["army_walk20", {"frame": 109, "next": "army_walk21", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["army_walk21", {"frame": 110, "next": "army_walk22", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["army_walk22", {"frame": 111, "next": "army_walk23", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk23", {"frame": 112, "next": "army_walk24", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_walk24", {"frame": 113, "next": "army_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 1.0}]}],
  ["army_run1", {"frame": 73, "next": "army_run2", "operations": [{"kind": "sound", "path": "soldier/idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.2}, {"kind": "ai", "mode": "run", "distance": 11.0}]}],
  ["army_run2", {"frame": 74, "next": "army_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 15.0}]}],
  ["army_run3", {"frame": 75, "next": "army_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}]}],
  ["army_run4", {"frame": 76, "next": "army_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}]}],
  ["army_run5", {"frame": 77, "next": "army_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 8.0}]}],
  ["army_run6", {"frame": 78, "next": "army_run7", "operations": [{"kind": "ai", "mode": "run", "distance": 15.0}]}],
  ["army_run7", {"frame": 79, "next": "army_run8", "operations": [{"kind": "ai", "mode": "run", "distance": 10.0}]}],
  ["army_run8", {"frame": 80, "next": "army_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 8.0}]}],
  ["army_atk1", {"frame": 81, "next": "army_atk2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["army_atk2", {"frame": 82, "next": "army_atk3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["army_atk3", {"frame": 83, "next": "army_atk4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["army_atk4", {"frame": 84, "next": "army_atk5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["army_atk5", {"frame": 85, "next": "army_atk6", "operations": [{"kind": "action", "name": "grunt:army_atk5"}]}],
  ["army_atk6", {"frame": 86, "next": "army_atk7", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["army_atk7", {"frame": 87, "next": "army_atk8", "operations": [{"kind": "action", "name": "grunt:army_atk7"}]}],
  ["army_atk8", {"frame": 88, "next": "army_atk9", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["army_atk9", {"frame": 89, "next": "army_run1", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["army_pain1", {"frame": 40, "next": "army_pain2", "operations": []}],
  ["army_pain2", {"frame": 41, "next": "army_pain3", "operations": []}],
  ["army_pain3", {"frame": 42, "next": "army_pain4", "operations": []}],
  ["army_pain4", {"frame": 43, "next": "army_pain5", "operations": []}],
  ["army_pain5", {"frame": 44, "next": "army_pain6", "operations": []}],
  ["army_pain6", {"frame": 45, "next": "army_run1", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["army_painb1", {"frame": 46, "next": "army_painb2", "operations": []}],
  ["army_painb2", {"frame": 47, "next": "army_painb3", "operations": [{"kind": "ai", "mode": "painforward", "distance": 13.0}]}],
  ["army_painb3", {"frame": 48, "next": "army_painb4", "operations": [{"kind": "ai", "mode": "painforward", "distance": 9.0}]}],
  ["army_painb4", {"frame": 49, "next": "army_painb5", "operations": []}],
  ["army_painb5", {"frame": 50, "next": "army_painb6", "operations": []}],
  ["army_painb6", {"frame": 51, "next": "army_painb7", "operations": []}],
  ["army_painb7", {"frame": 52, "next": "army_painb8", "operations": []}],
  ["army_painb8", {"frame": 53, "next": "army_painb9", "operations": []}],
  ["army_painb9", {"frame": 54, "next": "army_painb10", "operations": []}],
  ["army_painb10", {"frame": 55, "next": "army_painb11", "operations": []}],
  ["army_painb11", {"frame": 56, "next": "army_painb12", "operations": []}],
  ["army_painb12", {"frame": 57, "next": "army_painb13", "operations": [{"kind": "ai", "mode": "pain", "distance": 2.0}]}],
  ["army_painb13", {"frame": 58, "next": "army_painb14", "operations": []}],
  ["army_painb14", {"frame": 59, "next": "army_run1", "operations": []}],
  ["army_painc1", {"frame": 60, "next": "army_painc2", "operations": []}],
  ["army_painc2", {"frame": 61, "next": "army_painc3", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["army_painc3", {"frame": 62, "next": "army_painc4", "operations": []}],
  ["army_painc4", {"frame": 63, "next": "army_painc5", "operations": []}],
  ["army_painc5", {"frame": 64, "next": "army_painc6", "operations": [{"kind": "ai", "mode": "painforward", "distance": 1.0}]}],
  ["army_painc6", {"frame": 65, "next": "army_painc7", "operations": [{"kind": "ai", "mode": "painforward", "distance": 1.0}]}],
  ["army_painc7", {"frame": 66, "next": "army_painc8", "operations": []}],
  ["army_painc8", {"frame": 67, "next": "army_painc9", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["army_painc9", {"frame": 68, "next": "army_painc10", "operations": [{"kind": "ai", "mode": "painforward", "distance": 4.0}]}],
  ["army_painc10", {"frame": 69, "next": "army_painc11", "operations": [{"kind": "ai", "mode": "painforward", "distance": 3.0}]}],
  ["army_painc11", {"frame": 70, "next": "army_painc12", "operations": [{"kind": "ai", "mode": "painforward", "distance": 6.0}]}],
  ["army_painc12", {"frame": 71, "next": "army_painc13", "operations": [{"kind": "ai", "mode": "painforward", "distance": 8.0}]}],
  ["army_painc13", {"frame": 72, "next": "army_run1", "operations": []}],
  ["army_die1", {"frame": 8, "next": "army_die2", "operations": []}],
  ["army_die2", {"frame": 9, "next": "army_die3", "operations": []}],
  ["army_die3", {"frame": 10, "next": "army_die4", "operations": [{"kind": "action", "name": "grunt:army_die3"}]}],
  ["army_die4", {"frame": 11, "next": "army_die5", "operations": []}],
  ["army_die5", {"frame": 12, "next": "army_die6", "operations": []}],
  ["army_die6", {"frame": 13, "next": "army_die7", "operations": []}],
  ["army_die7", {"frame": 14, "next": "army_die8", "operations": []}],
  ["army_die8", {"frame": 15, "next": "army_die9", "operations": []}],
  ["army_die9", {"frame": 16, "next": "army_die10", "operations": []}],
  ["army_die10", {"frame": 17, "next": "army_die10", "operations": []}],
  ["army_cdie1", {"frame": 18, "next": "army_cdie2", "operations": []}],
  ["army_cdie2", {"frame": 19, "next": "army_cdie3", "operations": [{"kind": "action", "name": "ai_back(5)"}]}],
  ["army_cdie3", {"frame": 20, "next": "army_cdie4", "operations": [{"kind": "action", "name": "grunt:army_cdie3"}]}],
  ["army_cdie4", {"frame": 21, "next": "army_cdie5", "operations": [{"kind": "action", "name": "ai_back(13)"}]}],
  ["army_cdie5", {"frame": 22, "next": "army_cdie6", "operations": [{"kind": "action", "name": "ai_back(3)"}]}],
  ["army_cdie6", {"frame": 23, "next": "army_cdie7", "operations": [{"kind": "action", "name": "ai_back(4)"}]}],
  ["army_cdie7", {"frame": 24, "next": "army_cdie8", "operations": []}],
  ["army_cdie8", {"frame": 25, "next": "army_cdie9", "operations": []}],
  ["army_cdie9", {"frame": 26, "next": "army_cdie10", "operations": []}],
  ["army_cdie10", {"frame": 27, "next": "army_cdie11", "operations": []}],
  ["army_cdie11", {"frame": 28, "next": "army_cdie11", "operations": []}],
]);
