/* quakec_hipnotic/hiparma.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["armagon_stand1", {"frame": 64, "next": "armagon_stand2", "operations": [{"kind": "action", "name": "hiparma:armagon_stand1"}]}],
  ["armagon_stand2", {"frame": 65, "next": "armagon_stand3", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand3", {"frame": 66, "next": "armagon_stand4", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand4", {"frame": 67, "next": "armagon_stand5", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand5", {"frame": 68, "next": "armagon_stand6", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand6", {"frame": 69, "next": "armagon_stand7", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand7", {"frame": 70, "next": "armagon_stand8", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand8", {"frame": 71, "next": "armagon_stand9", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand9", {"frame": 72, "next": "armagon_stand10", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand10", {"frame": 73, "next": "armagon_stand11", "operations": [{"kind": "action", "name": "hiparma:armagon_stand1"}]}],
  ["armagon_stand11", {"frame": 74, "next": "armagon_stand12", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand12", {"frame": 75, "next": "armagon_stand13", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand13", {"frame": 76, "next": "armagon_stand14", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand14", {"frame": 77, "next": "armagon_stand15", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand15", {"frame": 78, "next": "armagon_stand16", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand16", {"frame": 79, "next": "armagon_stand17", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand17", {"frame": 80, "next": "armagon_stand18", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand18", {"frame": 81, "next": "armagon_stand19", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand19", {"frame": 82, "next": "armagon_stand20", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_stand20", {"frame": 83, "next": "armagon_stand1", "operations": [{"kind": "action", "name": "hiparma:armagon_stand1"}]}],
  ["armagon_walk1", {"frame": 0, "next": "armagon_walk2", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_walk2", {"frame": 1, "next": "armagon_walk3", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_walk3", {"frame": 2, "next": "armagon_walk4", "operations": [{"kind": "action", "name": "hiparma:armagon_walk3"}]}],
  ["armagon_walk4", {"frame": 3, "next": "armagon_walk5", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_walk5", {"frame": 4, "next": "armagon_walk6", "operations": [{"kind": "action", "name": "hiparma:armagon_walk5"}]}],
  ["armagon_walk6", {"frame": 5, "next": "armagon_walk7", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_walk7", {"frame": 6, "next": "armagon_walk8", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_walk8", {"frame": 7, "next": "armagon_walk9", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_walk9", {"frame": 8, "next": "armagon_walk10", "operations": [{"kind": "action", "name": "hiparma:armagon_walk3"}]}],
  ["armagon_walk10", {"frame": 9, "next": "armagon_walk11", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_walk11", {"frame": 10, "next": "armagon_walk12", "operations": [{"kind": "action", "name": "hiparma:armagon_walk5"}]}],
  ["armagon_walk12", {"frame": 11, "next": "armagon_walk1", "operations": [{"kind": "action", "name": "movetogoal(14)"}, {"kind": "action", "name": "armagon_walkthink"}]}],
  ["armagon_run1", {"frame": 0, "next": "armagon_run2", "operations": [{"kind": "action", "name": "hiparma:armagon_run1"}]}],
  ["armagon_run2", {"frame": 1, "next": "armagon_run3", "operations": [{"kind": "action", "name": "hiparma:armagon_run1"}]}],
  ["armagon_run3", {"frame": 2, "next": "armagon_run4", "operations": [{"kind": "action", "name": "hiparma:armagon_run3"}]}],
  ["armagon_run4", {"frame": 3, "next": "armagon_run5", "operations": [{"kind": "action", "name": "hiparma:armagon_run1"}]}],
  ["armagon_run5", {"frame": 4, "next": "armagon_run6", "operations": [{"kind": "action", "name": "hiparma:armagon_run5"}]}],
  ["armagon_run6", {"frame": 5, "next": "armagon_run7", "operations": [{"kind": "action", "name": "hiparma:armagon_run1"}]}],
  ["armagon_run7", {"frame": 6, "next": "armagon_run8", "operations": [{"kind": "action", "name": "hiparma:armagon_run1"}]}],
  ["armagon_run8", {"frame": 7, "next": "armagon_run9", "operations": [{"kind": "action", "name": "hiparma:armagon_run1"}]}],
  ["armagon_run9", {"frame": 8, "next": "armagon_run10", "operations": [{"kind": "action", "name": "hiparma:armagon_run3"}]}],
  ["armagon_run10", {"frame": 9, "next": "armagon_run11", "operations": [{"kind": "action", "name": "hiparma:armagon_run1"}]}],
  ["armagon_run11", {"frame": 10, "next": "armagon_run12", "operations": [{"kind": "action", "name": "hiparma:armagon_run5"}]}],
  ["armagon_run12", {"frame": 11, "next": "armagon_run1", "operations": [{"kind": "action", "name": "hiparma:armagon_run12"}]}],
  ["armagon_watk1", {"frame": 12, "next": "armagon_watk2", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_watk2", {"frame": 13, "next": "armagon_watk3", "operations": [{"kind": "action", "name": "hiparma:armagon_watk2"}]}],
  ["armagon_watk3", {"frame": 14, "next": "armagon_watk4", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_watk4", {"frame": 15, "next": "armagon_watk5", "operations": [{"kind": "action", "name": "hiparma:armagon_watk4"}]}],
  ["armagon_watk5", {"frame": 16, "next": "armagon_watk6", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_watk6", {"frame": 17, "next": "armagon_watk7", "operations": [{"kind": "action", "name": "hiparma:armagon_watk6"}]}],
  ["armagon_watk7", {"frame": 18, "next": "armagon_watk8", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_watk8", {"frame": 19, "next": "armagon_watk9", "operations": [{"kind": "action", "name": "hiparma:armagon_watk2"}]}],
  ["armagon_watk9", {"frame": 20, "next": "armagon_watk10", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_watk10", {"frame": 21, "next": "armagon_watk11", "operations": [{"kind": "action", "name": "hiparma:armagon_watk4"}]}],
  ["armagon_watk11", {"frame": 22, "next": "armagon_watk13", "operations": [{"kind": "action", "name": "hiparma:armagon_watk11"}]}],
  ["armagon_watk13", {"frame": 23, "next": "armagon_run1", "operations": [{"kind": "action", "name": "hiparma:armagon_watk13"}]}],
  ["armagon_wlaseratk1", {"frame": 12, "next": "armagon_wlaseratk2", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_wlaseratk2", {"frame": 13, "next": "armagon_wlaseratk3", "operations": [{"kind": "action", "name": "hiparma:armagon_watk2"}]}],
  ["armagon_wlaseratk3", {"frame": 14, "next": "armagon_wlaseratk4", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_wlaseratk4", {"frame": 15, "next": "armagon_wlaseratk5", "operations": [{"kind": "action", "name": "hiparma:armagon_watk4"}]}],
  ["armagon_wlaseratk5", {"frame": 16, "next": "armagon_wlaseratk6", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_wlaseratk6", {"frame": 17, "next": "armagon_wlaseratk7", "operations": [{"kind": "action", "name": "hiparma:armagon_wlaseratk6"}]}],
  ["armagon_wlaseratk7", {"frame": 18, "next": "armagon_wlaseratk8", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_wlaseratk8", {"frame": 19, "next": "armagon_wlaseratk9", "operations": [{"kind": "action", "name": "hiparma:armagon_watk2"}]}],
  ["armagon_wlaseratk9", {"frame": 20, "next": "armagon_wlaseratk10", "operations": [{"kind": "action", "name": "hiparma:armagon_watk1"}]}],
  ["armagon_wlaseratk10", {"frame": 21, "next": "armagon_wlaseratk11", "operations": [{"kind": "action", "name": "hiparma:armagon_watk4"}]}],
  ["armagon_wlaseratk11", {"frame": 22, "next": "armagon_wlaseratk13", "operations": [{"kind": "action", "name": "hiparma:armagon_wlaseratk11"}]}],
  ["armagon_wlaseratk13", {"frame": 23, "next": "armagon_run1", "operations": [{"kind": "action", "name": "hiparma:armagon_watk13"}]}],
  ["armagon_overleft1", {"frame": 25, "next": "armagon_overleft2", "operations": [{"kind": "action", "name": "hiparma:armagon_overleft1"}]}],
  ["armagon_overleft2", {"frame": 26, "next": "armagon_overleft3", "operations": [{"kind": "action", "name": "armagon_overleft_think"}]}],
  ["armagon_overleft3", {"frame": 27, "next": "armagon_overleft4", "operations": [{"kind": "action", "name": "hiparma:armagon_overleft3"}]}],
  ["armagon_overleft4", {"frame": 28, "next": "armagon_overleft5", "operations": [{"kind": "action", "name": "armagon_overleft_think"}]}],
  ["armagon_overleft5", {"frame": 29, "next": "armagon_overleft6", "operations": [{"kind": "action", "name": "hiparma:armagon_overleft5"}]}],
  ["armagon_overleft6", {"frame": 30, "next": "armagon_overleft7", "operations": [{"kind": "action", "name": "armagon_overleft_think"}]}],
  ["armagon_overleft7", {"frame": 31, "next": "armagon_overleft8", "operations": [{"kind": "action", "name": "armagon_overleft_think"}]}],
  ["armagon_overleft8", {"frame": 32, "next": "armagon_overleft9", "operations": [{"kind": "action", "name": "hiparma:armagon_overleft3"}]}],
  ["armagon_overleft9", {"frame": 33, "next": "armagon_overleft10", "operations": [{"kind": "action", "name": "armagon_overleft_think"}]}],
  ["armagon_overleft10", {"frame": 34, "next": "armagon_overleft11", "operations": [{"kind": "action", "name": "hiparma:armagon_overleft5"}]}],
  ["armagon_overleft11", {"frame": 35, "next": "armagon_overleft12", "operations": [{"kind": "action", "name": "hiparma:armagon_overleft11"}]}],
  ["armagon_overleft12", {"frame": 36, "next": "armagon_overleft13", "operations": [{"kind": "action", "name": "hiparma:armagon_overleft12"}]}],
  ["armagon_overleft13", {"frame": 37, "next": "armagon_overleft14", "operations": [{"kind": "action", "name": "armagon_overleft_think"}]}],
  ["armagon_overleft14", {"frame": 38, "next": "armagon_overleft15", "operations": [{"kind": "action", "name": "armagon_overleft_think"}]}],
  ["armagon_overleft15", {"frame": 39, "next": "armagon_run1", "operations": [{"kind": "action", "name": "armagon_overleft_think"}, {"kind": "action", "name": "SUB_AttackFinished(1.0)"}]}],
  ["armagon_overright1", {"frame": 40, "next": "armagon_overright2", "operations": [{"kind": "action", "name": "hiparma:armagon_overright1"}]}],
  ["armagon_overright2", {"frame": 41, "next": "armagon_overright3", "operations": [{"kind": "action", "name": "armagon_overright_think"}]}],
  ["armagon_overright3", {"frame": 42, "next": "armagon_overright4", "operations": [{"kind": "action", "name": "hiparma:armagon_overright3"}]}],
  ["armagon_overright4", {"frame": 43, "next": "armagon_overright5", "operations": [{"kind": "action", "name": "armagon_overright_think"}]}],
  ["armagon_overright5", {"frame": 44, "next": "armagon_overright6", "operations": [{"kind": "action", "name": "hiparma:armagon_overright5"}]}],
  ["armagon_overright6", {"frame": 45, "next": "armagon_overright7", "operations": [{"kind": "action", "name": "hiparma:armagon_overright6"}]}],
  ["armagon_overright7", {"frame": 46, "next": "armagon_overright8", "operations": [{"kind": "action", "name": "armagon_overright_think"}]}],
  ["armagon_overright8", {"frame": 47, "next": "armagon_overright9", "operations": [{"kind": "action", "name": "hiparma:armagon_overright3"}]}],
  ["armagon_overright9", {"frame": 48, "next": "armagon_overright10", "operations": [{"kind": "action", "name": "armagon_overright_think"}]}],
  ["armagon_overright10", {"frame": 49, "next": "armagon_overright11", "operations": [{"kind": "action", "name": "hiparma:armagon_overright10"}]}],
  ["armagon_overright11", {"frame": 50, "next": "armagon_overright12", "operations": [{"kind": "action", "name": "armagon_overright_think"}]}],
  ["armagon_overright12", {"frame": 51, "next": "armagon_run1", "operations": [{"kind": "action", "name": "armagon_overright_think"}, {"kind": "action", "name": "SUB_AttackFinished(1.0)"}]}],
  ["armagon_plant1", {"frame": 64, "next": "armagon_plant1", "operations": [{"kind": "action", "name": "armagon_stand_attack"}, {"kind": "action", "name": "armagon_think"}]}],
  ["armagon_stop1", {"frame": 84, "next": "armagon_stop2", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_stop2", {"frame": 85, "next": "armagon_plant1", "operations": [{"kind": "action", "name": "hiparma:armagon_stop2"}]}],
  ["armagon_satk1", {"frame": 52, "next": "armagon_satk2", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk2", {"frame": 53, "next": "armagon_satk3", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk3", {"frame": 54, "next": "armagon_satk4", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk4", {"frame": 55, "next": "armagon_satk5", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk5", {"frame": 56, "next": "armagon_satk6", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk6", {"frame": 57, "next": "armagon_satk7", "operations": [{"kind": "action", "name": "hiparma:armagon_satk6"}]}],
  ["armagon_satk7", {"frame": 58, "next": "armagon_satk8", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk8", {"frame": 59, "next": "armagon_satk9", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk9", {"frame": 60, "next": "armagon_satk10", "operations": [{"kind": "action", "name": "hiparma:armagon_satk9"}]}],
  ["armagon_satk10", {"frame": 61, "next": "armagon_satk11", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk11", {"frame": 60, "next": "armagon_satk12", "operations": [{"kind": "action", "name": "hiparma:armagon_satk9"}]}],
  ["armagon_satk12", {"frame": 61, "next": "armagon_satk13", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk13", {"frame": 60, "next": "armagon_satk14", "operations": [{"kind": "action", "name": "hiparma:armagon_satk9"}]}],
  ["armagon_satk14", {"frame": 61, "next": "armagon_satk15", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk15", {"frame": 62, "next": "armagon_satk16", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_satk16", {"frame": 63, "next": "armagon_plant1", "operations": [{"kind": "action", "name": "armagon_think"}, {"kind": "action", "name": "SUB_AttackFinished(0.3)"}]}],
  ["armagon_slaser1", {"frame": 52, "next": "armagon_slaser2", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser2", {"frame": 53, "next": "armagon_slaser3", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser3", {"frame": 54, "next": "armagon_slaser4", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser4", {"frame": 55, "next": "armagon_slaser5", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser5", {"frame": 56, "next": "armagon_slaser6", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser6", {"frame": 57, "next": "armagon_slaser7", "operations": [{"kind": "action", "name": "hiparma:armagon_satk6"}]}],
  ["armagon_slaser7", {"frame": 58, "next": "armagon_slaser8", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser8", {"frame": 59, "next": "armagon_slaser9", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser9", {"frame": 60, "next": "armagon_slaser10", "operations": [{"kind": "action", "name": "armagon_think"}, {"kind": "action", "name": "armagon_launch_laser(40)"}, {"kind": "action", "name": "armagon_launch_laser(-40)"}]}],
  ["armagon_slaser10", {"frame": 61, "next": "armagon_slaser11", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser11", {"frame": 60, "next": "armagon_slaser12", "operations": [{"kind": "action", "name": "armagon_think"}, {"kind": "action", "name": "armagon_launch_laser(40)"}, {"kind": "action", "name": "armagon_launch_laser(-40)"}]}],
  ["armagon_slaser12", {"frame": 61, "next": "armagon_slaser13", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser13", {"frame": 60, "next": "armagon_slaser14", "operations": [{"kind": "action", "name": "armagon_think"}, {"kind": "action", "name": "armagon_launch_laser(40)"}, {"kind": "action", "name": "armagon_launch_laser(-40)"}]}],
  ["armagon_slaser14", {"frame": 61, "next": "armagon_slaser15", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser15", {"frame": 60, "next": "armagon_slaser16", "operations": [{"kind": "action", "name": "armagon_think"}, {"kind": "action", "name": "armagon_launch_laser(40)"}, {"kind": "action", "name": "armagon_launch_laser(-40)"}]}],
  ["armagon_slaser16", {"frame": 61, "next": "armagon_slaser17", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser17", {"frame": 60, "next": "armagon_slaser18", "operations": [{"kind": "action", "name": "armagon_think"}, {"kind": "action", "name": "armagon_launch_laser(40)"}, {"kind": "action", "name": "armagon_launch_laser(-40)"}]}],
  ["armagon_slaser18", {"frame": 61, "next": "armagon_slaser19", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser19", {"frame": 62, "next": "armagon_slaser20", "operations": [{"kind": "action", "name": "armagon_think"}]}],
  ["armagon_slaser20", {"frame": 63, "next": "armagon_plant1", "operations": [{"kind": "action", "name": "armagon_think"}, {"kind": "action", "name": "SUB_AttackFinished(0.3)"}]}],
  ["armagon_die1", {"frame": 84, "next": "armagon_die2", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die2", {"frame": 85, "next": "armagon_die3", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die3", {"frame": 86, "next": "armagon_die4", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die4", {"frame": 87, "next": "armagon_die5", "operations": [{"kind": "action", "name": "hiparma:armagon_die4"}]}],
  ["armagon_die5", {"frame": 88, "next": "armagon_die6", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die6", {"frame": 89, "next": "armagon_die7", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die7", {"frame": 90, "next": "armagon_die8", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die8", {"frame": 91, "next": "armagon_die9", "operations": [{"kind": "action", "name": "hiparma:armagon_die8"}]}],
  ["armagon_die9", {"frame": 92, "next": "armagon_die10", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die10", {"frame": 93, "next": "armagon_die11", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die11", {"frame": 94, "next": "armagon_die12", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die12", {"frame": 95, "next": "armagon_die13", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die13", {"frame": 96, "next": "armagon_die14", "operations": [{"kind": "action", "name": "hiparma:armagon_stand2"}]}],
  ["armagon_die14", {"frame": 97, "next": "armagon_die14", "operations": [{"kind": "action", "name": "hiparma:armagon_die14"}]}],
]);
