/* quakec_hipnotic/hipgrem.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["gremlin_stand1", {"frame": 0, "next": "gremlin_stand2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand2", {"frame": 1, "next": "gremlin_stand3", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand3", {"frame": 2, "next": "gremlin_stand4", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand4", {"frame": 3, "next": "gremlin_stand5", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand5", {"frame": 4, "next": "gremlin_stand6", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand6", {"frame": 5, "next": "gremlin_stand7", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand7", {"frame": 6, "next": "gremlin_stand8", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand8", {"frame": 7, "next": "gremlin_stand9", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand9", {"frame": 8, "next": "gremlin_stand10", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand10", {"frame": 9, "next": "gremlin_stand11", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand11", {"frame": 10, "next": "gremlin_stand12", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand12", {"frame": 11, "next": "gremlin_stand13", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand13", {"frame": 12, "next": "gremlin_stand14", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand14", {"frame": 13, "next": "gremlin_stand15", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand15", {"frame": 14, "next": "gremlin_stand16", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand16", {"frame": 15, "next": "gremlin_stand17", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_stand17", {"frame": 16, "next": "gremlin_stand1", "operations": [{"kind": "action", "name": "hipgrem:gremlin_stand1"}]}],
  ["gremlin_walk1", {"frame": 17, "next": "gremlin_walk2", "operations": [{"kind": "sound", "path": "grem/idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.1}, {"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk2", {"frame": 18, "next": "gremlin_walk3", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk3", {"frame": 19, "next": "gremlin_walk4", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk4", {"frame": 20, "next": "gremlin_walk5", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk5", {"frame": 21, "next": "gremlin_walk6", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk6", {"frame": 22, "next": "gremlin_walk7", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk7", {"frame": 23, "next": "gremlin_walk8", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk8", {"frame": 24, "next": "gremlin_walk9", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk9", {"frame": 25, "next": "gremlin_walk10", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk10", {"frame": 26, "next": "gremlin_walk11", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk11", {"frame": 27, "next": "gremlin_walk12", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_walk12", {"frame": 28, "next": "gremlin_walk1", "operations": [{"kind": "action", "name": "gremlin_walk(8)"}]}],
  ["gremlin_run1", {"frame": 29, "next": "gremlin_run2", "operations": [{"kind": "sound", "path": "grem/idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.1}, {"kind": "action", "name": "gremlin_run(0)"}]}],
  ["gremlin_run2", {"frame": 30, "next": "gremlin_run3", "operations": [{"kind": "action", "name": "gremlin_run(8)"}]}],
  ["gremlin_run3", {"frame": 31, "next": "gremlin_run4", "operations": [{"kind": "action", "name": "gremlin_run(12)"}]}],
  ["gremlin_run4", {"frame": 32, "next": "gremlin_run5", "operations": [{"kind": "action", "name": "gremlin_run(16)"}]}],
  ["gremlin_run5", {"frame": 33, "next": "gremlin_run6", "operations": [{"kind": "action", "name": "gremlin_run(16)"}]}],
  ["gremlin_run6", {"frame": 34, "next": "gremlin_run7", "operations": [{"kind": "action", "name": "gremlin_run(12)"}]}],
  ["gremlin_run7", {"frame": 35, "next": "gremlin_run8", "operations": [{"kind": "action", "name": "gremlin_run(8)"}]}],
  ["gremlin_run8", {"frame": 36, "next": "gremlin_run9", "operations": [{"kind": "action", "name": "gremlin_run(0)"}]}],
  ["gremlin_run9", {"frame": 37, "next": "gremlin_run10", "operations": [{"kind": "action", "name": "gremlin_run(8)"}]}],
  ["gremlin_run10", {"frame": 38, "next": "gremlin_run11", "operations": [{"kind": "action", "name": "gremlin_run(12)"}]}],
  ["gremlin_run11", {"frame": 39, "next": "gremlin_run12", "operations": [{"kind": "action", "name": "gremlin_run(16)"}]}],
  ["gremlin_run12", {"frame": 40, "next": "gremlin_run1", "operations": [{"kind": "action", "name": "gremlin_run(16)"}]}],
  ["gremlin_run13", {"frame": 41, "next": "gremlin_run14", "operations": [{"kind": "action", "name": "gremlin_run(12)"}]}],
  ["gremlin_run14", {"frame": 42, "next": "gremlin_run15", "operations": [{"kind": "action", "name": "gremlin_run(8)"}]}],
  ["gremlin_run15", {"frame": 43, "next": "gremlin_run1", "operations": [{"kind": "action", "name": "gremlin_run(0)"}]}],
  ["gremlin_jump1", {"frame": 44, "next": "gremlin_jump2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["gremlin_jump2", {"frame": 45, "next": "gremlin_jump3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["gremlin_jump3", {"frame": 46, "next": "gremlin_jump4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["gremlin_jump4", {"frame": 47, "next": "gremlin_jump5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["gremlin_jump5", {"frame": 48, "next": "gremlin_jump6", "operations": [{"kind": "action", "name": "hipgrem:gremlin_jump5"}]}],
  ["gremlin_jump6", {"frame": 49, "next": "gremlin_jump7", "operations": []}],
  ["gremlin_jump7", {"frame": 50, "next": "gremlin_jump8", "operations": []}],
  ["gremlin_jump8", {"frame": 51, "next": "gremlin_jump9", "operations": []}],
  ["gremlin_jump9", {"frame": 52, "next": "gremlin_jump10", "operations": []}],
  ["gremlin_jump10", {"frame": 53, "next": "gremlin_jump11", "operations": []}],
  ["gremlin_jump11", {"frame": 54, "next": "gremlin_jump1", "operations": [{"kind": "action", "name": "hipgrem:gremlin_jump11"}]}],
  ["gremlin_jump12", {"frame": 55, "next": "gremlin_jump13", "operations": []}],
  ["gremlin_jump13", {"frame": 56, "next": "gremlin_jump14", "operations": []}],
  ["gremlin_jump14", {"frame": 57, "next": "gremlin_jump15", "operations": []}],
  ["gremlin_jump15", {"frame": 58, "next": "gremlin_jump16", "operations": []}],
  ["gremlin_jump16", {"frame": 59, "next": "gremlin_run1", "operations": []}],
  ["gremlin_shot1", {"frame": 135, "next": "gremlin_shot2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_shot1"}]}],
  ["gremlin_shot2", {"frame": 136, "next": "gremlin_shot3", "operations": []}],
  ["gremlin_shot3", {"frame": 137, "next": "gremlin_shot4", "operations": []}],
  ["gremlin_shot4", {"frame": 138, "next": "gremlin_shot5", "operations": []}],
  ["gremlin_shot5", {"frame": 139, "next": "gremlin_shot6", "operations": []}],
  ["gremlin_shot6", {"frame": 140, "next": "gremlin_run1", "operations": []}],
  ["gremlin_nail1", {"frame": 135, "next": "gremlin_nail2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_nail1"}]}],
  ["gremlin_nail2", {"frame": 135, "next": "gremlin_nail3", "operations": [{"kind": "action", "name": "hipgrem:gremlin_nail1"}]}],
  ["gremlin_nail3", {"frame": 135, "next": "gremlin_nail4", "operations": [{"kind": "action", "name": "hipgrem:gremlin_nail1"}]}],
  ["gremlin_nail4", {"frame": 135, "next": "gremlin_nail5", "operations": [{"kind": "action", "name": "hipgrem:gremlin_nail1"}]}],
  ["gremlin_nail5", {"frame": 135, "next": "gremlin_nail6", "operations": [{"kind": "action", "name": "hipgrem:gremlin_nail1"}]}],
  ["gremlin_nail6", {"frame": 135, "next": "gremlin_nail7", "operations": [{"kind": "action", "name": "hipgrem:gremlin_nail1"}]}],
  ["gremlin_nail7", {"frame": 135, "next": "gremlin_run1", "operations": []}],
  ["gremlin_laser1", {"frame": 135, "next": "gremlin_laser2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_laser1"}]}],
  ["gremlin_laser2", {"frame": 135, "next": "gremlin_laser3", "operations": [{"kind": "action", "name": "hipgrem:gremlin_laser1"}]}],
  ["gremlin_laser3", {"frame": 135, "next": "gremlin_laser4", "operations": [{"kind": "action", "name": "hipgrem:gremlin_laser1"}]}],
  ["gremlin_laser4", {"frame": 135, "next": "gremlin_laser5", "operations": [{"kind": "action", "name": "hipgrem:gremlin_laser1"}]}],
  ["gremlin_laser5", {"frame": 135, "next": "gremlin_laser6", "operations": [{"kind": "action", "name": "hipgrem:gremlin_laser1"}]}],
  ["gremlin_laser6", {"frame": 135, "next": "gremlin_laser7", "operations": [{"kind": "action", "name": "hipgrem:gremlin_laser1"}]}],
  ["gremlin_laser7", {"frame": 135, "next": "gremlin_run1", "operations": []}],
  ["gremlin_light1", {"frame": 135, "next": "gremlin_light2", "operations": [{"kind": "action", "name": "Gremlin_FireLightningGun"}]}],
  ["gremlin_light2", {"frame": 135, "next": "gremlin_light3", "operations": [{"kind": "action", "name": "Gremlin_FireLightningGun"}]}],
  ["gremlin_light3", {"frame": 135, "next": "gremlin_light4", "operations": [{"kind": "action", "name": "Gremlin_FireLightningGun"}]}],
  ["gremlin_light4", {"frame": 135, "next": "gremlin_light5", "operations": [{"kind": "action", "name": "Gremlin_FireLightningGun"}]}],
  ["gremlin_light5", {"frame": 135, "next": "gremlin_run1", "operations": []}],
  ["gremlin_rocket1", {"frame": 135, "next": "gremlin_rocket2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_shot1"}]}],
  ["gremlin_rocket2", {"frame": 136, "next": "gremlin_rocket3", "operations": []}],
  ["gremlin_rocket3", {"frame": 137, "next": "gremlin_rocket4", "operations": []}],
  ["gremlin_rocket4", {"frame": 138, "next": "gremlin_rocket5", "operations": []}],
  ["gremlin_rocket5", {"frame": 139, "next": "gremlin_rocket6", "operations": []}],
  ["gremlin_rocket6", {"frame": 140, "next": "gremlin_run1", "operations": []}],
  ["gremlin_lunge1", {"frame": 124, "next": "gremlin_lunge2", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge2", {"frame": 125, "next": "gremlin_lunge3", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge3", {"frame": 126, "next": "gremlin_lunge4", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge4", {"frame": 127, "next": "gremlin_lunge5", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge5", {"frame": 128, "next": "gremlin_lunge6", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge6", {"frame": 129, "next": "gremlin_lunge7", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge7", {"frame": 130, "next": "gremlin_lunge8", "operations": [{"kind": "ai", "mode": "charge", "distance": 15.0}]}],
  ["gremlin_lunge8", {"frame": 131, "next": "gremlin_lunge9", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}, {"kind": "action", "name": "Gremlin_Melee(0)"}]}],
  ["gremlin_lunge9", {"frame": 132, "next": "gremlin_lunge10", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge10", {"frame": 133, "next": "gremlin_lunge11", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_lunge11", {"frame": 134, "next": "gremlin_run1", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw1", {"frame": 60, "next": "gremlin_claw2", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw2", {"frame": 61, "next": "gremlin_claw3", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw3", {"frame": 62, "next": "gremlin_claw4", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw4", {"frame": 63, "next": "gremlin_claw5", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw5", {"frame": 64, "next": "gremlin_claw6", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw6", {"frame": 65, "next": "gremlin_claw7", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}, {"kind": "action", "name": "Gremlin_Melee(200)"}]}],
  ["gremlin_claw7", {"frame": 66, "next": "gremlin_claw8", "operations": [{"kind": "ai", "mode": "charge", "distance": 15.0}]}],
  ["gremlin_claw8", {"frame": 67, "next": "gremlin_claw9", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw9", {"frame": 68, "next": "gremlin_claw10", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw10", {"frame": 69, "next": "gremlin_claw11", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_claw11", {"frame": 70, "next": "gremlin_run1", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge1", {"frame": 71, "next": "gremlin_gorge2", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["gremlin_gorge2", {"frame": 72, "next": "gremlin_gorge3", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["gremlin_gorge3", {"frame": 73, "next": "gremlin_gorge4", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}]}],
  ["gremlin_gorge4", {"frame": 74, "next": "gremlin_gorge5", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge5", {"frame": 75, "next": "gremlin_gorge6", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge6", {"frame": 76, "next": "gremlin_gorge7", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}, {"kind": "action", "name": "Gremlin_Gorge(200)"}]}],
  ["gremlin_gorge7", {"frame": 77, "next": "gremlin_gorge8", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge8", {"frame": 78, "next": "gremlin_gorge9", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}, {"kind": "action", "name": "Gremlin_Gorge(-200)"}]}],
  ["gremlin_gorge9", {"frame": 79, "next": "gremlin_gorge10", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge10", {"frame": 80, "next": "gremlin_gorge11", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge11", {"frame": 81, "next": "gremlin_gorge12", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge12", {"frame": 82, "next": "gremlin_gorge13", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_gorge13", {"frame": 83, "next": "gremlin_gorge1", "operations": [{"kind": "ai", "mode": "charge", "distance": 0.0}]}],
  ["gremlin_look1", {"frame": 90, "next": "gremlin_look2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look2", {"frame": 91, "next": "gremlin_look3", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look3", {"frame": 92, "next": "gremlin_look4", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look4", {"frame": 93, "next": "gremlin_look5", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look5", {"frame": 94, "next": "gremlin_look6", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look6", {"frame": 95, "next": "gremlin_look7", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look7", {"frame": 96, "next": "gremlin_look8", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look8", {"frame": 97, "next": "gremlin_look9", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look1"}]}],
  ["gremlin_look9", {"frame": 98, "next": "gremlin_run1", "operations": [{"kind": "action", "name": "hipgrem:gremlin_look9"}]}],
  ["gremlin_glook1", {"frame": 141, "next": "gremlin_glook2", "operations": []}],
  ["gremlin_glook2", {"frame": 142, "next": "gremlin_glook3", "operations": []}],
  ["gremlin_glook3", {"frame": 143, "next": "gremlin_glook4", "operations": []}],
  ["gremlin_glook4", {"frame": 144, "next": "gremlin_glook5", "operations": []}],
  ["gremlin_glook5", {"frame": 145, "next": "gremlin_glook6", "operations": []}],
  ["gremlin_glook6", {"frame": 146, "next": "gremlin_glook7", "operations": []}],
  ["gremlin_glook7", {"frame": 147, "next": "gremlin_glook8", "operations": []}],
  ["gremlin_glook8", {"frame": 148, "next": "gremlin_glook9", "operations": []}],
  ["gremlin_glook9", {"frame": 149, "next": "gremlin_glook10", "operations": []}],
  ["gremlin_glook10", {"frame": 150, "next": "gremlin_glook11", "operations": []}],
  ["gremlin_glook11", {"frame": 151, "next": "gremlin_glook12", "operations": []}],
  ["gremlin_glook12", {"frame": 152, "next": "gremlin_glook13", "operations": []}],
  ["gremlin_glook13", {"frame": 153, "next": "gremlin_glook14", "operations": []}],
  ["gremlin_glook14", {"frame": 154, "next": "gremlin_glook15", "operations": []}],
  ["gremlin_glook15", {"frame": 155, "next": "gremlin_glook16", "operations": []}],
  ["gremlin_glook16", {"frame": 156, "next": "gremlin_glook17", "operations": []}],
  ["gremlin_glook17", {"frame": 157, "next": "gremlin_glook18", "operations": []}],
  ["gremlin_glook18", {"frame": 158, "next": "gremlin_glook19", "operations": []}],
  ["gremlin_glook19", {"frame": 159, "next": "gremlin_glook20", "operations": []}],
  ["gremlin_glook20", {"frame": 160, "next": "gremlin_glook20", "operations": [{"kind": "action", "name": "hipgrem:gremlin_glook20"}]}],
  ["gremlin_pain1", {"frame": 100, "next": "gremlin_pain2", "operations": [{"kind": "action", "name": "ai_back(4)"}]}],
  ["gremlin_pain2", {"frame": 101, "next": "gremlin_pain3", "operations": [{"kind": "action", "name": "ai_back(4)"}]}],
  ["gremlin_pain3", {"frame": 102, "next": "gremlin_pain4", "operations": [{"kind": "action", "name": "ai_back(2)"}]}],
  ["gremlin_pain4", {"frame": 103, "next": "gremlin_run1", "operations": []}],
  ["gremlin_gunpain1", {"frame": 161, "next": "gremlin_gunpain2", "operations": [{"kind": "action", "name": "ai_back(4)"}]}],
  ["gremlin_gunpain2", {"frame": 162, "next": "gremlin_gunpain3", "operations": [{"kind": "action", "name": "ai_back(2)"}]}],
  ["gremlin_gunpain3", {"frame": 163, "next": "gremlin_run1", "operations": []}],
  ["gremlin_spawn1", {"frame": 84, "next": "gremlin_spawn2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_spawn1"}]}],
  ["gremlin_spawn2", {"frame": 85, "next": "gremlin_spawn3", "operations": [{"kind": "action", "name": "hipgrem:gremlin_spawn2"}]}],
  ["gremlin_spawn3", {"frame": 86, "next": "gremlin_spawn4", "operations": [{"kind": "action", "name": "hipgrem:gremlin_spawn2"}]}],
  ["gremlin_spawn4", {"frame": 87, "next": "gremlin_spawn5", "operations": [{"kind": "action", "name": "hipgrem:gremlin_spawn2"}]}],
  ["gremlin_spawn5", {"frame": 88, "next": "gremlin_spawn6", "operations": [{"kind": "action", "name": "hipgrem:gremlin_spawn2"}]}],
  ["gremlin_spawn6", {"frame": 89, "next": "gremlin_run1", "operations": [{"kind": "action", "name": "hipgrem:gremlin_spawn6"}]}],
  ["gremlin_die1", {"frame": 104, "next": "gremlin_die2", "operations": [{"kind": "sound", "path": "grem/death.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["gremlin_die2", {"frame": 105, "next": "gremlin_die3", "operations": [{"kind": "ai", "mode": "forward", "distance": 2.0}]}],
  ["gremlin_die3", {"frame": 106, "next": "gremlin_die4", "operations": [{"kind": "ai", "mode": "forward", "distance": 1.0}]}],
  ["gremlin_die4", {"frame": 107, "next": "gremlin_die5", "operations": [{"kind": "ai", "mode": "forward", "distance": 2.0}]}],
  ["gremlin_die5", {"frame": 108, "next": "gremlin_die6", "operations": [{"kind": "ai", "mode": "forward", "distance": 1.0}]}],
  ["gremlin_die6", {"frame": 109, "next": "gremlin_die7", "operations": [{"kind": "solid", "solid": "none"}]}],
  ["gremlin_die7", {"frame": 110, "next": "gremlin_die8", "operations": [{"kind": "ai", "mode": "forward", "distance": 2.0}]}],
  ["gremlin_die8", {"frame": 111, "next": "gremlin_die9", "operations": [{"kind": "ai", "mode": "forward", "distance": 1.0}]}],
  ["gremlin_die9", {"frame": 112, "next": "gremlin_die10", "operations": [{"kind": "ai", "mode": "forward", "distance": 2.0}]}],
  ["gremlin_die10", {"frame": 113, "next": "gremlin_die11", "operations": [{"kind": "ai", "mode": "forward", "distance": 1.0}]}],
  ["gremlin_die11", {"frame": 114, "next": "gremlin_die12", "operations": [{"kind": "ai", "mode": "forward", "distance": 2.0}]}],
  ["gremlin_die12", {"frame": 115, "next": "gremlin_die12", "operations": []}],
  ["gremlin_flip1", {"frame": 116, "next": "gremlin_flip2", "operations": [{"kind": "action", "name": "hipgrem:gremlin_flip1"}]}],
  ["gremlin_flip2", {"frame": 117, "next": "gremlin_flip3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["gremlin_flip3", {"frame": 118, "next": "gremlin_flip4", "operations": []}],
  ["gremlin_flip4", {"frame": 119, "next": "gremlin_flip5", "operations": []}],
  ["gremlin_flip5", {"frame": 120, "next": "gremlin_flip6", "operations": []}],
  ["gremlin_flip6", {"frame": 121, "next": "gremlin_flip7", "operations": [{"kind": "action", "name": "hipgrem:gremlin_flip6"}]}],
  ["gremlin_flip7", {"frame": 122, "next": "gremlin_gib", "operations": [{"kind": "action", "name": "hipgrem:gremlin_jump11"}]}],
  ["gremlin_flip8", {"frame": 123, "next": "gremlin_flip8", "operations": [{"kind": "solid", "solid": "none"}]}],
]);
