/* quakec_hipnotic/hipscrge.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["scourge_stand1", {"frame": 0, "next": "scourge_stand2", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand2", {"frame": 1, "next": "scourge_stand3", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand3", {"frame": 2, "next": "scourge_stand4", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand4", {"frame": 3, "next": "scourge_stand5", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand5", {"frame": 4, "next": "scourge_stand6", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand6", {"frame": 5, "next": "scourge_stand7", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand7", {"frame": 6, "next": "scourge_stand8", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand8", {"frame": 7, "next": "scourge_stand9", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand9", {"frame": 8, "next": "scourge_stand10", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand10", {"frame": 9, "next": "scourge_stand11", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand11", {"frame": 10, "next": "scourge_stand12", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_stand12", {"frame": 11, "next": "scourge_stand1", "operations": [{"kind": "action", "name": "hipscrge:scourge_stand1"}]}],
  ["scourge_walk1", {"frame": 12, "next": "scourge_walk2", "operations": [{"kind": "action", "name": "hipscrge:scourge_walk1"}]}],
  ["scourge_walk2", {"frame": 13, "next": "scourge_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["scourge_walk3", {"frame": 14, "next": "scourge_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["scourge_walk4", {"frame": 15, "next": "scourge_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["scourge_walk5", {"frame": 16, "next": "scourge_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["scourge_walk6", {"frame": 17, "next": "scourge_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["scourge_run1", {"frame": 12, "next": "scourge_run2", "operations": [{"kind": "action", "name": "hipscrge:scourge_run1"}]}],
  ["scourge_run2", {"frame": 13, "next": "scourge_run3", "operations": [{"kind": "action", "name": "scourge_think"}, {"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["scourge_run3", {"frame": 14, "next": "scourge_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["scourge_run4", {"frame": 15, "next": "scourge_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["scourge_run5", {"frame": 16, "next": "scourge_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["scourge_run6", {"frame": 17, "next": "scourge_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["scourge_strafeleft1", {"frame": 12, "next": "scourge_strafeleft2", "operations": [{"kind": "action", "name": "hipscrge:scourge_strafeleft1"}]}],
  ["scourge_strafeleft2", {"frame": 13, "next": "scourge_strafeleft3", "operations": [{"kind": "action", "name": "ai_left(20)"}]}],
  ["scourge_strafeleft3", {"frame": 14, "next": "scourge_strafeleft4", "operations": [{"kind": "action", "name": "ai_left(20)"}]}],
  ["scourge_strafeleft4", {"frame": 15, "next": "scourge_strafeleft5", "operations": [{"kind": "action", "name": "ai_left(14)"}]}],
  ["scourge_strafeleft5", {"frame": 16, "next": "scourge_strafeleft6", "operations": [{"kind": "action", "name": "ai_left(14)"}]}],
  ["scourge_strafeleft6", {"frame": 17, "next": "scourge_run1", "operations": [{"kind": "action", "name": "ai_left(14)"}]}],
  ["scourge_straferight1", {"frame": 12, "next": "scourge_straferight2", "operations": [{"kind": "action", "name": "hipscrge:scourge_straferight1"}]}],
  ["scourge_straferight2", {"frame": 13, "next": "scourge_straferight3", "operations": [{"kind": "action", "name": "ai_right(20)"}]}],
  ["scourge_straferight3", {"frame": 14, "next": "scourge_straferight4", "operations": [{"kind": "action", "name": "ai_right(20)"}]}],
  ["scourge_straferight4", {"frame": 15, "next": "scourge_straferight5", "operations": [{"kind": "action", "name": "ai_right(14)"}]}],
  ["scourge_straferight5", {"frame": 16, "next": "scourge_straferight6", "operations": [{"kind": "action", "name": "ai_right(14)"}]}],
  ["scourge_straferight6", {"frame": 17, "next": "scourge_run1", "operations": [{"kind": "action", "name": "ai_right(14)"}]}],
  ["scourge_turn1", {"frame": 12, "next": "scourge_turn2", "operations": [{"kind": "action", "name": "hipscrge:scourge_turn1"}]}],
  ["scourge_turn2", {"frame": 13, "next": "scourge_turn3", "operations": [{"kind": "action", "name": "ai_turn_in_place"}]}],
  ["scourge_turn3", {"frame": 14, "next": "scourge_turn4", "operations": [{"kind": "action", "name": "ai_turn_in_place"}]}],
  ["scourge_turn4", {"frame": 15, "next": "scourge_turn5", "operations": [{"kind": "action", "name": "ai_turn_in_place"}]}],
  ["scourge_turn5", {"frame": 16, "next": "scourge_turn6", "operations": [{"kind": "action", "name": "ai_turn_in_place"}]}],
  ["scourge_turn6", {"frame": 17, "next": "scourge_turn1", "operations": [{"kind": "action", "name": "ai_turn_in_place"}]}],
  ["scourge_atk1", {"frame": 18, "next": "scourge_atk2", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk1"}]}],
  ["scourge_atk2", {"frame": 19, "next": "scourge_atk3", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk2"}]}],
  ["scourge_atk3", {"frame": 18, "next": "scourge_atk4", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk3"}]}],
  ["scourge_atk4", {"frame": 19, "next": "scourge_atk5", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk4"}]}],
  ["scourge_atk5", {"frame": 18, "next": "scourge_atk6", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk5"}]}],
  ["scourge_atk6", {"frame": 19, "next": "scourge_atk7", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk2"}]}],
  ["scourge_atk7", {"frame": 18, "next": "scourge_atk8", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk3"}]}],
  ["scourge_atk8", {"frame": 19, "next": "scourge_run1", "operations": [{"kind": "action", "name": "hipscrge:scourge_atk8"}]}],
  ["scourge_melee1", {"frame": 20, "next": "scourge_melee2", "operations": [{"kind": "action", "name": "hipscrge:scourge_melee1"}]}],
  ["scourge_melee2", {"frame": 21, "next": "scourge_melee3", "operations": [{"kind": "ai", "mode": "charge", "distance": 3.0}]}],
  ["scourge_melee3", {"frame": 22, "next": "scourge_melee4", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}]}],
  ["scourge_melee4", {"frame": 23, "next": "scourge_melee5", "operations": [{"kind": "ai", "mode": "charge", "distance": 2.0}]}],
  ["scourge_melee5", {"frame": 24, "next": "scourge_melee6", "operations": [{"kind": "sound", "path": "scourge/tailswng.wav", "channel": "weapon", "attenuation": 1, "comparison": "less", "chance": null}, {"kind": "ai", "mode": "charge", "distance": 3.0}]}],
  ["scourge_melee6", {"frame": 25, "next": "scourge_melee7", "operations": [{"kind": "ai", "mode": "charge", "distance": 1.0}]}],
  ["scourge_melee7", {"frame": 26, "next": "scourge_melee8", "operations": [{"kind": "action", "name": "Attack_With_Tail"}]}],
  ["scourge_melee8", {"frame": 27, "next": "scourge_melee9", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["scourge_melee9", {"frame": 28, "next": "scourge_melee10", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["scourge_melee10", {"frame": 29, "next": "scourge_melee11", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["scourge_melee11", {"frame": 30, "next": "scourge_run1", "operations": [{"kind": "action", "name": "hipscrge:scourge_melee11"}]}],
  ["scourge_pain1", {"frame": 31, "next": "scourge_pain2", "operations": [{"kind": "action", "name": "hipscrge:scourge_pain1"}]}],
  ["scourge_pain2", {"frame": 32, "next": "scourge_pain3", "operations": []}],
  ["scourge_pain3", {"frame": 33, "next": "scourge_pain4", "operations": []}],
  ["scourge_pain4", {"frame": 34, "next": "scourge_pain5", "operations": []}],
  ["scourge_pain5", {"frame": 35, "next": "scourge_run1", "operations": []}],
  ["scourge_die1", {"frame": 36, "next": "scourge_die2", "operations": [{"kind": "action", "name": "hipscrge:scourge_pain1"}]}],
  ["scourge_die2", {"frame": 37, "next": "scourge_die3", "operations": []}],
  ["scourge_die3", {"frame": 38, "next": "scourge_die4", "operations": [{"kind": "solid", "solid": "none"}]}],
  ["scourge_die4", {"frame": 39, "next": "scourge_die5", "operations": []}],
  ["scourge_die5", {"frame": 40, "next": "scourge_die5", "operations": []}],
]);
