/* quakec_rogue/invis_sw.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["sword_stand1", {"frame": 0, "next": "sword_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["sword_run1", {"frame": 1, "next": "sword_run2", "operations": [{"kind": "action", "name": "invis_sw:sword_run1"}]}],
  ["sword_run2", {"frame": 2, "next": "sword_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["sword_run3", {"frame": 3, "next": "sword_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["sword_run4", {"frame": 4, "next": "sword_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["sword_run5", {"frame": 5, "next": "sword_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["sword_run6", {"frame": 6, "next": "sword_run7", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["sword_run7", {"frame": 7, "next": "sword_run8", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["sword_run8", {"frame": 8, "next": "sword_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["sword_atk1", {"frame": 9, "next": "sword_atk2", "operations": [{"kind": "action", "name": "invis_sw:sword_atk1"}]}],
  ["sword_atk2", {"frame": 10, "next": "sword_atk3", "operations": [{"kind": "ai", "mode": "charge", "distance": 14.0}]}],
  ["sword_atk3", {"frame": 11, "next": "sword_atk4", "operations": [{"kind": "ai", "mode": "charge", "distance": 14.0}]}],
  ["sword_atk4", {"frame": 12, "next": "sword_atk5", "operations": [{"kind": "ai", "mode": "charge", "distance": 14.0}]}],
  ["sword_atk5", {"frame": 13, "next": "sword_atk6", "operations": [{"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["sword_atk6", {"frame": 14, "next": "sword_atk7", "operations": [{"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["sword_atk7", {"frame": 15, "next": "sword_atk8", "operations": [{"kind": "ai", "mode": "melee", "distance": 0.0}]}],
  ["sword_atk8", {"frame": 16, "next": "sword_atk9", "operations": [{"kind": "ai", "mode": "charge", "distance": 14.0}]}],
  ["sword_atk9", {"frame": 17, "next": "sword_atk10", "operations": [{"kind": "ai", "mode": "charge", "distance": 14.0}]}],
  ["sword_atk10", {"frame": 18, "next": "sword_run1", "operations": [{"kind": "ai", "mode": "charge", "distance": 14.0}]}],
  ["sword_die1", {"frame": 19, "next": "sword_die2", "operations": []}],
  ["sword_die2", {"frame": 20, "next": "sword_die3", "operations": []}],
  ["sword_die3", {"frame": 21, "next": "sword_die4", "operations": [{"kind": "solid", "solid": "none"}]}],
  ["sword_die4", {"frame": 22, "next": "sword_die5", "operations": []}],
  ["sword_die5", {"frame": 23, "next": "sword_die6", "operations": []}],
  ["sword_die6", {"frame": 24, "next": "sword_die7", "operations": []}],
  ["sword_die7", {"frame": 25, "next": "sword_die8", "operations": [{"kind": "action", "name": "invis_sw:sword_die7"}]}],
  ["sword_die8", {"frame": 26, "next": "sword_die9", "operations": []}],
  ["sword_die9", {"frame": 27, "next": "sword_die10", "operations": []}],
  ["sword_die10", {"frame": 28, "next": "sword_die10", "operations": []}],
  ["sword_dieb1", {"frame": 29, "next": "sword_dieb2", "operations": []}],
  ["sword_dieb2", {"frame": 30, "next": "sword_dieb3", "operations": []}],
  ["sword_dieb3", {"frame": 31, "next": "sword_dieb4", "operations": [{"kind": "solid", "solid": "none"}]}],
  ["sword_dieb4", {"frame": 32, "next": "sword_dieb5", "operations": []}],
  ["sword_dieb5", {"frame": 33, "next": "sword_dieb6", "operations": []}],
  ["sword_dieb6", {"frame": 34, "next": "sword_dieb7", "operations": []}],
  ["sword_dieb7", {"frame": 35, "next": "sword_dieb8", "operations": [{"kind": "action", "name": "invis_sw:sword_die7"}]}],
  ["sword_dieb8", {"frame": 36, "next": "sword_dieb9", "operations": []}],
  ["sword_dieb9", {"frame": 37, "next": "sword_dieb10", "operations": []}],
  ["sword_dieb10", {"frame": 38, "next": "sword_dieb11", "operations": []}],
  ["sword_dieb11", {"frame": 39, "next": "sword_dieb11", "operations": []}],
]);
