/* quakec_rogue/morph.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["morph_stand1", {"frame": 0, "next": "morph_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["morph_walk1", {"frame": 43, "next": "morph_walk2", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["morph_walk2", {"frame": 44, "next": "morph_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["morph_walk3", {"frame": 45, "next": "morph_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["morph_walk4", {"frame": 46, "next": "morph_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["morph_walk5", {"frame": 47, "next": "morph_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["morph_walk6", {"frame": 48, "next": "morph_walk7", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["morph_walk7", {"frame": 49, "next": "morph_walk8", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["morph_walk8", {"frame": 50, "next": "morph_walk9", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["morph_walk9", {"frame": 51, "next": "morph_walk10", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["morph_walk10", {"frame": 52, "next": "morph_walk11", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["morph_walk11", {"frame": 53, "next": "morph_walk12", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["morph_walk12", {"frame": 54, "next": "morph_walk13", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["morph_walk13", {"frame": 55, "next": "morph_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["morph_run1", {"frame": 32, "next": "morph_run2", "operations": [{"kind": "ai", "mode": "run", "distance": 7.0}]}],
  ["morph_run2", {"frame": 33, "next": "morph_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 11.0}]}],
  ["morph_run3", {"frame": 34, "next": "morph_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 16.0}]}],
  ["morph_run4", {"frame": 35, "next": "morph_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 16.0}]}],
  ["morph_run5", {"frame": 36, "next": "morph_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 11.0}]}],
  ["morph_run6", {"frame": 37, "next": "morph_run7", "operations": [{"kind": "ai", "mode": "run", "distance": 7.0}]}],
  ["morph_run7", {"frame": 38, "next": "morph_run8", "operations": [{"kind": "ai", "mode": "run", "distance": 11.0}]}],
  ["morph_run8", {"frame": 39, "next": "morph_run9", "operations": [{"kind": "ai", "mode": "run", "distance": 15.0}]}],
  ["morph_run9", {"frame": 40, "next": "morph_run10", "operations": [{"kind": "ai", "mode": "run", "distance": 19.0}]}],
  ["morph_run10", {"frame": 41, "next": "morph_run11", "operations": [{"kind": "ai", "mode": "run", "distance": 15.0}]}],
  ["morph_run11", {"frame": 42, "next": "morph_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 11.0}]}],
  ["morph_attack01", {"frame": 65, "next": "morph_attack02", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack02", {"frame": 66, "next": "morph_attack03", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack03", {"frame": 67, "next": "morph_attack04", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack04", {"frame": 68, "next": "morph_attack05", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack05", {"frame": 69, "next": "morph_attack06", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack06", {"frame": 70, "next": "morph_attack07", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack07", {"frame": 71, "next": "morph_attack08", "operations": [{"kind": "action", "name": "morph_stab2"}]}],
  ["morph_attack08", {"frame": 72, "next": "morph_attack09", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack09", {"frame": 73, "next": "morph_attack10", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack10", {"frame": 74, "next": "morph_attack11", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack11", {"frame": 75, "next": "morph_attack12", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_attack12", {"frame": 65, "next": "morph_run1", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack01", {"frame": 76, "next": "morph_bigattack02", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack02", {"frame": 77, "next": "morph_bigattack03", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack03", {"frame": 78, "next": "morph_bigattack04", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack04", {"frame": 79, "next": "morph_bigattack05", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack05", {"frame": 80, "next": "morph_bigattack06", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack06", {"frame": 81, "next": "morph_bigattack07", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack07", {"frame": 82, "next": "morph_bigattack08", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack08", {"frame": 83, "next": "morph_bigattack09", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack09", {"frame": 84, "next": "morph_bigattack10", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack10", {"frame": 85, "next": "morph_bigattack11", "operations": [{"kind": "action", "name": "morph_stab2"}]}],
  ["morph_bigattack11", {"frame": 86, "next": "morph_bigattack12", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack12", {"frame": 87, "next": "morph_bigattack13", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack13", {"frame": 88, "next": "morph_bigattack14", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack14", {"frame": 89, "next": "morph_bigattack15", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack15", {"frame": 90, "next": "morph_bigattack16", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack16", {"frame": 91, "next": "morph_bigattack17", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_bigattack17", {"frame": 76, "next": "morph_run1", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback01", {"frame": 92, "next": "morph_knockback02", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback02", {"frame": 93, "next": "morph_knockback03", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback03", {"frame": 94, "next": "morph_knockback04", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback04", {"frame": 95, "next": "morph_knockback05", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback05", {"frame": 96, "next": "morph_knockback06", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback06", {"frame": 97, "next": "morph_knockback07", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback07", {"frame": 98, "next": "morph_knockback08", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback08", {"frame": 99, "next": "morph_knockback09", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback09", {"frame": 100, "next": "morph_knockback10", "operations": [{"kind": "action", "name": "morph_smack"}]}],
  ["morph_knockback10", {"frame": 101, "next": "morph_knockback11", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback11", {"frame": 102, "next": "morph_knockback12", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_knockback12", {"frame": 103, "next": "morph_run1", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire1", {"frame": 56, "next": "morph_fire2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire2", {"frame": 57, "next": "morph_fire3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire3", {"frame": 58, "next": "morph_fire4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire4", {"frame": 59, "next": "morph_fire5", "operations": [{"kind": "action", "name": "morph_fire"}]}],
  ["morph_fire5", {"frame": 60, "next": "morph_fire6", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire6", {"frame": 61, "next": "morph_fire7", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire7", {"frame": 62, "next": "morph_fire8", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire8", {"frame": 63, "next": "morph_fire9", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_fire9", {"frame": 64, "next": "morph_run1", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["morph_painA1", {"frame": 104, "next": "morph_painA2", "operations": []}],
  ["morph_painA2", {"frame": 105, "next": "morph_painA3", "operations": []}],
  ["morph_painA3", {"frame": 106, "next": "morph_painA4", "operations": []}],
  ["morph_painA4", {"frame": 107, "next": "morph_painA5", "operations": []}],
  ["morph_painA5", {"frame": 108, "next": "morph_painA6", "operations": []}],
  ["morph_painA6", {"frame": 109, "next": "morph_painA7", "operations": []}],
  ["morph_painA7", {"frame": 110, "next": "morph_painA8", "operations": []}],
  ["morph_painA8", {"frame": 111, "next": "morph_painA9", "operations": []}],
  ["morph_painA9", {"frame": 112, "next": "morph_painA10", "operations": []}],
  ["morph_painA10", {"frame": 113, "next": "morph_run1", "operations": [{"kind": "action", "name": "morph_teleport"}]}],
  ["morph_painB1", {"frame": 114, "next": "morph_painB2", "operations": []}],
  ["morph_painB2", {"frame": 115, "next": "morph_painB3", "operations": []}],
  ["morph_painB3", {"frame": 116, "next": "morph_painB4", "operations": []}],
  ["morph_painB4", {"frame": 117, "next": "morph_painB5", "operations": []}],
  ["morph_painB5", {"frame": 118, "next": "morph_painB6", "operations": []}],
  ["morph_painB6", {"frame": 119, "next": "morph_painB7", "operations": []}],
  ["morph_painB7", {"frame": 120, "next": "morph_run1", "operations": [{"kind": "action", "name": "morph_teleport"}]}],
  ["morph_die1", {"frame": 121, "next": "morph_die2", "operations": []}],
  ["morph_die2", {"frame": 122, "next": "morph_die3", "operations": []}],
  ["morph_die3", {"frame": 123, "next": "morph_die4", "operations": []}],
  ["morph_die4", {"frame": 124, "next": "morph_die5", "operations": []}],
  ["morph_die5", {"frame": 125, "next": "morph_die6", "operations": []}],
  ["morph_die6", {"frame": 126, "next": "morph_die7", "operations": []}],
  ["morph_die7", {"frame": 127, "next": "morph_die8", "operations": []}],
  ["morph_die8", {"frame": 128, "next": "morph_die9", "operations": []}],
  ["morph_die9", {"frame": 129, "next": "morph_die10", "operations": [{"kind": "action", "name": "morph:morph_die9"}]}],
  ["morph_die10", {"frame": 130, "next": "morph_die11", "operations": []}],
  ["morph_die11", {"frame": 131, "next": "morph_die12", "operations": []}],
  ["morph_die12", {"frame": 132, "next": "morph_die13", "operations": []}],
  ["morph_die13", {"frame": 133, "next": "morph_die14", "operations": []}],
  ["morph_die14", {"frame": 134, "next": "morph_die15", "operations": []}],
  ["morph_die15", {"frame": 135, "next": "morph_die16", "operations": []}],
  ["morph_die16", {"frame": 136, "next": "morph_die17", "operations": []}],
  ["morph_die17", {"frame": 137, "next": "morph_die18", "operations": []}],
  ["morph_die18", {"frame": 138, "next": "morph_die19", "operations": []}],
  ["morph_die19", {"frame": 139, "next": "morph_die20", "operations": []}],
  ["morph_die20", {"frame": 140, "next": "morph_die21", "operations": []}],
  ["morph_die21", {"frame": 141, "next": "morph_die21", "operations": [{"kind": "action", "name": "morph:morph_die21"}]}],
  ["morph_wake1", {"frame": 1, "next": "morph_wake2", "operations": [{"kind": "action", "name": "morph:morph_wake1"}]}],
  ["morph_wake2", {"frame": 2, "next": "morph_wake3", "operations": []}],
  ["morph_wake3", {"frame": 3, "next": "morph_wake4", "operations": []}],
  ["morph_wake4", {"frame": 4, "next": "morph_wake5", "operations": []}],
  ["morph_wake5", {"frame": 5, "next": "morph_wake6", "operations": []}],
  ["morph_wake6", {"frame": 6, "next": "morph_wake7", "operations": []}],
  ["morph_wake7", {"frame": 7, "next": "morph_wake8", "operations": []}],
  ["morph_wake8", {"frame": 8, "next": "morph_wake9", "operations": []}],
  ["morph_wake9", {"frame": 9, "next": "morph_wake10", "operations": []}],
  ["morph_wake10", {"frame": 10, "next": "morph_wake11", "operations": []}],
  ["morph_wake11", {"frame": 11, "next": "morph_wake12", "operations": []}],
  ["morph_wake12", {"frame": 12, "next": "morph_wake13", "operations": []}],
  ["morph_wake13", {"frame": 13, "next": "morph_wake14", "operations": []}],
  ["morph_wake14", {"frame": 14, "next": "morph_wake15", "operations": []}],
  ["morph_wake15", {"frame": 15, "next": "morph_wake16", "operations": [{"kind": "action", "name": "morph:morph_wake15"}]}],
  ["morph_wake16", {"frame": 16, "next": "morph_wake17", "operations": []}],
  ["morph_wake17", {"frame": 17, "next": "morph_wake18", "operations": []}],
  ["morph_wake18", {"frame": 18, "next": "morph_wake20", "operations": []}],
  ["morph_wake20", {"frame": 20, "next": "morph_wake21", "operations": []}],
  ["morph_wake21", {"frame": 21, "next": "morph_wake22", "operations": []}],
  ["morph_wake22", {"frame": 22, "next": "morph_wake23", "operations": []}],
  ["morph_wake23", {"frame": 23, "next": "morph_wake24", "operations": []}],
  ["morph_wake24", {"frame": 24, "next": "morph_wake25", "operations": []}],
  ["morph_wake25", {"frame": 25, "next": "morph_wake26", "operations": []}],
  ["morph_wake26", {"frame": 26, "next": "morph_wake27", "operations": []}],
  ["morph_wake27", {"frame": 27, "next": "morph_wake28", "operations": []}],
  ["morph_wake28", {"frame": 28, "next": "morph_wake29", "operations": []}],
  ["morph_wake29", {"frame": 29, "next": "morph_wake30", "operations": []}],
  ["morph_wake30", {"frame": 30, "next": "morph_wake31", "operations": []}],
  ["morph_wake31", {"frame": 31, "next": "morph_stand1", "operations": [{"kind": "action", "name": "morph:morph_wake31"}]}],
]);
