/* quakec_rogue/mummy.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["mummy_stand1", {"frame": 0, "next": "mummy_stand2", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand2", {"frame": 1, "next": "mummy_stand3", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand3", {"frame": 2, "next": "mummy_stand4", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand4", {"frame": 3, "next": "mummy_stand5", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand5", {"frame": 4, "next": "mummy_stand6", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand6", {"frame": 5, "next": "mummy_stand7", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand7", {"frame": 6, "next": "mummy_stand8", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand8", {"frame": 7, "next": "mummy_stand9", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand9", {"frame": 8, "next": "mummy_stand10", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand10", {"frame": 9, "next": "mummy_stand11", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand11", {"frame": 10, "next": "mummy_stand12", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand12", {"frame": 11, "next": "mummy_stand13", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand13", {"frame": 12, "next": "mummy_stand14", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand14", {"frame": 13, "next": "mummy_stand15", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_stand15", {"frame": 14, "next": "mummy_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["mummy_walk1", {"frame": 15, "next": "mummy_walk2", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk2", {"frame": 16, "next": "mummy_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["mummy_walk3", {"frame": 17, "next": "mummy_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 5.0}]}],
  ["mummy_walk4", {"frame": 18, "next": "mummy_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["mummy_walk5", {"frame": 19, "next": "mummy_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["mummy_walk6", {"frame": 20, "next": "mummy_walk7", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk7", {"frame": 21, "next": "mummy_walk8", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk8", {"frame": 22, "next": "mummy_walk9", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk9", {"frame": 23, "next": "mummy_walk10", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk10", {"frame": 24, "next": "mummy_walk11", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk11", {"frame": 25, "next": "mummy_walk12", "operations": [{"kind": "ai", "mode": "walk", "distance": 3.0}]}],
  ["mummy_walk12", {"frame": 26, "next": "mummy_walk13", "operations": [{"kind": "ai", "mode": "walk", "distance": 4.0}]}],
  ["mummy_walk13", {"frame": 27, "next": "mummy_walk14", "operations": [{"kind": "ai", "mode": "walk", "distance": 2.0}]}],
  ["mummy_walk14", {"frame": 28, "next": "mummy_walk15", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk15", {"frame": 29, "next": "mummy_walk16", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk16", {"frame": 30, "next": "mummy_walk17", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk17", {"frame": 31, "next": "mummy_walk18", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk18", {"frame": 32, "next": "mummy_walk19", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}]}],
  ["mummy_walk19", {"frame": 33, "next": "mummy_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 0.0}, {"kind": "sound", "path": "zombie/z_idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.2}]}],
  ["mummy_run1", {"frame": 34, "next": "mummy_run2", "operations": [{"kind": "action", "name": "mummy:mummy_run1"}]}],
  ["mummy_run2", {"frame": 35, "next": "mummy_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["mummy_run3", {"frame": 36, "next": "mummy_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 0.0}]}],
  ["mummy_run4", {"frame": 37, "next": "mummy_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 2.0}]}],
  ["mummy_run5", {"frame": 38, "next": "mummy_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["mummy_run6", {"frame": 39, "next": "mummy_run7", "operations": [{"kind": "ai", "mode": "run", "distance": 6.0}]}],
  ["mummy_run7", {"frame": 40, "next": "mummy_run8", "operations": [{"kind": "ai", "mode": "run", "distance": 8.0}]}],
  ["mummy_run8", {"frame": 41, "next": "mummy_run9", "operations": [{"kind": "ai", "mode": "run", "distance": 8.0}]}],
  ["mummy_run9", {"frame": 42, "next": "mummy_run10", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["mummy_run10", {"frame": 43, "next": "mummy_run11", "operations": [{"kind": "ai", "mode": "run", "distance": 0.0}]}],
  ["mummy_run11", {"frame": 44, "next": "mummy_run12", "operations": [{"kind": "ai", "mode": "run", "distance": 0.0}]}],
  ["mummy_run12", {"frame": 45, "next": "mummy_run13", "operations": [{"kind": "ai", "mode": "run", "distance": 0.0}]}],
  ["mummy_run13", {"frame": 46, "next": "mummy_run14", "operations": [{"kind": "ai", "mode": "run", "distance": 4.0}]}],
  ["mummy_run14", {"frame": 47, "next": "mummy_run15", "operations": [{"kind": "ai", "mode": "run", "distance": 8.0}]}],
  ["mummy_run15", {"frame": 48, "next": "mummy_run16", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["mummy_run16", {"frame": 49, "next": "mummy_run17", "operations": [{"kind": "ai", "mode": "run", "distance": 14.0}]}],
  ["mummy_run17", {"frame": 50, "next": "mummy_run18", "operations": [{"kind": "ai", "mode": "run", "distance": 6.0}]}],
  ["mummy_run18", {"frame": 51, "next": "mummy_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 16.0}, {"kind": "sound", "path": "zombie/z_idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.2}, {"kind": "sound", "path": "zombie/z_idle1.wav", "channel": "voice", "attenuation": 2, "comparison": "greater", "chance": 0.8}]}],
  ["mummy_atta1", {"frame": 52, "next": "mummy_atta2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta2", {"frame": 53, "next": "mummy_atta3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta3", {"frame": 54, "next": "mummy_atta4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta4", {"frame": 55, "next": "mummy_atta5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta5", {"frame": 56, "next": "mummy_atta6", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta6", {"frame": 57, "next": "mummy_atta7", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta7", {"frame": 58, "next": "mummy_atta8", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta8", {"frame": 59, "next": "mummy_atta9", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta9", {"frame": 60, "next": "mummy_atta10", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta10", {"frame": 61, "next": "mummy_atta11", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta11", {"frame": 62, "next": "mummy_atta12", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta12", {"frame": 63, "next": "mummy_atta13", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_atta13", {"frame": 64, "next": "mummy_run1", "operations": [{"kind": "action", "name": "mummy:mummy_atta13"}]}],
  ["mummy_attb1", {"frame": 65, "next": "mummy_attb2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb2", {"frame": 66, "next": "mummy_attb3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb3", {"frame": 67, "next": "mummy_attb4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb4", {"frame": 68, "next": "mummy_attb5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb5", {"frame": 69, "next": "mummy_attb6", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb6", {"frame": 70, "next": "mummy_attb7", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb7", {"frame": 71, "next": "mummy_attb8", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb8", {"frame": 72, "next": "mummy_attb9", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb9", {"frame": 73, "next": "mummy_attb10", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb10", {"frame": 74, "next": "mummy_attb11", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb11", {"frame": 75, "next": "mummy_attb12", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb12", {"frame": 76, "next": "mummy_attb13", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb13", {"frame": 77, "next": "mummy_attb14", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attb14", {"frame": 77, "next": "mummy_run1", "operations": [{"kind": "action", "name": "mummy:mummy_attb14"}]}],
  ["mummy_attc1", {"frame": 79, "next": "mummy_attc2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc2", {"frame": 80, "next": "mummy_attc3", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc3", {"frame": 81, "next": "mummy_attc4", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc4", {"frame": 82, "next": "mummy_attc5", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc5", {"frame": 83, "next": "mummy_attc6", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc6", {"frame": 84, "next": "mummy_attc7", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc7", {"frame": 85, "next": "mummy_attc8", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc8", {"frame": 86, "next": "mummy_attc9", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc9", {"frame": 87, "next": "mummy_attc10", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc10", {"frame": 88, "next": "mummy_attc11", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc11", {"frame": 89, "next": "mummy_attc12", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["mummy_attc12", {"frame": 90, "next": "mummy_run1", "operations": [{"kind": "action", "name": "mummy:mummy_attc12"}]}],
  ["mummy_paina1", {"frame": 91, "next": "mummy_paina2", "operations": [{"kind": "sound", "path": "zombie/z_pain.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["mummy_paina2", {"frame": 92, "next": "mummy_paina3", "operations": [{"kind": "ai", "mode": "painforward", "distance": 3.0}]}],
  ["mummy_paina3", {"frame": 93, "next": "mummy_paina4", "operations": [{"kind": "ai", "mode": "painforward", "distance": 1.0}]}],
  ["mummy_paina4", {"frame": 94, "next": "mummy_paina5", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_paina5", {"frame": 95, "next": "mummy_paina6", "operations": [{"kind": "ai", "mode": "pain", "distance": 3.0}]}],
  ["mummy_paina6", {"frame": 96, "next": "mummy_paina7", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_paina7", {"frame": 97, "next": "mummy_paina8", "operations": []}],
  ["mummy_paina8", {"frame": 98, "next": "mummy_paina9", "operations": []}],
  ["mummy_paina9", {"frame": 99, "next": "mummy_paina10", "operations": []}],
  ["mummy_paina10", {"frame": 100, "next": "mummy_paina11", "operations": []}],
  ["mummy_paina11", {"frame": 101, "next": "mummy_paina12", "operations": []}],
  ["mummy_paina12", {"frame": 102, "next": "mummy_run1", "operations": []}],
  ["mummy_painb1", {"frame": 103, "next": "mummy_painb2", "operations": [{"kind": "sound", "path": "zombie/z_pain1.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["mummy_painb2", {"frame": 104, "next": "mummy_painb3", "operations": [{"kind": "ai", "mode": "pain", "distance": 2.0}]}],
  ["mummy_painb3", {"frame": 105, "next": "mummy_painb4", "operations": [{"kind": "ai", "mode": "pain", "distance": 8.0}]}],
  ["mummy_painb4", {"frame": 106, "next": "mummy_painb5", "operations": [{"kind": "ai", "mode": "pain", "distance": 6.0}]}],
  ["mummy_painb5", {"frame": 107, "next": "mummy_painb6", "operations": [{"kind": "ai", "mode": "pain", "distance": 2.0}]}],
  ["mummy_painb6", {"frame": 108, "next": "mummy_painb7", "operations": []}],
  ["mummy_painb7", {"frame": 109, "next": "mummy_painb8", "operations": []}],
  ["mummy_painb8", {"frame": 110, "next": "mummy_painb9", "operations": []}],
  ["mummy_painb9", {"frame": 111, "next": "mummy_painb10", "operations": [{"kind": "sound", "path": "zombie/z_fall.wav", "channel": "body", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["mummy_painb10", {"frame": 112, "next": "mummy_painb11", "operations": []}],
  ["mummy_painb11", {"frame": 113, "next": "mummy_painb12", "operations": []}],
  ["mummy_painb12", {"frame": 114, "next": "mummy_painb13", "operations": []}],
  ["mummy_painb13", {"frame": 115, "next": "mummy_painb14", "operations": []}],
  ["mummy_painb14", {"frame": 116, "next": "mummy_painb15", "operations": []}],
  ["mummy_painb15", {"frame": 117, "next": "mummy_painb16", "operations": []}],
  ["mummy_painb16", {"frame": 118, "next": "mummy_painb17", "operations": []}],
  ["mummy_painb17", {"frame": 119, "next": "mummy_painb18", "operations": []}],
  ["mummy_painb18", {"frame": 120, "next": "mummy_painb19", "operations": []}],
  ["mummy_painb19", {"frame": 121, "next": "mummy_painb20", "operations": []}],
  ["mummy_painb20", {"frame": 122, "next": "mummy_painb21", "operations": []}],
  ["mummy_painb21", {"frame": 123, "next": "mummy_painb22", "operations": []}],
  ["mummy_painb22", {"frame": 124, "next": "mummy_painb23", "operations": []}],
  ["mummy_painb23", {"frame": 125, "next": "mummy_painb24", "operations": []}],
  ["mummy_painb24", {"frame": 126, "next": "mummy_painb25", "operations": []}],
  ["mummy_painb25", {"frame": 127, "next": "mummy_painb26", "operations": [{"kind": "ai", "mode": "painforward", "distance": 1.0}]}],
  ["mummy_painb26", {"frame": 128, "next": "mummy_painb27", "operations": []}],
  ["mummy_painb27", {"frame": 129, "next": "mummy_painb28", "operations": []}],
  ["mummy_painb28", {"frame": 130, "next": "mummy_run1", "operations": []}],
  ["mummy_painc1", {"frame": 131, "next": "mummy_painc2", "operations": [{"kind": "sound", "path": "zombie/z_pain1.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["mummy_painc2", {"frame": 132, "next": "mummy_painc3", "operations": []}],
  ["mummy_painc3", {"frame": 133, "next": "mummy_painc4", "operations": [{"kind": "ai", "mode": "pain", "distance": 3.0}]}],
  ["mummy_painc4", {"frame": 134, "next": "mummy_painc5", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_painc5", {"frame": 135, "next": "mummy_painc6", "operations": []}],
  ["mummy_painc6", {"frame": 136, "next": "mummy_painc7", "operations": []}],
  ["mummy_painc7", {"frame": 137, "next": "mummy_painc8", "operations": []}],
  ["mummy_painc8", {"frame": 138, "next": "mummy_painc9", "operations": []}],
  ["mummy_painc9", {"frame": 139, "next": "mummy_painc10", "operations": []}],
  ["mummy_painc10", {"frame": 140, "next": "mummy_painc11", "operations": []}],
  ["mummy_painc11", {"frame": 141, "next": "mummy_painc12", "operations": [{"kind": "ai", "mode": "painforward", "distance": 1.0}]}],
  ["mummy_painc12", {"frame": 142, "next": "mummy_painc13", "operations": [{"kind": "ai", "mode": "painforward", "distance": 1.0}]}],
  ["mummy_painc13", {"frame": 143, "next": "mummy_painc14", "operations": []}],
  ["mummy_painc14", {"frame": 144, "next": "mummy_painc15", "operations": []}],
  ["mummy_painc15", {"frame": 145, "next": "mummy_painc16", "operations": []}],
  ["mummy_painc16", {"frame": 146, "next": "mummy_painc17", "operations": []}],
  ["mummy_painc17", {"frame": 147, "next": "mummy_painc18", "operations": []}],
  ["mummy_painc18", {"frame": 148, "next": "mummy_run1", "operations": []}],
  ["mummy_paind1", {"frame": 149, "next": "mummy_paind2", "operations": [{"kind": "sound", "path": "zombie/z_pain.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["mummy_paind2", {"frame": 150, "next": "mummy_paind3", "operations": []}],
  ["mummy_paind3", {"frame": 151, "next": "mummy_paind4", "operations": []}],
  ["mummy_paind4", {"frame": 152, "next": "mummy_paind5", "operations": []}],
  ["mummy_paind5", {"frame": 153, "next": "mummy_paind6", "operations": []}],
  ["mummy_paind6", {"frame": 154, "next": "mummy_paind7", "operations": []}],
  ["mummy_paind7", {"frame": 155, "next": "mummy_paind8", "operations": []}],
  ["mummy_paind8", {"frame": 156, "next": "mummy_paind9", "operations": []}],
  ["mummy_paind9", {"frame": 157, "next": "mummy_paind10", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_paind10", {"frame": 158, "next": "mummy_paind11", "operations": []}],
  ["mummy_paind11", {"frame": 159, "next": "mummy_paind12", "operations": []}],
  ["mummy_paind12", {"frame": 160, "next": "mummy_paind13", "operations": []}],
  ["mummy_paind13", {"frame": 161, "next": "mummy_run1", "operations": []}],
  ["mummy_paine1", {"frame": 162, "next": "mummy_paine2", "operations": [{"kind": "sound", "path": "zombie/z_pain.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["mummy_paine2", {"frame": 163, "next": "mummy_paine3", "operations": [{"kind": "ai", "mode": "pain", "distance": 8.0}]}],
  ["mummy_paine3", {"frame": 164, "next": "mummy_paine4", "operations": [{"kind": "ai", "mode": "pain", "distance": 5.0}]}],
  ["mummy_paine4", {"frame": 165, "next": "mummy_paine5", "operations": [{"kind": "ai", "mode": "pain", "distance": 3.0}]}],
  ["mummy_paine5", {"frame": 166, "next": "mummy_paine6", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_paine6", {"frame": 167, "next": "mummy_paine7", "operations": [{"kind": "ai", "mode": "pain", "distance": 2.0}]}],
  ["mummy_paine7", {"frame": 168, "next": "mummy_paine8", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_paine8", {"frame": 169, "next": "mummy_paine9", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_paine9", {"frame": 170, "next": "mummy_paine10", "operations": [{"kind": "ai", "mode": "pain", "distance": 2.0}]}],
  ["mummy_paine10", {"frame": 171, "next": "mummy_paine11", "operations": [{"kind": "sound", "path": "zombie/z_fall.wav", "channel": "body", "attenuation": 1, "comparison": "less", "chance": null}, {"kind": "solid", "solid": "none"}]}],
  ["mummy_paine11", {"frame": 172, "next": "mummy_paine12", "operations": [{"kind": "action", "name": "mummy:mummy_paine11"}]}],
  ["mummy_paine12", {"frame": 173, "next": "mummy_paine13", "operations": [{"kind": "action", "name": "mummy:mummy_paine12"}]}],
  ["mummy_paine13", {"frame": 174, "next": "mummy_paine14", "operations": []}],
  ["mummy_paine14", {"frame": 175, "next": "mummy_paine15", "operations": []}],
  ["mummy_paine15", {"frame": 176, "next": "mummy_paine16", "operations": []}],
  ["mummy_paine16", {"frame": 177, "next": "mummy_paine17", "operations": []}],
  ["mummy_paine17", {"frame": 178, "next": "mummy_paine18", "operations": []}],
  ["mummy_paine18", {"frame": 179, "next": "mummy_paine19", "operations": []}],
  ["mummy_paine19", {"frame": 180, "next": "mummy_paine20", "operations": []}],
  ["mummy_paine20", {"frame": 181, "next": "mummy_paine21", "operations": []}],
  ["mummy_paine21", {"frame": 182, "next": "mummy_paine22", "operations": []}],
  ["mummy_paine22", {"frame": 183, "next": "mummy_paine23", "operations": []}],
  ["mummy_paine23", {"frame": 184, "next": "mummy_paine24", "operations": []}],
  ["mummy_paine24", {"frame": 185, "next": "mummy_paine25", "operations": []}],
  ["mummy_paine25", {"frame": 186, "next": "mummy_paine26", "operations": [{"kind": "ai", "mode": "painforward", "distance": 5.0}]}],
  ["mummy_paine26", {"frame": 187, "next": "mummy_paine27", "operations": [{"kind": "ai", "mode": "painforward", "distance": 3.0}]}],
  ["mummy_paine27", {"frame": 188, "next": "mummy_paine28", "operations": [{"kind": "ai", "mode": "painforward", "distance": 1.0}]}],
  ["mummy_paine28", {"frame": 189, "next": "mummy_paine29", "operations": [{"kind": "ai", "mode": "pain", "distance": 1.0}]}],
  ["mummy_paine29", {"frame": 190, "next": "mummy_paine30", "operations": []}],
  ["mummy_paine30", {"frame": 191, "next": "mummy_run1", "operations": []}],
  ["mummy_sleep", {"frame": 172, "next": "mummy_sleep", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
]);
