/* quakec_hipnotic/monsters/rottweiler.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["dog_stand1", {"frame": 69, "next": "dog_stand2", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand2", {"frame": 70, "next": "dog_stand3", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand3", {"frame": 71, "next": "dog_stand4", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand4", {"frame": 72, "next": "dog_stand5", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand5", {"frame": 73, "next": "dog_stand6", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand6", {"frame": 74, "next": "dog_stand7", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand7", {"frame": 75, "next": "dog_stand8", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand8", {"frame": 76, "next": "dog_stand9", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_stand9", {"frame": 77, "next": "dog_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["dog_walk1", {"frame": 78, "next": "dog_walk2", "operations": [{"kind": "sound", "path": "dog/idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.2}, {"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_walk2", {"frame": 79, "next": "dog_walk3", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_walk3", {"frame": 80, "next": "dog_walk4", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_walk4", {"frame": 81, "next": "dog_walk5", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_walk5", {"frame": 82, "next": "dog_walk6", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_walk6", {"frame": 83, "next": "dog_walk7", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_walk7", {"frame": 84, "next": "dog_walk8", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_walk8", {"frame": 85, "next": "dog_walk1", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["dog_run1", {"frame": 48, "next": "dog_run2", "operations": [{"kind": "sound", "path": "dog/idle.wav", "channel": "voice", "attenuation": 2, "comparison": "less", "chance": 0.2}, {"kind": "ai", "mode": "run", "distance": 16.0}]}],
  ["dog_run2", {"frame": 49, "next": "dog_run3", "operations": [{"kind": "ai", "mode": "run", "distance": 32.0}]}],
  ["dog_run3", {"frame": 50, "next": "dog_run4", "operations": [{"kind": "ai", "mode": "run", "distance": 32.0}]}],
  ["dog_run4", {"frame": 51, "next": "dog_run5", "operations": [{"kind": "ai", "mode": "run", "distance": 20.0}]}],
  ["dog_run5", {"frame": 52, "next": "dog_run6", "operations": [{"kind": "ai", "mode": "run", "distance": 64.0}]}],
  ["dog_run6", {"frame": 53, "next": "dog_run7", "operations": [{"kind": "ai", "mode": "run", "distance": 32.0}]}],
  ["dog_run7", {"frame": 54, "next": "dog_run8", "operations": [{"kind": "ai", "mode": "run", "distance": 16.0}]}],
  ["dog_run8", {"frame": 55, "next": "dog_run9", "operations": [{"kind": "ai", "mode": "run", "distance": 32.0}]}],
  ["dog_run9", {"frame": 56, "next": "dog_run10", "operations": [{"kind": "ai", "mode": "run", "distance": 32.0}]}],
  ["dog_run10", {"frame": 57, "next": "dog_run11", "operations": [{"kind": "ai", "mode": "run", "distance": 20.0}]}],
  ["dog_run11", {"frame": 58, "next": "dog_run12", "operations": [{"kind": "ai", "mode": "run", "distance": 64.0}]}],
  ["dog_run12", {"frame": 59, "next": "dog_run1", "operations": [{"kind": "ai", "mode": "run", "distance": 32.0}]}],
  ["dog_atta1", {"frame": 0, "next": "dog_atta2", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}]}],
  ["dog_atta2", {"frame": 1, "next": "dog_atta3", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}]}],
  ["dog_atta3", {"frame": 2, "next": "dog_atta4", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}]}],
  ["dog_atta4", {"frame": 3, "next": "dog_atta5", "operations": [{"kind": "sound", "path": "dog/dattack1.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}, {"kind": "action", "name": "dog_bite"}]}],
  ["dog_atta5", {"frame": 4, "next": "dog_atta6", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}]}],
  ["dog_atta6", {"frame": 5, "next": "dog_atta7", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}]}],
  ["dog_atta7", {"frame": 6, "next": "dog_atta8", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}]}],
  ["dog_atta8", {"frame": 7, "next": "dog_run1", "operations": [{"kind": "ai", "mode": "charge", "distance": 10.0}]}],
  ["dog_leap1", {"frame": 60, "next": "dog_leap2", "operations": [{"kind": "ai", "mode": "face", "distance": 0.0}]}],
  ["dog_leap2", {"frame": 61, "next": "dog_leap3", "operations": [{"kind": "action", "name": "rottweiler:dog_leap2"}]}],
  ["dog_leap3", {"frame": 62, "next": "dog_leap4", "operations": []}],
  ["dog_leap4", {"frame": 63, "next": "dog_leap5", "operations": []}],
  ["dog_leap5", {"frame": 64, "next": "dog_leap6", "operations": []}],
  ["dog_leap6", {"frame": 65, "next": "dog_leap7", "operations": []}],
  ["dog_leap7", {"frame": 66, "next": "dog_leap8", "operations": []}],
  ["dog_leap8", {"frame": 67, "next": "dog_leap9", "operations": []}],
  ["dog_leap9", {"frame": 68, "next": "dog_leap9", "operations": []}],
  ["dog_pain1", {"frame": 26, "next": "dog_pain2", "operations": []}],
  ["dog_pain2", {"frame": 27, "next": "dog_pain3", "operations": []}],
  ["dog_pain3", {"frame": 28, "next": "dog_pain4", "operations": []}],
  ["dog_pain4", {"frame": 29, "next": "dog_pain5", "operations": []}],
  ["dog_pain5", {"frame": 30, "next": "dog_pain6", "operations": []}],
  ["dog_pain6", {"frame": 31, "next": "dog_run1", "operations": []}],
  ["dog_painb1", {"frame": 32, "next": "dog_painb2", "operations": []}],
  ["dog_painb2", {"frame": 33, "next": "dog_painb3", "operations": []}],
  ["dog_painb3", {"frame": 34, "next": "dog_painb4", "operations": [{"kind": "ai", "mode": "pain", "distance": 4.0}]}],
  ["dog_painb4", {"frame": 35, "next": "dog_painb5", "operations": [{"kind": "ai", "mode": "pain", "distance": 12.0}]}],
  ["dog_painb5", {"frame": 36, "next": "dog_painb6", "operations": [{"kind": "ai", "mode": "pain", "distance": 12.0}]}],
  ["dog_painb6", {"frame": 37, "next": "dog_painb7", "operations": [{"kind": "ai", "mode": "pain", "distance": 2.0}]}],
  ["dog_painb7", {"frame": 38, "next": "dog_painb8", "operations": []}],
  ["dog_painb8", {"frame": 39, "next": "dog_painb9", "operations": [{"kind": "ai", "mode": "pain", "distance": 4.0}]}],
  ["dog_painb9", {"frame": 40, "next": "dog_painb10", "operations": []}],
  ["dog_painb10", {"frame": 41, "next": "dog_painb11", "operations": [{"kind": "ai", "mode": "pain", "distance": 10.0}]}],
  ["dog_painb11", {"frame": 42, "next": "dog_painb12", "operations": []}],
  ["dog_painb12", {"frame": 43, "next": "dog_painb13", "operations": []}],
  ["dog_painb13", {"frame": 44, "next": "dog_painb14", "operations": []}],
  ["dog_painb14", {"frame": 45, "next": "dog_painb15", "operations": []}],
  ["dog_painb15", {"frame": 46, "next": "dog_painb16", "operations": []}],
  ["dog_painb16", {"frame": 47, "next": "dog_run1", "operations": []}],
  ["dog_die1", {"frame": 8, "next": "dog_die2", "operations": []}],
  ["dog_die2", {"frame": 9, "next": "dog_die3", "operations": []}],
  ["dog_die3", {"frame": 10, "next": "dog_die4", "operations": []}],
  ["dog_die4", {"frame": 11, "next": "dog_die5", "operations": []}],
  ["dog_die5", {"frame": 12, "next": "dog_die6", "operations": []}],
  ["dog_die6", {"frame": 13, "next": "dog_die7", "operations": []}],
  ["dog_die7", {"frame": 14, "next": "dog_die8", "operations": []}],
  ["dog_die8", {"frame": 15, "next": "dog_die9", "operations": []}],
  ["dog_die9", {"frame": 16, "next": "dog_die9", "operations": []}],
  ["dog_dieb1", {"frame": 17, "next": "dog_dieb2", "operations": []}],
  ["dog_dieb2", {"frame": 18, "next": "dog_dieb3", "operations": []}],
  ["dog_dieb3", {"frame": 19, "next": "dog_dieb4", "operations": []}],
  ["dog_dieb4", {"frame": 20, "next": "dog_dieb5", "operations": []}],
  ["dog_dieb5", {"frame": 21, "next": "dog_dieb6", "operations": []}],
  ["dog_dieb6", {"frame": 22, "next": "dog_dieb7", "operations": []}],
  ["dog_dieb7", {"frame": 23, "next": "dog_dieb8", "operations": []}],
  ["dog_dieb8", {"frame": 24, "next": "dog_dieb9", "operations": []}],
  ["dog_dieb9", {"frame": 25, "next": "dog_dieb9", "operations": []}],
]);
