/* quakec_rogue/s_wrath.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["overlord_stand1", {"frame": 1, "next": "overlord_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["overlord_walk01", {"frame": 1, "next": "overlord_walk02", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk02", {"frame": 2, "next": "overlord_walk03", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk03", {"frame": 3, "next": "overlord_walk04", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk04", {"frame": 4, "next": "overlord_walk05", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk05", {"frame": 5, "next": "overlord_walk06", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk06", {"frame": 6, "next": "overlord_walk07", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk07", {"frame": 7, "next": "overlord_walk08", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk08", {"frame": 8, "next": "overlord_walk09", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk09", {"frame": 9, "next": "overlord_walk10", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk10", {"frame": 10, "next": "overlord_walk11", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk11", {"frame": 11, "next": "overlord_walk12", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk12", {"frame": 12, "next": "overlord_walk13", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk13", {"frame": 13, "next": "overlord_walk14", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk14", {"frame": 14, "next": "overlord_walk15", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_walk15", {"frame": 15, "next": "overlord_walk01", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["overlord_run01", {"frame": 1, "next": "overlord_run02", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run02", {"frame": 2, "next": "overlord_run03", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run03", {"frame": 3, "next": "overlord_run04", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run04", {"frame": 4, "next": "overlord_run05", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run05", {"frame": 5, "next": "overlord_run06", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run06", {"frame": 6, "next": "overlord_run07", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run07", {"frame": 7, "next": "overlord_run08", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run08", {"frame": 8, "next": "overlord_run09", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run09", {"frame": 9, "next": "overlord_run10", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run10", {"frame": 10, "next": "overlord_run11", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run11", {"frame": 11, "next": "overlord_run12", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run12", {"frame": 12, "next": "overlord_run13", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run13", {"frame": 13, "next": "overlord_run14", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run14", {"frame": 14, "next": "overlord_run15", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_run15", {"frame": 15, "next": "overlord_run01", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["overlord_at_a01", {"frame": 16, "next": "overlord_at_a02", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a02", {"frame": 17, "next": "overlord_at_a03", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a03", {"frame": 18, "next": "overlord_at_a04", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a04", {"frame": 19, "next": "overlord_at_a05", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a05", {"frame": 20, "next": "overlord_at_a06", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a06", {"frame": 21, "next": "overlord_at_a07", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a07", {"frame": 22, "next": "overlord_at_a08", "operations": [{"kind": "action", "name": "overlord_smash"}]}],
  ["overlord_at_a08", {"frame": 23, "next": "overlord_at_a09", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a09", {"frame": 24, "next": "overlord_at_a10", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_a10", {"frame": 25, "next": "overlord_run01", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b01", {"frame": 26, "next": "overlord_at_b02", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b02", {"frame": 27, "next": "overlord_at_b03", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b03", {"frame": 28, "next": "overlord_at_b04", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b04", {"frame": 29, "next": "overlord_at_b05", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b05", {"frame": 30, "next": "overlord_at_b06", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b06", {"frame": 31, "next": "overlord_at_b07", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b07", {"frame": 32, "next": "overlord_at_b08", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b08", {"frame": 33, "next": "overlord_at_b09", "operations": [{"kind": "action", "name": "overlord_smash"}]}],
  ["overlord_at_b09", {"frame": 34, "next": "overlord_at_b10", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b10", {"frame": 35, "next": "overlord_at_b11", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b11", {"frame": 36, "next": "overlord_at_b12", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b12", {"frame": 37, "next": "overlord_at_b13", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b13", {"frame": 38, "next": "overlord_at_b14", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_b14", {"frame": 39, "next": "overlord_run01", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c01", {"frame": 40, "next": "overlord_at_c02", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c02", {"frame": 41, "next": "overlord_at_c03", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c03", {"frame": 42, "next": "overlord_at_c04", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c04", {"frame": 43, "next": "overlord_at_c05", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c05", {"frame": 44, "next": "overlord_at_c06", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c06", {"frame": 45, "next": "overlord_at_c07", "operations": [{"kind": "action", "name": "overlord_smash"}]}],
  ["overlord_at_c07", {"frame": 46, "next": "overlord_at_c08", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c08", {"frame": 47, "next": "overlord_at_c09", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c09", {"frame": 48, "next": "overlord_at_c10", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c10", {"frame": 49, "next": "overlord_at_c11", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c11", {"frame": 50, "next": "overlord_at_c12", "operations": [{"kind": "action", "name": "overlord_smash"}]}],
  ["overlord_at_c12", {"frame": 51, "next": "overlord_at_c13", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c13", {"frame": 52, "next": "overlord_at_c14", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_at_c14", {"frame": 53, "next": "overlord_run01", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a01", {"frame": 54, "next": "overlord_msl_a02", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a02", {"frame": 55, "next": "overlord_msl_a03", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a03", {"frame": 56, "next": "overlord_msl_a04", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a04", {"frame": 57, "next": "overlord_msl_a05", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a05", {"frame": 58, "next": "overlord_msl_a06", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a06", {"frame": 59, "next": "overlord_msl_a07", "operations": [{"kind": "action", "name": "WrathMissile(4)"}]}],
  ["overlord_msl_a07", {"frame": 60, "next": "overlord_msl_a08", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a08", {"frame": 61, "next": "overlord_msl_a09", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a09", {"frame": 62, "next": "overlord_msl_a10", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a10", {"frame": 63, "next": "overlord_msl_a11", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a11", {"frame": 64, "next": "overlord_msl_a12", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["overlord_msl_a12", {"frame": 65, "next": "overlord_run01", "operations": [{"kind": "action", "name": "overlord_teleport"}]}],
  ["overlord_pn_a01", {"frame": 66, "next": "overlord_pn_a02", "operations": []}],
  ["overlord_pn_a02", {"frame": 67, "next": "overlord_pn_a03", "operations": []}],
  ["overlord_pn_a03", {"frame": 68, "next": "overlord_pn_a04", "operations": [{"kind": "action", "name": "overlord_teleport"}]}],
  ["overlord_pn_a04", {"frame": 69, "next": "overlord_pn_a05", "operations": []}],
  ["overlord_pn_a05", {"frame": 70, "next": "overlord_pn_a06", "operations": []}],
  ["overlord_pn_a06", {"frame": 71, "next": "overlord_pn_a07", "operations": []}],
  ["overlord_pn_a07", {"frame": 72, "next": "overlord_run01", "operations": []}],
  ["overlord_pn_b01", {"frame": 80, "next": "overlord_pn_b02", "operations": []}],
  ["overlord_pn_b02", {"frame": 81, "next": "overlord_pn_b03", "operations": []}],
  ["overlord_pn_b03", {"frame": 82, "next": "overlord_pn_b04", "operations": [{"kind": "action", "name": "overlord_teleport"}]}],
  ["overlord_pn_b04", {"frame": 83, "next": "overlord_pn_b05", "operations": []}],
  ["overlord_pn_b05", {"frame": 84, "next": "overlord_pn_b06", "operations": []}],
  ["overlord_pn_b06", {"frame": 85, "next": "overlord_pn_b07", "operations": []}],
  ["overlord_pn_b07", {"frame": 86, "next": "overlord_run01", "operations": []}],
  ["overlord_die01", {"frame": 91, "next": "overlord_die02", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die02", {"frame": 92, "next": "overlord_die03", "operations": [{"kind": "action", "name": "s_wrath:overlord_die02"}]}],
  ["overlord_die03", {"frame": 93, "next": "overlord_die04", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die04", {"frame": 94, "next": "overlord_die05", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die05", {"frame": 95, "next": "overlord_die06", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die06", {"frame": 96, "next": "overlord_die07", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die07", {"frame": 97, "next": "overlord_die08", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die08", {"frame": 98, "next": "overlord_die09", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die09", {"frame": 99, "next": "overlord_die10", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die10", {"frame": 99, "next": "overlord_die11", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die11", {"frame": 100, "next": "overlord_die12", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die12", {"frame": 101, "next": "overlord_die13", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die13", {"frame": 102, "next": "overlord_die14", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die14", {"frame": 103, "next": "overlord_die15", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die15", {"frame": 104, "next": "overlord_die16", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die16", {"frame": 105, "next": "overlord_die17", "operations": [{"kind": "action", "name": "s_wrath:overlord_die01"}]}],
  ["overlord_die17", {"frame": 106, "next": "overlord_die18", "operations": [{"kind": "action", "name": "s_wrath:overlord_die17"}]}],
  ["overlord_die18", {"frame": 107, "next": "overlord_die19", "operations": [{"kind": "action", "name": "s_wrath:overlord_die18"}]}],
  ["overlord_die19", {"frame": 107, "next": "overlord_die19", "operations": [{"kind": "action", "name": "s_wrath:overlord_die19"}]}],
]);
