/* quakec_rogue/wrath.qc source frame order. Copyright (C) 1996-2022 id Software LLC. GPL-2.0-or-later. */
import type { MonsterFrame } from "../../../base/animation.ts";

export const frames: ReadonlyMap<string, MonsterFrame> = new Map<string, MonsterFrame>([
  ["wrath_stand1", {"frame": 1, "next": "wrath_stand1", "operations": [{"kind": "ai", "mode": "stand", "distance": 0.0}]}],
  ["wrath_walk01", {"frame": 1, "next": "wrath_walk02", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk02", {"frame": 2, "next": "wrath_walk03", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk03", {"frame": 3, "next": "wrath_walk04", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk04", {"frame": 4, "next": "wrath_walk05", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk05", {"frame": 5, "next": "wrath_walk06", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk06", {"frame": 6, "next": "wrath_walk07", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk07", {"frame": 7, "next": "wrath_walk08", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk08", {"frame": 8, "next": "wrath_walk09", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk09", {"frame": 9, "next": "wrath_walk10", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk10", {"frame": 10, "next": "wrath_walk11", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk11", {"frame": 11, "next": "wrath_walk12", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_walk12", {"frame": 12, "next": "wrath_walk01", "operations": [{"kind": "ai", "mode": "walk", "distance": 8.0}]}],
  ["wrath_run01", {"frame": 1, "next": "wrath_run02", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run02", {"frame": 2, "next": "wrath_run03", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run03", {"frame": 3, "next": "wrath_run04", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run04", {"frame": 4, "next": "wrath_run05", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run05", {"frame": 5, "next": "wrath_run06", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run06", {"frame": 6, "next": "wrath_run07", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run07", {"frame": 7, "next": "wrath_run08", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run08", {"frame": 8, "next": "wrath_run09", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run09", {"frame": 9, "next": "wrath_run10", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run10", {"frame": 10, "next": "wrath_run11", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run11", {"frame": 11, "next": "wrath_run12", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_run12", {"frame": 12, "next": "wrath_run01", "operations": [{"kind": "ai", "mode": "run", "distance": 12.0}]}],
  ["wrath_at_a01", {"frame": 13, "next": "wrath_at_a02", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a02", {"frame": 14, "next": "wrath_at_a03", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a03", {"frame": 15, "next": "wrath_at_a04", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a04", {"frame": 16, "next": "wrath_at_a05", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a05", {"frame": 17, "next": "wrath_at_a06", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a06", {"frame": 18, "next": "wrath_at_a07", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a07", {"frame": 19, "next": "wrath_at_a08", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a08", {"frame": 20, "next": "wrath_at_a09", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a09", {"frame": 21, "next": "wrath_at_a10", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a10", {"frame": 22, "next": "wrath_at_a11", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a11", {"frame": 23, "next": "wrath_at_a12", "operations": [{"kind": "action", "name": "WrathMissile(1)"}]}],
  ["wrath_at_a12", {"frame": 24, "next": "wrath_at_a13", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a13", {"frame": 25, "next": "wrath_at_a14", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_a14", {"frame": 26, "next": "wrath_run01", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b01", {"frame": 27, "next": "wrath_at_b02", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b02", {"frame": 28, "next": "wrath_at_b03", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b03", {"frame": 29, "next": "wrath_at_b04", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b04", {"frame": 30, "next": "wrath_at_b05", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b05", {"frame": 31, "next": "wrath_at_b06", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b06", {"frame": 32, "next": "wrath_at_b07", "operations": [{"kind": "action", "name": "WrathMissile(2)"}]}],
  ["wrath_at_b07", {"frame": 33, "next": "wrath_at_b08", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b08", {"frame": 34, "next": "wrath_at_b09", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b09", {"frame": 35, "next": "wrath_at_b10", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b10", {"frame": 36, "next": "wrath_at_b11", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b11", {"frame": 37, "next": "wrath_at_b12", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b12", {"frame": 38, "next": "wrath_at_b13", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_b13", {"frame": 39, "next": "wrath_run01", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c01", {"frame": 40, "next": "wrath_at_c02", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c02", {"frame": 41, "next": "wrath_at_c03", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c03", {"frame": 42, "next": "wrath_at_c04", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c04", {"frame": 43, "next": "wrath_at_c05", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c05", {"frame": 44, "next": "wrath_at_c06", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c06", {"frame": 45, "next": "wrath_at_c07", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c07", {"frame": 46, "next": "wrath_at_c08", "operations": [{"kind": "action", "name": "WrathMissile(3)"}]}],
  ["wrath_at_c08", {"frame": 47, "next": "wrath_at_c09", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c09", {"frame": 48, "next": "wrath_at_c10", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c10", {"frame": 49, "next": "wrath_at_c11", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c11", {"frame": 50, "next": "wrath_at_c12", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c12", {"frame": 51, "next": "wrath_at_c13", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c13", {"frame": 52, "next": "wrath_at_c14", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c14", {"frame": 53, "next": "wrath_at_c15", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_at_c15", {"frame": 54, "next": "wrath_run01", "operations": [{"kind": "ai", "mode": "charge", "distance": 12.0}]}],
  ["wrath_pn_a01", {"frame": 55, "next": "wrath_pn_a02", "operations": []}],
  ["wrath_pn_a02", {"frame": 56, "next": "wrath_pn_a03", "operations": []}],
  ["wrath_pn_a03", {"frame": 57, "next": "wrath_pn_a04", "operations": []}],
  ["wrath_pn_a04", {"frame": 58, "next": "wrath_pn_a05", "operations": []}],
  ["wrath_pn_a05", {"frame": 59, "next": "wrath_pn_a06", "operations": []}],
  ["wrath_pn_a06", {"frame": 60, "next": "wrath_run01", "operations": []}],
  ["wrath_pn_b01", {"frame": 61, "next": "wrath_pn_b02", "operations": []}],
  ["wrath_pn_b02", {"frame": 62, "next": "wrath_pn_b03", "operations": []}],
  ["wrath_pn_b03", {"frame": 63, "next": "wrath_pn_b04", "operations": []}],
  ["wrath_pn_b04", {"frame": 64, "next": "wrath_pn_b05", "operations": []}],
  ["wrath_pn_b05", {"frame": 65, "next": "wrath_pn_b06", "operations": []}],
  ["wrath_pn_b06", {"frame": 66, "next": "wrath_pn_b07", "operations": []}],
  ["wrath_pn_b07", {"frame": 67, "next": "wrath_pn_b08", "operations": []}],
  ["wrath_pn_b08", {"frame": 68, "next": "wrath_pn_b09", "operations": []}],
  ["wrath_pn_b09", {"frame": 69, "next": "wrath_pn_b10", "operations": []}],
  ["wrath_pn_b10", {"frame": 70, "next": "wrath_pn_b11", "operations": []}],
  ["wrath_pn_b11", {"frame": 71, "next": "wrath_run01", "operations": []}],
  ["wrath_die02", {"frame": 73, "next": "wrath_die03", "operations": [{"kind": "sound", "path": "wrath/wdthc.wav", "channel": "voice", "attenuation": 1, "comparison": "less", "chance": null}]}],
  ["wrath_die03", {"frame": 74, "next": "wrath_die04", "operations": []}],
  ["wrath_die04", {"frame": 75, "next": "wrath_die05", "operations": []}],
  ["wrath_die05", {"frame": 76, "next": "wrath_die07", "operations": []}],
  ["wrath_die07", {"frame": 78, "next": "wrath_die09", "operations": []}],
  ["wrath_die09", {"frame": 80, "next": "wrath_die11", "operations": []}],
  ["wrath_die11", {"frame": 82, "next": "wrath_die13", "operations": []}],
  ["wrath_die13", {"frame": 84, "next": "wrath_die15", "operations": []}],
  ["wrath_die15", {"frame": 86, "next": "wrath_die15", "operations": [{"kind": "action", "name": "wrath:wrath_die15"}]}],
]);
